const fs = require("fs");
const prev = JSON.parse(fs.readFileSync("C:/dev/srs-mccqe1/data/_parts123.json","utf8"));
const cards = [...prev];
let n = 136;
function c(id,q,a,ex,d,bl,tags,tid){return{id,question:q,answer:a,explanation:ex,difficulty:d,bloomLevel:bl,tags,topicId:tid};}

// RHEUMATOLOGY - RA (10)
cards.push(c("card-tn3-rheum-"+n++,"What are the 2010 ACR/EULAR classification criteria for RA?","Score >=6/10: Joint involvement (0-5), Serology RF/anti-CCP (0-3), Acute phase ESR/CRP (0-1), Duration >=6wk (0-1). Requires at least 1 swollen joint not explained otherwise","Early RA diagnosis critical - treat within window of opportunity (first 3-6 months). Anti-CCP >95% specific. Seronegative RA exists. CRA 2012 guidelines recommend early aggressive DMARD therapy.",4,"recall",["RA","ACR/EULAR","classification"],"rheum-ra"));
cards.push(c("card-tn3-rheum-"+n++,"What is the treat-to-target approach in RA?","DMARD within 3mo of diagnosis. Target remission or low disease activity by 6mo. MTX first-line 15-25mg/wk + folic acid. If inadequate at 3mo: add/switch DMARD or biologic","CRA 2012. Monitor CBC/LFTs/Cr q4-8wk on MTX. Biologic options: TNFi, abatacept, tocilizumab, rituximab, JAK inhibitors. Bridge with short-course prednisone <=7.5mg while waiting for DMARD effect.",5,"apply",["RA","treat-to-target","methotrexate"],"rheum-ra"));
cards.push(c("card-tn3-rheum-"+n++,"What are the conventional DMARDs and their key monitoring?","MTX: hepatotoxicity, myelosuppression (CBC/LFTs). Sulfasalazine: GI, myelosuppression. Leflunomide: hepatotoxicity, teratogenic. HCQ: retinal toxicity (eye exam after 5yr)","All take 6-12wk for effect. MTX contraindicated in pregnancy, liver disease, renal impairment. Folic acid reduces MTX side effects. Leflunomide requires washout with cholestyramine if pregnancy desired.",4,"recall",["DMARDs","methotrexate","monitoring"],"rheum-ra"));
cards.push(c("card-tn3-rheum-"+n++,"What biologics are used in RA and what pre-screening is required?","TNFi, IL-6i (tocilizumab), abatacept, rituximab, JAKi (tofacitinib). Pre-screen: TB (IGRA), HBV/HCV, CXR, update vaccines. Avoid live vaccines on biologics","Treat latent TB before starting. TNFi CI in Class III/IV HF and demyelinating disease. JAKi: VTE and malignancy concerns (ORAL Surveillance trial). Biologics increase infection risk significantly.",5,"apply",["biologics","TNF inhibitor","RA"],"rheum-ra"));
cards.push(c("card-tn3-rheum-"+n++,"What are the extra-articular manifestations of RA?","Rheumatoid nodules, ILD, pericarditis/pleuritis, scleritis, vasculitis, Felty syndrome (splenomegaly+neutropenia), atlantoaxial subluxation, accelerated atherosclerosis","1.5-2x CV mortality. Screen CV risk factors. ILD in ~10%. C-spine XR before surgery. Secondary amyloidosis in poorly controlled disease. Cervical myelopathy risk with atlantoaxial instability.",4,"recall",["RA","extra-articular","complications"],"rheum-ra"));
cards.push(c("card-tn3-rheum-"+n++,"How do RA and OA differ clinically?","RA: symmetric, MCP/PIP/wrist, stiffness >60min, inflammatory, soft tissue swelling. OA: asymmetric, DIP/CMC/knee/hip, stiffness <30min, bony enlargement, non-inflammatory","RA spares DIP (DIP = OA or PsA). RA: ulnar deviation, swan-neck, boutonniere. OA: Heberden (DIP) and Bouchard (PIP) nodes. XR: RA=erosions+periarticular osteopenia; OA=osteophytes+joint space narrowing.",3,"analyze",["RA","OA","differential"],"rheum-ra"));
cards.push(c("card-tn3-rheum-"+n++,"How is an RA flare managed?","Short-course prednisone 10-15mg taper 2-4wk, IA steroid for monoarticular flare, optimize DMARD, assess adherence. Rule out septic arthritis in acute monoarthritis","Avoid long-term glucocorticoids. >=2 flares on current regimen: escalate therapy. NSAIDs for symptoms but no disease modification. Septic joint is always in differential for acute monoarticular flare.",4,"apply",["RA flare","prednisone","management"],"rheum-ra"));
cards.push(c("card-tn3-rheum-"+n++,"What perioperative considerations exist for RA patients on DMARDs?","MTX: continue (reduces flare). Biologics: hold 2-5 half-lives pre-surgery. C-spine XR for intubation safety. Stress-dose steroids if on chronic prednisone. Resume biologics when wound healed","CRA/ACR perioperative guidelines. Infection risk increased post-surgery on biologics. Flexion-extension C-spine views assess atlantoaxial stability. Fragile skin and osteoporosis considerations.",4,"apply",["RA","perioperative","biologics"],"rheum-ra"));
cards.push(c("card-tn3-rheum-"+n++,"What is the management of acute gout vs chronic gout prevention?","Acute: NSAIDs or colchicine (1.2mg then 0.6mg at 1h) or prednisone 30-40mg x5d. Do NOT start/stop allopurinol during flare. Chronic: allopurinol start 100mg titrate to urate <360 umol/L","Crystal confirmation gold standard (negatively birefringent MSU). Allopurinol start low (50mg if CKD). Febuxostat if intolerant. Colchicine prophylaxis 0.6mg daily x6mo when starting ULT. Lifestyle: weight loss, limit alcohol/purines.",4,"apply",["gout","colchicine","allopurinol"],"rheum-ra"));
cards.push(c("card-tn3-rheum-"+n++,"How is pseudogout (CPPD) differentiated from gout?","CPPD: positively birefringent rhomboid crystals, chondrocalcinosis on XR, large joints (knee/wrist). No ULT equivalent. Treat acute: NSAIDs/colchicine/steroids. If <60: investigate metabolic causes (hyperPTH, hemochromatosis)","Unlike gout no disease-modifying therapy exists. Chronic CPPD can mimic RA or OA. Associated: hyperparathyroidism, hemochromatosis, hypomagnesemia. Joint aspiration is both diagnostic and therapeutic.",3,"analyze",["pseudogout","CPPD","crystal arthropathy"],"rheum-ra"));

// RHEUMATOLOGY - OA (10)
cards.push(c("card-tn3-rheum-"+n++,"What are the clinical and radiographic features of OA?","Clinical: pain with activity, stiffness <30min, bony enlargement, crepitus. XR: joint space narrowing, osteophytes, subchondral sclerosis, subchondral cysts. Labs normal","Clinical diagnosis - XR not required. Severity of XR changes correlates poorly with symptoms. Common joints: knee, hip, hand (DIP>PIP, 1st CMC), spine. No blood markers for OA.",3,"recall",["OA","radiographic","diagnosis"],"rheum-osteo"));
cards.push(c("card-tn3-rheum-"+n++,"What is the stepwise management of knee OA?","1st: exercise + weight loss + education. 2nd: topical NSAIDs, acetaminophen. 3rd: oral NSAIDs (lowest dose/shortest). 4th: IA corticosteroid. 5th: TKA. No evidence for glucosamine or IA hyaluronic acid","Exercise is most effective non-surgical intervention. 5-10% weight loss significantly reduces symptoms. Max 3-4 IA steroid/year/joint. OARSI guidelines. Physiotherapy referral for structured exercise program.",4,"apply",["knee OA","management","exercise"],"rheum-osteo"));
cards.push(c("card-tn3-rheum-"+n++,"When is joint replacement indicated for OA?","Severe pain limiting function despite optimal conservative treatment, significant QoL impact, radiographic severe joint destruction. No age cutoff. Pre-op: weight loss, smoking cessation, prehab","Prosthesis lasts 15-20yr. Infection risk 1-2%. DVT prophylaxis post-op. Periprosthetic joint infection: urgent orthopedic referral. BMI >40 increases surgical risk.",4,"apply",["joint replacement","TKA","OA"],"rheum-osteo"));
cards.push(c("card-tn3-rheum-"+n++,"What are the modifiable risk factors for OA?","Obesity (strongest modifiable - 4kg less knee load per 1kg weight loss), joint injury (ACL tear = 4-6x OA risk), occupational repetitive loading, malalignment, muscle weakness","Exercise does NOT cause OA in normal joints. Quadriceps strengthening protects knee. No pharmacological prevention. Weight management is most impactful modifiable intervention.",3,"recall",["OA","risk factors","prevention"],"rheum-osteo"));
cards.push(c("card-tn3-rheum-"+n++,"What are the risks of NSAIDs in OA management?","GI: bleeding 2-4x (add PPI if >=65 or history). CV: increased events (naproxen safest). Renal: avoid eGFR<30. HTN worsening. Celecoxib: lower GI risk. Topical NSAIDs: minimal systemic risk (first-line)","Avoid NSAIDs + anticoagulants. Avoid in HF. Short courses preferred. Drug interactions: warfarin, lithium, methotrexate, antihypertensives. Topical diclofenac gel effective with minimal systemic absorption.",4,"apply",["NSAIDs","adverse effects","OA"],"rheum-osteo"));
cards.push(c("card-tn3-rheum-"+n++,"What is erosive OA?","Inflammatory OA subtype: DIP/PIP, central erosions (gull-wing pattern on XR), intermittent inflammatory flares, female predominance. Differentiate from RA (DIP, no RF/CCP) and PsA (no skin/nail findings)","Erosive OA: central (not marginal) erosions distinguishes from RA. Management: same as OA + colchicine or HCQ for inflammatory flares. Self-limited inflammatory episodes. Does not respond to DMARDs.",4,"analyze",["erosive OA","inflammatory","differential"],"rheum-osteo"));
cards.push(c("card-tn3-rheum-"+n++,"What is the role of IA injections in OA?","Corticosteroid: short-term relief 4-8wk, max 3-4/yr/joint. Hyaluronic acid: NOT recommended. PRP: insufficient evidence. US guidance improves accuracy especially for hip","IA steroid for acute flare. Repeated injections may accelerate cartilage loss. Avoid if septic joint suspected. Post-injection flare 24-48h possible. Monitor glucose in diabetics for 48-72h.",3,"apply",["intra-articular","corticosteroid","OA"],"rheum-osteo"));
cards.push(c("card-tn3-rheum-"+n++,"What non-pharmacological treatments have best evidence in OA?","Strong: land-based exercise, aquatic exercise, weight loss, self-management. Moderate: assistive devices (cane, brace), PT, OT. Weak: acupuncture, TENS","Exercise adherence is main challenge. Group programs, telehealth improve adherence. Quadriceps for knee, hip strengthening for hip OA. Cane in contralateral hand. OT for hand OA (splints, adaptive devices).",3,"recall",["non-pharmacological","exercise","OA"],"rheum-osteo"));
cards.push(c("card-tn3-rheum-"+n++,"How is hand OA managed?","Splinting (thumb CMC), exercises, topical NSAIDs (first-line Rx), acetaminophen, oral NSAIDs short-term. Surgery for severe 1st CMC. OT for adaptive devices","1st CMC very common and debilitating. Thumb spica splint provides relief. Heberden (DIP) and Bouchard (PIP) nodes are bony. No DMARDs for hand OA. Avoid disuse from over-splinting.",3,"apply",["hand OA","splinting","management"],"rheum-osteo"));
cards.push(c("card-tn3-rheum-"+n++,"What is the differential for acute monoarthritis?","Septic arthritis (emergency), gout, CPPD, trauma, reactive arthritis, OA flare, hemarthrosis. MUST aspirate if infection possible: WBC, crystals, gram stain, culture","Septic: >50k WBC, >75% PMN. Gout: neg birefringent needles. CPPD: pos birefringent rhomboids. Inflammatory: 2-50k WBC. Non-inflammatory: <2k. Never miss septic arthritis.",4,"analyze",["monoarthritis","septic arthritis","aspiration"],"rheum-osteo"));

// RHEUMATOLOGY - LUPUS (10)
cards.push(c("card-tn3-rheum-"+n++,"What are the 2019 EULAR/ACR classification criteria for SLE?","Entry: ANA >=1:80. Score domains (>=10): hematologic, neuropsych, mucocutaneous, serosal, MSK, renal + immunology (anti-dsDNA, complement, aPL). Each criterion not attributable to other diagnosis","ANA 98% sensitive, not specific. Anti-dsDNA and anti-Smith are specific. Weighted scoring replaced 1997 criteria. Anti-dsDNA: monitor for flare (rising titer). Low complement: active disease.",5,"recall",["SLE","classification","ANA"],"rheum-lupus"));
cards.push(c("card-tn3-rheum-"+n++,"How is SLE managed by severity?","Mild (skin/joints): HCQ + NSAIDs + topical steroids. Moderate (serositis/cytopenias): + low-dose pred + MTX/AZA. Severe (nephritis/CNS): + high-dose steroids + MMF or cyclophosphamide + belimumab","HCQ for ALL SLE: reduces flares, damage, mortality, thrombosis. 5mg/kg/day. Eye exam after 5yr. Lupus nephritis: biopsy to classify, Class III/IV need aggressive IS. Voclosporin newer option for nephritis.",5,"apply",["SLE","hydroxychloroquine","management"],"rheum-lupus"));
cards.push(c("card-tn3-rheum-"+n++,"What lab monitoring is needed in SLE?","CBC (cytopenias), Cr, urinalysis + uPCR, C3/C4 (low=active), anti-dsDNA (rising=flare), ESR. Active nephritis: low complement + rising dsDNA + active sediment (RBC casts, proteinuria)","SLEDAI for disease activity. Drug monitoring: CBC for AZA/MTX, LFTs for MTX, eye exam for HCQ. Distinguish flare from infection: procalcitonin may help. Annual: lipids, glucose (accelerated atherosclerosis).",4,"apply",["SLE","monitoring","complement"],"rheum-lupus"));
cards.push(c("card-tn3-rheum-"+n++,"What are the major complications of SLE?","Nephritis (50%), accelerated atherosclerosis (leading late death), infections (leading early death), AVN (steroids), APS (20-30%), lymphoma risk","CV disease 5-10x. Manage CV risk aggressively. Pregnancy: high-risk, plan when quiescent x6mo. Anti-Ro/La: neonatal lupus risk, congenital heart block 2%.",4,"recall",["SLE","complications","nephritis"],"rheum-lupus"));
cards.push(c("card-tn3-rheum-"+n++,"What is antiphospholipid syndrome and how is it managed?","Clinical (thrombosis or pregnancy morbidity) + lab (LAC, aCL, anti-B2GP x2 tests 12wk apart). Treatment: lifelong warfarin (NOT DOACs per TRAPS trial). Pregnancy: LMWH + ASA","APS primary or secondary to SLE. INR 2-3 venous, consider 3-4 arterial. Catastrophic APS: multi-organ failure, treat with plasma exchange + anticoag + steroids + IVIG. DOACs inferior to warfarin.",5,"apply",["APS","antiphospholipid","warfarin"],"rheum-lupus"));
cards.push(c("card-tn3-rheum-"+n++,"How is SLE managed in pregnancy?","Continue HCQ (safe, protective). Stop MTX/MMF/CYC (teratogenic). Use AZA if IS needed. ASA from 12wk. Monitor anti-Ro (2% CHB risk, fetal HR from 16wk). Plan when quiescent >=6mo","Flare vs preeclampsia: low complement + active sediment = flare. High-risk: preeclampsia, flare, IUGR, preterm. Multidisciplinary care. Breastfeeding safe with HCQ, AZA, prednisone, NSAIDs.",5,"apply",["SLE","pregnancy","HCQ"],"rheum-lupus"));
cards.push(c("card-tn3-rheum-"+n++,"What is drug-induced lupus?","Triggers: hydralazine, procainamide, INH, minocycline, TNFi. Features: arthralgia, serositis, no renal/CNS. Anti-histone Ab+ (>95%), anti-dsDNA usually negative. Resolves on discontinuation","Milder than SLE. No nephritis or significant cytopenias. Symptoms resolve weeks-months after stopping drug. Short-course NSAIDs or low-dose prednisone for symptom control if needed.",3,"analyze",["drug-induced lupus","anti-histone"],"rheum-lupus"));
cards.push(c("card-tn3-rheum-"+n++,"What skin manifestations occur in SLE?","Malar rash (spares nasolabial folds), discoid (scarring), photosensitivity, oral ulcers (usually painless), alopecia, Raynaud. Subacute cutaneous: annular, anti-Ro+, photosensitive","Malar vs rosacea (involves nasolabial folds) vs seborrheic dermatitis. Discoid can occur without systemic SLE (5-10% progress). Livedo reticularis suggests APS. Bullous lupus with vesicles/bullae.",3,"recall",["SLE","skin","malar rash"],"rheum-lupus"));
cards.push(c("card-tn3-rheum-"+n++,"What is lupus nephritis classification and treatment?","ISN/RPS I-VI. Class III/IV (proliferative): induction with MMF or CYC + steroids, maintenance with MMF/AZA. Class V (membranous): treat if nephrotic. Add belimumab or voclosporin","Biopsy essential for classification. Class IV worst prognosis. Target: proteinuria <0.5-0.8g/d by 12mo. 10-30% progress to ESRD. Monitor creatinine, proteinuria, complement, anti-dsDNA serially.",5,"apply",["lupus nephritis","ISN/RPS","MMF"],"rheum-lupus"));
cards.push(c("card-tn3-rheum-"+n++,"What infection risks exist in immunosuppressed SLE patients?","Increased: bacterial (pneumonia, UTI), herpes zoster, PCP, CMV, TB. Vaccinate before IS (no live vaccines on IS). PCP prophylaxis with TMP-SMX on CYC or high-dose steroids","Infections = leading cause early SLE death. Screen latent TB before biologics/CYC. Update pneumococcal, influenza, COVID, HBV. Shingrix (non-live) safe on IS. Fever: distinguish flare vs infection.",4,"apply",["SLE","infection","immunosuppression"],"rheum-lupus"));

console.log("Rheum cards added. Total: " + cards.length);
fs.writeFileSync("C:/dev/srs-mccqe1/data/_parts1234.json", JSON.stringify(cards));
console.log("Saved");
