const crypto = require('crypto');
function id(q) { return 'card-' + crypto.createHash('sha256').update(q.trim().toLowerCase()).digest('hex').slice(0,12); }
const cards = [];
function add(topicId, question, answer, explanation, difficulty, bloomLevel, tags) {
  cards.push({ id: id(question), question, answer, explanation, difficulty, bloomLevel, tags, topicId });
}

// card-htn (need 5)
add('card-htn','What is the target blood pressure for patients with diabetes according to Hypertension Canada 2020?','<130/80 mmHg','Diabetes Canada and Hypertension Canada recommend a target of <130/80 mmHg for patients with diabetes to reduce microvascular and macrovascular complications. SPRINT-like intensive targets may apply to high-risk non-diabetic patients.',2,'recall',['hypertension','diabetes','BP-target','Hypertension-Canada']);
add('card-htn','Which antihypertensive is contraindicated in bilateral renal artery stenosis?','ACE inhibitors and ARBs','ACEi/ARBs dilate the efferent arteriole, which maintains GFR in the setting of reduced renal perfusion. In bilateral RAS, blocking this mechanism can precipitate acute kidney injury. Screen with renal Doppler or MRA if suspected.',3,'apply',['hypertension','renal-artery-stenosis','ACEi','ARB','AKI']);
add('card-htn','What defines resistant hypertension?','BP above target despite optimal doses of 3 antihypertensives including a diuretic, or controlled BP requiring 4 or more agents','Resistant HTN affects ~10% of treated patients. Exclude pseudoresistance (non-adherence, white-coat effect). Work up for secondary causes: primary aldosteronism, renal artery stenosis, pheochromocytoma, OSA. Spironolactone is the recommended add-on.',3,'apply',['resistant-hypertension','spironolactone','secondary-hypertension','adherence']);
add('card-htn','What is the most common secondary cause of hypertension?','Primary aldosteronism (Conn syndrome)','Primary aldosteronism accounts for 5-10% of all hypertension and up to 20% of resistant HTN. Screening: aldosterone-to-renin ratio (ARR). Confirmatory testing with salt loading or fludrocortisone suppression test. Treatment: surgery for adenoma, spironolactone for bilateral hyperplasia.',3,'apply',['primary-aldosteronism','Conn-syndrome','ARR','secondary-hypertension']);
add('card-htn','A patient presents with severe hypertension (220/130 mmHg), headache, and papilledema. What is the diagnosis and initial management?','Hypertensive emergency with papilledema (malignant hypertension); IV labetalol or nicardipine to lower MAP by no more than 25% in the first hour','Hypertensive emergency involves end-organ damage (encephalopathy, AKI, pulmonary edema, aortic dissection). Rapid but controlled BP reduction is essential — excessive lowering risks cerebral ischemia. IV agents allow titration.',4,'analyze',['hypertensive-emergency','papilledema','labetalol','nicardipine','end-organ-damage']);

// endo-dm (need 18)
add('endo-dm','What is the diagnostic criterion for diabetes using fasting plasma glucose?','FPG ≥7.0 mmol/L on two separate occasions','Diabetes Canada criteria: FPG ≥7.0, 2h OGTT ≥11.1, HbA1c ≥6.5%, or random PG ≥11.1 with symptoms. Two abnormal tests on different days are required in asymptomatic patients. A single test suffices if symptomatic with random PG ≥11.1.',1,'recall',['diabetes','FPG','diagnosis','Diabetes-Canada']);
add('endo-dm','What is the HbA1c target for most adults with type 2 diabetes per Diabetes Canada?','≤7.0%','A target of ≤7.0% reduces microvascular complications. Individualize: ≤6.5% for some (short duration, no CVD); 7.1-8.5% for frail elderly, limited life expectancy, or recurrent severe hypoglycemia. Avoid intensive targets if hypoglycemia unawareness.',2,'recall',['diabetes','HbA1c','target','Diabetes-Canada']);
add('endo-dm','What is the first-line pharmacotherapy for type 2 diabetes?','Metformin','Metformin reduces hepatic glucose production and improves insulin sensitivity. Start 500 mg daily, titrate to 1000 mg BID. Contraindicated if eGFR <30. Reduce dose if eGFR 30-45. Main side effect: GI (diarrhea, nausea). Rare but serious: lactic acidosis.',1,'recall',['metformin','diabetes','first-line','pharmacotherapy']);
add('endo-dm','A patient with T2DM and established ASCVD is not at HbA1c target on metformin. Which second-line agent is preferred?','SGLT2 inhibitor (empagliflozin, canagliflozin) or GLP-1 RA (liraglutide, semaglutide) with proven CV benefit','EMPA-REG OUTCOME, CANVAS, and LEADER trials showed CV mortality reduction with these agents. Diabetes Canada recommends adding an agent with proven CV benefit for patients with established ASCVD, regardless of HbA1c.',3,'apply',['diabetes','SGLT2i','GLP1-RA','cardiovascular','ASCVD']);
add('endo-dm','What is diabetic ketoacidosis (DKA) and what are its diagnostic criteria?','Metabolic emergency: blood glucose >14 mmol/L, serum bicarbonate <18 mmol/L, pH <7.30, positive serum ketones, anion gap >12','DKA results from absolute or relative insulin deficiency with counter-regulatory hormone excess. Treatment: IV fluids (NS initially), IV insulin infusion, potassium replacement (add K+ when <5.3), monitor q1-2h. Look for precipitant: infection, missed insulin, new-onset T1DM.',3,'apply',['DKA','ketoacidosis','anion-gap','insulin','type-1-diabetes']);
add('endo-dm','What is the Somogyi effect vs. dawn phenomenon in diabetes management?','Dawn phenomenon: early morning hyperglycemia due to overnight GH/cortisol surge (normal physiology); Somogyi effect: rebound hyperglycemia from nocturnal hypoglycemia triggering counter-regulatory hormones','Distinguish by checking 3 AM glucose: low in Somogyi (reduce evening insulin), normal/high in dawn phenomenon (increase basal insulin or add evening dose). Dawn phenomenon is more common.',3,'apply',['dawn-phenomenon','Somogyi','nocturnal-hypoglycemia','insulin-adjustment']);
add('endo-dm','Which microvascular complications should be screened for annually in diabetes?','Retinopathy (dilated eye exam), nephropathy (urine ACR + eGFR), neuropathy (monofilament foot exam)','Screening starts at diagnosis for T2DM and 5 years after diagnosis for T1DM (then annually). ACR >2 mg/mmol (men) or >2.8 mg/mmol (women) indicates albuminuria. Refer for laser photocoagulation if proliferative retinopathy.',2,'recall',['diabetes','microvascular','retinopathy','nephropathy','neuropathy']);
add('endo-dm','What is hyperosmolar hyperglycemic state (HHS) and how does it differ from DKA?','HHS: extreme hyperglycemia (>33 mmol/L), hyperosmolality (>320 mOsm/kg), minimal ketosis, altered mental status; typically T2DM; higher mortality than DKA','HHS develops insidiously with massive dehydration (8-12L deficit). Treatment priority: aggressive IV fluids before insulin. Insulin is given at lower rates than DKA. Precipitants: infection, non-compliance, new diagnosis, medications (steroids, thiazides).',4,'analyze',['HHS','hyperosmolar','T2DM','dehydration','osmolality']);
add('endo-dm','What is the role of continuous glucose monitoring (CGM) in diabetes management?','CGM provides real-time interstitial glucose readings, reveals glycemic variability, and improves time in range (3.9-10 mmol/L); recommended for T1DM and insulin-treated T2DM','Flash CGM (FreeStyle Libre) and real-time CGM (Dexcom) reduce HbA1c and hypoglycemia. Time in range >70% correlates with HbA1c ~7%. Alerts for hypo/hyperglycemia improve safety, especially in hypoglycemia unawareness.',2,'recall',['CGM','continuous-glucose-monitoring','time-in-range','diabetes-technology']);
add('endo-dm','A patient with T2DM on metformin and gliclazide presents with diaphoresis, tremor, and confusion. Glucose is 2.8 mmol/L. What is the treatment?','Administer 15-20g fast-acting glucose (glucose tablets, juice); recheck in 15 min; if still <4 mmol/L repeat; follow with complex carbohydrate snack','Sulfonylureas (gliclazide, glyburide) cause hypoglycemia by stimulating insulin secretion regardless of glucose level. Glyburide has higher hypoglycemia risk than gliclazide. In severe cases (unconscious): IV dextrose 50% or IM glucagon 1 mg.',3,'apply',['hypoglycemia','sulfonylurea','gliclazide','treatment','glucagon']);
add('endo-dm','What are the Canadian Diabetes Association recommendations for lipid management in diabetes?','Statin therapy for all T2DM patients ≥40 years or with microvascular disease, regardless of baseline LDL; target LDL <2.0 mmol/L or >50% reduction','Most T2DM patients qualify for statin therapy. High-intensity statin (atorvastatin 40-80mg, rosuvastatin 20-40mg) for those with ASCVD. Ezetimibe or PCSK9 inhibitors for those not at target on maximally tolerated statin.',2,'recall',['diabetes','statin','LDL','lipid-management','cardiovascular-prevention']);
add('endo-dm','What is the pathophysiology of type 1 diabetes?','Autoimmune destruction of pancreatic beta cells by T lymphocytes, leading to absolute insulin deficiency; associated with HLA-DR3/DR4, anti-GAD, anti-IA2, anti-insulin antibodies','T1DM typically presents in children/young adults with polyuria, polydipsia, weight loss, and DKA. C-peptide is low/undetectable. Requires lifelong insulin therapy. Autoantibody testing confirms autoimmune etiology.',2,'recall',['type-1-diabetes','autoimmune','beta-cell','anti-GAD','HLA']);
add('endo-dm','What insulin regimen best mimics physiologic insulin secretion?','Basal-bolus regimen: long-acting insulin (glargine or detemir) once/twice daily + rapid-acting (lispro, aspart) before meals','Basal insulin covers hepatic glucose output between meals; bolus insulin covers postprandial glucose excursions. Insulin pump therapy (CSII) provides most flexible basal-bolus delivery. Carb counting guides bolus dosing.',2,'recall',['insulin','basal-bolus','glargine','rapid-acting','carb-counting']);
add('endo-dm','Which oral diabetes medication causes weight loss?','SGLT2 inhibitors (empagliflozin, dapagliflozin, canagliflozin) — cause glucosuria and caloric loss; GLP-1 RAs also cause weight loss (injectable, not oral except oral semaglutide)','SGLT2i cause ~2-3 kg weight loss. Side effects: genital mycotic infections, UTIs, euglycemic DKA (rare), Fournier gangrene (very rare). Avoid if eGFR <20 for glycemic effect (renal/cardiac benefits persist at lower eGFR).',2,'recall',['SGLT2i','weight-loss','diabetes','glucosuria','empagliflozin']);
add('endo-dm','What is gestational diabetes and how is it screened?','Glucose intolerance first diagnosed in pregnancy; screen all pregnant women at 24-28 weeks with 50g glucose challenge test (GCT) or 75g OGTT','GCT: 1h glucose ≥7.8 → proceed to 75g OGTT. OGTT diagnostic criteria (Diabetes Canada): fasting ≥5.1, 1h ≥10.0, 2h ≥8.5. Management: dietary modification first, insulin if targets not met. Metformin is second-line. Increases risk of future T2DM.',3,'apply',['gestational-diabetes','GDM','screening','OGTT','pregnancy']);
add('endo-dm','What is the significance of microalbuminuria in diabetes?','Earliest sign of diabetic nephropathy; ACR 2-20 mg/mmol indicates microalbuminuria; warrants ACEi/ARB initiation regardless of blood pressure','Microalbuminuria also predicts cardiovascular disease in diabetes. Confirm with repeat testing (2 of 3 samples abnormal). ACEi/ARBs reduce progression to macroalbuminuria and ESRD. SGLT2i provide additional nephroprotection.',3,'apply',['microalbuminuria','diabetic-nephropathy','ACR','ACEi','nephroprotection']);
add('endo-dm','A patient with T1DM develops gastroparesis. What is the pathophysiology and management?','Autonomic neuropathy damages vagus nerve → delayed gastric emptying; management: small frequent meals, low-fat/low-fiber diet, prokinetics (domperidone, metoclopramide), optimize glycemic control','Gastroparesis causes nausea, vomiting, early satiety, and erratic glucose levels. Diagnosed by gastric emptying scintigraphy (>10% retention at 4h). Metoclopramide has risk of tardive dyskinesia (limit to <12 weeks).',3,'apply',['gastroparesis','autonomic-neuropathy','diabetes','domperidone','vagus-nerve']);
add('endo-dm','What are the indications for insulin therapy in type 2 diabetes?','Symptomatic hyperglycemia, HbA1c >1.5% above target despite oral agents, pregnancy, renal/hepatic failure limiting oral agents, acute illness/surgery, or when oral agents fail to achieve targets','Start with bedtime basal insulin (NPH or glargine) 10 units or 0.1-0.2 U/kg. Titrate by 1-2 units every 3-7 days to fasting glucose target. Add mealtime insulin if postprandial glucose remains elevated.',3,'apply',['insulin','type-2-diabetes','indications','basal-insulin','intensification']);

// psych-mood (need 19)
add('psych-mood','What are the DSM-5 criteria for a major depressive episode?','≥5 of 9 SIGECAPS criteria for ≥2 weeks, including depressed mood or anhedonia: Sleep changes, Interest loss, Guilt, Energy loss, Concentration difficulty, Appetite changes, Psychomotor changes, Suicidal ideation','Symptoms must cause significant functional impairment and not be attributable to substances or medical conditions. Must exclude bipolar disorder by screening for past mania/hypomania. PHQ-9 is a validated screening tool.',2,'recall',['depression','DSM-5','SIGECAPS','major-depressive-episode','PHQ-9']);
add('psych-mood','What is the first-line pharmacotherapy for moderate-to-severe major depressive disorder?','SSRI (sertraline, escitalopram, fluoxetine) or SNRI (venlafaxine, duloxetine)','SSRIs are preferred for their favorable side-effect profile. Onset of therapeutic effect: 2-4 weeks. Full effect at 6-8 weeks. Continue for ≥6-12 months after remission for first episode; longer for recurrent episodes. CANMAT guidelines recommend SSRIs first-line.',2,'recall',['depression','SSRI','first-line','sertraline','escitalopram']);
add('psych-mood','A patient with depression has not responded to an adequate trial of sertraline. What are the next steps per CANMAT guidelines?','Optimize dose, ensure adequate duration (4-6 weeks at therapeutic dose), then switch to another SSRI/SNRI, or augment with aripiprazole, lithium, or add psychotherapy','STAR*D trial showed ~30% remission with first SSRI, decreasing with each subsequent trial. Augmentation strategies: aripiprazole (best evidence), lithium, bupropion add-on, or mirtazapine combination ("California rocket fuel" with SNRI).',3,'apply',['treatment-resistant-depression','CANMAT','augmentation','aripiprazole','STAR-D']);
add('psych-mood','What distinguishes bipolar I from bipolar II disorder?','Bipolar I: at least one manic episode (≥7 days or hospitalized); Bipolar II: at least one hypomanic episode (≥4 days) + at least one major depressive episode; no full mania in BP-II','Bipolar II is not a milder form — depression burden is often greater. Misdiagnosis as unipolar depression is common (always screen for hypomania). Antidepressant monotherapy in bipolar can trigger mania/rapid cycling.',3,'apply',['bipolar','mania','hypomania','DSM-5','mood-disorders']);
add('psych-mood','What are the first-line mood stabilizers for acute mania?','Lithium, valproic acid (divalproex), or atypical antipsychotics (quetiapine, risperidone, olanzapine, aripiprazole)','Lithium is most effective for classic euphoric mania and has anti-suicidal properties. Valproate is preferred for mixed episodes and rapid cycling. Atypical antipsychotics have fastest onset. Combination therapy often needed for severe mania.',3,'apply',['mania','lithium','valproate','mood-stabilizer','antipsychotic']);
add('psych-mood','What monitoring is required for a patient on lithium?','Lithium level (0.6-1.2 mEq/L), renal function (creatinine, eGFR), TSH, calcium, ECG at baseline; levels q3-6 months, renal/thyroid annually','Lithium causes nephrogenic diabetes insipidus (polyuria), hypothyroidism (20%), hyperparathyroidism, and renal tubular injury. Narrow therapeutic index — toxicity risk with dehydration, NSAIDs, ACEi, thiazides. Teratogenic (Ebstein anomaly).',3,'apply',['lithium','monitoring','therapeutic-drug-monitoring','thyroid','nephrotoxicity']);
add('psych-mood','What is the role of electroconvulsive therapy (ECT) in mood disorders?','ECT is highly effective (70-90% response) for severe, treatment-resistant depression, catatonia, psychotic depression, and acute suicidality when rapid response is needed','ECT is safe with modern anesthesia. Main side effect: transient retrograde amnesia. Contraindicated: raised ICP. Can be used in pregnancy. Maintenance ECT prevents relapse. Stigma remains a barrier to appropriate use.',3,'apply',['ECT','electroconvulsive-therapy','treatment-resistant','depression','catatonia']);
add('psych-mood','A 25-year-old woman presents with depressed mood, hypersomnia, increased appetite, and leaden paralysis. What depression subtype is this?','Atypical depression — characterized by mood reactivity, hypersomnia, increased appetite/weight gain, leaden paralysis, rejection sensitivity','Atypical depression responds better to MAOIs and SSRIs than TCAs. It is common in bipolar II depression. Distinguish from melancholic depression (anhedonia, early morning awakening, weight loss, psychomotor changes, worse in morning).',3,'apply',['atypical-depression','mood-reactivity','hypersomnia','depression-subtype']);
add('psych-mood','What is the Edinburgh Postnatal Depression Scale (EPDS) used for?','Screening for perinatal depression (antepartum and postpartum); 10-item self-report questionnaire; score ≥13 suggests major depression','Perinatal depression affects 10-20% of women. Screen at first prenatal visit and postpartum. Treatment: psychotherapy (CBT, IPT) for mild-moderate; SSRIs (sertraline preferred due to low breastmilk levels) for moderate-severe.',2,'recall',['postpartum-depression','EPDS','perinatal','screening','depression']);
add('psych-mood','What is persistent depressive disorder (dysthymia)?','Chronic depressed mood for ≥2 years (≥1 year in children/adolescents) with ≥2 of: appetite changes, sleep changes, low energy, low self-esteem, poor concentration, hopelessness','Dysthymia is less severe but more chronic than MDD. "Double depression" occurs when MDD superimposes on dysthymia. Treatment: antidepressants + psychotherapy (CBASP is specifically designed for chronic depression).',2,'recall',['dysthymia','persistent-depressive-disorder','chronic-depression','DSM-5']);
add('psych-mood','Which antidepressant should be avoided in patients with seizure disorders?','Bupropion — dose-dependently lowers seizure threshold (risk highest at doses >450 mg/day)','Bupropion is contraindicated in seizure disorders, eating disorders (bulimia/anorexia), and abrupt alcohol/benzodiazepine withdrawal. It is useful for patients concerned about sexual dysfunction or weight gain as it lacks both side effects.',2,'recall',['bupropion','seizure','antidepressant','contraindication']);
add('psych-mood','What is the recommended duration of antidepressant treatment after a first episode of MDD?','Continue for at least 6-12 months after achieving remission, then gradually taper over 2-4 weeks','Premature discontinuation risks relapse (50% within 6 months). For recurrent episodes (≥3) or chronic MDD: consider indefinite maintenance. When tapering, reduce by 25% every 2-4 weeks. Discontinuation syndrome: dizziness, nausea, paresthesias, irritability.',2,'recall',['antidepressant','duration','maintenance','discontinuation','relapse-prevention']);
add('psych-mood','A 68-year-old man with depression has prominent psychomotor retardation, early morning awakening, anorexia, and nihilistic delusions. What is the subtype and treatment?','Psychotic depression (MDD with psychotic features); treatment: antidepressant + antipsychotic combination, or ECT','Psychotic depression has a poor response to antidepressant monotherapy (~25% vs ~50% for non-psychotic MDD). Combination of SSRI/SNRI + olanzapine or quetiapine is effective. ECT has highest response rate (>80%). Hospitalization usually required.',4,'analyze',['psychotic-depression','nihilistic-delusions','ECT','antipsychotic','treatment']);
add('psych-mood','What are the key differences between grief and major depressive disorder?','Grief: sadness in waves triggered by reminders, self-esteem preserved, may see/hear deceased briefly; MDD: persistent pervasive depressed mood, worthlessness/guilt, suicidal ideation, functional impairment ≥2 weeks','DSM-5 removed the bereavement exclusion — MDD can be diagnosed during bereavement if full criteria are met. Prolonged grief disorder (>12 months) is a separate DSM-5-TR diagnosis.',3,'apply',['grief','bereavement','depression','DSM-5','prolonged-grief']);
add('psych-mood','What is seasonal affective disorder (SAD) and what is its first-line treatment?','Recurrent MDD with seasonal pattern (typically winter); first-line: bright light therapy (10,000 lux for 30 min each morning) and/or SSRIs','SAD is more common at higher latitudes. Light therapy should be started in early fall for prevention. CBT adapted for SAD is also effective. Bupropion XL is approved for SAD prevention. Melatonin has limited evidence.',2,'recall',['SAD','seasonal-affective-disorder','light-therapy','winter-depression']);
add('psych-mood','What are the warning signs that a depressed patient may have undiagnosed bipolar disorder?','Early onset (<25), family history of bipolar, antidepressant-induced mania/hypomania, rapid cycling, psychotic features, atypical features, treatment resistance to antidepressants','Up to 40% of bipolar patients are initially misdiagnosed with unipolar depression. Mood Disorder Questionnaire (MDQ) screens for bipolar. Always ask about prior manic/hypomanic episodes before starting antidepressants.',3,'apply',['bipolar','misdiagnosis','screening','antidepressant-induced-mania','MDQ']);
add('psych-mood','What is the mechanism of action of SSRIs?','Selective inhibition of serotonin reuptake transporter (SERT) in presynaptic neurons, increasing serotonin availability in the synaptic cleft','Therapeutic effect takes 2-4 weeks due to 5-HT1A autoreceptor desensitization. Common side effects: nausea, headache, sexual dysfunction, insomnia/somnolence, weight gain (long-term). Activation syndrome in first weeks (anxiety, agitation) — monitor closely in youth.',2,'recall',['SSRI','mechanism','serotonin','SERT','pharmacology']);
add('psych-mood','A patient on paroxetine for 3 years wants to stop. After abrupt cessation she develops dizziness, electric shock sensations, nausea, and irritability. What is this?','SSRI discontinuation syndrome — most common with short half-life SSRIs (paroxetine, venlafaxine); symptoms begin 1-3 days after stopping','FINISH mnemonic: Flu-like symptoms, Insomnia, Nausea, Imbalance, Sensory disturbances (brain zaps), Hyperarousal. Treatment: restart SSRI and taper gradually. Fluoxetine has longest half-life and rarely causes discontinuation syndrome.',3,'apply',['discontinuation-syndrome','paroxetine','SSRI','brain-zaps','tapering']);
add('psych-mood','What is the role of ketamine and esketamine in treatment-resistant depression?','Rapid-acting antidepressant (hours to days vs weeks for SSRIs); esketamine (Spravato) nasal spray is approved for TRD in combination with an oral antidepressant; NMDA receptor antagonist','Ketamine provides rapid relief of suicidal ideation. Must be administered in monitored healthcare setting due to dissociation, BP elevation, and abuse potential. Effects are transient; repeated dosing needed. IV ketamine is also used off-label.',4,'analyze',['ketamine','esketamine','treatment-resistant-depression','NMDA','rapid-acting']);

// derm-general (need 21)
add('derm-general','What is the difference between a macule and a papule?','Macule: flat, non-palpable lesion <1 cm (if >1 cm = patch); Papule: raised, palpable lesion <1 cm (if >1 cm = plaque)','Dermatology description follows a systematic approach: distribution, configuration, morphology (primary lesion type), color, border, surface. Secondary lesions include scale, crust, erosion, ulcer, excoriation, lichenification.',1,'recall',['dermatology','morphology','macule','papule','terminology']);
add('derm-general','What is the most common cause of erythema nodosum?','Idiopathic (50%); when a cause is identified: streptococcal infection, sarcoidosis, IBD, OCP use, pregnancy','Erythema nodosum presents as tender red nodules on the anterior shins (septal panniculitis). Self-limiting over 3-6 weeks. Treatment: NSAIDs, rest, compression stockings. Biopsy rarely needed. Investigate for underlying cause.',3,'apply',['erythema-nodosum','panniculitis','sarcoidosis','IBD','shin-nodules']);
add('derm-general','A patient presents with target (iris) lesions on palms and soles. What is the diagnosis?','Erythema multiforme — most commonly triggered by HSV infection (>50% of cases); also drugs (sulfonamides, phenytoin, penicillin)','EM minor: target lesions with mild/no mucosal involvement. EM major: mucosal involvement ≥2 sites. Distinguish from SJS (atypical targets, widespread, drug-induced). Treat underlying HSV with prophylactic acyclovir if recurrent.',3,'apply',['erythema-multiforme','target-lesion','HSV','drug-reaction']);
add('derm-general','What is dermatomyositis and what are its pathognomonic skin findings?','Autoimmune inflammatory myopathy; heliotrope rash (violaceous eyelid erythema with edema) and Gottron papules (erythematous papules over MCPs, PIPs, knuckles)','Additional findings: V-sign (chest), shawl sign (shoulders/back), mechanic\'s hands, periungual telangiectasia. Associated with malignancy in adults (20-25%) — requires age-appropriate cancer screening. CK elevated, anti-Mi-2, anti-Jo-1 antibodies.',3,'apply',['dermatomyositis','heliotrope-rash','Gottron-papules','myopathy','malignancy-screening']);
add('derm-general','What is the most effective treatment for moderate-to-severe plaque psoriasis not responding to topicals?','Biologic therapy (TNF inhibitors, IL-17 inhibitors like secukinumab, IL-23 inhibitors like guselkumab) or phototherapy (NB-UVB)','Step-up approach: topicals → phototherapy → systemic (methotrexate, cyclosporine) → biologics. PASI score measures severity. Biologics achieve PASI 75 in 70-90% of patients. Screen for TB and hepatitis before biologics.',3,'apply',['psoriasis','biologic','IL-17','phototherapy','PASI']);
add('derm-general','A 40-year-old woman has symmetric hyperpigmented velvety plaques in axillae and neck. BMI is 38. What is the diagnosis?','Acanthosis nigricans — marker of insulin resistance; associated with obesity, T2DM, PCOS, and rarely internal malignancy (gastric cancer)','Acanthosis nigricans in young obese patients suggests metabolic syndrome/prediabetes. Screen with fasting glucose and HbA1c. Treatment: address underlying insulin resistance (weight loss, metformin). Malignancy-associated AN appears rapidly and is widespread.',2,'recall',['acanthosis-nigricans','insulin-resistance','obesity','metabolic-syndrome']);
add('derm-general','What is pemphigus vulgaris and how is it diagnosed?','Autoimmune blistering disease with flaccid blisters and erosions of skin and mucous membranes; anti-desmoglein 3 (mucosal) and anti-desmoglein 1 (cutaneous) antibodies; diagnose by biopsy with direct immunofluorescence','DIF shows intercellular IgG in a "chicken wire" pattern (intraepidermal acantholysis). Nikolsky sign positive (gentle pressure causes blistering). Treatment: systemic corticosteroids + rituximab (now first-line steroid-sparing agent).',4,'analyze',['pemphigus-vulgaris','autoimmune-blistering','desmoglein','Nikolsky-sign','rituximab']);
add('derm-general','What is the difference between bullous pemphigoid and pemphigus vulgaris?','BP: tense blisters, subepidermal split, anti-BP180/BP230 antibodies, linear IgG at BMZ on DIF, elderly patients, lower mortality; PV: flaccid blisters, intraepidermal split, anti-desmoglein, higher mortality','BP presents as tense blisters on an urticarial base, often on trunk/extremities. PV has fragile flaccid blisters that rupture easily leaving erosions. Oral involvement is common in PV (often presenting sign) but rare in BP.',3,'apply',['bullous-pemphigoid','pemphigus-vulgaris','blistering-disease','DIF','autoimmune']);
add('derm-general','A 16-year-old girl has painful oral ulcers, genital ulcers, and anterior uveitis. What is the diagnosis?','Behcet disease — systemic vasculitis with recurrent oral and genital ulcers, uveitis, pathergy, skin lesions','Behcet disease is more common along the Silk Road (Turkey, Middle East, East Asia). HLA-B51 associated. Pathergy test: papule/pustule at site of needle prick. Treatment: colchicine for mucocutaneous disease, immunosuppressants for severe organ involvement.',3,'apply',['Behcet-disease','oral-ulcers','genital-ulcers','uveitis','pathergy']);
add('derm-general','What is the classic presentation of pityriasis rosea?','Herald patch (single oval, scaly, salmon-colored plaque) followed 1-2 weeks later by smaller similar lesions in a "Christmas tree" distribution on the trunk','Pityriasis rosea is likely viral (HHV-6/7). Self-limiting over 6-8 weeks. Pruritus is mild. Must distinguish from secondary syphilis (check RPR/VDRL, especially if palms/soles involved). No treatment needed; UVB can shorten course.',2,'recall',['pityriasis-rosea','herald-patch','Christmas-tree','HHV-6','self-limiting']);
add('derm-general','What is urticaria and when does it become chronic?','Urticaria: pruritic, erythematous, edematous wheals (hives) that are transient (<24h per lesion); chronic if episodes persist >6 weeks','Acute urticaria is often allergic (foods, drugs, infections). Chronic spontaneous urticaria (CSU) is rarely allergic — often autoimmune (anti-FcεRI antibodies). Treatment: second-generation antihistamines (cetirizine, loratadine); omalizumab for refractory CSU.',2,'recall',['urticaria','chronic-urticaria','antihistamine','omalizumab','hives']);
add('derm-general','What is the appropriate workup for suspected cutaneous drug eruption?','Timeline of drug exposure vs. rash onset, morphology classification, drug causality assessment; biopsy if uncertain or severe (SJS/TEN, DRESS)','Exanthematous (morbilliform) eruption is most common drug reaction (4-14 days after starting drug). DRESS syndrome (Drug Reaction with Eosinophilia and Systemic Symptoms) has longer latency (2-8 weeks) and involves liver, kidneys.',3,'apply',['drug-eruption','DRESS','morbilliform','drug-reaction','biopsy']);
add('derm-general','What is seborrheic dermatitis and how is it treated?','Chronic inflammatory condition with greasy, yellowish scales on sebaceous areas (scalp, nasolabial folds, eyebrows); associated with Malassezia yeast; treat with ketoconazole shampoo/cream and low-potency topical corticosteroids','Seborrheic dermatitis is common in infants (cradle cap) and adults. Exacerbated by stress, cold weather, and immunosuppression (severe in HIV — consider HIV testing if extensive). Calcineurin inhibitors (pimecrolimus) are steroid-sparing options.',2,'recall',['seborrheic-dermatitis','Malassezia','ketoconazole','scalp','cradle-cap']);
add('derm-general','A patient presents with diffuse hair loss 3 months after a severe illness. What is the diagnosis?','Telogen effluvium — diffuse non-scarring alopecia occurring 2-4 months after a stressor (illness, surgery, pregnancy, crash diet, medication)','Telogen effluvium shifts a large proportion of hairs into the telogen (resting) phase simultaneously. Self-limiting over 6-12 months. No specific treatment needed. Pull test is positive (>10% of pulled hairs in telogen). Distinguish from alopecia areata (patchy) and androgenetic alopecia.',2,'recall',['telogen-effluvium','alopecia','hair-loss','non-scarring','stress']);
add('derm-general','What is the significance of a positive Nikolsky sign?','Lateral pressure on skin causes detachment of epidermis; indicates intraepidermal blister (pemphigus vulgaris, SJS/TEN, staphylococcal scalded skin syndrome)','Nikolsky sign is absent in bullous pemphigoid (subepidermal split). Asboe-Hansen sign: extension of blister with gentle pressure. Both suggest fragile skin. In SSSS (staphylococcal scalded skin syndrome), exfoliative toxin causes superficial epidermal split.',2,'recall',['Nikolsky-sign','pemphigus','SJS','SSSS','blistering']);
add('derm-general','What is the approach to a patient with suspected scabies?','Intensely pruritic rash (worse at night) with burrows in web spaces, wrists, and genitalia; diagnose by skin scraping with mineral oil showing mites/eggs; treat with permethrin 5% cream applied neck down, wash off after 8-14 hours','Treat all household contacts simultaneously. Wash clothing/bedding in hot water. Repeat permethrin in 1-2 weeks. Oral ivermectin (200 mcg/kg × 2 doses) for crusted (Norwegian) scabies or institutional outbreaks. Post-scabies itch may persist for 2-4 weeks.',3,'apply',['scabies','permethrin','ivermectin','burrows','pruritus']);
add('derm-general','What is the difference between scarring and non-scarring alopecia?','Non-scarring: follicular openings preserved (telogen effluvium, androgenetic, alopecia areata); Scarring: follicular openings destroyed (lichen planopilaris, discoid lupus, central centrifugal cicatricial alopecia)','Scarring alopecia is irreversible — early diagnosis and treatment are crucial to prevent further hair loss. Scalp biopsy is indicated for scarring alopecia. Non-scarring alopecia is usually reversible.',2,'recall',['alopecia','scarring','non-scarring','follicular','lichen-planopilaris']);
add('derm-general','A 55-year-old man has facial flushing, papules, pustules, and telangiectasia on the nose and cheeks but no comedones. What is the diagnosis?','Rosacea (papulopustular subtype); distinguished from acne by absence of comedones, presence of flushing/telangiectasia, and central facial distribution','Rosacea triggers: alcohol, spicy food, sun, stress, hot beverages. Treatment: topical metronidazole or azelaic acid for papulopustular; brimonidine for erythema; doxycycline for moderate-severe. Rhinophyma (sebaceous hyperplasia of nose) is a late complication.',2,'recall',['rosacea','papulopustular','flushing','telangiectasia','metronidazole']);
add('derm-general','What is the most common cause of erythroderma (exfoliative dermatitis)?','Exacerbation of pre-existing dermatosis (psoriasis, atopic dermatitis) accounts for ~50%; also drug reactions, CTCL (Sezary syndrome), and idiopathic','Erythroderma: generalized erythema and scaling involving >90% BSA. Medical emergency — high-output cardiac failure, hypothermia, protein loss, infection risk. Admit, IV fluids, emollients, treat underlying cause. Skin biopsy to identify etiology.',4,'analyze',['erythroderma','exfoliative-dermatitis','Sezary-syndrome','psoriasis','emergency']);
add('derm-general','What topical immunomodulators are used as steroid-sparing agents in dermatology?','Calcineurin inhibitors: tacrolimus (Protopic) 0.03%/0.1% and pimecrolimus (Elidel) 1% — safe for face and intertriginous areas where steroids cause atrophy','Calcineurin inhibitors inhibit T-cell activation. No atrophy risk unlike topical steroids. Common side effect: burning/stinging on initial application. FDA black box warning about theoretical lymphoma risk (not confirmed in practice). Used for atopic dermatitis, seborrheic dermatitis, vitiligo.',2,'recall',['calcineurin-inhibitor','tacrolimus','pimecrolimus','steroid-sparing','atopic-dermatitis']);
add('derm-general','What are the clinical features of discoid lupus erythematosus (DLE)?','Chronic scarring plaques with follicular plugging, central atrophy/scarring, hypopigmentation centrally with hyperpigmented borders, primarily on sun-exposed areas (face, scalp, ears)','DLE is the most common form of cutaneous lupus. Only 5-10% progress to SLE. Scalp involvement causes scarring alopecia. Treatment: strict sun protection, topical/intralesional corticosteroids, hydroxychloroquine. Biopsy shows interface dermatitis.',3,'apply',['discoid-lupus','DLE','scarring-alopecia','follicular-plugging','hydroxychloroquine']);

// ph-social-det (need 21)
add('ph-social-det','What are the social determinants of health as defined by the WHO?','Conditions in which people are born, grow, live, work, and age — including income, education, employment, housing, food security, social support, early childhood development, and healthcare access','SDOH account for 30-55% of health outcomes. The remaining is attributed to healthcare (25%), genetics (15%), and health behaviors. Addressing SDOH is essential for health equity.',1,'recall',['social-determinants','WHO','health-equity','SDOH']);
add('ph-social-det','What is health equity versus health equality?','Health equality: same resources/services for everyone; Health equity: resources distributed based on need to achieve equal health outcomes — recognizes that different populations require different support levels','Equity-oriented care acknowledges structural barriers (racism, poverty, colonialism). The Canadian Medical Association recognizes health equity as a priority. Achieving equity may require unequal allocation of resources.',2,'recall',['health-equity','equality','social-determinants','structural-barriers']);
add('ph-social-det','How does income affect health outcomes in Canada?','Low income is the strongest social determinant — associated with 21% shorter life expectancy, higher rates of chronic disease, mental illness, infant mortality, and reduced access to medications and preventive care','The income-health gradient exists across the entire income spectrum (not just poverty). Universal healthcare reduces but does not eliminate income-related health disparities due to gaps in pharmacare, dental, vision, and social services.',3,'apply',['income','poverty','health-gradient','health-outcomes','inequality']);
add('ph-social-det','What is structural racism and how does it affect health?','Systemic policies and practices embedded in institutions that produce and maintain racial inequity in access, treatment, and outcomes — independent of individual prejudice','Indigenous peoples in Canada face lower life expectancy (10-15 years less), higher infant mortality, and disproportionate burden of diabetes, mental health issues, and substance use due to colonial legacy, residential schools, and ongoing systemic barriers.',3,'apply',['structural-racism','Indigenous-health','health-disparities','colonialism']);
add('ph-social-det','What is food insecurity and what is its prevalence in Canada?','Inadequate or insecure access to food due to financial constraints; affects ~12.7% of Canadian households (higher in single-parent, Indigenous, and racialized households)','Food insecurity is associated with poorer diet quality, obesity, diabetes, depression, and medication non-adherence (choosing between food and medications). PROOF (research program) tracks food insecurity. Interventions: income support, food programs, social assistance reform.',2,'recall',['food-insecurity','nutrition','poverty','PROOF','social-determinants']);
add('ph-social-det','How does housing affect health?','Inadequate housing (homelessness, overcrowding, poor conditions) increases risk of respiratory infections, mental illness, injury, substance use, and communicable diseases (TB); housing instability worsens chronic disease management','Housing First programs (providing stable housing without preconditions) improve health outcomes and reduce healthcare costs. Inadequate housing disproportionately affects Indigenous communities, refugees, and those with mental illness.',3,'apply',['housing','homelessness','Housing-First','social-determinants','respiratory-disease']);
add('ph-social-det','What is the concept of intersectionality in health?','Recognition that multiple social identities (race, gender, class, sexuality, disability, Indigeneity) interact to create unique experiences of privilege or oppression that affect health outcomes','Intersectionality explains why a low-income Indigenous woman faces different health barriers than a low-income white man. Clinical practice should consider the cumulative impact of intersecting disadvantages.',3,'apply',['intersectionality','social-identities','health-disparities','equity']);
add('ph-social-det','What are adverse childhood experiences (ACEs) and their long-term health impact?','Childhood abuse, neglect, and household dysfunction (substance use, mental illness, incarceration, domestic violence); ACE score ≥4 associated with dramatically increased risk of chronic disease, mental illness, substance use, and early death','ACEs affect brain development and HPA axis regulation, creating lifelong stress responses. Dose-response relationship: more ACEs = worse outcomes. Trauma-informed care is essential in healthcare settings.',3,'apply',['ACEs','adverse-childhood-experiences','trauma','chronic-disease','HPA-axis']);
add('ph-social-det','What is health literacy and why does it matter?','The ability to access, understand, and use health information to make informed decisions; low health literacy affects ~60% of Canadian adults and is associated with medication errors, poorer self-management, more hospitalizations','Use plain language (grade 6 reading level), teach-back method, visual aids, and culturally appropriate materials. Low health literacy is more prevalent in elderly, immigrants, and those with limited education.',2,'recall',['health-literacy','plain-language','teach-back','patient-education']);
add('ph-social-det','What is cultural safety in healthcare?','Going beyond cultural awareness and cultural competence to create an environment where patients feel safe from discrimination — defined by the patient, not the provider; recognizes power imbalances in the healthcare relationship','Cultural safety is especially important for Indigenous peoples in Canada given historical trauma from residential schools and ongoing systemic racism in healthcare. Providers must examine their own biases and the institutional context.',3,'apply',['cultural-safety','Indigenous-health','power-imbalance','bias','healthcare']);
add('ph-social-det','How does education level affect health outcomes?','Higher education → better health literacy, higher income, healthier behaviors, better working conditions, greater social support; each additional year of education is associated with measurably better health outcomes','Education affects health through multiple pathways: direct (knowledge, health literacy), indirect (employment, income), and psychosocial (sense of control, social networks). Education policy is health policy.',2,'recall',['education','health-outcomes','health-literacy','social-determinants']);
add('ph-social-det','What is the "inverse care law"?','Those who most need medical care are least likely to receive it; described by Tudor Hart (1971) — the availability of good medical care varies inversely with the need for it in the population','The inverse care law operates most completely in market-driven health systems but persists even in universal systems. Marginalized populations face barriers: transportation, childcare, language, distrust of healthcare, lack of culturally safe care.',2,'recall',['inverse-care-law','Tudor-Hart','healthcare-access','equity']);
add('ph-social-det','What is the role of a physician in advocacy for social determinants of health?','Physicians have a professional responsibility to advocate for health equity at individual (screening for SDOH, connecting to resources), community (partnering with organizations), and systemic (policy advocacy) levels','CanMEDS Health Advocate role requires physicians to respond to individual patient needs and advocate for systemic change. Screen for SDOH using tools like the Poverty screening tool ("Do you ever have difficulty making ends meet?").',3,'apply',['advocacy','CanMEDS','health-advocate','SDOH-screening','physician-role']);
add('ph-social-det','What is the impact of immigration and refugee status on health?','Healthy immigrant effect (initially better health than Canadian-born) dissipates over time; refugees face additional challenges: trauma, torture, limited language, precarious immigration status, restricted healthcare coverage','Interim Federal Health Program (IFHP) provides limited coverage for refugee claimants. Barriers include lack of provincial health insurance during waiting periods, difficulty navigating the system, and discrimination.',3,'apply',['immigration','refugee-health','healthy-immigrant-effect','IFHP','healthcare-access']);
add('ph-social-det','What is the Truth and Reconciliation Commission\'s Call to Action for health?','TRC calls include: acknowledging health disparities, increasing Indigenous health professionals, providing cultural competency training, recognizing Indigenous healing practices, addressing SDOH, and closing gaps in health outcomes','The TRC identified 94 Calls to Action (2015). Calls 18-24 specifically address health. Jordan\'s Principle ensures First Nations children receive services without jurisdictional disputes. Medical schools are integrating Indigenous health curricula.',3,'apply',['TRC','Truth-and-Reconciliation','Indigenous-health','Jordan-Principle','Calls-to-Action']);
add('ph-social-det','How does employment and working conditions affect health?','Precarious employment (temporary, part-time, gig work) without benefits (pharmacare, dental, sick leave) worsens health; occupational hazards, workplace stress, and job insecurity contribute to physical and mental health problems','Unemployment is associated with increased mortality, cardiovascular disease, depression, and suicide. Underemployment and presenteeism (working while sick) also have health consequences. Workplace health promotion programs can improve outcomes.',2,'recall',['employment','precarious-work','occupational-health','unemployment','social-determinants']);
add('ph-social-det','What is a trauma-informed approach to care?','Healthcare delivery that recognizes the widespread impact of trauma, understands paths to recovery, recognizes signs/symptoms, integrates knowledge into policies and practices, and actively avoids re-traumatization','Key principles: safety, trustworthiness, peer support, collaboration, empowerment, cultural/gender sensitivity. Ask "what happened to you?" rather than "what\'s wrong with you?" Universal screening for trauma is debated — focus on creating safe environments.',3,'apply',['trauma-informed-care','ACEs','safety','re-traumatization','healthcare']);
add('ph-social-det','What is the difference between upstream and downstream approaches to health?','Downstream: treating individuals after they become ill (clinical care); Upstream: addressing root causes before illness occurs (SDOH, policy, regulation); Midstream: community-level interventions (programs, education)','The river analogy: pulling people out of the river (downstream) vs. preventing them from falling in (upstream). Population health approach requires upstream action on SDOH. Both are necessary; neither is sufficient alone.',2,'recall',['upstream','downstream','population-health','prevention','social-determinants']);
add('ph-social-det','How does social isolation and loneliness affect health?','Social isolation increases mortality risk equivalent to smoking 15 cigarettes/day; associated with increased dementia (50%), coronary heart disease (29%), and stroke (32%) risk','Elderly, immigrants, LGBTQ2S+ individuals, and those with disabilities are at highest risk. Social prescribing (connecting patients to community activities, groups, services) is an emerging intervention. Assess social support as part of comprehensive care.',3,'apply',['social-isolation','loneliness','social-prescribing','mortality','elderly']);
add('ph-social-det','What is environmental racism?','Disproportionate exposure of racialized and marginalized communities to environmental hazards (air pollution, contaminated water, toxic waste, industrial sites) due to systemic inequity','Examples in Canada: Grassy Narrows mercury contamination, boil water advisories in First Nations communities, higher air pollution in low-income neighborhoods. Environmental health is a social determinant requiring policy intervention.',3,'apply',['environmental-racism','environmental-health','Indigenous-health','pollution','water-contamination']);
add('ph-social-det','What is the "two-eyed seeing" approach in Indigenous health?','Integrating Indigenous ways of knowing (traditional healing, ceremony, land-based practices) alongside Western biomedical approaches — giving equal value to both knowledge systems','Coined by Mi\'kmaw Elder Albert Marshall. Respects Indigenous epistemology while utilizing Western medicine. Examples: integrating traditional healers in hospital settings, land-based healing programs for addiction. Required for culturally safe care.',3,'apply',['two-eyed-seeing','Indigenous-health','traditional-healing','cultural-safety','Albert-Marshall']);

// obgyn-obstetric-emerg (need 21)
add('obgyn-obstetric-emerg','What is the definition of postpartum hemorrhage (PPH)?','Blood loss ≥500 mL after vaginal delivery or ≥1000 mL after cesarean section; most common cause is uterine atony (70-80%)','4 T\'s of PPH: Tone (atony), Tissue (retained products), Trauma (lacerations, uterine rupture), Thrombin (coagulopathy). Management: uterine massage, oxytocin 10-40 IU IV, carboprost (Hemabate), tranexamic acid 1g IV within 3h.',3,'apply',['PPH','postpartum-hemorrhage','uterine-atony','oxytocin','4Ts']);
add('obgyn-obstetric-emerg','What is placental abruption and how does it present?','Premature separation of placenta from uterine wall; presents with painful vaginal bleeding, uterine tenderness, tetanic contractions, and fetal distress; concealed hemorrhage possible','Risk factors: hypertension (strongest), trauma, cocaine, smoking, prior abruption. Diagnosis is clinical (ultrasound sensitivity only 50%). Mild: expectant management; Severe: emergency cesarean delivery. Complications: DIC, Couvelaire uterus.',4,'analyze',['placental-abruption','vaginal-bleeding','DIC','emergency-cesarean','hypertension']);
add('obgyn-obstetric-emerg','What is placenta previa and how is it managed?','Placenta implanted over or near the internal cervical os; painless bright red vaginal bleeding in 2nd-3rd trimester; diagnosed by ultrasound','Do NOT perform digital vaginal exam (can provoke massive hemorrhage). Management depends on severity and gestational age. Partial/marginal previa may resolve with growth. Complete previa requires cesarean delivery at 36-37 weeks. Admit if active bleeding.',3,'apply',['placenta-previa','painless-bleeding','cesarean','ultrasound','third-trimester']);
add('obgyn-obstetric-emerg','What is eclampsia and how is it treated?','New-onset generalized tonic-clonic seizures in a patient with preeclampsia; treatment: IV magnesium sulfate 4-6g loading dose then 1-2g/h maintenance; delivery is the definitive treatment','Magnesium prevents and treats eclamptic seizures. Monitor for toxicity: loss of DTRs (first sign), respiratory depression, cardiac arrest. Antidote: calcium gluconate 1g IV. Delivery should occur once mother is stabilized regardless of gestational age.',4,'analyze',['eclampsia','preeclampsia','magnesium-sulfate','seizure','delivery']);
add('obgyn-obstetric-emerg','What are the criteria for diagnosing preeclampsia?','New-onset hypertension (≥140/90) after 20 weeks gestation PLUS proteinuria (≥300 mg/24h or protein/creatinine ratio ≥30 mg/mmol) OR end-organ dysfunction (thrombocytopenia, renal insufficiency, elevated liver enzymes, cerebral symptoms)','Severe features: SBP ≥160 or DBP ≥110, platelets <100, creatinine >106 µmol/L, elevated transaminases (2× ULN), pulmonary edema, cerebral/visual symptoms. HELLP syndrome: Hemolysis, Elevated Liver enzymes, Low Platelets.',3,'apply',['preeclampsia','hypertension','pregnancy','proteinuria','HELLP']);
add('obgyn-obstetric-emerg','What is shoulder dystocia and how is it managed?','Impaction of anterior fetal shoulder behind pubic symphysis after delivery of the head; obstetric emergency requiring immediate maneuvers','HELPERR mnemonic: call for Help, Evaluate for episiotomy, Legs (McRoberts maneuver — hyperflex hips), suprapubic Pressure, Enter rotational maneuvers (Wood screw, Rubin), Remove posterior arm, Roll to all fours. Avoid fundal pressure (worsens impaction).',4,'analyze',['shoulder-dystocia','McRoberts','HELPERR','emergency','brachial-plexus']);
add('obgyn-obstetric-emerg','What is uterine rupture and how does it present?','Disruption of the uterine wall during labor; classic triad: sudden severe abdominal pain, vaginal bleeding, loss of fetal station; non-reassuring fetal heart tracing','Strongest risk factor: prior classical (vertical) uterine incision. Low transverse scar has 0.5-1% rupture risk during TOLAC. Management: immediate laparotomy and delivery. Often requires hysterectomy. Fetal mortality is 6% if not delivered within minutes.',4,'analyze',['uterine-rupture','TOLAC','VBAC','cesarean-scar','emergency-laparotomy']);
add('obgyn-obstetric-emerg','What is umbilical cord prolapse and how is it managed?','Descent of umbilical cord below the presenting part with intact membranes (occult) or through the cervix (overt); causes cord compression and fetal hypoxia','Management of overt prolapse: manually elevate presenting part (hand in vagina pushing fetal head up), fill bladder with 500-700mL saline, knee-chest or Trendelenburg position, emergency cesarean delivery. Do NOT attempt to replace cord.',4,'analyze',['cord-prolapse','emergency-cesarean','fetal-hypoxia','presenting-part']);
add('obgyn-obstetric-emerg','What is amniotic fluid embolism (AFE)?','Catastrophic obstetric emergency: amniotic fluid enters maternal circulation causing cardiovascular collapse, DIC, and respiratory failure; mortality 20-60%','AFE typically occurs during labor, cesarean, or immediately postpartum. Classic triad: sudden dyspnea, hypotension, DIC. Diagnosis is clinical (exclusion). Treatment: aggressive resuscitation, intubation, vasopressors, blood products for DIC, perimortem cesarean if cardiac arrest.',5,'analyze',['amniotic-fluid-embolism','DIC','cardiovascular-collapse','perimortem-cesarean']);
add('obgyn-obstetric-emerg','What is ectopic pregnancy and what is the most common location?','Implantation outside the uterine cavity; ampulla of the fallopian tube (70%); presents with amenorrhea, abdominal/pelvic pain, and vaginal bleeding; β-hCG rises abnormally (<66% in 48h)','Ruptured ectopic is a surgical emergency (hemodynamic instability, peritoneal signs). Unruptured ectopic options: methotrexate (if β-hCG <5000, no fetal cardiac activity, <4 cm) or laparoscopic salpingostomy/salpingectomy. Risk factors: PID, prior ectopic, IUD, tubal surgery.',4,'analyze',['ectopic-pregnancy','ampullary','methotrexate','beta-hCG','salpingectomy']);
add('obgyn-obstetric-emerg','What is the management of a complete miscarriage vs. incomplete miscarriage?','Complete: closed cervical os, no products on ultrasound, expectant management; Incomplete: open os, retained products, requires expectant/medical (misoprostol) or surgical (suction curettage) management','Types of miscarriage: threatened (bleeding, closed os, viable fetus), inevitable (open os, intact products), incomplete (partial passage), complete (all passed), missed (non-viable, closed os, no symptoms). Anti-D immunoglobulin for Rh-negative patients.',3,'apply',['miscarriage','incomplete','misoprostol','suction-curettage','Rh-immunoglobulin']);
add('obgyn-obstetric-emerg','What is the biophysical profile (BPP) and how is it scored?','Ultrasound assessment of fetal well-being: fetal breathing movements, gross body movements, fetal tone, amniotic fluid volume (each 0 or 2 points) + NST (0 or 2); total 0-10','BPP 8-10 = reassuring; 6 = equivocal (repeat in 24h); ≤4 = non-reassuring (consider delivery). Modified BPP = NST + amniotic fluid index. Used for high-risk pregnancies (postdates, IUGR, gestational diabetes).',2,'recall',['biophysical-profile','BPP','NST','fetal-surveillance','amniotic-fluid']);
add('obgyn-obstetric-emerg','What is the management of non-reassuring fetal heart rate tracing in labor?','Intrauterine resuscitation: left lateral position, IV fluid bolus, stop oxytocin, supplemental O2; if persistent: amnioinfusion for variable decelerations, consider operative delivery (vacuum/forceps or cesarean)','Category III tracing (absent variability with recurrent late/variable decelerations or bradycardia) requires immediate intervention and preparation for expedited delivery. Fetal scalp stimulation: acceleration = reassuring pH.',4,'analyze',['fetal-heart-rate','non-reassuring','intrauterine-resuscitation','Category-III','cesarean']);
add('obgyn-obstetric-emerg','What are the indications for emergency perimortem cesarean section?','Maternal cardiac arrest >4 minutes without ROSC, at ≥20 weeks gestation (or fundus at/above umbilicus); perform within 5 minutes of arrest onset','Perimortem cesarean improves both maternal (relieves aortocaval compression) and fetal survival. Do not delay for operating room — perform at bedside during ongoing CPR. Continue maternal resuscitation after delivery.',5,'analyze',['perimortem-cesarean','cardiac-arrest','pregnancy','CPR','emergency']);
add('obgyn-obstetric-emerg','What is uterine inversion and how is it managed?','Uterus turns inside out through the cervix, usually due to excessive cord traction on a fundally implanted placenta; presents with hemorrhage, shock, and a mass at introitus','Management: do NOT remove placenta (worsens bleeding), immediately replace uterus manually (Johnson maneuver — push fundus through cervix), give uterine relaxants (nitroglycerin, terbutaline, halothane) if needed. IV fluids and blood products for shock.',4,'analyze',['uterine-inversion','Johnson-maneuver','cord-traction','hemorrhage','uterine-relaxant']);
add('obgyn-obstetric-emerg','What is vasa previa and why is it dangerous?','Fetal blood vessels crossing the internal os unsupported by placental tissue or umbilical cord; rupture of membranes causes fetal hemorrhage with >50% fetal mortality if undiagnosed','Suspect with painless vaginal bleeding at ROM with sudden fetal bradycardia. Apt test distinguishes fetal from maternal blood. Diagnosed prenatally by transvaginal ultrasound with color Doppler. Planned cesarean at 35-36 weeks if diagnosed.',4,'analyze',['vasa-previa','fetal-hemorrhage','Apt-test','Doppler','cesarean']);
add('obgyn-obstetric-emerg','What is the management of severe preeclampsia remote from term (24-34 weeks)?','IV magnesium sulfate for seizure prophylaxis, antihypertensives (labetalol, nifedipine, hydralazine) for severe HTN (≥160/110), antenatal corticosteroids for fetal lung maturity, and delivery at 34 weeks or earlier if maternal/fetal deterioration','Expectant management at tertiary center may allow corticosteroid benefit (betamethasone 12mg IM × 2 doses, 24h apart). Indications for immediate delivery: uncontrollable HTN, eclampsia, pulmonary edema, HELLP, abruption, non-reassuring fetal status.',4,'analyze',['severe-preeclampsia','magnesium','corticosteroids','expectant-management','delivery-timing']);
add('obgyn-obstetric-emerg','What is the Kleihauer-Betke test used for?','Quantifying fetal-maternal hemorrhage (FMH) to determine the appropriate dose of anti-D immunoglobulin (RhIG) in Rh-negative mothers after a potentially sensitizing event','Standard RhIG dose (300 µg) covers up to 30 mL of fetal blood. KB test identifies cases requiring additional doses. Sensitizing events: abruption, trauma, amniocentesis, delivery. Also useful after suspected large FMH causing fetal anemia.',3,'apply',['Kleihauer-Betke','fetal-maternal-hemorrhage','RhIG','Rh-negative','anti-D']);
add('obgyn-obstetric-emerg','What is HELLP syndrome and how does it relate to preeclampsia?','Hemolysis (schistocytes, elevated LDH, low haptoglobin), Elevated Liver enzymes (AST >70), Low Platelets (<100 × 10⁹/L); variant of severe preeclampsia requiring delivery','HELLP can occur without significant hypertension or proteinuria (15-20%). Complications: DIC, subcapsular liver hematoma/rupture, placental abruption. Corticosteroids for fetal maturity; dexamethasone may temporarily improve platelets. Delivery is definitive.',4,'analyze',['HELLP','preeclampsia','hemolysis','liver','thrombocytopenia']);
add('obgyn-obstetric-emerg','What are the risk factors and management of obstetric DIC?','Causes: placental abruption, amniotic fluid embolism, HELLP, retained dead fetus, septic abortion; management: treat underlying cause, replace blood products (pRBC, FFP, platelets, cryoprecipitate), fibrinogen >2 g/L target','DIC labs: prolonged PT/aPTT, low fibrinogen (<2 g/L is critical), elevated D-dimer, low platelets, schistocytes. Cryoprecipitate provides concentrated fibrinogen (10 units raise fibrinogen by ~1 g/L). Tranexamic acid 1g IV within 3 hours of bleeding.',4,'analyze',['DIC','obstetric-hemorrhage','coagulopathy','fibrinogen','cryoprecipitate']);
add('obgyn-obstetric-emerg','What is the partograph used for in labor?','Graphical record of labor progress plotting cervical dilation and fetal descent against time; alert line and action line identify prolonged labor requiring intervention','WHO partograph: if dilation crosses the action line (4h right of alert line), intervention is needed (augmentation with oxytocin, ARM, or cesarean). Normal active phase: ≥1 cm/h dilation. Prolonged labor increases risk of infection, fetal distress, PPH.',2,'recall',['partograph','labor-progress','cervical-dilation','prolonged-labor','WHO']);

process.stdout.write(JSON.stringify(cards));
