const fs = require("fs");
const prev = JSON.parse(fs.readFileSync("C:/dev/srs-mccqe1/data/_parts12.json","utf8"));
const cards = [...prev];
let n = 91;
function c(id,q,a,ex,d,bl,tags,tid){return{id,question:q,answer:a,explanation:ex,difficulty:d,bloomLevel:bl,tags,topicId:tid};}

// FAMILY MEDICINE - PREVENTIVE (15)
cards.push(c("card-tn3-fm-"+n++,"What components make up the Canadian periodic health exam for adults 18-39?","BP screening, cervical cancer screening (age 25+), chlamydia/gonorrhea screening if sexually active, mental health assessment, substance use screening, immunization update, contraception counseling","The periodic health exam is age/sex/risk-stratified. CTFPHC maneuvers guide evidence-based preventive care. Avoid unnecessary routine blood work in low-risk young adults. Focus on lifestyle counseling: diet, exercise, smoking cessation, alcohol.",3,"recall",["periodic health exam","preventive care"],"fm-preventive"));
cards.push(c("card-tn3-fm-"+n++,"What components make up the periodic health exam for adults 40-74?","BP, lipid screening, diabetes (FPG/A1c q3-5y from 40), colorectal Ca (FIT q2y from 50), breast Ca (mammo q2-3y 50-74), cervical Ca (Pap q3y 25-69), lung Ca (LDCT if 30+pack-yr 55-74), AAA (once men 65-80 ever-smoked)","Cardiovascular risk assessment using Framingham Risk Score. Statin therapy if 10-year CV risk >20% or >10% with risk-enhancing factors. Osteoporosis screening (FRAX/BMD) for women 65+. Vision/hearing assessment.",3,"recall",["periodic health exam","screening","preventive"],"fm-preventive"));
cards.push(c("card-tn3-fm-"+n++,"What are the CTFPHC smoking cessation recommendations?","Ask about tobacco at every visit. Advise all smokers to quit. Recommend NRT, varenicline, or bupropion. Brief interventions effective. Combine pharmacotherapy + behavioral counseling","Varenicline most effective single agent (OR 2.3 vs placebo). NRT forms: patch, gum, lozenge, inhaler, spray. Bupropion also treats depression. All provinces provide some smoking cessation coverage. E-cigarettes not recommended by CTFPHC.",3,"apply",["smoking cessation","NRT","varenicline"],"fm-preventive"));
cards.push(c("card-tn3-fm-"+n++,"What are the Canadian cardiovascular disease prevention guidelines for lipid screening?","Screen all adults >=40 (or earlier if risk factors). Use FRS for 10-year risk. High risk (>=20%): treat with statin. Moderate (10-19%): consider statin if LDL>3.5. Low (<10%): lifestyle","CCS 2021 lipid guidelines. Alternative: use CLEM score. Primary targets: LDL <2.0 or >50% reduction for high risk. ApoB <0.8. Non-HDL <2.6. Consider ASCVD risk enhancers: family history, South Asian ethnicity, CKD, inflammatory disease.",3,"apply",["lipid screening","cardiovascular prevention","statin"],"fm-preventive"));
cards.push(c("card-tn3-fm-"+n++,"What are the Canadian guidelines for alcohol screening and brief intervention?","Screen with AUDIT-C or CAGE. Canada Low-Risk Alcohol Drinking Guidelines (2023 update): no safe amount; <=2 drinks/wk low risk, 3-6 moderate, >=7 increasingly high risk","2023 CCSA guidance significantly reduced recommended limits from previous 10F/15M per week. Brief intervention (FRAMES: Feedback, Responsibility, Advice, Menu, Empathy, Self-efficacy) reduces consumption. Screen for alcohol use disorder with DSM-5 criteria (>=2 of 11 criteria).",3,"apply",["alcohol","screening","AUDIT","brief intervention"],"fm-preventive"));
cards.push(c("card-tn3-fm-"+n++,"What are the osteoporosis screening guidelines in Canada?","FRAX or CAROC assessment for all >=50 with risk factors. BMD (DXA) for: all women >=65, men >=70, postmenopausal women or men >=50 with risk factors. T-score <=-2.5 = osteoporosis","Osteoporosis Canada 2010 guidelines. 10-year fracture risk: low <10%, moderate 10-20%, high >20%. Treat high risk. Moderate: consider if additional risk factors. Vertebral fracture assessment adds to DXA. Calcium 1000-1200mg + Vit D 800-2000 IU daily for all >=50.",3,"recall",["osteoporosis","screening","DXA","FRAX"],"fm-preventive"));
cards.push(c("card-tn3-fm-"+n++,"What are the Canadian Hypertension Education Program (now Hypertension Canada) BP targets?","General: <140/90. Diabetes: <130/80. High-risk (CKD, CV disease): <120 systolic considered. Office BP >=130/85 warrants out-of-office measurement (ABPM or HBPM)","Hypertension Canada 2020. Diagnosis requires elevated BP on 2+ visits or ABPM/HBPM confirmation. First-line: thiazide, ACEi/ARB, long-acting CCB, or combination. Lifestyle: DASH diet, sodium <2000mg/d, exercise 30-60min 4-7d/wk, limit alcohol, maintain healthy weight.",3,"recall",["hypertension","BP targets","Hypertension Canada"],"fm-preventive"));
cards.push(c("card-tn3-fm-"+n++,"What immunizations should be discussed at each periodic health exam?","Influenza annually. Tdap/Td q10y. Pneumococcal >=65. Shingrix >=50. HPV catch-up <=26. HepB if not immunized. COVID per NACI. Travel vaccines as needed","Pregnancy: Tdap each pregnancy 27-32wk, influenza. Immunocompromised: avoid live vaccines. Catch-up schedules available at CANImmunize.ca. Provincial coverage varies. Document and maintain immunization records.",3,"recall",["immunization","preventive care"],"fm-preventive"));
cards.push(c("card-tn3-fm-"+n++,"What are the recommendations for physical activity counseling in primary care?","Canadian 24-Hour Movement Guidelines: 150 min/wk moderate-vigorous aerobic + 2 days strength. Reduce sedentary time. Brief exercise prescription (FITT: Frequency, Intensity, Time, Type)","Exercise is medicine. Benefits: 30% reduction all-cause mortality, improves depression, CV risk, diabetes control, bone health. Even 15 min/day provides benefit. Assess readiness to change (transtheoretical model). Address barriers.",2,"apply",["physical activity","exercise","preventive"],"fm-preventive"));
cards.push(c("card-tn3-fm-"+n++,"What are the Canadian guidelines for skin cancer prevention?","Sun protection counseling for all. No population-based skin cancer screening recommended by CTFPHC. Clinical skin examination for high-risk individuals (FHx melanoma, >50 nevi, fair skin, prior skin cancer)","Canadian Dermatology Association recommends sun protection. SPF 30+ broad-spectrum, reapply q2h. Avoid tanning beds. Educate on ABCDE for self-monitoring. Dermoscopy improves diagnostic accuracy in primary care.",2,"recall",["skin cancer","sun protection","prevention"],"fm-preventive"));
cards.push(c("card-tn3-fm-"+n++,"What are the indications for ASA for primary cardiovascular prevention?","CTFPHC 2019: do NOT recommend ASA for primary prevention in most adults. May consider in high CV risk (10-year >20%) ages 40-70 if low bleeding risk, after shared decision-making","Differs from previous recommendations. ASPREE, ARRIVE, ASCEND trials showed harms (bleeding) outweigh benefits for most. Secondary prevention: ASA 81mg remains indicated post-ACS/stroke. Consider clopidogrel if ASA-intolerant.",3,"apply",["ASA","primary prevention","cardiovascular"],"fm-preventive"));
cards.push(c("card-tn3-fm-"+n++,"What are the elements of anticipatory guidance for new parents?","Safe sleep (back to sleep, firm surface, no bedsharing), breastfeeding support, immunization schedule, car seat safety, injury prevention, postpartum depression screening, contraception","CPS Well-Baby Visit schedule: 1-2wk, 1mo, 2mo, 4mo, 6mo, 9mo, 12mo, 15mo, 18mo, then annually. Rourke Baby Record is Canadian standardized tool for well-child visits. Screen maternal mental health at each visit.",2,"recall",["anticipatory guidance","well-child","parenting"],"fm-preventive"));
cards.push(c("card-tn3-fm-"+n++,"What is the approach to STI screening in primary care?","Screen sexually active <25 and high-risk for chlamydia/gonorrhea (urine NAAT). HIV screening offered to all. Syphilis in MSM, endemic exposure, pregnancy. HBV/HCV in high-risk","Canadian STI Guidelines (PHAC). Chlamydia: azithromycin 1g PO or doxycycline 100mg BID x 7d. Gonorrhea: ceftriaxone 250mg IM + azithromycin 1g. Report gonorrhea/syphilis to public health. Partner notification mandatory.",3,"apply",["STI","screening","chlamydia","gonorrhea"],"fm-preventive"));
cards.push(c("card-tn3-fm-"+n++,"What are the key elements of the well-child visit in Canada?","Growth/development monitoring (Rourke Baby Record/Nipissing), immunizations per schedule, nutrition counseling, injury prevention, vision/hearing screening, dental health, family assessment, maternal mental health","Developmental screening at 18-24 months with validated tool (M-CHAT for autism). Milestone monitoring at every visit. Anemia screening (CBC) at 9-12 months in high-risk. Lead screening if risk factors.",3,"recall",["well-child","Rourke","developmental screening"],"fm-preventive"));
cards.push(c("card-tn3-fm-"+n++,"What cancer screening is recommended for patients with strong family history?","Breast: start 10y before youngest affected relative, consider MRI if BRCA. Colon: colonoscopy from 40 or 10y before youngest case, q5y. Consider genetic referral for: >=2 first-degree relatives, young onset, Lynch/BRCA patterns","High-risk screening protocols differ from average-risk CTFPHC guidelines. Genetic counseling and testing criteria: multiple affected relatives, young onset (<50), associated cancers (Lynch: colon+endometrial+ovarian). Provincial genetics programs provide assessment.",4,"apply",["familial cancer","genetic screening","high-risk"],"fm-preventive"));

// FAMILY MEDICINE - MULTIMORBIDITY (15)
cards.push(c("card-tn3-fm-"+n++,"What is polypharmacy and why is it a concern in multimorbid patients?","Polypharmacy: >=5 concurrent medications. Problematic polypharmacy: more medications than clinically indicated. Risks: ADRs (doubled with >=5 meds), falls, cognitive impairment, non-adherence, drug interactions","~30% Canadian seniors on 5+ medications. Prescribing cascades: drug A causes side effect treated by drug B. Apply Beers Criteria and STOPP/START criteria. Deprescribing.org provides Canadian evidence-based deprescribing guidelines.",4,"recall",["polypharmacy","multimorbidity","deprescribing"],"fm-multimorbid"));
cards.push(c("card-tn3-fm-"+n++,"What are the principles of deprescribing?","1) Identify medications to discontinue. 2) Prioritize by harm risk. 3) Plan tapering schedule. 4) Monitor for withdrawal/disease recurrence. 5) Shared decision-making with patient. Use deprescribing.org algorithms","Key targets: PPIs (taper over 4-8wk), benzodiazepines (10% reduction q1-2wk), anticholinergics, opioids, antipsychotics in elderly. Deprescribing reduces falls, improves cognition, reduces ADRs. STOPP criteria identify potentially inappropriate prescriptions.",4,"apply",["deprescribing","polypharmacy","medication safety"],"fm-multimorbid"));
cards.push(c("card-tn3-fm-"+n++,"How should diabetes be managed in the context of multimorbidity?","Individualize A1c targets: <=7.0% generally, <=8.0% or <=8.5% for frail elderly with limited life expectancy. Avoid hypoglycemia. Prefer agents with low hypo risk (metformin, SGLT2i, GLP1-RA). Simplify regimens","Diabetes Canada 2018. SGLT2i (empagliflozin, dapagliflozin) have CV and renal benefits. GLP1-RA reduce CV events. Deprescribe sulfonylureas and insulin where possible in frail elderly. Renal dosing: metformin to eGFR 30, SGLT2i to eGFR 20-25.",4,"apply",["diabetes","multimorbidity","A1c targets"],"fm-multimorbid"));
cards.push(c("card-tn3-fm-"+n++,"How is chronic pain managed in patients with multiple comorbidities?","Multimodal approach: non-pharmacological first (exercise, CBT, physiotherapy). Pharmacological: acetaminophen, topical NSAIDs, duloxetine/gabapentinoids for neuropathic. Avoid systemic NSAIDs if CKD/CV/GI risk. Opioids last resort","Canadian Pain Guidelines 2017 emphasize non-opioid multimodal analgesia. If opioids needed: lowest effective dose, reassess regularly, naloxone co-prescribing if >=50 MME/day. Monitor with PMP (provincial prescription monitoring programs).",4,"apply",["chronic pain","multimodal","multimorbidity"],"fm-multimorbid"));
cards.push(c("card-tn3-fm-"+n++,"What is the approach to treatment burden in multimorbid patients?","Assess patient capacity vs treatment workload. Minimize visits, simplify regimens, coordinate care, set realistic goals. Use ARIADNE principles: assess interactions, rank priorities, individualize, decide together, evaluate regularly","Treatment burden includes medications, appointments, monitoring, lifestyle changes, self-management tasks. Minimally disruptive medicine framework. Single-disease guidelines may not apply. Focus on patient-centered outcomes not disease-specific targets.",3,"analyze",["treatment burden","multimorbidity","patient-centered"],"fm-multimorbid"));
cards.push(c("card-tn3-fm-"+n++,"How is hypertension managed in patients with CKD and diabetes?","Target <130/80 per Hypertension Canada. First-line: ACEi or ARB (renal protection). Monitor creatinine and K+ at 1-2 weeks. Accept up to 30% rise in creatinine. Add thiazide-like or CCB as needed","Do not combine ACEi+ARB (ONTARGET trial: no benefit, more harm). Hold ACEi/ARB for acute illness (sick day rules). SGLT2i provide additional renal and CV benefit. Avoid NSAIDs (worsen CKD and HTN). Refer nephrology if eGFR <30 or rapidly declining.",4,"apply",["hypertension","CKD","diabetes","ACEi"],"fm-multimorbid"));
cards.push(c("card-tn3-fm-"+n++,"What drug interactions should be monitored in multimorbid patients on anticoagulation?","Warfarin: CYP2C9 interactions (amiodarone increases INR, rifampin decreases). DOACs: P-gp inhibitors (amiodarone, dronedarone increase levels). All anticoagulants + NSAIDs/ASA = increased bleeding. Check renal function for DOACs","Common dangerous interactions: macrolides + warfarin, antifungals + DOACs, SSRIs increase bleeding risk. Dose-adjust DOACs for renal function and age/weight. INR monitoring for warfarin q4-12wk when stable. Fall risk alone is NOT a contraindication to anticoagulation.",4,"apply",["drug interactions","anticoagulation","warfarin","DOAC"],"fm-multimorbid"));
cards.push(c("card-tn3-fm-"+n++,"How is heart failure managed in patients with concurrent COPD?","Cardioselective beta-blockers (bisoprolol, metoprolol) are SAFE in COPD-HF. Avoid non-selective (carvedilol with caution). LAMA/LABA preferred over ICS for COPD. Avoid systemic corticosteroids if possible (fluid retention)","Beta-blockers reduce HF mortality and should NOT be withheld for COPD. Cardioselective agents at appropriate doses do not significantly worsen FEV1. Short-acting beta-agonists safe in HF. Diuretics for volume management must balance COPD dehydration.",4,"apply",["heart failure","COPD","beta-blocker","multimorbidity"],"fm-multimorbid"));
cards.push(c("card-tn3-fm-"+n++,"What are the Beers Criteria and STOPP/START criteria?","Beers: list of potentially inappropriate medications in >=65 (AGS updated 2023). STOPP: screening tool for older persons prescriptions to STOP. START: screening tool to START indicated but omitted medications","Beers high-risk drugs: anticholinergics, benzodiazepines, NSAIDs, long-acting sulfonylureas, meperidine, first-gen antipsychotics. STOPP/START more applicable to Canadian practice than Beers alone. Both tools reduce ADRs and inappropriate prescribing in elderly.",4,"recall",["Beers criteria","STOPP/START","elderly","inappropriate prescribing"],"fm-multimorbid"));
cards.push(c("card-tn3-fm-"+n++,"How should chronic kidney disease be managed in primary care?","Classify by eGFR and albuminuria (KDIGO). ACEi/ARB for proteinuria. SGLT2i (dapagliflozin/empagliflozin) for eGFR 20-90 with albuminuria. BP <130/80. Avoid nephrotoxins. Finerenone for DKD","Refer nephrology: eGFR <30, rapid decline (>5/yr), nephrotic proteinuria, refractory HTN, electrolyte abnormalities. Adjust medications for GFR. Avoid gadolinium if eGFR <30. Annual monitoring: eGFR, ACR, electrolytes, CBC, PTH, vitamin D.",4,"apply",["CKD","KDIGO","SGLT2i","nephrology"],"fm-multimorbid"));
cards.push(c("card-tn3-fm-"+n++,"What is the approach to managing depression in patients with chronic medical illness?","SSRIs first-line (sertraline/escitalopram). Consider drug interactions (CYP2D6 inhibitors, bleeding with anticoagulants). Avoid TCAs in cardiac disease. Combine with CBT/behavioral activation. Address pain/sleep","Depression occurs in 20-30% of chronic disease patients and worsens outcomes. Treat comorbid depression to improve adherence and quality of life. Exercise is evidence-based adjunct. Collaborative care models improve outcomes. Screen with PHQ-9.",4,"apply",["depression","chronic disease","SSRI"],"fm-multimorbid"));
cards.push(c("card-tn3-fm-"+n++,"How is atrial fibrillation managed in elderly multimorbid patients?","Anticoagulation: CHADS2-VASc score >=2 (most elderly). DOACs preferred over warfarin (less ICH). Rate control preferred: bisoprolol or diltiazem (not both). Target HR <100 resting. Avoid rhythm control if asymptomatic","Falls are NOT a reason to withhold anticoagulation (need 295 falls/year for bleeding risk to exceed stroke prevention benefit). Dose-adjust DOACs: apixaban 2.5mg BID if >=2 of: age>=80, weight<=60kg, Cr>=133. Assess bleeding risk (HAS-BLED) but do not use to withhold therapy.",4,"apply",["atrial fibrillation","anticoagulation","elderly"],"fm-multimorbid"));
cards.push(c("card-tn3-fm-"+n++,"What are the sick day rules for patients on chronic medications?","Hold during acute illness: ACEi/ARB, diuretics, NSAIDs, metformin, SGLT2i, sulfonylureas (SADMANS mnemonic). Resume when eating/drinking normally. Educate patients proactively","SADMANS: Sulfonylureas, ACEi, Diuretics/Direct-acting anticoagulants, Metformin, ARBs, NSAIDs, SGLT2i. Prevents AKI, hypoglycemia, hyperkalemia during volume depletion. Especially important in elderly, CKD, HF. Provide written instructions.",3,"apply",["sick day rules","AKI prevention","SADMANS"],"fm-multimorbid"));
cards.push(c("card-tn3-fm-"+n++,"How is the patient with diabetes, CKD, and heart failure optimally treated pharmacologically?","Metformin (if eGFR>30) + SGLT2i (triple benefit: glycemic, renal, cardiac) + ACEi/ARB + beta-blocker (bisoprolol/carvedilol/metoprolol) + MRA if symptomatic HF + statin. Finerenone if DKD","SGLT2i (empagliflozin/dapagliflozin) have evidence in all three conditions (EMPA-REG, DAPA-CKD, DAPA-HF). Quadruple HFrEF therapy: ACEi/ARB/ARNI + BB + MRA + SGLT2i. Adjust doses for renal function. Monitor K+ closely with ACEi+MRA combination.",5,"apply",["diabetes","CKD","heart failure","SGLT2i"],"fm-multimorbid"));
cards.push(c("card-tn3-fm-"+n++,"What role does advance care planning play in multimorbidity management?","Early discussions about goals of care, values, acceptable outcomes. Document SDM/POA. Use Serious Illness Conversation Guide. Reassess with disease progression. Integrate palliative approach early","Advance Care Planning Canada provides tools. Discussions improve goal-concordant care, reduce unwanted ICU admissions, improve family satisfaction. Not just about resuscitation status - explores values, fears, hopes. GCD (Goals of Care Designation) standardized in many provinces.",3,"apply",["advance care planning","goals of care","palliative"],"fm-multimorbid"));

// FAMILY MEDICINE - GERIATRICS (15)
cards.push(c("card-tn3-fm-"+n++,"What is the comprehensive geriatric assessment (CGA)?","Systematic evaluation of: medical (comorbidities, medications, nutrition), functional (ADLs, IADLs, mobility), psychological (cognition, mood, behavior), social (support, caregiver, housing, finances)","CGA improves outcomes: reduces mortality, institutionalization, and functional decline. Interdisciplinary team approach. Tools: Katz ADL index, Lawton IADL, MMSE/MoCA, GDS, Timed Up and Go. Canadian Geriatrics Society promotes CGA in acute and community settings.",3,"recall",["CGA","geriatric assessment","functional status"],"fm-geriatrics"));
cards.push(c("card-tn3-fm-"+n++,"How are delirium and dementia differentiated clinically?","Delirium: acute onset, fluctuating, inattention, often reversible. Dementia: gradual onset, progressive, attention initially preserved, irreversible. Delirium can be superimposed on dementia","Delirium screening: CAM (Confusion Assessment Method) - requires acute change + inattention + EITHER disorganized thinking OR altered LOC. Dementia screening: MoCA (>=26 normal) or MMSE (>=24). Delirium is a medical EMERGENCY requiring cause identification.",4,"analyze",["delirium","dementia","CAM","MoCA"],"fm-geriatrics"));
cards.push(c("card-tn3-fm-"+n++,"What are the common causes of delirium (mnemonic)?","DELIRIUM(S): Drugs, Electrolytes, Lack of drugs (withdrawal), Infection (UTI, pneumonia), Reduced sensory input, Intracranial event, Urinary retention/constipation, Myocardial/pulmonary event, (Subdural)","Drugs are the most common modifiable cause (anticholinergics, benzodiazepines, opioids). Non-pharmacological prevention: orientation, mobilization, sleep hygiene, hydration, avoid restraints. Avoid antipsychotics unless patient is danger to self/others.",4,"recall",["delirium","causes","geriatrics"],"fm-geriatrics"));
cards.push(c("card-tn3-fm-"+n++,"What is the approach to falls prevention in elderly patients?","Multifactorial assessment: gait/balance (TUG test), medications (review for culprits), vision, orthostatic BP, home hazards, footwear, vitamin D, strength/balance exercise (Otago program)","Falls affect 30% of >=65 annually, leading cause of injury-related death in elderly. High-risk meds: benzodiazepines, antihypertensives, anticholinergics, opioids, antipsychotics. Tai chi and Otago exercise program have best evidence. Home safety assessment by OT reduces falls.",4,"apply",["falls prevention","elderly","geriatrics"],"fm-geriatrics"));
cards.push(c("card-tn3-fm-"+n++,"What are the stages and types of dementia?","Alzheimer (60-80%): memory first, gradual. Vascular: stepwise, executive dysfunction. Lewy body: visual hallucinations, parkinsonism, fluctuations. Frontotemporal: personality/behavior changes, younger onset. Staging: mild/moderate/severe by function","Diagnosis: clinical history + cognitive testing (MoCA) + labs to exclude reversible causes (TSH, B12, calcium, CBC, electrolytes, glucose) + CT/MRI. Alzheimer treatment: cholinesterase inhibitors (donepezil, rivastigmine, galantamine) for mild-moderate, memantine for moderate-severe.",4,"recall",["dementia","Alzheimer","Lewy body","vascular"],"fm-geriatrics"));
cards.push(c("card-tn3-fm-"+n++,"What medications are used for dementia and what are their side effects?","Cholinesterase inhibitors (donepezil 5-10mg, rivastigmine, galantamine): nausea, diarrhea, bradycardia, syncope. Memantine (NMDA antagonist): for moderate-severe, better tolerated. Neither reverses or halts progression","Start low go slow. Modest benefit: ~2 points MMSE. Discontinue if no benefit after 3-6 months or severe stage. Monitor for bradycardia (caution with beta-blockers). Anticholinergic medications worsen cognition and should be discontinued.",4,"apply",["dementia treatment","donepezil","memantine"],"fm-geriatrics"));
cards.push(c("card-tn3-fm-"+n++,"What is the approach to urinary incontinence in elderly?","Classify: stress (cough/sneeze), urge (detrusor overactivity), overflow (retention), functional (mobility/cognition). Assess: bladder diary, PVR, UA. Treat: pelvic floor exercises (stress), bladder training + antimuscarinics (urge)","Avoid oxybutynin in elderly (crosses BBB, cognitive impairment). Mirabegron (beta-3 agonist) preferred for urge incontinence in elderly. Timed voiding for functional incontinence. Address contributing factors: constipation, medications, caffeine, mobility.",3,"apply",["urinary incontinence","elderly","geriatrics"],"fm-geriatrics"));
cards.push(c("card-tn3-fm-"+n++,"What is frailty and how is it assessed?","Frailty phenotype (Fried): >=3 of: unintentional weight loss, exhaustion, low physical activity, slow gait, weak grip. Pre-frail: 1-2. Also: Clinical Frailty Scale (Rockwood) 1-9","Frailty predicts adverse outcomes: falls, disability, hospitalization, mortality. CFS is widely used in Canadian healthcare (used in COVID triage). Frailty is potentially modifiable with exercise, nutrition optimization, medication review, and social support.",3,"recall",["frailty","Clinical Frailty Scale","geriatrics"],"fm-geriatrics"));
cards.push(c("card-tn3-fm-"+n++,"What are the principles of prescribing in elderly patients?","Start low, go slow, but get there. Review all medications regularly. Use Beers/STOPP/START criteria. Avoid anticholinergic burden (ACB score). Consider life expectancy in preventive therapy. Deprescribe proactively","Pharmacokinetic changes: decreased renal clearance, hepatic metabolism, increased body fat (longer half-life lipophilic drugs), decreased albumin (higher free drug). Pharmacodynamic: increased sensitivity to CNS depressants, anticholinergics, anticoagulants.",3,"apply",["prescribing","elderly","pharmacology"],"fm-geriatrics"));
cards.push(c("card-tn3-fm-"+n++,"How is elder abuse screened for and managed?","Types: physical, emotional, financial, sexual, neglect. Screen: direct questioning, look for unexplained injuries, poor hygiene, fearfulness. Report to APS (Adult Protective Services) per provincial legislation. Mandatory reporting varies by province","Elder abuse affects ~10% of Canadian seniors. Risk factors: social isolation, dementia, caregiver stress, financial dependence. Physicians should screen in private without caregiver present. Document findings carefully. Connect with community resources and social work.",3,"apply",["elder abuse","screening","geriatrics"],"fm-geriatrics"));
cards.push(c("card-tn3-fm-"+n++,"What is the approach to malnutrition in elderly patients?","Screen with MNA (Mini Nutritional Assessment). Causes: poor dentition, depression, medications, poverty, functional limitations, malabsorption. Target protein 1-1.2 g/kg/day. Supplement vitamin D. Address reversible causes","Malnutrition affects 30-50% of hospitalized elderly. Consequences: poor wound healing, immune dysfunction, muscle wasting (sarcopenia), increased mortality. Oral nutritional supplements improve outcomes. Dietitian referral. Address social determinants (food insecurity, Meals on Wheels).",3,"apply",["malnutrition","nutrition","elderly"],"fm-geriatrics"));
cards.push(c("card-tn3-fm-"+n++,"What is the approach to driving assessment in elderly patients with cognitive impairment?","MoCA <18 or significant functional impairment: consider unfit. Refer for comprehensive driving evaluation. Mandatory reporting of medically unfit drivers varies by province (mandatory in AB, ON; discretionary in BC, QC)","CMA Physician Guide to Determining Fitness to Drive. Dementia per se does not preclude driving - functional assessment needed. Provincial reporting obligations: physicians may/must report. Consider progressive nature. Patient safety vs autonomy. Discuss transportation alternatives.",4,"apply",["driving fitness","cognitive impairment","reporting"],"fm-geriatrics"));
cards.push(c("card-tn3-fm-"+n++,"What is the palliative approach to care in geriatrics?","Early integration of palliative principles alongside disease-directed therapy. Symptom management (pain, dyspnea, nausea, delirium). Goals of care conversations. Caregiver support. Hospice referral when appropriate","Palliative approach differs from end-of-life care - can be concurrent with curative treatment. In Canada hospice and palliative care is publicly funded. ESAS (Edmonton Symptom Assessment System) for symptom monitoring. Opioids for dyspnea and pain are appropriate at end of life.",3,"apply",["palliative care","geriatrics","symptom management"],"fm-geriatrics"));
cards.push(c("card-tn3-fm-"+n++,"What are the criteria for and management of behavioral and psychological symptoms of dementia (BPSD)?","Non-pharmacological first: identify triggers, routine, music therapy, redirection, caregiver education. Pharmacological only for severe agitation/psychosis: risperidone 0.25-1mg (only approved antipsychotic for BPSD in Canada). Time-limited trial","Antipsychotics carry black-box warning for increased mortality in elderly dementia (1.6-1.7x). Attempt taper after 3 months stability. Avoid benzodiazepines (paradoxical agitation, falls). Trazodone for sleep. Assess for pain, constipation, infection as causes.",4,"apply",["BPSD","dementia","antipsychotic","geriatrics"],"fm-geriatrics"));
cards.push(c("card-tn3-fm-"+n++,"What is the Choosing Wisely Canada approach to geriatric care?","Key recommendations: do not use antipsychotics first-line for BPSD, avoid benzodiazepines for insomnia in elderly, do not screen with PSA >70, avoid screening tests when life expectancy <10y, do not use PPI long-term without reassessment","Choosing Wisely Canada promotes evidence-based reduction of unnecessary tests and treatments. Particularly relevant in elderly where harms of interventions may exceed benefits. Each specialty society contributes top 5 recommendations. Promotes shared decision-making.",3,"recall",["Choosing Wisely","geriatrics","overtreatment"],"fm-geriatrics"));

console.log("FM cards added. Total: " + cards.length);
fs.writeFileSync("C:/dev/srs-mccqe1/data/_parts123.json", JSON.stringify(cards));
console.log("Parts 1-3 saved");
