const fs = require('fs');
const cards = [];
let n = 1;
function add(topicId, q, a, ex, diff, bloom, tags) {
  cards.push({ id: `card-tn2-psych-${n++}`, question: q, answer: a, explanation: ex, difficulty: diff, bloomLevel: bloom, tags, topicId });
}

// PSYCH-MOOD (15)
add('psych-mood','What are the DSM-5 criteria for major depressive disorder?','>=5 symptoms during the same 2-week period (must include depressed mood OR anhedonia): SIG-E-CAPS: Sleep changes, Interest loss (anhedonia), Guilt/worthlessness, Energy loss, Concentration difficulty, Appetite/weight change, Psychomotor agitation/retardation, Suicidal ideation. Causes significant distress or functional impairment. Not attributable to substance or medical condition.',
'MDD affects ~5% of Canadians at any time. CANMAT (Canadian Network for Mood and Anxiety Treatments) guidelines are the standard for treatment in Canada. The diagnosis requires functional impairment-meeting symptom criteria alone is insufficient. Screen for bipolar before starting antidepressants.',3,'recall',['MDD','DSM-5','SIG-E-CAPS','depression criteria','psychiatry']);

add('psych-mood','What is the PHQ-9 and how is it used in clinical practice?','Patient Health Questionnaire-9: 9 items corresponding to DSM-5 depression criteria, each scored 0-3 (not at all to nearly every day). Total score 0-27. Severity: 0-4 minimal, 5-9 mild, 10-14 moderate, 15-19 moderately severe, 20-27 severe. Item 9 specifically screens for suicidal ideation.',
'PHQ-9 is widely used in Canadian primary care for depression screening and monitoring treatment response. A decrease of >=5 points indicates clinically meaningful improvement. CTFPHC recommends against universal depression screening in primary care, but targeted screening with PHQ-9 is appropriate for at-risk populations.',3,'apply',['PHQ-9','depression screening','monitoring','psychiatry']);

add('psych-mood','What is the CANMAT first-line pharmacological treatment for MDD?','First-line: SSRIs (escitalopram, sertraline, fluoxetine), SNRIs (venlafaxine, duloxetine), bupropion, mirtazapine. Second-line: TCAs, quetiapine XR, trazodone. Third-line: MAOIs, lithium augmentation. Choice based on: side effect profile, comorbidities, prior response, drug interactions. Adequate trial: therapeutic dose for 4-8 weeks.',
'CANMAT 2023 guidelines recommend SSRIs/SNRIs as first-line due to efficacy, tolerability, and safety in overdose. Escitalopram and sertraline have best overall evidence. Bupropion is preferred when sexual dysfunction, weight gain, or smoking cessation are concerns. Start low, titrate to therapeutic dose.',4,'apply',['antidepressant','SSRI','SNRI','CANMAT','treatment','psychiatry']);

add('psych-mood','What are the key side effects of common antidepressant classes?','SSRIs: GI (nausea, diarrhea), sexual dysfunction (30-50%), weight gain, hyponatremia (SIADH, especially elderly), serotonin syndrome, increased suicidality in <25 (black box warning). SNRIs: same as SSRIs + elevated BP (venlafaxine), discontinuation syndrome. Bupropion: insomnia, seizure risk (dose-dependent, CI if eating disorder/seizures), NO sexual dysfunction. Mirtazapine: sedation, weight gain, NO sexual dysfunction. TCAs: anticholinergic, orthostatic hypotension, cardiac toxicity in overdose (QRS widening).',
'CANMAT considers side effect profiles in treatment selection. Serotonin syndrome (hyperthermia, rigidity, clonus, agitation) is a medical emergency-stop offending agent, cyproheptadine. SSRI discontinuation syndrome (dizziness, nausea, paresthesias) is most common with paroxetine and venlafaxine due to short half-lives.',4,'recall',['antidepressant side effects','SSRI','TCA','pharmacology','psychiatry']);

add('psych-mood','What are the DSM-5 criteria for bipolar I vs bipolar II disorder?','Bipolar I: >=1 manic episode (>=7 days or any duration if hospitalized: elevated/expansive/irritable mood + increased energy + >=3 of: decreased sleep, talkativeness, racing thoughts, distractibility, increased goal-directed activity, risky behavior). Bipolar II: >=1 hypomanic episode (>=4 days, same symptoms but less severe, no psychosis, no hospitalization) + >=1 major depressive episode.',
'Bipolar I does NOT require a depressive episode for diagnosis-mania alone suffices. Bipolar II is not milder than bipolar I; patients spend more time depressed and have high suicide risk. CANMAT emphasizes screening for bipolarity before starting antidepressants (antidepressant monotherapy can trigger mania).',4,'recall',['bipolar disorder','mania','hypomania','DSM-5','psychiatry']);

add('psych-mood','What is the pharmacological management of bipolar disorder (acute mania and maintenance)?','Acute mania: lithium or valproate (first-line mood stabilizers) + atypical antipsychotic (quetiapine, risperidone, olanzapine, aripiprazole) for acute stabilization. Bipolar depression: quetiapine monotherapy (first-line), lamotrigine, lithium, or lurasidone. Maintenance: lithium (gold standard, reduces suicide), valproate, quetiapine, lamotrigine. AVOID: antidepressant monotherapy (triggers mania/rapid cycling).',
'CANMAT bipolar guidelines recommend mood stabilizers as backbone therapy. Lithium requires monitoring: levels (0.6-1.2 mmol/L), renal function, TSH, calcium q6-12 months. Lithium has narrow therapeutic index-toxicity: coarse tremor, ataxia, confusion, renal failure. Valproate: monitor LFTs, CBC, levels.',5,'apply',['bipolar treatment','lithium','mood stabilizer','CANMAT','psychiatry']);

add('psych-mood','What lithium monitoring is required and what are the signs of toxicity?','Monitoring: serum lithium levels (12h post-dose, target 0.6-1.2 mmol/L for acute, 0.6-0.8 for maintenance), creatinine/eGFR q6-12mo, TSH q6-12mo (causes hypothyroidism 20%), calcium/PTH (hyperparathyroidism), pregnancy test (Ebstein anomaly risk). Toxicity: mild (1.5-2.0): coarse tremor, GI, lethargy. Moderate (2.0-2.5): confusion, myoclonus, hyperreflexia. Severe (>2.5): seizures, coma, renal failure, cardiac arrhythmia.',
'Lithium has the strongest evidence for reducing suicide in bipolar disorder. Common precipitants of toxicity: dehydration, NSAIDs, ACE inhibitors, thiazides (all increase lithium levels). Management of toxicity: stop lithium, IV fluids, hemodialysis if severe (>2.5 mmol/L or severe symptoms).',5,'apply',['lithium monitoring','toxicity','bipolar','psychiatry']);

add('psych-mood','What are the features and management of serotonin syndrome?','Triad: altered mental status, autonomic instability (hyperthermia, diaphoresis, tachycardia, HTN), neuromuscular excitability (clonus-especially lower extremity, hyperreflexia, rigidity). Caused by serotonergic drug combinations (SSRI + MAOI most dangerous, also tramadol, linezolid, triptans). Management: stop offending agents, IV fluids, benzodiazepines, cyproheptadine (serotonin antagonist) 12mg then 4mg q2h, active cooling.',
'Serotonin syndrome is distinct from neuroleptic malignant syndrome (NMS): SS has clonus/hyperreflexia and rapid onset; NMS has lead-pipe rigidity and slow onset. Hunter Serotonin Toxicity Criteria: clonus (spontaneous or inducible) is the most important diagnostic feature. Canadian guidelines mandate 14-day washout between MAOI and SSRI.',5,'apply',['serotonin syndrome','drug interaction','emergency','psychiatry']);

add('psych-mood','What is the approach to treatment-resistant depression (TRD)?','Definition: failure to respond to >=2 adequate antidepressant trials. CANMAT approach: (1) Optimize current therapy (dose, duration, adherence). (2) Switch within or between classes. (3) Augment: lithium, atypical antipsychotic (aripiprazole, quetiapine), thyroid hormone (T3). (4) Combination: SSRI + bupropion or mirtazapine. (5) Esketamine nasal spray (approved in Canada). (6) ECT (most effective treatment for severe TRD, catatonia, psychotic depression).',
'ECT has 50-70% response rate in TRD and is the most effective acute treatment for severe depression. Canadian guidelines support ECT availability as an essential psychiatric service. Esketamine (Spravato) is available in Canada under restricted access programs. Repetitive TMS is another option for TRD.',5,'apply',['treatment-resistant depression','augmentation','ECT','CANMAT','psychiatry']);

add('psych-mood','What are the risk factors and features of postpartum depression vs postpartum psychosis?','PPD: onset within 4 weeks to 12 months postpartum, features of MDD, may include anxiety, guilt about parenting, thoughts of harming infant. Risk factors: prior depression, poor social support, unplanned pregnancy. Postpartum psychosis: RARE (1/1000), onset within first 2 weeks, features: confusion, disorganized behavior, mood lability, hallucinations/delusions. Psychiatric EMERGENCY-risk of infanticide.',
'SOGC and CPS recommend Edinburgh Postnatal Depression Scale (EPDS) screening. Score >=13 warrants further assessment. PPD treated with SSRIs (sertraline safe in breastfeeding) + psychotherapy. Postpartum psychosis requires hospitalization, antipsychotics, mood stabilizers. History of bipolar is the strongest risk factor for postpartum psychosis.',4,'apply',['postpartum depression','postpartum psychosis','EPDS','psychiatry']);

add('psych-mood','What is the role of psychotherapy in mood disorders?','CBT (cognitive behavioral therapy): first-line for mild-moderate MDD, equivalent to antidepressants. IPT (interpersonal therapy): effective for MDD. DBT (dialectical behavior therapy): borderline personality disorder, chronic suicidality. CANMAT recommends combined pharmacotherapy + psychotherapy for moderate-severe MDD (superior to either alone). Mindfulness-based cognitive therapy: reduces relapse in recurrent depression.',
'CANMAT guidelines recommend psychotherapy as first-line for mild depression and combined with pharmacotherapy for moderate-severe. Access to psychotherapy in Canada is limited-many provinces lack public funding. Online CBT programs (e.g., BounceBack) are increasingly available across Canada.',3,'apply',['psychotherapy','CBT','mood disorders','CANMAT','psychiatry']);

add('psych-mood','What is the definition and management of persistent depressive disorder (dysthymia)?','DSM-5: depressed mood most of the day, more days than not, for >=2 years (1 year in children/adolescents) + >=2 of: appetite change, sleep change, low energy, low self-esteem, poor concentration, hopelessness. Never symptom-free for >2 months. May coexist with MDD episodes (double depression).',
'Persistent depressive disorder (formerly dysthymia) has lower symptom severity but longer duration, causing significant cumulative impairment. Treatment combines antidepressants + psychotherapy (CBT or CBASP). CANMAT recommends same antidepressant choices as MDD.',3,'recall',['dysthymia','persistent depressive disorder','DSM-5','psychiatry']);

add('psych-mood','What medical conditions should be excluded in the differential diagnosis of depression?','Hypothyroidism, Cushing syndrome, Addison disease, hyperparathyroidism, B12/folate deficiency, anemia, sleep apnea, chronic pain, cancer (particularly pancreatic), neurological disease (Parkinson, MS, dementia, stroke), medications (beta-blockers, corticosteroids, interferon, isotretinoin, oral contraceptives), substance use (alcohol, benzodiazepine withdrawal).',
'CANMAT recommends baseline investigations for new MDD diagnosis: TSH, CBC, electrolytes, glucose, B12 if risk factors. Medical conditions causing depressive symptoms should be treated before attributing to primary MDD. Depression is also highly comorbid with chronic medical conditions.',3,'analyze',['depression differential','medical causes','organic','psychiatry']);

add('psych-mood','When should antidepressant discontinuation be considered and how?','After first episode: continue for 6-12 months after remission. After 2+ episodes or chronic: consider indefinite treatment. Discontinuation: taper gradually over 4+ weeks (longer for paroxetine, venlafaxine). Discontinuation syndrome: dizziness, nausea, anxiety, insomnia, electric shock sensations (brain zaps), irritability. Onset 1-3 days, lasts 1-2 weeks. Fluoxetine has lowest risk due to long half-life.',
'CANMAT recommends gradual taper to minimize discontinuation syndrome. Relapse risk is highest in the first 6 months after stopping. Shared decision-making about duration. Canadian primary care guidelines recommend monitoring for relapse during and after taper.',3,'apply',['antidepressant discontinuation','taper','maintenance therapy','psychiatry']);

add('psych-mood','What is seasonal affective disorder (SAD) and its treatment?','DSM-5: recurrent MDD with regular seasonal pattern (typically fall/winter onset, spring/summer remission) for >=2 years. More prevalent in northern latitudes (relevant to Canada). First-line treatment: light therapy (10,000 lux for 30 min/day in morning, within 1 hour of waking). Also effective: SSRIs (fluoxetine), bupropion (prophylactic starting in fall), CBT.',
'SAD is particularly relevant in Canadian practice given latitude. Light therapy has rapid onset (1-2 weeks). Bupropion XR started in autumn prevents SAD episodes (Modell et al). CANMAT includes light therapy as first-line treatment for SAD, equivalent to pharmacotherapy.',3,'apply',['SAD','seasonal affective disorder','light therapy','psychiatry']);

// PSYCH-PSYCHOSIS (15)
add('psych-psychosis','What are the DSM-5 diagnostic criteria for schizophrenia?','>=2 of the following (>=1 must be 1, 2, or 3): (1) delusions, (2) hallucinations, (3) disorganized speech, (4) grossly disorganized or catatonic behavior, (5) negative symptoms (flat affect, alogia, avolition). Duration: continuous signs >=6 months with >=1 month of active symptoms. Functional decline from premorbid level. Rule out schizoaffective, mood disorders, substance, medical causes.',
'Schizophrenia affects ~1% of the population. Canadian guidelines emphasize early detection and intervention. Duration criterion (6 months) distinguishes schizophrenia from schizophreniform disorder (<6 months) and brief psychotic disorder (<1 month). Negative symptoms are most disabling and hardest to treat.',4,'recall',['schizophrenia','DSM-5','psychosis','diagnostic criteria','psychiatry']);

add('psych-psychosis','What are the first-line and second-line antipsychotics for schizophrenia?','First-line: atypical (second-generation) antipsychotics-risperidone, olanzapine, quetiapine, aripiprazole, paliperidone, ziprasidone, lurasidone. All have similar efficacy for positive symptoms. Second-line: typical (first-generation)-haloperidol, chlorpromazine, fluphenazine. Treatment-resistant: clozapine (gold standard after failure of >=2 adequate antipsychotic trials at adequate dose/duration).',
'Canadian Schizophrenia Guidelines recommend SGAs as first-line due to lower EPS risk. Choice is based on side effect profile. Long-acting injectable (LAI) antipsychotics (paliperidone palmitate, aripiprazole lauroxil) improve adherence. Clozapine is the only antipsychotic with proven superiority for treatment-resistant schizophrenia.',4,'apply',['antipsychotics','schizophrenia treatment','clozapine','psychiatry']);

add('psych-psychosis','What are the major side effects of antipsychotic medications by class?','Typical/FGA: extrapyramidal symptoms (acute dystonia, akathisia, parkinsonism), tardive dyskinesia, neuroleptic malignant syndrome. Atypical/SGA: metabolic syndrome (weight gain, dyslipidemia, hyperglycemia-worst with olanzapine and clozapine), QTc prolongation (ziprasidone), hyperprolactinemia (risperidone, paliperidone), sedation (quetiapine, olanzapine).',
'Metabolic monitoring is mandatory per Canadian Psychiatric Association: weight, waist circumference, fasting glucose, lipids at baseline, 3 months, then annually. Olanzapine and clozapine carry highest metabolic risk. Aripiprazole and ziprasidone are most weight-neutral. EPS treated with benztropine or benzodiazepines.',4,'recall',['antipsychotic side effects','EPS','metabolic syndrome','psychiatry']);

add('psych-psychosis','What is neuroleptic malignant syndrome (NMS) and how is it managed?','Clinical features: lead-pipe rigidity, hyperthermia (>38°C), autonomic instability (tachycardia, labile BP, diaphoresis), altered mental status. Labs: elevated CK (often >1000), leukocytosis, elevated LFTs, metabolic acidosis, myoglobinuria. Onset: days to weeks after antipsychotic initiation or dose increase. Management: stop antipsychotic, supportive care (cooling, IV fluids), dantrolene (muscle relaxant), bromocriptine (dopamine agonist).',
'NMS has 10-20% mortality if untreated. Differentiate from serotonin syndrome: NMS has lead-pipe rigidity (not clonus) and slow onset. Risk factors: high-potency FGA (haloperidol), dehydration, rapid dose escalation. Can recur-restart antipsychotic cautiously after >=2 weeks, different class, low dose.',5,'apply',['NMS','neuroleptic malignant syndrome','antipsychotic emergency','psychiatry']);

add('psych-psychosis','What is the monitoring protocol for clozapine?','Mandatory ANC monitoring (risk of agranulocytosis ~1%): weekly CBC for first 26 weeks, then q2 weeks for next 26 weeks, then monthly. Hold clozapine if ANC <1500 (non-benign ethnic neutropenia) or <1000 (BEN). Other monitoring: fasting glucose/lipids q3-6mo, weight monthly, ECG (myocarditis risk in first month), bowel function (constipation/ileus). Annual echocardiogram in some protocols.',
'Clozapine is the gold standard for treatment-resistant schizophrenia (30% respond who failed other antipsychotics). Unique side effects: agranulocytosis, myocarditis (first month), metabolic syndrome, seizures (dose-dependent), sialorrhea, severe constipation/ileus. Canadian Clozapine Registry tracks all patients.',5,'apply',['clozapine monitoring','agranulocytosis','treatment-resistant','psychiatry']);

add('psych-psychosis','What is the approach to first-episode psychosis in Canada?','Early intervention is critical: assess safety, medical workup (CBC, electrolytes, TSH, B12, HIV, syphilis, urine drug screen, CT/MRI brain if indicated). Start low-dose atypical antipsychotic. Refer to early psychosis intervention (EPI) program. Psychoeducation, family involvement, CBT for psychosis. Monitor closely for 2 years. Consider substance-induced psychosis as alternative diagnosis.',
'Canadian EPI programs (available in most provinces) improve outcomes through early identification and comprehensive treatment. First episode patients are more responsive and sensitive to antipsychotics-use lower doses. Duration of untreated psychosis (DUP) is the strongest modifiable predictor of outcome.',4,'apply',['first-episode psychosis','early intervention','EPI','psychiatry']);

add('psych-psychosis','What are the key differences between positive and negative symptoms of schizophrenia and their treatment implications?','Positive symptoms: delusions, hallucinations, disorganized speech/behavior-respond well to antipsychotics. Negative symptoms: flat affect, alogia (poverty of speech), avolition (lack of motivation), anhedonia, social withdrawal-poorly responsive to antipsychotics (except clozapine has modest benefit). Cognitive symptoms: impaired attention, memory, executive function-poorly responsive to medications.',
'Negative and cognitive symptoms are the primary determinants of functional disability in schizophrenia. Canadian Schizophrenia Guidelines recommend psychosocial interventions (supported employment, social skills training, cognitive remediation) for these domains. Cariprazine may have modest benefit for negative symptoms.',3,'recall',['positive symptoms','negative symptoms','cognitive symptoms','schizophrenia','psychiatry']);

add('psych-psychosis','What is the differential diagnosis of psychosis?','Primary psychiatric: schizophrenia, schizoaffective, brief psychotic disorder, delusional disorder, bipolar with psychotic features, MDD with psychotic features. Substance-induced: cannabis, methamphetamine, cocaine, hallucinogens, alcohol withdrawal (DT), corticosteroids. Medical: delirium (most common in hospital), autoimmune encephalitis (anti-NMDAR), CNS infections, brain tumor, temporal lobe epilepsy, metabolic (hepatic encephalopathy, porphyria), endocrine (thyroid, Cushing).',
'Canadian guidelines emphasize thorough medical workup before diagnosing primary psychotic disorder. Anti-NMDA receptor encephalitis is an increasingly recognized cause of psychosis, especially in young women. Substance-induced psychosis: if symptoms persist >1 month after cessation, consider primary psychotic disorder.',4,'analyze',['psychosis differential','substance-induced','medical causes','psychiatry']);

add('psych-psychosis','What is schizoaffective disorder and how does it differ from schizophrenia and mood disorders?','DSM-5: concurrent period with mood episode (major depressive or manic) AND delusions/hallucinations, PLUS >=2 weeks of delusions/hallucinations WITHOUT mood symptoms (key distinguishing criterion). If psychosis only during mood episodes = mood disorder with psychotic features. If mood symptoms brief relative to psychosis = schizophrenia.',
'Schizoaffective disorder is often a diagnostic challenge. Treatment combines antipsychotic + mood stabilizer or antidepressant depending on subtype (bipolar vs depressive). Canadian clinical practice often revisits this diagnosis over time as longitudinal course clarifies the picture.',4,'analyze',['schizoaffective','differential diagnosis','mood psychosis','psychiatry']);

add('psych-psychosis','What are the types of extrapyramidal symptoms (EPS) and their management?','Acute dystonia (hours-days): sustained muscle contractions (torticollis, oculogyric crisis). Treat: benztropine 1-2mg IM/IV or diphenhydramine 50mg IM. Akathisia (days-weeks): inner restlessness, inability to sit still. Treat: reduce dose, switch antipsychotic, propranolol, benzodiazepine, mirtazapine. Parkinsonism (weeks-months): bradykinesia, rigidity, tremor. Treat: reduce dose, benztropine. Tardive dyskinesia (months-years): involuntary choreoathetoid movements (lip smacking, tongue protrusion). Treat: switch to clozapine/quetiapine, valbenazine, deutetrabenazine.',
'EPS are more common with high-potency FGA (haloperidol) but can occur with any antipsychotic. TD is potentially irreversible-screen regularly with AIMS (Abnormal Involuntary Movement Scale). Valbenazine is approved in Canada for TD treatment. Young males are highest risk for acute dystonia.',4,'apply',['EPS','extrapyramidal symptoms','tardive dyskinesia','akathisia','psychiatry']);

add('psych-psychosis','What are the long-acting injectable (LAI) antipsychotic options and their role?','Available in Canada: paliperidone palmitate (monthly or q3month), aripiprazole lauroxil/monohydrate (monthly or q2month), risperidone LAI (q2 weeks), fluphenazine decanoate (q2-4 weeks), haloperidol decanoate (q4 weeks). Role: non-adherence (most common cause of relapse), patient preference, forensic settings, first-episode psychosis (CANMAT recommends early consideration).',
'LAI antipsychotics reduce relapse and rehospitalization by 30-50% compared to oral formulations. CANMAT now recommends discussing LAI early in treatment, not just after non-adherence. Overlap with oral medication is required during initiation (varies by formulation).',4,'apply',['LAI','long-acting injectable','adherence','antipsychotic','psychiatry']);

add('psych-psychosis','What psychosocial interventions are recommended for schizophrenia?','Supported employment (IPS model): most effective for improving employment outcomes. Social skills training. Cognitive behavioral therapy for psychosis (CBTp): reduces positive symptoms and distress. Family psychoeducation: reduces relapse. Assertive community treatment (ACT): for severely ill patients. Cognitive remediation. Peer support programs.',
'Canadian Schizophrenia Guidelines recommend comprehensive psychosocial programs alongside pharmacotherapy. ACT teams (intensive community-based multidisciplinary teams) are available in most Canadian provinces. Recovery-oriented care is the guiding philosophy of Canadian mental health policy.',3,'apply',['psychosocial interventions','supported employment','ACT','schizophrenia','psychiatry']);

add('psych-psychosis','What is the approach to catatonia?','Features: immobility/stupor, mutism, posturing, waxy flexibility, negativism, staring, stereotypies, echolalia, echopraxia. Can occur in schizophrenia, mood disorders, or medical conditions. Bush-Francis Catatonia Rating Scale for diagnosis. Treatment: (1) lorazepam challenge test (1-2mg IV-diagnostic and therapeutic, response within minutes confirms catatonia), (2) if no response: ECT (highly effective, potentially life-saving for malignant catatonia).',
'Catatonia is a medical emergency when malignant (autonomic instability, hyperthermia, rhabdomyolysis). AVOID antipsychotics in acute catatonia (can worsen symptoms or precipitate NMS). Benzodiazepines are first-line. ECT has response rates >80% in catatonia and should not be delayed if benzodiazepines fail.',5,'apply',['catatonia','lorazepam challenge','ECT','psychiatry']);

add('psych-psychosis','What are the metabolic monitoring requirements for patients on antipsychotics?','Baseline: weight, BMI, waist circumference, fasting glucose, HbA1c, lipid profile, BP. 1 month: weight. 3 months: weight, fasting glucose, lipids. 6 months: weight, fasting glucose, lipids. Annually: all of the above + HbA1c. If significant metabolic changes: lifestyle interventions, consider switch to metabolically neutral antipsychotic (aripiprazole, ziprasidone), consider metformin.',
'Canadian Psychiatric Association consensus guidelines mandate metabolic monitoring. Patients on antipsychotics have 20-year reduced life expectancy, largely due to cardiovascular disease. Metabolic syndrome rates: 30-40% in schizophrenia. Metformin (off-label) can reduce antipsychotic-associated weight gain by 3-4 kg.',4,'apply',['metabolic monitoring','antipsychotic','cardiovascular risk','psychiatry']);

// PSYCH-ANXIETY (15)
add('psych-anxiety','What are the DSM-5 criteria for generalized anxiety disorder?','Excessive anxiety and worry occurring more days than not for >=6 months about multiple events/activities. Difficulty controlling worry. >=3 of 6 symptoms: restlessness, fatigue, difficulty concentrating, irritability, muscle tension, sleep disturbance. Causes significant distress or functional impairment.',
'GAD is the most common anxiety disorder in primary care. CANMAT guidelines recommend both CBT and pharmacotherapy as first-line treatments. Differentiate from adjustment disorder (identifiable stressor, <6 months) and normal worry (no impairment).',3,'recall',['GAD','generalized anxiety disorder','DSM-5','psychiatry']);

add('psych-anxiety','What is the first-line pharmacotherapy for anxiety disorders per CANMAT?','GAD: escitalopram, sertraline, venlafaxine, duloxetine, pregabalin. Panic disorder: escitalopram, sertraline, venlafaxine. Social anxiety disorder: escitalopram, sertraline, venlafaxine, fluvoxamine, paroxetine. OCD: fluoxetine, fluvoxamine, sertraline, paroxetine (higher doses needed). PTSD: sertraline, paroxetine, venlafaxine.',
'CANMAT recommends SSRIs/SNRIs as first-line for all anxiety disorders. Start at half the antidepressant dose (anxiety patients are sensitive to activation effects). Benzodiazepines are second-line and time-limited. OCD requires higher SSRI doses (e.g., fluoxetine 40-80mg) than depression.',4,'apply',['anxiety treatment','SSRI','CANMAT','pharmacotherapy','psychiatry']);

add('psych-anxiety','What are the DSM-5 criteria for panic disorder and its management?','Recurrent unexpected panic attacks (abrupt surge of intense fear peaking within minutes with >=4 of 13 symptoms: palpitations, sweating, trembling, SOB, choking, chest pain, nausea, dizziness, chills/heat, paresthesias, derealization, fear of losing control, fear of dying). >=1 month of persistent concern about additional attacks OR maladaptive behavioral change.',
'CBT with interoceptive exposure is the most effective psychotherapy for panic disorder. CANMAT recommends SSRI/SNRI + CBT as optimal combination. Benzodiazepines for acute attacks but avoid long-term use. Rule out cardiac, pulmonary, and endocrine causes before diagnosing.',3,'recall',['panic disorder','DSM-5','panic attacks','psychiatry']);

add('psych-anxiety','What is the approach to obsessive-compulsive disorder (OCD)?','DSM-5: obsessions (recurrent intrusive thoughts causing anxiety) AND/OR compulsions (repetitive behaviors/mental acts in response to obsessions). Time-consuming (>1h/day) or causing distress/impairment. Treatment: first-line is exposure and response prevention (ERP)-specific CBT for OCD. Pharmacotherapy: SSRI at high dose (e.g., fluoxetine 40-80mg, sertraline 200mg). Augment with low-dose antipsychotic if partial SSRI response.',
'OCD has a distinct neurobiology (cortico-striato-thalamo-cortical circuit) and treatment approach from other anxiety disorders. CANMAT emphasizes ERP as the most effective treatment. Treatment-resistant OCD may respond to IV clomipramine, deep brain stimulation (experimental), or neurosurgery (extremely rare).',4,'apply',['OCD','obsessive-compulsive','ERP','treatment','psychiatry']);

add('psych-anxiety','What is the diagnosis and management of PTSD?','DSM-5 criteria: exposure to traumatic event + symptoms in 4 clusters lasting >1 month: (1) intrusion (flashbacks, nightmares, distress with reminders), (2) avoidance (of memories, triggers), (3) negative cognitions/mood (guilt, detachment, anhedonia), (4) hyperarousal (hypervigilance, startle, irritability, sleep disturbance, reckless behavior). Treatment: trauma-focused CBT (cognitive processing therapy, prolonged exposure) first-line. Pharmacotherapy: SSRI (sertraline, paroxetine) or venlafaxine.',
'CANMAT PTSD guidelines recommend trauma-focused psychotherapy as first-line over pharmacotherapy. Prazosin (alpha-1 blocker) can be used for PTSD-related nightmares. Benzodiazepines are NOT recommended for PTSD (may impair extinction of fear memory). Screen for comorbid substance use and depression.',4,'apply',['PTSD','trauma','CBT','treatment','psychiatry']);

add('psych-anxiety','What is social anxiety disorder and how is it differentiated from normal shyness?','DSM-5: marked fear/anxiety about social situations where scrutinized (speaking, eating, performing), fear of showing anxiety symptoms and being judged, social situations almost always provoke anxiety, avoided or endured with intense anxiety, out of proportion, >=6 months, functional impairment. Differentiate: shyness does not cause significant impairment or avoidance.',
'Social anxiety disorder (social phobia) is one of the most common anxiety disorders. CANMAT recommends CBT (including group CBT) and/or SSRI/SNRI as first-line. Performance-only subtype may respond to PRN propranolol or benzodiazepine. Comorbid alcohol use disorder is common (self-medication).',3,'recall',['social anxiety disorder','social phobia','DSM-5','psychiatry']);

add('psych-anxiety','What is the role and limitations of benzodiazepines in anxiety treatment?','Role: rapid symptom relief for acute anxiety, panic attacks, agitation. Short-term use (<2-4 weeks) during SSRI initiation. Limitations: tolerance, physical dependence (withdrawal: seizures, delirium), cognitive impairment (especially elderly), falls, paradoxical disinhibition, respiratory depression (especially with opioids), impair psychotherapy outcomes. Long-acting (clonazepam, diazepam) preferred over short-acting (alprazolam, lorazepam).',
'CANMAT recommends benzodiazepines as second-line and time-limited for anxiety disorders. Canadian guidelines emphasize deprescribing benzodiazepines in elderly (Beers criteria). Taper gradually (10-25% reduction every 1-2 weeks) to prevent withdrawal seizures. CTFPHC identifies benzodiazepines as a potentially inappropriate medication in elderly.',4,'apply',['benzodiazepines','limitations','anxiety','deprescribing','psychiatry']);

add('psych-anxiety','What are specific phobias and their treatment?','DSM-5: marked fear/anxiety about a specific object or situation (animals, natural environment, blood-injection-injury, situational, other), almost always provokes immediate anxiety, avoided or endured with intense anxiety, out of proportion, >=6 months. Treatment: exposure therapy (systematic desensitization, graded exposure) is the ONLY effective treatment. Pharmacotherapy is NOT first-line.',
'Specific phobias are the most common anxiety disorder. Blood-injection-injury phobia is unique: causes vasovagal response (bradycardia, hypotension, fainting) rather than tachycardia. Applied tension technique (tensing muscles during exposure) is the specific treatment for BII phobia. CBT exposure therapy has >90% success rate.',2,'apply',['specific phobia','exposure therapy','CBT','psychiatry']);

add('psych-anxiety','What is illness anxiety disorder (hypochondriasis) and somatic symptom disorder?','Illness anxiety disorder (DSM-5): preoccupation with having/acquiring a serious illness, somatic symptoms absent or mild, high anxiety about health, excessive health-related behaviors (checking, reassurance-seeking) or maladaptive avoidance. Somatic symptom disorder: >=1 distressing somatic symptom + disproportionate thoughts, feelings, or behaviors related to symptoms. Treatment: scheduled regular visits, CBT, SSRI, avoid unnecessary investigations.',
'These disorders are common in primary care. Key management principle: validate suffering without reinforcing sick role. Scheduled visits (not contingent on symptoms) reduce ED utilization. CANMAT recommends CBT as most effective treatment. Canadian guidelines emphasize avoiding iatrogenic harm from unnecessary investigations.',3,'apply',['illness anxiety disorder','somatic symptom disorder','management','psychiatry']);

add('psych-anxiety','What is the approach to acute agitation in the ED?','De-escalation first: quiet environment, verbal techniques, offer PRN oral medication. Oral: lorazepam 1-2mg OR olanzapine 5-10mg (dissolving tablet). If oral refused: IM olanzapine 10mg (do NOT combine with IM benzodiazepine-respiratory depression risk), OR IM haloperidol 5mg + lorazepam 2mg + diphenhydramine 50mg (B52 cocktail). Monitor vitals, consider medical causes (hypoglycemia, delirium, intoxication).',
'Canadian ER psychiatric guidelines emphasize verbal de-escalation and voluntary oral medication before chemical restraint. Physical restraint requires continuous monitoring and documentation. Rule out medical causes-20% of psychiatric presentations in ED have an underlying medical etiology.',4,'apply',['acute agitation','chemical restraint','ED management','psychiatry']);

add('psych-anxiety','What is the approach to body dysmorphic disorder (BDD)?','DSM-5: preoccupation with perceived defects in physical appearance not observable by others, repetitive behaviors (mirror checking, excessive grooming, reassurance-seeking, comparing). Related to OCD spectrum. Treatment: CBT (ERP-type, targeting avoidance and checking behaviors) + SSRI at high doses (same as OCD). Do NOT refer for cosmetic procedures (high dissatisfaction rate).',
'BDD is often underdiagnosed due to patient shame. Prevalence ~2%. Canadian guidelines recognize BDD as an OCD-spectrum disorder. Insight ranges from good to delusional (absent insight treated with SSRI augmented by antipsychotic, not antipsychotic alone). Suicide risk is elevated (25% attempt).',3,'apply',['body dysmorphic disorder','BDD','OCD spectrum','psychiatry']);

add('psych-anxiety','What is separation anxiety disorder in adults and children?','DSM-5: developmentally inappropriate, excessive anxiety about separation from attachment figures, >=3 of 8 symptoms (distress when separated, worry about losing attachment figure, reluctance to go out/be alone, nightmares about separation, somatic symptoms). Duration: >=4 weeks in children, >=6 months in adults. Peak onset: childhood, but can present in adults.',
'Separation anxiety disorder was previously only a childhood diagnosis-DSM-5 extended it to adults. Treatment: CBT focusing on graduated exposure to separation. In children, parental involvement in therapy is essential. SSRI for moderate-severe cases. Canadian child psychiatry guidelines emphasize school refusal as a common presentation.',3,'recall',['separation anxiety','childhood','adult','DSM-5','psychiatry']);

add('psych-anxiety','What are the features and management of adjustment disorder?','DSM-5: emotional/behavioral symptoms within 3 months of identifiable stressor, out of proportion to severity of stressor, significant impairment. Does NOT meet criteria for another mental disorder. Subtypes: with depressed mood, with anxiety, with mixed, with disturbance of conduct, unspecified. Resolves within 6 months of stressor ending. Treatment: supportive therapy, brief psychotherapy, short-term pharmacotherapy if needed.',
'Adjustment disorder is the most common psychiatric diagnosis in consultation-liaison psychiatry. Distinguished from normal stress reactions by functional impairment and from MDD/GAD by duration and precipitant. Self-limited by definition. If symptoms persist >6 months after stressor resolves, reconsider diagnosis.',2,'apply',['adjustment disorder','stressor','differential','psychiatry']);

// PSYCH-SUBSTANCE (15)
add('psych-substance','What are the CAGE and AUDIT screening tools for alcohol use disorder?','CAGE: Cut down (tried to?), Annoyed (by criticism?), Guilty (about drinking?), Eye-opener (morning drink?). >=2 positive = high suspicion for AUD. AUDIT (Alcohol Use Disorders Identification Test): 10 items scoring 0-40. 8-15: hazardous drinking. 16-19: harmful drinking. >=20: possible dependence. AUDIT-C (first 3 items): screening version, score >=4 men / >=3 women is positive.',
'CAGE is quick but less sensitive for early/hazardous drinking. AUDIT is the gold standard screening tool recommended by CCSA (Canadian Centre on Substance Abuse). AUDIT is more sensitive and specific than CAGE. Canadian primary care guidelines recommend universal alcohol screening.',3,'recall',['CAGE','AUDIT','alcohol screening','substance use','psychiatry']);

add('psych-substance','What are the DSM-5 criteria for substance use disorder?','>=2 of 11 criteria in 12 months: (1) larger amounts/longer than intended, (2) persistent desire/unsuccessful efforts to cut down, (3) excessive time obtaining/using/recovering, (4) craving, (5) failure to fulfill role obligations, (6) continued use despite social problems, (7) given up activities, (8) use in hazardous situations, (9) continued despite physical/psychological problems, (10) tolerance, (11) withdrawal. Severity: mild (2-3), moderate (4-5), severe (>=6).',
'DSM-5 eliminated the abuse/dependence distinction, creating a single spectrum. Craving was added as a new criterion. The dimensional severity approach guides treatment intensity. Canadian clinical practice guidelines use DSM-5 criteria for all substance use disorders.',3,'recall',['substance use disorder','DSM-5','diagnostic criteria','psychiatry']);

add('psych-substance','What is the management of alcohol withdrawal syndrome?','CIWA-Ar (Clinical Institute Withdrawal Assessment) guides treatment. Mild (CIWA <10): supportive, thiamine. Moderate (10-18): benzodiazepine (diazepam 10-20mg or lorazepam 2-4mg) on symptom-triggered protocol. Severe (>20) or seizures: aggressive benzodiazepine loading, ICU consideration. Prevention of Wernicke: thiamine 200-500mg IV BEFORE glucose. Phenobarbital for refractory cases. Nutritional support: thiamine, folate, magnesium.',
'Symptom-triggered protocols (benzodiazepines given based on CIWA score) are superior to fixed-schedule dosing (less medication, shorter treatment). Lorazepam is preferred in liver disease (no active metabolites). Alcohol withdrawal seizures peak at 24-48h. DT peak at 48-72h with 5-15% mortality if untreated.',5,'apply',['alcohol withdrawal','CIWA','benzodiazepine','delirium tremens','psychiatry']);

add('psych-substance','What are the pharmacological treatments for alcohol use disorder?','First-line: naltrexone 50mg/day PO or 380mg IM monthly (opioid antagonist, reduces craving/heavy drinking-contraindicated if opioid use). Acamprosate 666mg TID (GABA modulator, supports abstinence-safe in liver disease). Second-line: topiramate, gabapentin. Disulfiram 250mg/day (aldehyde dehydrogenase inhibitor-aversive therapy, requires motivation). Adjunct: thiamine supplementation.',
'CCSA and CRISM (Canadian Research Initiative on Substance Misuse) guidelines recommend naltrexone or acamprosate as first-line pharmacotherapy combined with psychosocial interventions. Naltrexone is particularly effective for reducing heavy drinking days. Canadian availability of injectable naltrexone (Vivitrol) is limited.',4,'apply',['alcohol use disorder treatment','naltrexone','acamprosate','psychiatry']);

add('psych-substance','What is the approach to opioid use disorder treatment in Canada?','First-line: opioid agonist therapy (OAT). Buprenorphine-naloxone (Suboxone): first-line per CRISM, can be initiated in office (micro-dosing or traditional induction), partial agonist, safer in overdose. Methadone: full agonist, requires daily witnessed ingestion initially, designated prescriber. Slow-release oral morphine (Kadian): second-line. Adjuncts: naltrexone (after detox only), psychosocial interventions, harm reduction.',
'Canadian Opioid Use Disorder Guidelines (CRISM) recommend buprenorphine-naloxone as first-line. OAT reduces mortality by 50%, reduces illicit opioid use, HIV/HCV transmission, and criminal activity. Naloxone kits are widely distributed in Canada for overdose reversal. Safe consumption sites are operating in several Canadian cities.',5,'apply',['opioid use disorder','buprenorphine','methadone','OAT','psychiatry']);

add('psych-substance','What is the management of acute opioid overdose?','Signs: respiratory depression (RR <12), miosis, decreased LOC. ABCs first. Naloxone: 0.4-2mg IV/IM/SC/IN, repeat q2-3min (max 10mg). Onset: 2 min IV, 5 min IM. Duration: 30-90 min (shorter than most opioids-monitor for renarcotization). If IV access unavailable: intranasal naloxone 4mg. Observe >=2h (longer for long-acting opioids). Consider intubation if no response to naloxone.',
'Canadian opioid crisis: >7000 deaths annually. Take-home naloxone programs are available across all provinces. Naloxone can precipitate withdrawal in opioid-dependent patients-titrate to adequate respirations, not full consciousness. Fentanyl overdoses may require higher naloxone doses.',5,'apply',['opioid overdose','naloxone','emergency management','psychiatry']);

add('psych-substance','What is the approach to cannabis use disorder?','Prevalence: ~7% of Canadian cannabis users meet criteria for CUD. Assessment: frequency, amount, method, age of onset, functional impairment. No approved pharmacotherapy for CUD. Treatment: CBT, motivational enhancement therapy (MET), contingency management. Cannabis hyperemesis syndrome: cyclic vomiting, hot bathing behavior, capsaicin cream. Psychosis risk: dose-dependent, especially with high-THC products and early-onset use.',
'Canada legalized recreational cannabis in 2018. CCSA Lower-Risk Cannabis Use Guidelines recommend: delay use until after 25, avoid high-THC products, avoid smoking, avoid frequent use. Cannabis use in adolescence increases psychosis risk 2-4x (particularly with daily use of high-potency products).',3,'apply',['cannabis use disorder','CUD','psychosis risk','psychiatry']);

add('psych-substance','What is the approach to benzodiazepine use disorder and deprescribing?','Gradual taper is essential (abrupt cessation causes seizures, delirium, death). Taper: switch to long-acting agent (diazepam) if on short-acting, reduce 10-25% every 1-2 weeks. Slower at lower doses. Total taper: 8-16 weeks minimum. Adjuncts: CBT for insomnia, pregabalin for anxiety during taper. Monitor for protracted withdrawal (anxiety, insomnia lasting months).',
'CCSA and Choosing Wisely Canada recommend deprescribing benzodiazepines in chronic users, especially elderly. Canadian Deprescribing Network provides guidelines. Benzodiazepine withdrawal syndrome: anxiety, insomnia, irritability, tremor, sensory hypersensitivity, psychosis, seizures. Risk of seizure increases with high dose and long duration.',4,'apply',['benzodiazepine deprescribing','taper','withdrawal','psychiatry']);

add('psych-substance','What are the clinical features and management of stimulant intoxication and withdrawal?','Intoxication (cocaine/amphetamine): euphoria, hyperactivity, tachycardia, hypertension, hyperthermia, dilated pupils, agitation, psychosis, seizures, chest pain (cocaine-coronary vasospasm). Management: benzodiazepines (NOT beta-blockers for cocaine-unopposed alpha stimulation), cooling, cardiac monitoring. Withdrawal: crash (fatigue, hypersomnia, dysphoria, increased appetite). No specific pharmacotherapy for stimulant use disorder.',
'Cocaine chest pain: treat as ACS but avoid beta-blockers (may worsen coronary vasospasm). Use benzodiazepines and nitroglycerin. Canadian stimulant use is rising (especially methamphetamine in Western Canada). Contingency management has best evidence for stimulant use disorder but limited availability in Canada.',4,'apply',['stimulant intoxication','cocaine','methamphetamine','psychiatry']);

add('psych-substance','What is Wernicke-Korsakoff syndrome and how is it prevented?','Wernicke encephalopathy (acute): triad of confusion, ataxia, ophthalmoplegia (nystagmus, 6th nerve palsy). Only 10-16% have classic triad. Caused by thiamine (B1) deficiency. Treatment: thiamine 200-500mg IV TID for 3-5 days (ALWAYS give BEFORE glucose). Korsakoff syndrome (chronic): anterograde and retrograde amnesia, confabulation. Often irreversible. Prevention: thiamine supplementation for ALL alcohol-dependent patients.',
'Wernicke is a medical emergency with 20% mortality if untreated. Oral thiamine is poorly absorbed in alcoholics-IV is essential. Give thiamine before glucose in all malnourished/alcohol patients to prevent precipitating Wernicke. Korsakoff develops in 80% of untreated Wernicke. Canadian guidelines recommend routine thiamine supplementation for all admitted alcohol-dependent patients.',5,'apply',['Wernicke-Korsakoff','thiamine','alcohol-related brain damage','psychiatry']);

add('psych-substance','What is the harm reduction approach to substance use in Canada?','Key principles: pragmatic acceptance that substance use exists, focus on reducing harm without requiring abstinence. Canadian programs: needle exchange programs, supervised consumption sites (supervised injection sites), naloxone distribution, drug checking services, safer supply programs, housing-first approaches.',
'Harm reduction is a pillar of Canadian drug policy per CCSA and Canadian federal health policy. InSite (Vancouver) was the first supervised consumption site in North America. Supreme Court of Canada upheld its legality in 2011. Safe supply prescribing (prescribed opioids to replace illicit supply) is expanding in Canada.',3,'recall',['harm reduction','supervised consumption','naloxone','Canadian drug policy','psychiatry']);

add('psych-substance','What is the management of nicotine dependence?','Fagerström Test for Nicotine Dependence assesses severity. First-line pharmacotherapy: varenicline (most effective, partial nicotinic agonist), NRT (patch + gum/lozenge combination), bupropion. Combination NRT = long-acting (patch) + short-acting (gum/inhaler/lozenge). Counseling + pharmacotherapy is most effective. Varenicline: start 1 week before quit date, 0.5mg x 3 days, 0.5mg BID x 4 days, then 1mg BID x 12 weeks. Extend to 24 weeks for relapse prevention.',
'CAN-ADAPTT (Canadian Action Network for Advancement and Prevention of Treatment of Tobacco) provides evidence-based guidelines. Smoking is the leading cause of preventable death in Canada. All healthcare encounters should include smoking status assessment and brief intervention (5 As: Ask, Advise, Assess, Assist, Arrange).',4,'apply',['smoking cessation','varenicline','NRT','nicotine dependence','psychiatry']);

add('psych-substance','What is motivational interviewing and its application in substance use?','MI: collaborative, person-centered communication style for strengthening motivation to change. Principles: express empathy (reflective listening), develop discrepancy (between current behavior and goals), roll with resistance (avoid arguing), support self-efficacy. Stages of Change: precontemplation, contemplation, preparation, action, maintenance, relapse.',
'MI is the most widely taught brief intervention technique in Canadian medical education. Evidence supports MI across substance use disorders, medication adherence, and health behavior change. A single MI session can reduce harmful alcohol use. FRAMES approach: Feedback, Responsibility, Advice, Menu, Empathy, Self-efficacy.',3,'apply',['motivational interviewing','stages of change','brief intervention','psychiatry']);

add('psych-substance','What is the approach to concurrent disorders (substance use + mental illness)?','Integrated treatment: address both simultaneously (sequential treatment leads to poor outcomes). Common combinations: AUD + depression, cannabis + psychosis, opioids + PTSD. Principles: stabilize acute intoxication/withdrawal first, then address both concurrently. Prefer medications effective for both conditions (e.g., SSRI for depression + AUD). Avoid benzodiazepines in patients with SUD.',
'50% of people with mental illness have a comorbid substance use disorder. Canadian guidelines (CCSA, CRISM) recommend integrated concurrent disorder programs. Many Canadian mental health acts allow involuntary admission for psychiatric emergency even when substance-related. Substance-induced mood/psychotic disorders typically resolve within 1 month of abstinence.',4,'apply',['concurrent disorders','dual diagnosis','integrated treatment','psychiatry']);

add('psych-substance','What are the medical complications of chronic alcohol use?','GI: fatty liver, alcoholic hepatitis, cirrhosis, pancreatitis, esophageal varices, Mallory-Weiss tears. Neuro: Wernicke-Korsakoff, peripheral neuropathy, cerebellar degeneration, alcohol-related dementia. Hematologic: macrocytic anemia (folate deficiency, direct toxicity), thrombocytopenia. Cardiac: alcoholic cardiomyopathy, holiday heart (AF). Other: increased cancer risk (oropharyngeal, esophageal, liver, breast, colorectal).',
'CCSA Low-Risk Alcohol Drinking Guidelines (updated 2023): no amount of alcohol is completely safe. New guidance: 0 drinks/week = no risk, 1-2 = low risk, 3-6 = moderate risk, 7+ = increasingly high risk. This represents a significant shift from previous Canadian guidelines that suggested "moderate" drinking was safe.',3,'recall',['alcohol complications','cirrhosis','medical consequences','psychiatry']);

// PSYCH-SUICIDE (15)
add('psych-suicide','What is the SAD PERSONS scale for suicide risk assessment?','S: Sex (male), A: Age (<19 or >45), D: Depression, P: Previous attempt, E: Ethanol/drug abuse, R: Rational thinking loss (psychosis), S: Social supports lacking, O: Organized plan, N: No spouse, S: Sickness (chronic illness). Each scores 1 point. 0-2: may be safe to discharge with follow-up. 3-4: close follow-up. 5-6: strongly consider hospitalization. 7-10: hospitalize.',
'While SAD PERSONS is widely taught, its predictive validity is limited. Canadian guidelines recommend comprehensive risk assessment over sole reliance on scales. Columbia Suicide Severity Rating Scale (C-SSRS) is increasingly used in Canadian EDs. No scale replaces clinical judgment.',3,'recall',['SAD PERSONS','suicide risk','assessment tool','psychiatry']);

add('psych-suicide','What are the key risk factors for completed suicide?','Strongest: previous suicide attempt (single strongest predictor), psychiatric illness (MDD, bipolar, schizophrenia, BPD, SUD), male sex (3:1 completed suicide ratio M:F), access to lethal means (especially firearms). Other: older age, chronic pain/illness, recent discharge from psychiatric care, family history, social isolation, recent loss, Indigenous identity (3x rate in Canada).',
'In Canada, suicide is the 9th leading cause of death and 2nd leading cause in youth (15-24). Canadian Armed Forces members and Indigenous peoples have significantly elevated rates. Means restriction (e.g., safe firearm storage, bridge barriers) is one of the most effective population-level interventions.',4,'recall',['suicide risk factors','completed suicide','epidemiology','psychiatry']);

add('psych-suicide','What is the approach to acute suicide risk assessment in the ED?','(1) Ensure safety (remove means, 1:1 observation). (2) Assess: suicidal ideation (active vs passive), plan (specific, lethal, available means), intent, timeline. (3) Prior attempts (method, lethality, rescue). (4) Risk factors and warning signs. (5) Protective factors (reasons for living, children, religious beliefs, social support, future-oriented thinking). (6) Formulation: low vs moderate vs high risk. (7) Disposition: safety plan + follow-up vs psychiatric consultation vs voluntary/involuntary admission.',
'No suicide risk assessment tool is predictive enough to determine disposition alone. Canadian psychiatric emergency guidelines emphasize clinical formulation. The "4 Ds" of high risk: desire, determined plan, dangerous method, deterrents absent. Asking about suicide does NOT increase risk-it opens dialogue.',5,'apply',['suicide assessment','ED','risk evaluation','psychiatry']);

add('psych-suicide','What is a safety plan and how does it differ from a no-harm contract?','Safety plan (Stanley-Brown): (1) Warning signs that crisis is developing, (2) Internal coping strategies (relaxation, distraction), (3) People/social settings that provide distraction, (4) People to contact for help (friends, family), (5) Professionals/agencies to contact (crisis lines, ED), (6) Making environment safe (means restriction). NO-HARM CONTRACTS are NOT recommended-no evidence of efficacy and may provide false reassurance.',
'Safety plans are evidence-based and reduce suicide attempts by 50% (Stanley et al, 2018). Canadian guidelines recommend safety planning for all patients with suicidal ideation. Crisis Services Canada 988 (national crisis line). Canadian Association for Suicide Prevention provides resources.',4,'apply',['safety plan','crisis intervention','means restriction','psychiatry']);

add('psych-suicide','What are the Canadian legal frameworks for involuntary psychiatric admission?','Each province has its own Mental Health Act. Common criteria: the person has a mental disorder AND is at risk of serious harm to self or others AND is unwilling/unable to consent to voluntary admission. Two physician certificates are typically required for extended hold. Initial police/physician hold: typically 72 hours for assessment. Patient has right to legal counsel and review board hearing.',
'In Ontario: Form 1 (72h assessment by physician), Form 3 (2-week certificate of involuntary admission), Form 4 (additional certificate for renewal). Criteria vary: some provinces include "deterioration criterion" (likely to deteriorate without treatment). Capacity to consent is assessed separately from certification under mental health legislation.',4,'apply',['involuntary admission','Mental Health Act','legal framework','psychiatry']);

add('psych-suicide','What are the warning signs of imminent suicide risk?','Acute warning signs: talking about wanting to die, looking for means (guns, pills, heights), giving away possessions, saying goodbye, increased substance use, withdrawing from activities/people, dramatic mood change (calm after being depressed), researching methods online, making final arrangements.',
'Canadian Suicide Prevention Service (988) emphasizes recognizing acute warning signs. A sudden improvement in mood in a previously severely depressed patient may indicate they have made the decision to die and feel relieved. This should heighten, not decrease, concern.',3,'recall',['warning signs','imminent suicide','recognition','psychiatry']);

add('psych-suicide','How should clinicians respond to a patient who discloses suicidal ideation?','(1) Remain calm and non-judgmental, (2) Validate feelings without reinforcing hopelessness, (3) Ask directly about plan, intent, means, and timeline-be specific, (4) Assess protective factors, (5) Determine level of risk, (6) Create safety plan collaboratively, (7) Means restriction counseling, (8) Document thoroughly, (9) Arrange appropriate follow-up or disposition. NEVER dismiss or minimize disclosure.',
'CMPA (Canadian Medical Protective Association) recommends thorough documentation of suicide risk assessments. Asking about suicide is a clinical duty-omission may constitute negligence. Canadian guidelines recommend that all healthcare providers receive suicide risk assessment training (Applied Suicide Intervention Skills Training-ASIST).',4,'apply',['suicidal ideation','clinical response','documentation','psychiatry']);

add('psych-suicide','What is the epidemiology of suicide in special populations in Canada?','Indigenous peoples: 3x national rate, Inuit youth 11x. LGBTQ+ youth: 4x more likely to attempt. Physicians: elevated risk compared to general population. Elderly men: highest rate of completed suicide per capita. Veterans/military: elevated risk. Post-discharge psychiatric patients: highest risk period is first 2 weeks after discharge.',
'Canadian federal government has identified Indigenous suicide as a public health crisis. Culturally appropriate, community-led interventions are essential. The "Hope for Wellness" helpline provides culturally competent crisis support for Indigenous peoples. Transition from inpatient to outpatient care is a critical high-risk period.',3,'recall',['suicide epidemiology','Indigenous','special populations','psychiatry']);

add('psych-suicide','What medications are associated with increased vs decreased suicide risk?','Increased risk: antidepressants in youth <25 (black box warning-monitor closely first 4 weeks), isotretinoin (controversial), corticosteroids, mefloquine, varenicline (warning removed but monitor). Decreased risk: lithium (only medication with strong anti-suicidal evidence-30% reduction), clozapine (reduces suicidality in schizophrenia-InterSePT trial), ketamine/esketamine (rapid anti-suicidal effect).',
'Health Canada black box warning on all antidepressants for age <25 mandates close monitoring (weekly for first 4 weeks). Lithium anti-suicidal effect is independent of mood-stabilizing effect. Clozapine is FDA-approved specifically for suicide risk reduction in schizophrenia. Canadian guidelines recommend lithium consideration when suicide risk is a prominent concern.',4,'apply',['medication suicide risk','lithium','black box warning','psychiatry']);

add('psych-suicide','What is the approach to self-harm (non-suicidal self-injury)?','NSSI: deliberate self-inflicted tissue damage without suicidal intent (cutting, burning, scratching). Distinct from suicide attempt but NSSI is a risk factor for eventual suicide. Assessment: function (emotion regulation, self-punishment, communication), frequency, severity. Treatment: DBT (most evidence), CBT, emotion regulation skills. Treat underlying conditions (BPD, depression). Do NOT assume it is "just attention-seeking."',
'NSSI prevalence is 15-25% of adolescents and 4% of adults. Canadian Emergency Department guidelines recommend compassionate, non-judgmental care. NSSI increases future suicide risk 3-6x. Social contagion (peer influence) is a recognized phenomenon, particularly in adolescent inpatient settings.',4,'apply',['self-harm','NSSI','non-suicidal self-injury','DBT','psychiatry']);

add('psych-suicide','What is the physician duty to report and duty to protect in suicidal patients?','Confidentiality may be broken when there is imminent risk of harm to self or others (per CMA Code of Ethics and provincial legislation). Duty to protect: warn identifiable third parties at risk (Tarasoff-type duty). Documentation requirements: risk assessment, clinical reasoning, safety plan, disposition rationale. Duty to follow up: arrange timely post-discharge care.',
'CMPA guidance emphasizes that adequate documentation of clinical reasoning protects against liability. Canadian courts have held physicians liable for inadequate suicide risk assessment. The standard is reasonable clinical judgment, not prediction of suicide. Collegial consultations should be documented.',4,'apply',['duty to report','confidentiality','legal obligations','psychiatry']);

add('psych-suicide','What is the approach to suicide bereavement and postvention?','Postvention: organized response after a suicide to promote healing and prevent further suicides (suicide contagion). Components: immediate crisis response for family/close contacts, screening for at-risk individuals, memorial guidance (avoid glorification), support groups. Bereaved individuals have elevated suicide risk (peer and family). Clinician self-care after patient suicide (50% of psychiatrists experience patient suicide during career).',
'Canadian Mental Health Association provides suicide bereavement resources. Media guidelines for reporting suicide (avoid details of method, avoid sensationalization) reduce imitative suicides. Schools should have postvention protocols. Clinicians experiencing patient suicide should access peer support-CMPA provides assistance.',3,'recall',['postvention','suicide bereavement','contagion prevention','psychiatry']);

add('psych-suicide','What are the protective factors against suicide and how are they incorporated into risk assessment?','Individual: problem-solving skills, coping abilities, reasons for living, fear of death/pain, future-oriented thinking, help-seeking behavior. Social: strong family connections, social support, children in the home, therapeutic alliance. Community: access to mental health services, cultural/religious beliefs against suicide. These factors modulate risk but do NOT eliminate it in the presence of strong risk factors.',
'Canadian suicide risk assessment frameworks (e.g., CARMS: Columbia, Assessment, Risk, Mitigation, Safety plan) integrate protective factors into formulation. Protective factors should be actively strengthened as part of the safety plan. Reasons for living (Linehan inventory) can be used therapeutically.',3,'apply',['protective factors','risk assessment','safety planning','psychiatry']);

add('psych-suicide','What is the management of suicide risk in adolescents?','Assessment adapted for age: collateral from parents/school, assess social media involvement, bullying, LGBTQ+ identity/discrimination, academic stress. Treatment: CBT, DBT-A (adolescent adaptation), family therapy. Pharmacotherapy: fluoxetine has best risk-benefit profile (only SSRI consistently showing efficacy in adolescent MDD). Close monitoring during SSRI initiation. Safety: means restriction counseling with parents, school-based interventions.',
'Youth suicide is the second leading cause of death in Canadian adolescents. Kids Help Phone (1-800-668-6868) provides 24/7 support. CPS recommends universal screening for depression/suicidality in adolescents. Social media use and cyberbullying are emerging risk factors. School-based gatekeeper training programs (e.g., safeTALK) are widely implemented in Canada.',4,'apply',['adolescent suicide','youth mental health','fluoxetine','psychiatry']);

add('psych-suicide','What are the ethical considerations in end-of-life requests and distinguishing from suicidality?','Medical Assistance in Dying (MAID) is legal in Canada (Bill C-14, expanded C-7). Eligibility: >=18, capable of consent, serious and incurable illness/condition, in advanced state of irreversible decline, enduring suffering. Mental illness as sole condition: currently under legislative review/moratorium in Canada. MAID requests require 2 independent physician assessments. Suicidality from mental illness is NOT equivalent to a MAID request.',
'Canada is one of few countries where MAID is available for conditions where death is not reasonably foreseeable (Track 2). The extension of MAID to mental illness as sole condition was postponed to 2027. Clinicians must carefully differentiate MAID requests from suicidal ideation driven by treatable mental illness.',5,'analyze',['MAID','end of life','medical assistance in dying','ethics','psychiatry']);

fs.writeFileSync('C:/dev/srs-mccqe1/data/_psych_cards.json', JSON.stringify(cards, null, 2));
console.log('Psychiatry cards written:', cards.length);
