const crypto = require('crypto');
function id(q) { return 'card-' + crypto.createHash('sha256').update(q.trim().toLowerCase()).digest('hex').slice(0,12); }
const cards = [];
function add(topicId, question, answer, explanation, difficulty, bloomLevel, tags) {
  cards.push({ id: id(question), question, answer, explanation, difficulty, bloomLevel, tags, topicId });
}

// CARDIOLOGY - card-acs (20)
add('card-acs','A 58-year-old man presents with crushing substernal chest pain radiating to his left arm for 90 minutes. ECG shows ST elevation in leads II, III, aVF. What is the most appropriate immediate management?','Primary PCI within 90 minutes of first medical contact','STEMI management per CCS guidelines prioritizes primary PCI as the reperfusion strategy of choice when door-to-balloon time can be achieved within 90 minutes. Inferior STEMI (II, III, aVF) suggests RCA occlusion. Fibrinolysis is used when PCI is unavailable within 120 minutes.',4,'apply',['STEMI','ACS','PCI','cardiology']);
add('card-acs','What ECG changes define STEMI requiring emergent reperfusion?','ST elevation ≥1 mm in ≥2 contiguous limb leads or ≥2 mm in ≥2 contiguous precordial leads, or new LBBB','CCS guidelines define STEMI by these ECG criteria, which indicate complete coronary artery occlusion requiring emergent reperfusion. New LBBB with ischemic symptoms is treated as STEMI equivalent. Posterior MI may show ST depression in V1-V3.',3,'recall',['STEMI','ECG','ACS','cardiology']);
add('card-acs','A 65-year-old woman has chest pain and troponin elevated at 0.8 ng/mL. ECG shows ST depression in V4-V6. She is hemodynamically stable. What is the diagnosis and risk stratification approach?','NSTEMI; use GRACE or TIMI score to guide timing of invasive strategy','NSTEMI is defined by elevated troponin without ST elevation. CCS guidelines recommend risk stratification using GRACE score: high-risk patients benefit from early invasive strategy within 24 hours. Antiplatelet therapy with ASA plus P2Y12 inhibitor should be initiated.',4,'analyze',['NSTEMI','ACS','troponin','risk stratification','cardiology']);
add('card-acs','What is the standard dual antiplatelet therapy for ACS in Canada?','ASA 162-325 mg loading then 81 mg daily PLUS ticagrelor 180 mg loading then 90 mg BID (preferred over clopidogrel)','CCS guidelines recommend DAPT for all ACS patients. Ticagrelor is preferred over clopidogrel based on the PLATO trial. DAPT duration is typically 12 months post-ACS, with consideration for shorter duration in high bleeding risk.',3,'recall',['DAPT','antiplatelet','ACS','ticagrelor','cardiology']);
add('card-acs','A patient with STEMI arrives at a hospital without PCI capability. The nearest PCI centre is 3 hours away. What is the appropriate reperfusion strategy?','Fibrinolysis (tenecteplase) immediately if no contraindications, then transfer for pharmaco-invasive strategy within 3-24 hours','When PCI cannot be achieved within 120 minutes, fibrinolysis should be given within 30 minutes of arrival. The pharmaco-invasive strategy involves routine angiography 3-24 hours after successful lysis per CCS guidelines.',4,'apply',['STEMI','fibrinolysis','pharmaco-invasive','reperfusion','cardiology']);
add('card-acs','Which is an absolute contraindication to fibrinolysis? A) Age >75 B) Prior ischemic stroke 2 years ago C) Prior hemorrhagic stroke D) BP 180/110','C) Prior hemorrhagic stroke at any time','Absolute contraindications include any prior hemorrhagic stroke, ischemic stroke within 3 months, active bleeding, suspected aortic dissection, and significant closed head trauma within 3 months. Uncontrolled HTN and age >75 are relative contraindications.',3,'apply',['fibrinolysis','contraindications','STEMI','ACS','cardiology']);
add('card-acs','What troponin pattern is consistent with acute MI versus chronic elevation?','Acute MI: rising and/or falling pattern with ≥1 value above 99th percentile URL and >20% delta change; chronic: stable elevated values','CCS/ACC define Type 1 MI as acute plaque rupture with dynamic troponin rise/fall. High-sensitivity troponin allows earlier rule-in/rule-out. Serial troponins at 0 and 3 hours are standard in Canadian EDs.',3,'apply',['troponin','MI','biomarkers','ACS','cardiology']);
add('card-acs','A 72-year-old diabetic has fatigue and dyspnea for 2 days, no chest pain. ECG shows new Q waves in V1-V4. Troponin is elevated. What presentation is this?','Silent/atypical MI — common in diabetics and elderly due to autonomic neuropathy','Diabetic patients and the elderly frequently present with atypical ACS symptoms. Autonomic neuropathy impairs pain perception. CCS guidelines emphasize high clinical suspicion in these populations.',4,'analyze',['silent MI','atypical ACS','diabetes','elderly','cardiology']);
add('card-acs','What five medication classes should be prescribed at discharge post-MI?','ASA, P2Y12 inhibitor (DAPT), beta-blocker, ACE inhibitor/ARB, high-intensity statin','CCS secondary prevention guidelines mandate all five drug classes post-MI. High-intensity statin targets LDL <1.8 mmol/L or ≥50% reduction. ACE inhibitors reduce remodeling and mortality.',2,'recall',['secondary prevention','post-MI','medications','cardiology','ACS']);
add('card-acs','A patient 2 days post-STEMI develops a harsh holosystolic murmur at the left sternal border with sudden hemodynamic deterioration. What is the diagnosis?','Ventricular septal defect (VSD) — mechanical complication of MI','Post-MI mechanical complications include VSD (days 3-7), papillary muscle rupture with acute MR (days 2-7), and free wall rupture. VSD presents with new harsh murmur and right heart failure. Echocardiography confirms. Emergent surgical repair required.',5,'analyze',['VSD','MI complication','mechanical complication','ACS','cardiology']);
add('card-acs','What is Dressler syndrome?','Post-MI autoimmune pericarditis occurring 2-10 weeks after MI, presenting with fever, pleuritic chest pain, and pericardial friction rub','Dressler syndrome is caused by immune response to released pericardial antigens. Treatment is ASA or NSAIDs plus colchicine. Distinguishing from recurrent ischemia requires ECG and troponin assessment.',3,'recall',['Dressler syndrome','pericarditis','MI complication','ACS','cardiology']);
add('card-acs','A patient with known CAD has chest pain at rest relieved by nitrates. Troponin is negative x2. ECG shows transient ST depression during pain. What is the diagnosis?','Unstable angina (UA)','Unstable angina has new-onset, rest, or accelerating angina without troponin elevation. It is part of the ACS spectrum with similar pathophysiology as NSTEMI. Management includes antiplatelet therapy, anticoagulation, and risk stratification.',3,'apply',['unstable angina','ACS','cardiology','troponin']);
add('card-acs','What is the role of anticoagulation in NSTEMI/UA?','Anticoagulation (UFH, enoxaparin, or fondaparinux) is recommended with DAPT for all NSTEMI/UA patients during the acute phase','CCS guidelines recommend anticoagulation to prevent thrombus propagation. Fondaparinux is preferred for non-invasive strategy. Enoxaparin or UFH used if early invasive strategy planned. Stopped after PCI unless another indication.',3,'recall',['anticoagulation','NSTEMI','ACS','enoxaparin','cardiology']);
add('card-acs','A 48-year-old cocaine user has chest pain and ST elevation. Angiography shows no significant stenosis. What is the mechanism?','Cocaine-induced coronary vasospasm via alpha-adrenergic stimulation and norepinephrine reuptake inhibition','Treatment: benzodiazepines, nitrates, calcium channel blockers. Beta-blockers are contraindicated in cocaine-induced ACS as unopposed alpha stimulation may worsen vasospasm. Variant (Prinzmetal) angina is managed similarly with nitrates and CCBs.',4,'analyze',['cocaine','vasospasm','Prinzmetal','ACS','cardiology']);
add('card-acs','What defines high-risk NSTEMI requiring early invasive strategy within 24 hours?','GRACE score >140, or any: ST depression ≥0.5mm, elevated troponin, hemodynamic instability, sustained VT, new LBBB, heart failure, prior PCI within 6 months','CCS guidelines stratify NSTEMI into immediate (<2h), early (<24h), and delayed (24-72h) invasive strategies. The GRACE score incorporates age, HR, BP, creatinine, Killip class, cardiac arrest, ST deviation, and troponin.',4,'analyze',['NSTEMI','risk stratification','GRACE score','invasive strategy','cardiology']);
add('card-acs','What is Type 2 MI? Give two examples.','MI from oxygen supply-demand mismatch without plaque rupture; examples: severe anemia, tachyarrhythmia, hypertensive emergency, coronary vasospasm','Type 2 MI must be distinguished from Type 1 (spontaneous plaque rupture) as management differs. Treatment addresses the underlying cause rather than PCI.',3,'apply',['Type 2 MI','ACS','troponin','oxygen demand','cardiology']);
add('card-acs','What is the significance of right ventricular infarction complicating inferior STEMI?','RV infarction causes hypotension, JVD, and clear lungs — give IV fluids, avoid nitrates and diuretics','RV infarction complicates 30-50% of inferior STEMIs. Diagnosis: ST elevation in V4R. IV fluids (1-2L) maintain BP. Nitrates and diuretics reduce preload and can cause severe hypotension. Reperfusion of the RCA is critical.',4,'analyze',['RV infarction','inferior STEMI','ACS','hemodynamics','cardiology']);
add('card-acs','What is Killip classification in MI?','Class I: no HF; Class II: mild HF (crackles <50% lung fields); Class III: pulmonary edema; Class IV: cardiogenic shock — higher class = higher mortality','Killip classification is part of the GRACE score for ACS risk stratification. Killip class IV (cardiogenic shock) has >50% in-hospital mortality. CCS guidelines emphasize early revascularization and hemodynamic support for cardiogenic shock.',3,'recall',['Killip class','heart failure','MI','risk stratification','ACS','cardiology']);
add('card-acs','A 60-year-old has worsening exertional chest pain for 3 months. Stress test shows 2mm lateral ST depression at moderate workload. Angiography shows 75% LAD stenosis. What is the next step?','PCI or CABG based on coronary anatomy — stable ischemic heart disease with significant ischemia warrants revascularization discussion','CCS guidelines recommend revascularization for stable CAD with significant ischemia (>10% of myocardium) if symptoms not controlled by optimal medical therapy. CABG preferred for multivessel disease, diabetes, or reduced EF.',4,'analyze',['stable angina','CAD','revascularization','PCI','CABG','cardiology']);
add('card-acs','What is the recommended LDL target after ACS per Canadian guidelines?','LDL <1.8 mmol/L AND ≥50% reduction from baseline; add ezetimibe or PCSK9 inhibitor if target not achieved on maximally tolerated statin','CCS Dyslipidemia Guidelines 2021 recommend high-intensity statin for all post-ACS patients. PCSK9 inhibitors are indicated for very high-risk patients not achieving targets on statin + ezetimibe.',3,'recall',['LDL','statin','secondary prevention','ACS','PCSK9','cardiology']);

// CARDIOLOGY - card-hf (15)
add('card-hf','A 70-year-old presents with dyspnea, orthopnea, bilateral leg edema, and basal crackles. BNP 850 pg/mL. Echo EF 30%. Diagnosis and initial management?','HFrEF; start ACE inhibitor, beta-blocker, MRA, SGLT2 inhibitor, and loop diuretic for symptom relief','CCS Heart Failure Guidelines define HFrEF as EF <40%. The four pillars are ACEi/ARB/ARNI, beta-blocker, MRA, and SGLT2 inhibitor. Loop diuretics relieve congestion but do not improve mortality.',4,'apply',['HFrEF','heart failure','BNP','ACE inhibitor','cardiology']);
add('card-hf','What are the four GDMT pillars for HFrEF per CCS 2021 guidelines?','ACEi/ARB or ARNI (sacubitril-valsartan), beta-blocker (carvedilol/metoprolol succinate/bisoprolol), MRA (spironolactone/eplerenone), SGLT2 inhibitor (dapagliflozin/empagliflozin)','SGLT2 inhibitors were added as the fourth pillar based on DAPA-HF and EMPEROR-Reduced trials. Sacubitril-valsartan is superior to ACEi for reducing mortality in ambulatory HFrEF patients.',2,'recall',['GDMT','HFrEF','heart failure','SGLT2 inhibitor','ARNI','cardiology']);
add('card-hf','A 68-year-old has HF with EF 55%. What is the diagnosis and how does management differ from HFrEF?','HFpEF (EF ≥50%); management focuses on symptom relief with diuretics, BP control, comorbidity treatment, and SGLT2 inhibitors','EMPEROR-Preserved and DELIVER trials showed empagliflozin and dapagliflozin reduce HF hospitalization in HFpEF. CCS guidelines now recommend SGLT2 inhibitors for HFpEF. Diuretics manage congestion.',4,'analyze',['HFpEF','heart failure','SGLT2','cardiology']);
add('card-hf','What BNP/NT-proBNP thresholds help diagnose acute HF in the ED?','BNP >100 pg/mL or NT-proBNP >300 pg/mL supports HF; BNP <100 or NT-proBNP <300 makes HF unlikely','Natriuretic peptides have high NPV for excluding HF in dyspneic patients. CCS guidelines recommend BNP/NT-proBNP in evaluation of suspected HF. Elevated levels also occur in PE, RV failure, and CKD.',2,'recall',['BNP','NT-proBNP','heart failure','diagnosis','cardiology']);
add('card-hf','A patient with HFrEF on ACE inhibitor remains symptomatic. What is the preferred next step per CCS?','Switch ACEi to sacubitril-valsartan (ARNI) if symptomatic despite ACEi and SBP >100 mmHg — 36-hour washout required before switching','PARADIGM-HF showed sacubitril-valsartan reduced CV death and HF hospitalization by 20% vs. enalapril. CCS recommends ARNI as preferred RAS blocker for symptomatic HFrEF. Washout prevents angioedema.',3,'apply',['ARNI','sacubitril-valsartan','HFrEF','ACE inhibitor','cardiology']);
add('card-hf','What are indications for ICD in heart failure?','HFrEF with EF ≤35% despite ≥3 months optimal GDMT, NYHA class II-III, expected survival >1 year','CCS guidelines recommend ICD for primary prevention of sudden cardiac death in HFrEF. EF must be reassessed after 3 months of GDMT. CRT-D indicated when EF ≤35% with LBBB, QRS ≥150ms, NYHA II-III.',3,'recall',['ICD','HFrEF','sudden cardiac death','CRT','cardiology']);
add('card-hf','A 75-year-old with HFrEF has BP 85/60, cold extremities, oliguria. Hemodynamic profile and treatment?','Cardiogenic shock (cold and wet): low CO, high PCWP — dobutamine for inotropy, norepinephrine for MAP >65; consider mechanical circulatory support','Cardiogenic shock management includes IV dobutamine and norepinephrine. Mechanical circulatory support (IABP, Impella, ECMO) may be required. Urgent coronary angiography if ischemia is suspected.',5,'analyze',['cardiogenic shock','heart failure','inotropes','hemodynamics','cardiology']);
add('card-hf','What is CRT and who benefits?','Biventricular pacing to coordinate LV contraction; indicated for HFrEF (EF ≤35%), LBBB with QRS ≥150ms, NYHA II-IV on optimal GDMT','CARE-HF and COMPANION trials showed CRT improves mortality and quality of life. CCS recommends CRT-D when both ICD and CRT criteria are met. LBBB morphology predicts better response than RBBB.',3,'recall',['CRT','cardiac resynchronization','HFrEF','LBBB','cardiology']);
add('card-hf','What drug classes should be AVOIDED in HFrEF?','Non-DHP CCBs (diltiazem, verapamil), NSAIDs, thiazolidinediones, most antiarrhythmics (except amiodarone), type IC antiarrhythmics','Non-DHP CCBs have negative inotropic effects. NSAIDs cause sodium retention and antagonize diuretics. Type IC antiarrhythmics (flecainide, propafenone) increase mortality in structural heart disease.',2,'recall',['drug avoidance','HFrEF','CCB','NSAIDs','cardiology']);
add('card-hf','A patient with HFrEF on lisinopril, spironolactone, and furosemide has K+ 5.8 mEq/L. What adjustment is needed?','Hold or reduce spironolactone; consider reducing ACEi dose — MRA should be held when K+ >5.5 mEq/L','CCS guidelines recommend electrolyte monitoring within 1-2 weeks of starting MRA. Novel potassium binders (patiromer, sodium zirconium cyclosilicate) may allow continuation of GDMT in patients with hyperkalemia.',4,'apply',['hyperkalemia','spironolactone','MRA','HFrEF','electrolytes','cardiology']);
add('card-hf','What is the NYHA classification of heart failure?','Class I: no symptoms; Class II: mild symptoms with moderate exertion; Class III: symptoms with minimal exertion; Class IV: symptoms at rest','NYHA classification guides HF treatment decisions. GDMT benefits demonstrated across NYHA II-IV. Class IV refractory patients should be assessed for advanced therapies (LVAD, cardiac transplantation).',1,'recall',['NYHA','heart failure classification','symptoms','cardiology']);
add('card-hf','How does spironolactone benefit HFrEF and what monitoring is required?','30% mortality reduction in NYHA III-IV HFrEF (RALES trial); monitor K+ and creatinine within 1 week of initiation','MRAs block aldosterone, reducing fibrosis and sodium retention. CCS recommends MRA for HFrEF with EF ≤35% and NYHA II-IV. Contraindicated in GFR <30 or baseline K+ >5.0 mEq/L.',3,'recall',['spironolactone','MRA','HFrEF','potassium monitoring','cardiology']);
add('card-hf','How is acute pulmonary edema managed in the ED?','IV furosemide, IV nitroglycerin if SBP >90, supplemental O2/NIV (BiPAP), sit upright, treat precipitating cause','NIV (BiPAP/CPAP) reduces intubation need and improves oxygenation. IV nitroglycerin reduces preload rapidly. Identify and treat precipitants: ACS, hypertensive emergency, arrhythmia, infection.',4,'apply',['pulmonary edema','acute HF','furosemide','BiPAP','cardiology']);
add('card-hf','Which beta-blockers are guideline-recommended for HFrEF and when should they be started?','Carvedilol, metoprolol succinate (XL), bisoprolol — started when patient is euvolemic, NOT during acute decompensation','Three beta-blockers have proven mortality benefit: carvedilol (COPERNICUS), metoprolol succinate (MERIT-HF), bisoprolol (CIBIS-II). Continue in patients already on them during acute decompensation.',2,'recall',['beta-blocker','HFrEF','carvedilol','metoprolol','cardiology']);
add('card-hf','What follow-up does CCS recommend after HF discharge?','Follow-up within 1-2 weeks of discharge; reassess EF in 3-6 months after optimization of GDMT','Early post-discharge follow-up reduces 30-day readmission. Medication titration, fluid status, and electrolyte monitoring are priorities. EF reassessment guides ICD/CRT decision-making.',3,'apply',['heart failure','follow-up','discharge planning','CCS guidelines','cardiology']);

// CARDIOLOGY - card-arrhythmia (20)
add('card-arrhythmia','A patient has an ECG showing irregularly irregular rhythm with no discernible P waves and ventricular rate 110 bpm. Diagnosis and initial management?','Atrial fibrillation with rapid ventricular response; rate control with beta-blocker or diltiazem, assess for anticoagulation (CHA2DS2-VASc)','AF is the most common sustained arrhythmia. Initial management focuses on rate control (target HR <100-110 bpm). CCS mandates anticoagulation assessment: score ≥2 in men or ≥3 in women warrants OAC.',3,'apply',['atrial fibrillation','rate control','anticoagulation','ECG','arrhythmia']);
add('card-arrhythmia','What is CHA2DS2-VASc and when is anticoagulation recommended in AF?','CHF(1), HTN(1), Age≥75(2), Diabetes(1), Stroke/TIA(2), Vascular disease(1), Age 65-74(1), Sex female(1); anticoagulate if score ≥2 men or ≥3 women','CCS AF guidelines recommend DOACs (apixaban, rivaroxaban, dabigatran, edoxaban) preferred over warfarin for non-valvular AF. Valvular AF (mechanical valve or moderate-severe MS) requires warfarin.',2,'recall',['CHA2DS2-VASc','AF','anticoagulation','stroke prevention','arrhythmia']);
add('card-arrhythmia','What rhythm control options are available for AF?','Electrical cardioversion (DCCV), pharmacological cardioversion (flecainide/propafenone for no structural disease; amiodarone for structural disease), or catheter ablation (pulmonary vein isolation)','EAST-AFNET 4 showed early rhythm control reduces CV outcomes. Catheter ablation is first-line for symptomatic AF refractory to or intolerant of antiarrhythmics. Anticoagulation ≥3 weeks or TEE before cardioversion.',4,'apply',['AF','rhythm control','cardioversion','ablation','amiodarone','arrhythmia']);
add('card-arrhythmia','A 35-year-old has delta waves, short PR interval, and wide QRS on ECG. Diagnosis and main concern?','Wolff-Parkinson-White syndrome; concern is pre-excited AF rapidly conducted through accessory pathway potentially causing VF','Avoid AV nodal blockers (adenosine, beta-blockers, CCBs, digoxin) in WPW with AF — may paradoxically accelerate conduction through accessory pathway. Treatment: procainamide IV or DCCV.',5,'analyze',['WPW','pre-excitation','delta wave','AF','accessory pathway','arrhythmia']);
add('card-arrhythmia','What ECG pattern defines first-degree AV block and is treatment needed?','Prolonged PR interval >200 ms with all P waves conducted; no treatment needed — benign finding','First-degree AV block is a conduction delay at the AV node. All P waves are followed by QRS. Causes: increased vagal tone, inferior MI, digoxin toxicity, electrolyte abnormalities. No pacing required.',1,'recall',['AV block','first-degree','PR interval','ECG','arrhythmia']);
add('card-arrhythmia','Distinguish Mobitz type I from Mobitz type II second-degree AV block.','Mobitz I: progressive PR prolongation then dropped QRS (Wenckebach); Mobitz II: constant PR with sudden dropped QRS — Mobitz II is more serious and often requires pacemaker','Mobitz I is usually benign (nodal level, often inferior MI). Mobitz II is infranodal with high risk of progression to complete heart block and usually requires permanent pacemaker.',3,'recall',['Mobitz','AV block','second-degree','Wenckebach','pacemaker','arrhythmia']);
add('card-arrhythmia','A patient has complete P-wave to QRS dissociation, HR 38 bpm, and syncope. Diagnosis and management?','Third-degree (complete) AV block; urgent temporary transvenous pacing then permanent pacemaker','Complete heart block: no atrial impulses conduct to ventricles. Causes: inferior MI (usually transient), Lyme disease, infiltrative disease, drug toxicity. Atropine may bridge temporarily. CCS recommends permanent pacemaker.',4,'apply',['complete heart block','pacemaker','syncope','arrhythmia']);
add('card-arrhythmia','What are the ECG criteria for LBBB and its clinical significance?','QRS ≥120 ms, broad notched R in I, aVL, V5-V6; rS or QS in V1; new LBBB with chest pain treated as STEMI equivalent','LBBB obscures ST changes making ischemia diagnosis difficult. Sgarbossa criteria can be applied. Chronic LBBB with HFrEF (EF ≤35%, QRS ≥150ms) is an indication for CRT.',3,'apply',['LBBB','bundle branch block','ECG','STEMI equivalent','arrhythmia']);
add('card-arrhythmia','A patient with HR 170 bpm, narrow complex regular tachycardia is given adenosine 6 mg IV, which terminates it. Likely diagnosis?','AVNRT — most common cause of regular narrow complex tachycardia in adults','AVNRT accounts for 60% of SVT. Reentrant circuit in AV node. P waves buried in or after QRS. Long-term: beta-blockers, CCBs, or catheter ablation (95% cure rate). Vagal maneuvers (Valsalva) may terminate it.',3,'apply',['AVNRT','SVT','adenosine','narrow complex tachycardia','arrhythmia']);
add('card-arrhythmia','What ECG changes occur in hyperkalemia and at what K+ levels?','Peaked T waves (>5.5); PR prolongation and wide QRS (>6.5); sine wave, VF, asystole (>8.0)','Progressive ECG changes with rising K+. Treatment: calcium gluconate stabilizes cardiac membrane, insulin + dextrose shifts K+ intracellularly, sodium bicarbonate in acidosis, kayexalate/patiromer for elimination.',3,'apply',['hyperkalemia','ECG changes','peaked T waves','electrolytes','arrhythmia']);
add('card-arrhythmia','A patient on sotalol has QTc 520 ms with runs of polymorphic VT. Diagnosis and management?','Torsades de pointes; IV magnesium sulfate 2g IV, remove offending drug, consider temporary pacing if bradycardia-dependent','TdP is polymorphic VT associated with QT prolongation, characteristic twisting pattern. Risk factors: QT-prolonging drugs, hypokalemia, hypomagnesemia, bradycardia. Correct electrolytes and stop offending drug.',4,'analyze',['torsades de pointes','QT prolongation','polymorphic VT','magnesium','arrhythmia']);
add('card-arrhythmia','How do you manage stable wide complex tachycardia of unknown etiology?','Treat as VT until proven otherwise; IV amiodarone 150 mg over 10 min or procainamide; DCCV if hemodynamically unstable','Wide complex tachycardia is VT until proven otherwise. Avoid verapamil (may cause degeneration to VF in VT). Adenosine may be used for presumed SVT with aberrancy if hemodynamically stable.',4,'apply',['ventricular tachycardia','wide complex tachycardia','amiodarone','arrhythmia']);
add('card-arrhythmia','A 65-year-old with ischemic cardiomyopathy has recurrent sustained VT despite amiodarone. Next therapeutic option?','Catheter ablation of VT circuit, or consider ICD if not already implanted','Catheter ablation for VT targets scar-related reentrant circuits; 50-70% success in ischemic cardiomyopathy. CCS recommends ablation for recurrent VT causing ICD shocks or amiodarone intolerance.',4,'analyze',['VT','catheter ablation','ICD','amiodarone','arrhythmia']);
add('card-arrhythmia','What ECG changes suggest posterior STEMI?','ST depression in V1-V3 with tall R waves and upright T waves (reciprocal); confirm with posterior leads V7-V9 showing ST elevation','Posterior STEMI caused by circumflex or dominant RCA occlusion. CCS guidelines recommend posterior leads when posterior STEMI suspected. Treatment is emergent primary PCI.',4,'apply',['posterior STEMI','ECG','posterior leads','arrhythmia','ACS']);
add('card-arrhythmia','What is the significance of ST elevation in lead aVR?','Suggests left main or proximal LAD occlusion, or diffuse subendocardial ischemia — mandates urgent coronary angiography','ST elevation in aVR with diffuse ST depression indicates global subendocardial ischemia or LMCA occlusion. This is a high-risk ACS presentation per CCS guidelines.',4,'analyze',['aVR','ST elevation','left main occlusion','ECG','ACS','arrhythmia']);
add('card-arrhythmia','How do you distinguish atrial flutter from AF on ECG?','Flutter: regular sawtooth flutter waves 250-350 bpm with regular ventricular rate (usually 2:1 = ~150 bpm); AF: irregularly irregular, no discernible P waves','Typical atrial flutter involves cavo-tricuspid isthmus — catheter ablation achieves >95% cure. Rate control and anticoagulation managed similarly to AF. Flutter waves best seen in II, III, aVF.',2,'recall',['atrial flutter','AF','flutter waves','ECG','arrhythmia']);
add('card-arrhythmia','How long must a patient be anticoagulated before elective DCCV for AF?','3 weeks of therapeutic anticoagulation before elective cardioversion, OR TEE to exclude left atrial thrombus if earlier cardioversion needed','CCS guidelines require ≥3 weeks therapeutic OAC before elective DCCV to prevent thromboembolic events. Anticoagulation must continue ≥4 weeks post-cardioversion regardless of success.',2,'recall',['cardioversion','AF','anticoagulation','TEE','arrhythmia']);
add('card-arrhythmia','What is the Brugada pattern and its clinical significance?','Coved-type ST elevation ≥2mm in V1-V2 with RBBB morphology; associated with risk of VF and sudden cardiac death in structurally normal hearts','Brugada syndrome is an SCN5A channelopathy. ICD for survivors of cardiac arrest or symptomatic patients. Avoid sodium channel blockers and treat fever aggressively. Type 1 (coved) pattern is diagnostic.',4,'analyze',['Brugada','ECG','sudden cardiac death','channelopathy','arrhythmia']);
add('card-arrhythmia','A patient has sinus bradycardia 38 bpm with hypotension unresponsive to atropine. Management?','Transcutaneous or transvenous pacing; identify and treat reversible causes (inferior MI, hypothyroidism, beta-blocker toxicity)','Bradycardia unresponsive to atropine may indicate infranodal block. Transcutaneous pacing is immediate bridge; transvenous pacing more reliable. Permanent pacemaker for symptomatic sinus node dysfunction.',3,'apply',['sinus bradycardia','pacing','sick sinus syndrome','atropine','arrhythmia']);
add('card-arrhythmia','What are the main indications for permanent pacemaker?','Symptomatic sinus node dysfunction, complete/high-degree AV block, symptomatic Mobitz II AV block, chronotropic incompetence','CCS pacemaker guidelines recommend implantation for symptomatic bradyarrhythmias with established symptom-rhythm correlation, or high-risk conduction abnormalities. Asymptomatic first-degree AV block does not require pacing.',2,'recall',['pacemaker','indications','AV block','sick sinus','arrhythmia']);

// CARDIOLOGY - card-htn (20)
add('card-htn','What are the Hypertension Canada diagnostic thresholds for hypertension by measurement method?','Office BP ≥140/90 (≥2 visits); ABPM 24h average ≥130/80; home BP ≥135/85; AOBP ≥135/85','Hypertension Canada 2020 recommends AOBP as preferred measurement. ABPM is gold standard for white coat and masked hypertension. Single-visit diagnosis allowed if BP ≥180/110.',2,'recall',['hypertension','diagnosis','ABPM','AOBP','Hypertension Canada']);
add('card-htn','What are BP targets per Hypertension Canada for general adults vs. high-risk patients?','General: <140/90 mmHg; high-risk (diabetes, CKD, CVD, Framingham risk >15%): <130/80 mmHg','SPRINT trial evidence supports lower targets for high-risk patients. Canadian guidelines adopt <130/80 for high-risk as balance between benefit and risk of adverse events.',2,'recall',['hypertension','BP target','high-risk','CKD','Hypertension Canada']);
add('card-htn','A 55-year-old Black man has BP 158/95 on three visits. No comorbidities. First-line antihypertensive?','Long-acting DHP-CCB (amlodipine) or thiazide diuretic (indapamide or HCTZ) — ACEi less effective as monotherapy in Black patients','Black patients have lower renin activity, so CCBs and thiazide diuretics are preferred. ACEi/ARB are still important if diabetes or CKD present. Combination therapy often required.',3,'apply',['hypertension','amlodipine','thiazide','treatment','Hypertension Canada']);
add('card-htn','A 62-year-old with HTN, type 2 diabetes, and microalbuminuria (ACR 45 mg/mmol). Preferred antihypertensive?','ACE inhibitor (e.g., ramipril) or ARB — nephroprotective via reducing intraglomerular pressure and proteinuria','ACEi/ARB are first-line for HTN with diabetes and microalbuminuria per Hypertension Canada and CDA guidelines. SGLT2 inhibitors also recommended for cardiorenal protection in diabetic CKD.',3,'apply',['hypertension','diabetes','ACE inhibitor','diabetic nephropathy','microalbuminuria']);
add('card-htn','Define hypertensive emergency and urgency.','Emergency: BP >180/120 with acute target organ damage (encephalopathy, HF, stroke, AKI, aortic dissection); Urgency: BP >180/120 without target organ damage','Hypertensive emergency requires IV treatment and BP reduction by 20-25% in first hour (not to normal — risk of ischemic stroke). Urgency managed with oral agents and close follow-up.',4,'analyze',['hypertensive emergency','urgency','target organ damage','hypertension']);
add('card-htn','A patient has BP 220/130, severe headache, papilledema, and confusion. How rapidly should BP be lowered?','Reduce MAP by 20-25% in first hour with IV labetalol or nicardipine — do NOT normalize BP rapidly','Rapid normalization causes watershed ischemia as cerebral autoregulation is shifted. Target: reduce MAP by 10-15% in 30-60 min, then to 160/100 over 2-6 hours. CT head to exclude hemorrhagic stroke.',5,'analyze',['hypertensive encephalopathy','hypertensive emergency','BP reduction','labetalol','hypertension']);
add('card-htn','What secondary causes of hypertension should be investigated in a young patient with resistant HTN?','Renal artery stenosis, primary hyperaldosteronism, pheochromocytoma, Cushing syndrome, coarctation of aorta, sleep apnea, drugs (NSAIDs, OCP)','Secondary HTN is more common in young patients or with clinical clues. Primary hyperaldosteronism is the most common secondary cause (5-10% of all HTN). Hypertension Canada recommends secondary workup for resistant HTN.',3,'recall',['secondary hypertension','resistant hypertension','primary hyperaldosteronism','pheochromocytoma','renal artery stenosis']);
add('card-htn','How is resistant hypertension defined and what is the best add-on agent?','BP ≥140/90 despite ≥3 agents at maximum doses including a diuretic; add spironolactone as 4th agent (PATHWAY-2 trial evidence)','PATHWAY-2 showed spironolactone is most effective add-on for resistant HTN. Confirm adherence, rule out white coat HTN (ABPM), and eliminate drug interactions before diagnosing true resistance.',4,'analyze',['resistant hypertension','spironolactone','PATHWAY-2','hypertension']);
add('card-htn','What lifestyle modifications reduce BP in hypertension?','DASH diet, sodium <2000 mg/day, weight loss, aerobic exercise 30-60 min 4-7 days/week, limit alcohol ≤2 drinks/day, smoking cessation','Hypertension Canada quantifies benefit: DASH diet ~11 mmHg, sodium restriction ~5 mmHg, weight loss ~1 mmHg/kg, exercise ~4-9 mmHg. Lifestyle changes can achieve targets without medication in stage 1 HTN.',2,'recall',['lifestyle','DASH diet','sodium','exercise','hypertension management']);
add('card-htn','A 70-year-old has isolated systolic hypertension (BP 168/72). Preferred antihypertensive?','Long-acting DHP-CCB (amlodipine) or thiazide-like diuretic (indapamide) — most evidence for isolated systolic HTN in elderly','SHEP and Syst-Eur trials demonstrated benefit of treating isolated systolic HTN. Target SBP <140 in elderly. Slow titration to avoid postural hypotension.',3,'apply',['isolated systolic hypertension','elderly','amlodipine','indapamide','hypertension']);
add('card-htn','What causes ACE inhibitor cough and what is the alternative?','ACEi cough from bradykinin accumulation; switch to ARB which does not affect bradykinin metabolism','ACEi cough occurs in 5-20% (more common in Asians, women, non-smokers). Class effect — switching to another ACEi will not help. ACEi and ARBs should not be combined due to AKI and hyperkalemia risk.',2,'recall',['ACE inhibitor','cough','bradykinin','ARB','hypertension']);
add('card-htn','What antihypertensives are safe in pregnancy?','Labetalol, methyldopa, nifedipine XL are safe; avoid ACEi and ARBs (teratogenic — fetal renal agenesis, oligohydramnios)','SOGC guidelines recommend treatment for BP ≥140/90 in pregnancy. Severe HTN (≥160/110) requires urgent treatment to prevent maternal stroke. Magnesium sulfate for seizure prophylaxis in severe preeclampsia.',4,'apply',['hypertension in pregnancy','labetalol','methyldopa','preeclampsia','SOGC']);
add('card-htn','What is the CV risk reduction from antihypertensive therapy?','Each 10 mmHg reduction in SBP reduces stroke risk ~35-40%, MI risk ~20-25%, heart failure ~50%','Meta-analyses confirm significant CV benefit from BP lowering regardless of drug class, proportional to degree of reduction. Absolute risk reduction depends on baseline risk.',3,'recall',['cardiovascular risk','blood pressure reduction','stroke','MI prevention','hypertension']);
add('card-htn','A 45-year-old has BP 152/96 and 10-year CV risk of 18%. When should pharmacotherapy start?','Treat when BP ≥130/80 for high-risk patients (10-year CV risk ≥15%); lifestyle modification accompanies pharmacotherapy','Hypertension Canada 2020 incorporates global CV risk. For high-risk patients, treatment threshold is lower and target is <130/80 mmHg, based on SPRINT evidence.',3,'apply',['CV risk','Framingham','treatment threshold','high-risk hypertension']);
add('card-htn','What is the role of beta-blockers in hypertension per Hypertension Canada?','NOT first-line for uncomplicated HTN in patients ≥60 years; preferred for compelling indications: post-MI, HFrEF, angina, AF rate control','Hypertension Canada downgraded beta-blockers due to inferior stroke prevention in elderly (LIFE trial). Acceptable option in patients <60 without compelling indication.',3,'recall',['beta-blockers','hypertension','first-line','compelling indications','Hypertension Canada']);
add('card-htn','A patient on amlodipine 10mg and ramipril 10mg has BP 148/94. Next step?','Add thiazide-like diuretic (indapamide SR 1.5mg or HCTZ 25mg) — triple therapy ACEi + CCB + diuretic','Hypertension Canada recommends ACEi + CCB + diuretic as the preferred triple regimen. Three-drug combination more effective than any dual combination.',3,'apply',['combination therapy','triple therapy','indapamide','hypertension management']);
add('card-htn','What BP target and preferred agents for CKD without diabetes?','Target <140/90; ACEi or ARB for nephroprotection — avoid combining ACEi + ARB','ACEi/ARB recommended for CKD with proteinuria (ACR >30 mg/mmol) to reduce intraglomerular pressure. Up to 30% creatinine rise acceptable if K+ remains <5.5 mEq/L.',3,'recall',['CKD','hypertension','ACE inhibitor','ARB','renal protection']);
add('card-htn','A hypertensive patient has hypokalemia (K+ 2.9), suppressed renin, and elevated aldosterone/renin ratio. Diagnosis?','Primary hyperaldosteronism; most common cause is bilateral adrenal hyperplasia (60%) or aldosterone-producing adenoma (35%)','Screen: aldosterone/renin ratio >30 with aldosterone >15 ng/dL. Confirm with saline suppression test. CT then adrenal vein sampling to lateralize. Treatment: adenoma → adrenalectomy; bilateral hyperplasia → spironolactone.',4,'analyze',['primary hyperaldosteronism','Conn syndrome','aldosterone','renin ratio','secondary hypertension']);
add('card-htn','How is pheochromocytoma diagnosed and what is the pre-operative treatment priority?','Diagnose with plasma free metanephrines or 24h urine catecholamines; pre-op: alpha-blockade first (phenoxybenzamine), THEN beta-blockade','Plasma free metanephrines have highest sensitivity (96%). MRI/CT adrenal localizes tumor. Never start beta-blocker before alpha-blocker — risk of hypertensive crisis from unopposed alpha stimulation.',4,'analyze',['pheochromocytoma','hypertension','metanephrines','alpha-blockade','secondary hypertension']);
add('card-htn','How should BP be properly measured per Hypertension Canada?','Rest 5 min, no caffeine/smoking 30 min prior, empty bladder, seated back supported, arm at heart level, appropriate cuff size, average 2-3 readings — prefer AOBP','AOBP eliminates white-coat effect. AOBP measures 5 consecutive readings while patient is alone; mean of readings 2-5 is used. Measurement errors are a common cause of apparent treatment failure.',2,'recall',['BP measurement','AOBP','technique','Hypertension Canada','white coat hypertension']);

// CARDIOLOGY - card-valve (10)
add('card-valve','A 75-year-old has exertional syncope, angina, and dyspnea. Harsh systolic murmur at right upper sternal border radiating to neck. Echo: AVA 0.8 cm2, mean gradient 45 mmHg. Diagnosis and management?','Severe aortic stenosis; SAVR or TAVR depending on surgical risk — symptomatic severe AS has 2-year mortality ~50% without intervention','CCS guidelines recommend intervention for symptomatic severe AS (AVA <1.0 cm2, mean gradient >40 mmHg). TAVR for high-risk/inoperable; SAVR preferred for low-risk patients <65.',5,'analyze',['aortic stenosis','AVR','TAVR','severe AS','cardiology','valvular']);
add('card-valve','What physical exam findings characterize mitral stenosis?','Opening snap after S2, low-pitched mid-diastolic rumble at apex, loud S1, signs of pulmonary hypertension','Mitral stenosis is most commonly rheumatic. Severity: MVA <1.0 cm2 = severe. AF common due to LA enlargement. Treatment: diuretics, anticoagulation if AF, balloon mitral valvuloplasty, or MVR.',3,'apply',['mitral stenosis','opening snap','rheumatic heart disease','valvular','cardiology']);
add('card-valve','A 40-year-old with bicuspid aortic valve has severe AR. Echo shows LVEDD 65mm, LVESD 45mm, EF 55%. When to recommend surgery?','Surgery for severe AR with: EF <50%, LVEDD >70mm, LVESD >50mm, or symptoms','CCS guidelines recommend AVR for symptomatic severe AR or asymptomatic meeting echocardiographic thresholds. Vasodilators temporize but do not replace surgery. Surveillance echo every 6-12 months.',4,'analyze',['aortic regurgitation','AVR','LV dilation','valvular','cardiology']);
add('card-valve','What is the Carpentier classification of mitral regurgitation?','Type I: normal leaflet motion (annular dilation, perforation); Type II: excessive motion (prolapse, chordal rupture); Type III: restricted motion (rheumatic IIIa, ischemic IIIb)','Understanding MR mechanism guides surgical approach. Type II MR is most amenable to repair. CCS prefers mitral valve repair over replacement. Surgery for severe MR with symptoms or EF <60% or LVESD >40mm.',4,'analyze',['mitral regurgitation','Carpentier classification','valvular','cardiology']);
add('card-valve','What antibiotic is used for IE prophylaxis before dental procedures in high-risk patients?','Amoxicillin 2g PO 30-60 min before procedure (clindamycin 600mg if penicillin allergic)','Prophylaxis only for high-risk conditions: prosthetic valve, prior IE, unrepaired cyanotic CHD. NOT recommended for MVP alone or most native valve disease — significant narrowing of indications from prior guidelines.',2,'recall',['endocarditis prophylaxis','amoxicillin','dental procedure','high-risk cardiac','valvular']);
add('card-valve','A 65-year-old with MVP has sudden severe MR and flail posterior leaflet on echo after minor chest trauma. Management?','Urgent mitral valve surgery (repair if feasible); stabilize with IV nitroprusside and diuretics as bridge','Acute severe MR causes volume overload of non-dilated LV, rapid hemodynamic deterioration. Nitroprusside reduces afterload and improves forward flow. IABP can bridge to OR.',5,'analyze',['acute MR','chordal rupture','mitral valve repair','valvular','emergent surgery']);
add('card-valve','What are the major Duke criteria for infective endocarditis?','Positive blood cultures (typical organisms x2 or persistent bacteremia) AND evidence of endocardial involvement (echo vegetation, new regurgitation, positive Q-gate CT)','Definite IE: 2 major, 1 major + 3 minor, or 5 minor criteria. TOE preferred for sensitivity. Blood cultures (3 sets before antibiotics) are critical.',3,'recall',['Duke criteria','infective endocarditis','blood cultures','echocardiography','valvular']);
add('card-valve','Common organisms in native valve vs. prosthetic valve endocarditis?','Native valve: Strep viridans (subacute), Staph aureus (acute), Enterococcus; Early prosthetic (<60d): CoNS, Staph aureus; Late prosthetic (>60d): similar to native','Strep viridans causes subacute IE via dental portals. Staph aureus causes acute IE with rapid valve destruction. IV drug use: Staph aureus, right-sided (tricuspid). Duration: 4-6 weeks IV antibiotics.',3,'recall',['endocarditis organisms','native valve','prosthetic valve','Staph aureus','valvular']);
add('card-valve','A patient with mechanical mitral valve has INR 6.5 and minor bleeding. Management?','Hold warfarin, give vitamin K 1-2.5 mg PO; if major bleeding: 4-factor PCC + IV vitamin K — DOACs are contraindicated with mechanical valves','Mechanical valves require lifelong anticoagulation (INR 2.5-3.5 for mitral). DOACs contraindicated with mechanical valves (RE-ALIGN trial showed increased thromboembolism).',4,'apply',['mechanical valve','INR reversal','warfarin','vitamin K','valvular']);
add('card-valve','What cardiac manifestations are associated with Marfan syndrome?','Aortic root dilation/dissection (major cause of death) and mitral valve prolapse with regurgitation','Prophylactic aortic root repair when diameter ≥5.0 cm. Beta-blockers and losartan slow aortic expansion. Annual surveillance MRI/CT of aorta.',3,'recall',['Marfan syndrome','aortic dissection','mitral valve prolapse','valvular']);

// RESPIROLOGY - resp-asthma (15)
add('resp-asthma','A 22-year-old has episodic wheezing, dyspnea, and cough worsening at night. Spirometry shows FEV1/FVC 0.68 (predicted 0.80) that improves to 0.79 after bronchodilator. Diagnosis?','Asthma; bronchodilator reversibility ≥12% and ≥200 mL improvement in FEV1 confirms diagnosis','GINA and CTS asthma guidelines diagnose asthma by characteristic symptoms plus objective confirmation of variable airflow limitation. Bronchodilator reversibility, diurnal PEF variability >10%, or positive bronchoprovocation test confirms diagnosis.',3,'apply',['asthma','spirometry','bronchodilator reversibility','FEV1','respirology']);
add('resp-asthma','What is the stepwise treatment approach for asthma per GINA/CTS guidelines?','Step 1: SABA PRN; Step 2: low-dose ICS + SABA PRN; Step 3: low-dose ICS/LABA or medium ICS; Step 4: medium-high ICS/LABA; Step 5: add-on tiotropium, anti-IL5, or oral steroids','CTS 2021 guidelines now recommend low-dose ICS-formoterol as preferred reliever at Steps 3-5 (MART strategy) over SABA alone, based on reduced exacerbations. ICS is the cornerstone of asthma treatment.',2,'recall',['asthma treatment','ICS','GINA','stepwise','respirology']);
add('resp-asthma','A 30-year-old with asthma uses salbutamol >3 days/week and wakes at night 2x/month. Current level of control and next step?','Partially controlled asthma; step up therapy — add or increase ICS (step up one level)','GINA defines controlled asthma as: daytime symptoms ≤2 days/week, no nighttime symptoms, SABA use ≤2 days/week, no activity limitation. Partially controlled = 1-2 of these criteria not met. Step-up for uncontrolled.',3,'apply',['asthma control','GINA','ICS','step-up therapy','respirology']);
add('resp-asthma','What are features of a severe acute asthma exacerbation requiring ICU?','SpO2 <90%, PEF <40% predicted, pulsus paradoxus >25 mmHg, silent chest, altered consciousness, inability to speak in sentences','Severe/life-threatening asthma: silent chest (no wheeze), cyanosis, altered mental status, respiratory failure (rising PaCO2 indicates fatigue). Management: high-flow O2, continuous nebulized SABA, IV/IM corticosteroids, IV magnesium sulfate.',4,'analyze',['severe asthma','asthma exacerbation','ICU','respirology']);
add('resp-asthma','What is the role of inhaled corticosteroids in asthma management?','ICS reduce airway inflammation, decrease exacerbations and hospitalizations, and improve lung function — cornerstone of asthma treatment from Step 2 onward','GINA and CTS guidelines recommend ICS for all patients with persistent asthma. ICS do not cure asthma but control symptoms and prevent exacerbations. Common side effects: oral candidiasis (use spacer, rinse mouth), dysphonia.',2,'recall',['ICS','inhaled corticosteroids','asthma management','inflammation','respirology']);
add('resp-asthma','A 45-year-old has asthma uncontrolled on medium-dose ICS/LABA. What add-on biologics are available and how are they chosen?','Anti-IgE (omalizumab for allergic asthma), anti-IL5 (mepolizumab, benralizumab for eosinophilic asthma), anti-IL4/13 (dupilumab)','CTS guidelines recommend biologics for severe uncontrolled asthma at Step 5 based on phenotype. Eosinophil count (≥300) guides anti-IL5 choice. Omalizumab requires elevated serum IgE and allergen sensitization.',4,'analyze',['biologics','severe asthma','omalizumab','mepolizumab','eosinophilic','respirology']);
add('resp-asthma','What is the MART strategy in asthma and what are its benefits?','Maintenance And Reliever Therapy using ICS-formoterol (budesonide-formoterol) as both daily controller and as-needed reliever — reduces exacerbations vs. SABA PRN approach','GINA 2021 recommends ICS-formoterol as preferred reliever at Steps 3-5 because each reliever use delivers anti-inflammatory medication. This reduces exacerbation frequency and asthma-related deaths compared to SABA-only relief.',3,'recall',['MART','ICS-formoterol','budesonide-formoterol','asthma management','respirology']);
add('resp-asthma','How is occupational asthma diagnosed and managed?','Serial PEF monitoring at work vs. away, specific bronchoprovocation testing; management: remove from exposure — symptoms may not fully resolve even after removal','Occupational asthma accounts for 9-15% of adult-onset asthma. Common causes: isocyanates (spray painters), flour dust (bakers), latex, animals. Early diagnosis and removal from exposure improves prognosis.',3,'apply',['occupational asthma','PEF monitoring','workplace exposure','respirology']);
add('resp-asthma','A pregnant patient has moderate persistent asthma. Can ICS and LABAs be continued?','Yes — poorly controlled asthma is more dangerous to fetus than ICS/LABA. Continue ICS (budesonide preferred), LABA, and SABA','CTS guidelines state poorly controlled asthma increases risk of preterm birth, IUGR, and maternal complications. Benefits of ICS far outweigh risks. Oral corticosteroids can be used for exacerbations. Most asthma medications are safe in pregnancy.',3,'apply',['asthma in pregnancy','ICS','budesonide','safety','respirology']);
add('resp-asthma','What triggers should patients with asthma be counselled to avoid?','Allergens (dust mites, pet dander, mold, pollen), respiratory infections, tobacco smoke, cold air, NSAIDs/ASA, exercise, workplace exposures, GERD','Trigger avoidance is a key non-pharmacologic intervention. ASA/NSAID sensitivity (Samter triad: asthma + nasal polyps + ASA sensitivity) requires substitution with acetaminophen. Beta-blockers are relatively contraindicated in asthma.',2,'recall',['asthma triggers','allergen avoidance','Samter triad','NSAIDs','respirology']);
add('resp-asthma','A 16-year-old with asthma has SpO2 94%, moderate respiratory distress, and PEF 55% predicted after 2 puffs of salbutamol. Next management steps?','Continue salbutamol q20min x3, add ipratropium bromide, systemic corticosteroids (oral prednisone or IV methylprednisolone), supplemental O2','Moderate exacerbation: PEF 40-69%, SpO2 >90%, speaking in phrases. Adding ipratropium to SABA reduces hospitalization. Systemic corticosteroids should be given early. Reassess after initial treatment to determine if hospitalization needed.',4,'apply',['asthma exacerbation','salbutamol','ipratropium','corticosteroids','respirology']);
add('resp-asthma','What is the role of leukotriene receptor antagonists (montelukast) in asthma?','Add-on therapy for persistent asthma not controlled on ICS alone; also useful for allergic rhinitis comorbidity and exercise-induced bronchoconstriction','Montelukast is a Step 3 add-on option per CTS guidelines. It is less effective than LABA as add-on therapy. Health Canada has a boxed warning for neuropsychiatric adverse effects (depression, suicidal ideation) — counsel patients.',3,'recall',['montelukast','LTRA','asthma add-on therapy','respirology']);
add('resp-asthma','How is exercise-induced bronchoconstriction (EIB) managed?','SABA 15 min before exercise for prevention; warm-up period; consider LTRA or ICS if frequent; diagnose with exercise challenge test (FEV1 drop ≥10%)','EIB occurs in up to 90% of asthmatics. Diagnosis confirmed by ≥10% FEV1 drop on standardized exercise challenge. SABA pre-treatment is most effective. ICS reduces EIB with regular use.',2,'recall',['exercise-induced bronchoconstriction','EIB','SABA','prevention','respirology']);
add('resp-asthma','What defines asthma-COPD overlap (ACO) and how is it managed?','Persistent airflow limitation (post-BD FEV1/FVC <0.70) plus features of both asthma (variable airflow) and COPD (age >40, smoking history); manage with ICS/LABA — avoid LABA without ICS','ACO has increased exacerbation risk. CTS recommends ICS as cornerstone since ICS monotherapy is inappropriate in COPD but ICS-containing therapy is appropriate in ACO. Smoking cessation is critical.',4,'analyze',['ACO','asthma-COPD overlap','ICS','LABA','respirology']);
add('resp-asthma','What are the indications for referral to a respirologist for asthma management?','Uncontrolled asthma despite Step 3-4 therapy, severe exacerbations requiring ICU, uncertain diagnosis, occupational asthma, consideration for biologic therapy, frequent ED visits','CTS guidelines recommend specialist referral for difficult-to-treat asthma. Specialist evaluation includes allergy testing, comprehensive spirometry, bronchoprovocation testing, and assessment for comorbidities (GERD, rhinosinusitis, OSA, obesity) that may worsen asthma.',3,'recall',['asthma referral','specialist','difficult asthma','respirology']);

// RESPIROLOGY - resp-copd (15)
add('resp-copd','A 65-year-old smoker (45 pack-years) has progressive dyspnea, chronic productive cough, and spirometry showing FEV1/FVC 0.62 post-bronchodilator. Diagnosis and GOLD staging?','COPD; GOLD stage based on FEV1: Stage I ≥80%, Stage II 50-79%, Stage III 30-49%, Stage IV <30% predicted','CTS/GOLD guidelines define COPD by post-bronchodilator FEV1/FVC <0.70. GOLD classification guides pharmacotherapy. Clinical assessment (exacerbation history, mMRC dyspnea score, CAT score) determines GOLD group A-D.',3,'apply',['COPD','GOLD staging','spirometry','FEV1','respirology']);
add('resp-copd','What is the single most important intervention for COPD management?','Smoking cessation — the only intervention proven to slow FEV1 decline and reduce mortality','CTS guidelines strongly recommend smoking cessation for all COPD patients. Pharmacotherapy (varenicline preferred, NRT, bupropion) combined with behavioral support doubles cessation rates. Even after decades of smoking, cessation slows disease progression.',1,'recall',['COPD','smoking cessation','FEV1 decline','respirology']);
add('resp-copd','What is the first-line pharmacotherapy for mild-moderate symptomatic COPD (GOLD group A-B)?','Long-acting bronchodilator: LAMA (tiotropium, umeclidinium) or LABA (salmeterol, formoterol) — LAMA preferred for dyspnea reduction','CTS COPD guidelines recommend LAMA as first-line for most symptomatic COPD patients. LAMA (tiotropium) superior to LABA for reducing exacerbations and hospitalizations (UPLIFT trial). LAMA+LABA combination for persistent symptoms.',2,'recall',['COPD treatment','LAMA','tiotropium','LABA','bronchodilator','respirology']);
add('resp-copd','When are inhaled corticosteroids (ICS) indicated in COPD?','ICS added to LAMA+LABA when: ≥2 moderate or ≥1 severe exacerbation per year AND eosinophil count ≥300 cells/μL (or ≥100 with frequent exacerbations)','CTS guidelines recommend triple therapy (ICS+LAMA+LABA) for high-risk COPD patients (Group D/E). ICS alone is inappropriate in COPD. Blood eosinophil count guides ICS benefit — higher counts predict greater response.',3,'recall',['ICS','COPD','triple therapy','eosinophils','exacerbations','respirology']);
add('resp-copd','A 68-year-old with COPD has PaO2 54 mmHg at rest on room air. What is indicated?','Long-term home oxygen therapy (LTOT) for ≥15-18 hours/day — improves survival in severe hypoxemia','NOCTURNAL O2 and MRC trials showed LTOT survival benefit when PaO2 ≤55 mmHg or SaO2 ≤88%. Indications: PaO2 ≤55 mmHg (SaO2 ≤88%), or PaO2 56-59 mmHg with polycythemia, cor pulmonale, or pulmonary hypertension. Minimum 15h/day for benefit.',3,'apply',['LTOT','long-term oxygen','COPD','hypoxemia','respirology']);
add('resp-copd','What characterizes an acute exacerbation of COPD (AECOPD) and how is it managed?','AECOPD: acute worsening of respiratory symptoms beyond normal variation requiring change in therapy; treat with short-acting bronchodilators, systemic corticosteroids (prednisone 40mg x5 days), antibiotics if purulent sputum','CTS guidelines: antibiotics for AECOPD with purulent sputum or requiring hospitalization. Preferred antibiotics: doxycycline, amoxicillin-clavulanate, azithromycin. NIV (BiPAP) for AECOPD with hypercapnic respiratory failure reduces intubation and mortality.',4,'apply',['AECOPD','exacerbation','corticosteroids','antibiotics','NIV','respirology']);
add('resp-copd','What is the role of pulmonary rehabilitation in COPD?','Pulmonary rehab reduces dyspnea, improves exercise capacity and quality of life, reduces hospitalizations — recommended for all COPD patients with MRC dyspnea ≥2 or after exacerbation','CTS guidelines strongly recommend pulmonary rehabilitation as a core COPD treatment. Programs include exercise training, education, and psychosocial support. Benefits are greatest when started within 4 weeks of an exacerbation.',2,'recall',['pulmonary rehabilitation','COPD','exercise','dyspnea','respirology']);
add('resp-copd','What is the difference between emphysema and chronic bronchitis in COPD?','Emphysema: destruction of alveolar walls and airspace enlargement (pink puffer: thin, barrel chest, pursed-lip breathing); Chronic bronchitis: productive cough ≥3 months/year for ≥2 consecutive years (blue bloater: cyanotic, edematous)','These are clinical phenotypes within COPD spectrum. Most patients have features of both. Emphysema is a pathological diagnosis; chronic bronchitis is clinical. CT findings of emphysema correlate with worse prognosis.',2,'recall',['emphysema','chronic bronchitis','COPD phenotypes','pink puffer','blue bloater','respirology']);
add('resp-copd','What are indications for NIV (BiPAP) in AECOPD?','Acute hypercapnic respiratory failure (pH <7.35, PaCO2 >45 mmHg) with moderate-severe dyspnea, accessory muscle use — reduces intubation and mortality','NICE and CTS guidelines recommend NIV as first-line for AECOPD with acute hypercapnic failure when pH 7.25-7.35. NIV reduces mortality by ~48% and intubation rate. Contraindications: unconscious, vomiting, hemodynamic instability.',4,'apply',['NIV','BiPAP','AECOPD','hypercapnia','respiratory failure','respirology']);
add('resp-copd','What vaccinations are recommended for COPD patients?','Influenza (annual), pneumococcal (PCV13 + PPSV23), COVID-19, RSV vaccine (age ≥60), Tdap booster','CTS guidelines recommend all COPD patients receive influenza and pneumococcal vaccines to reduce exacerbations and pneumonia. Influenza vaccination reduces AECOPD hospitalizations by ~40%. RSV vaccine now recommended for older COPD patients.',2,'recall',['COPD','vaccines','influenza','pneumococcal','respirology']);
add('resp-copd','A 70-year-old with severe COPD is in respiratory failure. When should intubation and mechanical ventilation be considered?','When NIV fails or is contraindicated; clinical indicators: pH <7.25, severe encephalopathy, hemodynamic instability, inability to protect airway, respiratory arrest','Invasive MV in COPD has significant complications (VAP, prolonged weaning, diaphragm atrophy). Goals of care discussion is critical before intubation. Non-invasive strategies (NIV, high-flow NC) should be maximized first.',5,'analyze',['COPD','intubation','mechanical ventilation','NIV failure','respiratory failure','respirology']);
add('resp-copd','What alpha-1 antitrypsin deficiency causes and how is it diagnosed?','A1AT deficiency (ZZ genotype) causes early-onset panacinar emphysema (especially lower lobes), liver disease; diagnose with serum A1AT level and genotyping','A1AT deficiency should be suspected in COPD patients <45 years, non-smokers, or with family history. Treatment: smoking cessation, standard COPD therapy, A1AT augmentation therapy for severe deficiency with emphysema.',3,'apply',['alpha-1 antitrypsin','A1AT deficiency','emphysema','COPD','genotyping','respirology']);
add('resp-copd','What spirometry pattern defines COPD and how does it differ from restrictive lung disease?','COPD: obstructive pattern — FEV1/FVC <0.70 post-bronchodilator, FVC normal or reduced; Restrictive: FEV1/FVC normal or elevated, TLC <80% predicted','COPD is defined by persistent airflow obstruction. Restrictive disease (fibrosis, obesity, NMD) shows reduced TLC with preserved or increased FEV1/FVC ratio. Mixed patterns occur (bronchiectasis with fibrosis).',2,'recall',['spirometry','obstructive','restrictive','FEV1/FVC','COPD','respirology']);
add('resp-copd','A 66-year-old COPD patient develops worsening dyspnea and peripheral edema. CXR shows enlarged heart and bilateral pleural effusions. What complication is present?','Cor pulmonale — right heart failure from pulmonary hypertension secondary to chronic hypoxemia','COPD-related pulmonary hypertension results from hypoxic pulmonary vasoconstriction and vascular remodeling. Treatment: LTOT is most effective intervention. Diuretics for edema. Sildenafil and other pulmonary arterial HTN drugs have limited evidence in COPD-associated PH.',4,'analyze',['cor pulmonale','pulmonary hypertension','COPD complication','LTOT','respirology']);
add('resp-copd','What are the criteria for hospital admission in AECOPD?','Severe dyspnea, SpO2 <88%, altered mental status, inability to manage at home, high social risk, respiratory failure (pH <7.35, PaCO2 >45), failure of outpatient treatment','CTS guidelines provide criteria for safe outpatient management vs. hospitalization. Patients with comorbidities (pneumonia, CHF, PE) require admission. ICU transfer for pH <7.25, hemodynamic instability, or NIV failure.',3,'apply',['AECOPD','hospital admission','criteria','respirology']);

// RESPIROLOGY - resp-pneumonia (15)
add('resp-pneumonia','A 55-year-old presents with productive cough, fever, pleuritic chest pain, and CXR showing right lower lobe consolidation. WBC 18,000. How is severity assessed?','Use CURB-65 score: Confusion, Urea >7 mmol/L, RR ≥30, BP <90/60, Age ≥65; 0-1: outpatient; 2: inpatient; ≥3: ICU consideration','CTS CAP guidelines recommend CURB-65 to guide site of care decisions. Pneumonia Severity Index (PSI) is an alternative. High-severity CAP (ICU) features include: shock, need for ventilation, multilobar infiltrates.',3,'apply',['CAP','pneumonia','CURB-65','severity','respirology']);
add('resp-pneumonia','What are the most common organisms causing community-acquired pneumonia (CAP)?','Typical: Streptococcus pneumoniae (most common), Haemophilus influenzae; Atypical: Mycoplasma pneumoniae, Chlamydophila pneumoniae, Legionella pneumophila','S. pneumoniae accounts for ~30-40% of CAP requiring hospitalization. Atypical organisms are more common in younger, healthier patients. Legionella associated with cooling towers, travel, smokers.',2,'recall',['CAP','pneumonia organisms','Streptococcus pneumoniae','atypical','respirology']);
add('resp-pneumonia','What is the empiric antibiotic treatment for outpatient CAP in a healthy adult without comorbidities?','Amoxicillin 1g TID (preferred) OR doxycycline 100mg BID — macrolone alone not recommended due to increasing resistance in Canada','CTS 2019 CAP guidelines recommend amoxicillin or doxycycline for outpatient CAP. Azithromycin alone no longer recommended due to S. pneumoniae macrolide resistance in Canada. Duration: 5-7 days for uncomplicated outpatient CAP.',3,'apply',['CAP treatment','amoxicillin','doxycycline','outpatient pneumonia','respirology']);
add('resp-pneumonia','What antibiotic regimen is recommended for hospitalized non-ICU CAP?','Beta-lactam (ampicillin-sulbactam or ceftriaxone) PLUS azithromycin OR respiratory fluoroquinolone (levofloxacin/moxifloxacin) monotherapy','CTS guidelines recommend combination beta-lactam + macrolide or monotherapy with respiratory fluoroquinolone for hospitalized non-ICU CAP. Combination therapy covers atypicals and reduces mortality.',3,'recall',['CAP','hospitalized pneumonia','ceftriaxone','azithromycin','fluoroquinolone','respirology']);
add('resp-pneumonia','A 70-year-old with CAP is hypotensive, requires ICU admission. What additional antibiotic coverage is needed?','Add anti-pseudomonal beta-lactam (piperacillin-tazobactam or cefepime) if Pseudomonas risk factors; otherwise ceftriaxone + azithromycin ± oseltamivir (if influenza season)','Severe CAP (ICU): beta-lactam + macrolide is standard. Anti-MRSA (vancomycin) added if post-influenza or necrotizing pneumonia. CTS recommends considering antifungal coverage in immunocompromised.',4,'analyze',['severe CAP','ICU pneumonia','Pseudomonas','antibiotic coverage','respirology']);
add('resp-pneumonia','What is the clinical presentation of Legionella pneumonia and how is it diagnosed?','High fever, headache, GI symptoms (diarrhea), confusion, hyponatremia, lymphopenia, elevated LFTs; diagnosis: urine Legionella antigen (90% sensitive for L. pneumophila serogroup 1)','Legionella is associated with cooling towers, hot tubs, travel. Gram stain shows no organisms despite clinical pneumonia. Treatment: respiratory fluoroquinolone or azithromycin. Reportable disease in Canada.',4,'apply',['Legionella','atypical pneumonia','urine antigen','respirology']);
add('resp-pneumonia','What is aspiration pneumonia vs. aspiration pneumonitis?','Pneumonitis: chemical aspiration of gastric acid causing sterile inflammatory response — supportive care only; Pneumonia: aspiration of oropharyngeal bacteria requiring antibiotics','Aspiration pneumonitis usually resolves in 24-48 hours without antibiotics. Aspiration pneumonia develops when bacteria are aspirated, typically in patients with impaired swallowing (stroke, ALS, intoxication). Antibiotics: ampicillin-sulbactam or clindamycin (anaerobic coverage).',4,'analyze',['aspiration pneumonia','aspiration pneumonitis','antibiotic treatment','respirology']);
add('resp-pneumonia','What is the standard workup for hospitalized CAP?','Sputum Gram stain and culture, blood cultures x2, CBC, electrolytes, creatinine, LFTs, urine Legionella antigen, urine pneumococcal antigen, oxygen saturation, CXR','CTS guidelines recommend blood cultures for hospitalized CAP — positive in 5-14% but guide de-escalation. Urine antigens have high specificity. Respiratory viral panel (influenza, COVID) in season. Repeat CXR at 6 weeks to confirm resolution.',3,'recall',['CAP workup','blood cultures','urine antigens','hospitalized pneumonia','respirology']);
add('resp-pneumonia','When should a parapneumonic effusion be drained?','Drain if: pH <7.20, glucose <2.2 mmol/L, LDH >1000 IU/L, positive Gram stain or culture (empyema) — complicated parapneumonic effusion','CTS guidelines use Light criteria to characterize parapneumonic effusions. Empyema (pus in pleural space) requires drainage (thoracocentesis or chest tube). VATS decortication for loculated/organized empyema.',4,'analyze',['parapneumonic effusion','empyema','thoracocentesis','Light criteria','respirology']);
add('resp-pneumonia','What is hospital-acquired pneumonia (HAP) vs. ventilator-associated pneumonia (VAP)?','HAP: pneumonia developing ≥48h after hospital admission, not intubated; VAP: pneumonia developing ≥48h after endotracheal intubation — both require broader antibiotic coverage than CAP','HAP/VAP organisms include Pseudomonas aeruginosa, Klebsiella, MRSA, Acinetobacter. Empiric treatment: anti-pseudomonal beta-lactam ± aminoglycoside or fluoroquinolone ± MRSA coverage depending on risk.',3,'recall',['HAP','VAP','hospital-acquired pneumonia','ventilator-associated','respirology']);
add('resp-pneumonia','What is Pneumocystis jirovecii pneumonia (PCP) and who gets it?','Fungal pneumonia in immunocompromised patients (HIV with CD4 <200, organ transplant, high-dose steroids); presents with subacute dyspnea, non-productive cough, bilateral interstitial infiltrates on CXR','Diagnosis: BAL with immunofluorescence, serum beta-D-glucan. Treatment: TMP-SMX (trimethoprim-sulfamethoxazole) is drug of choice; add prednisone if PaO2 <70 mmHg. Prophylaxis: TMP-SMX when CD4 <200.',4,'apply',['PCP','Pneumocystis','HIV','immunocompromised','respirology']);
add('resp-pneumonia','What is the CXR pattern in different pneumonia types?','Lobar/segmental consolidation: typical bacterial; Bilateral interstitial: atypical, viral, PCP; Cavitation: TB, Staph aureus, anaerobes, Klebsiella; Upper lobe: TB; Lower lobe: aspiration','Radiographic patterns guide differential diagnosis but overlap is common. All hospitalized CAP patients require follow-up CXR at 6 weeks to confirm resolution and exclude underlying malignancy in smokers >50.',3,'apply',['CXR pattern','pneumonia radiology','cavitation','atypical pneumonia','respirology']);
add('resp-pneumonia','When is antifungal treatment indicated for pneumonia?','Invasive fungal pneumonia in immunocompromised: Aspergillus (voriconazole), Candida pneumonia (fluconazole or echinocandin), Cryptococcus (amphotericin B + flucytosine then fluconazole)','Aspergillus pneumonia occurs in prolonged neutropenia or high-dose steroids. Galactomannan assay and CT (halo sign) help diagnose invasive aspergillosis. Cryptococcal pneumonia is associated with HIV; diagnose with serum cryptococcal antigen.',4,'analyze',['fungal pneumonia','Aspergillus','voriconazole','immunocompromised','respirology']);
add('resp-pneumonia','What are indications for influenza testing and treatment in pneumonia?','Test for influenza (rapid PCR or antigen test) during influenza season for all hospitalized pneumonia patients; treat with oseltamivir within 48 hours of symptom onset','CTS recommends oseltamivir for hospitalized patients with confirmed or suspected influenza regardless of symptom duration. Influenza pneumonia can cause severe respiratory failure. Secondary bacterial pneumonia (Staph aureus, S. pneumoniae) should be treated with antibiotics.',3,'apply',['influenza','oseltamivir','pneumonia treatment','respirology']);
add('resp-pneumonia','When is follow-up CXR required after community-acquired pneumonia?','CXR at 6-8 weeks post-discharge for smokers, patients >50 years, or incomplete clinical resolution — to exclude underlying malignancy','Studies show lung cancer underlies CAP in up to 10-15% of adults >50. CTS CAP guidelines recommend routine follow-up imaging in higher-risk patients. CT chest is indicated if plain CXR does not clear at 6-8 weeks.',3,'recall',['follow-up CXR','pneumonia','lung cancer','post-pneumonia','respirology']);

// RESPIROLOGY - resp-pe (15)
add('resp-pe','A 45-year-old woman on OCP presents with sudden onset dyspnea and pleuritic chest pain. HR 112, SpO2 92%, RR 24. ECG shows sinus tachycardia. What is the pretest probability and next step?','Calculate Wells PE score; moderate-high probability → CT pulmonary angiography (CTPA); low probability → D-dimer first','Wells PE criteria: clinical signs of DVT (3), no alternative diagnosis (3), HR >100 (1.5), immobilization/surgery (1.5), prior DVT/PE (1.5), hemoptysis (1), malignancy (1). Score >4 = moderate probability.',4,'apply',['pulmonary embolism','Wells score','CTPA','D-dimer','respirology']);
add('resp-pe','What is the PERC rule and when can it safely exclude PE without further testing?','PERC: all 8 criteria must be met — age <50, HR <100, SpO2 ≥95%, no unilateral leg swelling, no hemoptysis, no recent surgery/trauma, no prior DVT/PE, no estrogen use — reduces PE miss rate to <2%','PERC rule is used in low pretest probability PE to avoid unnecessary testing. If any criterion is positive, proceed to D-dimer. CTS guidelines endorse PERC in low-risk patients to reduce overtesting.',3,'apply',['PERC rule','pulmonary embolism','low probability','D-dimer','respirology']);
add('resp-pe','A pregnant woman has suspected PE. What is the preferred diagnostic imaging?','V/Q scan preferred in pregnancy (lower radiation dose to fetus); CTPA is alternative if CXR abnormal','SOGC and CTS guidelines recommend V/Q scan as first-line in pregnancy due to lower fetal radiation exposure. D-dimer is unreliable in pregnancy (physiologically elevated). Bilateral leg Doppler may avoid further imaging if positive.',4,'apply',['PE in pregnancy','V/Q scan','CTPA','radiation','respirology','SOGC']);
add('resp-pe','What is massive PE and how is it managed?','Massive PE: hemodynamic instability (SBP <90 mmHg or 40 mmHg drop ≥15 min) caused by PE — requires systemic thrombolysis (alteplase 100mg over 2h) or catheter-directed therapy/surgical embolectomy','CCS/CTS guidelines recommend systemic thrombolysis for massive PE without absolute contraindications. Anticoagulation alone is insufficient for hemodynamic compromise. ECMO as bridge in cardiac arrest.',5,'analyze',['massive PE','thrombolysis','hemodynamic instability','alteplase','respirology']);
add('resp-pe','What are the preferred anticoagulants for acute PE management?','DOAC preferred (rivaroxaban or apixaban — no parenteral bridging needed); LMWH + warfarin if DOAC contraindicated; LMWH preferred in cancer-associated VTE (rivaroxaban/apixaban also acceptable per CTS 2023)','CTS VTE guidelines support DOAC monotherapy for most acute PE. Rivaroxaban 15mg BID x21 days then 20mg OD; apixaban 10mg BID x7 days then 5mg BID. Avoid DOACs in antiphospholipid syndrome (triple positive) — use warfarin.',3,'recall',['PE anticoagulation','DOAC','rivaroxaban','apixaban','VTE treatment','respirology']);
add('resp-pe','How long should anticoagulation be continued for PE?','Provoked PE (transient risk factor): 3 months; Unprovoked PE: minimum 3 months then reassess for extended therapy; Cancer-associated PE: until cancer resolved or indefinitely','CTS guidelines recommend extended anticoagulation for unprovoked PE if bleeding risk is low/moderate, as recurrence risk is 30% at 5 years. Risk stratification tools (DASH, Vienna score) guide duration decisions.',3,'apply',['PE duration','anticoagulation duration','VTE','provoked unprovoked','respirology']);
add('resp-pe','What is the ECG finding classically described in PE and how sensitive is it?','S1Q3T3 pattern (S wave in lead I, Q wave and inverted T wave in lead III) — sensitivity only ~20%, non-specific','The most common ECG findings in PE are sinus tachycardia and right heart strain (RBBB, right axis deviation). S1Q3T3 is classically taught but rarely seen and not diagnostic. ECG primarily helps exclude other diagnoses (ACS, pericarditis).',2,'recall',['PE ECG','S1Q3T3','sinus tachycardia','right heart strain','respirology']);
add('resp-pe','What is submassive (intermediate-risk) PE and when should thrombolysis be considered?','Submassive PE: hemodynamically stable but with RV dysfunction on echo/CT and/or elevated troponin/BNP; thrombolysis controversial — consider catheter-directed therapy in deteriorating patients','CTS guidelines recommend anticoagulation alone for most submassive PE. Escalation to thrombolysis or catheter-directed therapy (EKOS) for clinical deterioration. PEITHO trial showed benefit of thrombolysis offset by increased bleeding.',4,'analyze',['submassive PE','intermediate risk','RV dysfunction','thrombolysis','catheter-directed','respirology']);
add('resp-pe','A 55-year-old with DVT of the right leg is confirmed by Doppler. No symptoms of PE. How is DVT managed?','Anticoagulation with DOAC (rivaroxaban, apixaban) for 3 months for provoked, longer for unprovoked — LMWH + warfarin if DOAC contraindicated','CTS guidelines treat proximal DVT (above knee: popliteal, femoral, iliac) with systemic anticoagulation. Distal DVT (below-knee isolated) managed on individual basis — may monitor or treat depending on symptoms and risk. IVC filter not recommended routinely.',3,'apply',['DVT','anticoagulation','DOAC','deep vein thrombosis','respirology']);
add('resp-pe','What are the risk factors for venous thromboembolism (VTE)?','Strong: surgery, major trauma, hospitalization, prior VTE, cancer, antiphospholipid syndrome; Moderate: OCP, HRT, pregnancy, obesity; Weak: immobility, age, varicose veins','Virchow triad: stasis, hypercoagulability, endothelial injury. Thrombophilia testing indicated in select patients: unprovoked VTE <50 years, family history, unusual site. Timing of testing: after anticoagulation discontinued.',2,'recall',['VTE risk factors','DVT','PE','thrombophilia','Virchow triad','respirology']);
add('resp-pe','What is an IVC filter and when is it indicated?','IVC filter indicated when anticoagulation is absolutely contraindicated AND patient has acute proximal DVT or PE — retrievable filters preferred','CTS guidelines limit IVC filter use to patients with absolute contraindication to anticoagulation. Filters prevent PE but increase DVT recurrence and do not reduce overall mortality. Must restart anticoagulation as soon as safe and retrieve filter if retrievable.',3,'recall',['IVC filter','anticoagulation contraindication','VTE','DVT','respirology']);
add('resp-pe','What is chronic thromboembolic pulmonary hypertension (CTEPH) and how is it diagnosed?','Persistent pulmonary hypertension (mean PAP ≥25 mmHg) due to unresolved PE clots after ≥3 months of anticoagulation; diagnosed with V/Q scan and right heart catheterization','CTEPH occurs in 2-4% of PE survivors. V/Q scan is more sensitive than CTPA for CTEPH. Treatment: pulmonary endarterectomy (PEA) is curative if operable; riociguat for inoperable disease. Lifelong anticoagulation required.',4,'analyze',['CTEPH','chronic thromboembolic','pulmonary hypertension','VTE complication','respirology']);
add('resp-pe','When should thrombophilia testing be performed after VTE?','After completing anticoagulation (≥3 months), not during acute event or anticoagulation; test: Factor V Leiden, prothrombin gene mutation, antiphospholipid antibodies, protein C/S, antithrombin','Anticoagulants affect thrombophilia tests: DOAC/heparin affects AT, warfarin affects protein C/S. Antiphospholipid antibodies should be repeated at 12 weeks to confirm diagnosis. Testing affects duration of anticoagulation decisions.',3,'apply',['thrombophilia testing','VTE','antiphospholipid','Factor V Leiden','respirology']);
add('resp-pe','What compression stocking regimen reduces post-thrombotic syndrome after DVT?','Graduated compression stockings (30-40 mmHg knee-high) for 2 years after proximal DVT — reduces PTS development','Post-thrombotic syndrome (PTS) occurs in 20-50% of proximal DVT and causes chronic leg pain, swelling, and skin changes. Elastic compression stockings reduce PTS severity. SOX trial found below-knee stockings do not reduce PTS in non-severe cases.',3,'recall',['post-thrombotic syndrome','compression stockings','DVT complication','VTE','respirology']);
add('resp-pe','A 60-year-old with unprovoked PE has completed 3 months of anticoagulation. What factors guide decision for extended therapy?','Low bleeding risk + unprovoked PE → extend anticoagulation indefinitely; weigh annual recurrence risk (5-10%/year) vs. major bleeding risk (~1-2%/year on DOAC)','CTS guidelines recommend extended anticoagulation for most unprovoked PE in patients with low-moderate bleeding risk. Low-dose rivaroxaban (10mg OD) or apixaban (2.5mg BID) extended therapy reduces recurrence with less bleeding than full-dose.',4,'analyze',['unprovoked PE','extended anticoagulation','bleeding risk','VTE recurrence','respirology']);

// RESPIROLOGY - resp-sarcoid (7)
add('resp-sarcoid','A 35-year-old Black woman presents with bilateral hilar lymphadenopathy on CXR, erythema nodosum, and elevated ACE. Diagnosis and staging?','Sarcoidosis; Stage I: bilateral hilar lymphadenopathy alone; Stage II: BHL + pulmonary infiltrates; Stage III: infiltrates without BHL; Stage IV: pulmonary fibrosis','Sarcoidosis is a systemic granulomatous disease. Definitive diagnosis requires biopsy showing non-caseating granulomas (exclude TB, fungal). ACE is elevated in ~60%. Calcium elevated in ~10%. Black patients have more severe disease.',4,'analyze',['sarcoidosis','bilateral hilar lymphadenopathy','ACE','staging','respirology']);
add('resp-sarcoid','What are the extrapulmonary manifestations of sarcoidosis?','Eyes (uveitis, most common), skin (erythema nodosum, lupus pernio), heart (conduction block, VT), nervous system (cranial nerve palsies, esp CN VII), liver, kidneys, bones','Cardiac sarcoidosis causes sudden death from VT/heart block — all sarcoidosis patients need ECG. Neurosarcoidosis: CN VII palsy is most common. Lofgren syndrome (bilateral hilar adenopathy + erythema nodosum + polyarthritis) has excellent prognosis.',3,'recall',['sarcoidosis','extrapulmonary','uveitis','cardiac sarcoidosis','respirology']);
add('resp-sarcoid','When is treatment indicated for pulmonary sarcoidosis?','Symptomatic pulmonary disease, declining lung function (FVC decline >10%), hypercalcemia, cardiac/neurological sarcoidosis, severe skin involvement','Not all sarcoidosis requires treatment. Stage I and II asymptomatic may be observed. Corticosteroids (prednisone 20-40mg) are first-line for progressive or organ-threatening disease. Steroid-sparing agents: methotrexate, azathioprine, hydroxychloroquine.',3,'apply',['sarcoidosis treatment','corticosteroids','pulmonary sarcoidosis','respirology']);
add('resp-sarcoid','What is Lofgren syndrome and what is its prognosis?','Acute sarcoidosis triad: bilateral hilar adenopathy + erythema nodosum/periarthritis + fever; excellent prognosis — self-limited, resolves spontaneously in >90%','Lofgren syndrome is the most common acute presentation of sarcoidosis in Northern Europeans. It usually resolves within 2 years without treatment. NSAIDs for symptomatic relief. This presentation has better prognosis than insidious-onset sarcoidosis.',3,'recall',['Lofgren syndrome','sarcoidosis','erythema nodosum','prognosis','respirology']);
add('resp-sarcoid','What is interstitial lung disease (ILD) and what are the main categories?','ILD: diffuse parenchymal lung diseases causing alveolar inflammation and/or fibrosis; categories: idiopathic (IPF, NSIP), connective tissue disease-associated, hypersensitivity pneumonitis, drug-induced, sarcoidosis','ILD presents with progressive dyspnea, dry cough, bilateral crackles, and restrictive spirometry. HRCT is essential for pattern recognition. IPF has the worst prognosis; most other ILDs respond to immunosuppression.',2,'recall',['ILD','interstitial lung disease','IPF','categories','respirology']);
add('resp-sarcoid','What HRCT pattern characterizes idiopathic pulmonary fibrosis (IPF) and what is its treatment?','Usual interstitial pneumonia (UIP) pattern on HRCT: bilateral basal-predominant subpleural honeycombing ± traction bronchiectasis; treat with nintedanib or pirfenidone (antifibrotic agents)','IPF is the most common ILD with median survival 3-5 years from diagnosis. Diagnosis requires exclusion of other causes. Antifibrotics slow FVC decline but do not reverse fibrosis. Lung transplantation is the only curative option.',4,'analyze',['IPF','UIP pattern','nintedanib','pirfenidone','antifibrotic','respirology']);
add('resp-sarcoid','What is hypersensitivity pneumonitis (HP) and how is it diagnosed?','Immune-mediated ILD from repeated inhalation of organic antigens (bird droppings, mold, farmer lung — thermophilic actinomyces); diagnose with exposure history, serum precipitins, HRCT, BAL lymphocytosis ± lung biopsy','Chronic HP can progress to fibrosis (chronic HP with fibrotic UIP pattern). Treatment: antigen avoidance (most important), corticosteroids for acute/subacute forms. Smoking paradoxically protective for HP development but worsens prognosis if fibrosis develops.',4,'analyze',['hypersensitivity pneumonitis','HP','organic antigen','bird fancier','farmer lung','respirology']);

process.stdout.write(JSON.stringify(cards));
