const fs = require('fs');
const cards = [];
let n = 1;
function add(topicId, q, a, ex, diff, bloom, tags) {
  cards.push({ id: `card-tn2-surg-${n++}`, question: q, answer: a, explanation: ex, difficulty: diff, bloomLevel: bloom, tags, topicId });
}

// SURG-ACUTE-ABDOMEN (15)
add('surg-acute-abdomen','What is the Alvarado score (MANTRELS) for appendicitis and how is it interpreted?','Migration of pain (1), Anorexia (1), Nausea/vomiting (1), Tenderness in RLQ (2), Rebound (1), Elevated temperature (1), Leukocytosis (2), Shift to left (1). Total 10. Score 1-4: unlikely; 5-6: possible (CT); 7-8: probable; 9-10: very probable appendicitis.',
'The Alvarado score is a clinical decision tool for appendicitis validated in Canadian EDs. Score >=7 has high specificity but low sensitivity. CT abdomen/pelvis is recommended for equivocal scores (5-6). Appendicitis is the most common surgical emergency.',3,'apply',['Alvarado score','appendicitis','acute abdomen','surgery']);

add('surg-acute-abdomen','What is the differential diagnosis for acute RLQ pain in a young woman?','Appendicitis, ruptured ovarian cyst, ovarian torsion, ectopic pregnancy, PID/tubo-ovarian abscess, Meckel diverticulitis, mesenteric adenitis, Crohn disease (terminal ileitis), right ureteral colic, endometriosis.',
'Beta-hCG is mandatory in all women of childbearing age with abdominal pain to exclude ectopic pregnancy. Pelvic ultrasound is first-line imaging for suspected gynecologic pathology. CT is the gold standard for appendicitis (sensitivity >95%).',3,'analyze',['RLQ pain','differential diagnosis','acute abdomen','surgery']);

add('surg-acute-abdomen','What are the indications for emergent laparotomy in acute abdomen?','Generalized peritonitis with hemodynamic instability, free air on imaging (perforated viscus), suspected mesenteric ischemia with peritoneal signs, ruptured AAA, uncontrolled hemorrhage, bowel obstruction with signs of strangulation (fever, tachycardia, localized tenderness, leukocytosis).',
'Hemodynamically unstable patients with peritonitis should go directly to OR without further imaging. Upright CXR or CT for pneumoperitoneum. Canadian surgical guidelines emphasize clinical judgment over scoring systems in the unstable patient.',5,'apply',['emergent laparotomy','peritonitis','acute abdomen','surgery']);

add('surg-acute-abdomen','How is small bowel obstruction (SBO) differentiated from large bowel obstruction and managed?','SBO: multiple air-fluid levels, dilated small bowel (>3cm), decompressed colon. LBO: dilated colon (>6cm, cecum >9cm), decompressed small bowel unless incompetent ileocecal valve. SBO management: NPO, NGT, IV fluids, serial exams. Surgery if signs of strangulation or no improvement in 48-72h.',
'CT with oral and IV contrast is the imaging modality of choice. Adhesions are the most common cause of SBO (60-75%) in developed countries. Water-soluble contrast (Gastrografin) study can be diagnostic and therapeutic in adhesive SBO. Most partial SBO resolves non-operatively.',4,'apply',['bowel obstruction','SBO','LBO','acute abdomen','surgery']);

add('surg-acute-abdomen','What are the signs of mesenteric ischemia and how is it diagnosed?','Acute mesenteric ischemia presents with severe abdominal pain out of proportion to physical exam, often in patients with AF or vascular disease. CT angiography is the diagnostic study of choice (sensitivity >95%). Labs: elevated lactate, metabolic acidosis, leukocytosis.',
'Mesenteric ischemia has high mortality (60-80%) if not treated promptly. SMA embolism (50% of cases) is most common, often from AF. Early surgical consultation and anticoagulation are essential. Canadian guidelines recommend CTA as first-line imaging.',5,'apply',['mesenteric ischemia','SMA','acute abdomen','surgery']);

add('surg-acute-abdomen','What is the management algorithm for acute pancreatitis?','Aggressive IV fluid resuscitation (goal-directed, lactated Ringer preferred), pain control (hydromorphone, avoid morphine per tradition though evidence is weak), NPO initially then early oral feeding as tolerated, no routine antibiotics. ERCP within 24h only if cholangitis or persistent biliary obstruction.',
'Revised Atlanta Classification grades severity: mild (no organ failure), moderately severe (transient organ failure <48h), severe (persistent organ failure >48h). Canadian guidelines follow AGA recommendations. Cholecystectomy during same admission for gallstone pancreatitis to prevent recurrence.',4,'apply',['pancreatitis','management','fluid resuscitation','surgery']);

add('surg-acute-abdomen','What is the Ranson criteria for pancreatitis severity?','At admission: Age >55, WBC >16,000, Glucose >11 mmol/L, LDH >350, AST >250. At 48h: Hct drop >10%, BUN rise >1.8 mmol/L, Ca <2.0 mmol/L, PaO2 <60, Base deficit >4, Fluid sequestration >6L. Score >=3 predicts severe disease.',
'Ranson criteria are limited by requiring 48 hours for completion. APACHE II and BISAP scores can be calculated earlier. CT severity index (Balthazar) assesses local complications. In Canada, BISAP is increasingly used for bedside assessment.',3,'recall',['Ranson criteria','pancreatitis','severity scoring','surgery']);

add('surg-acute-abdomen','What are the indications for cholecystectomy and the management of acute cholecystitis?','Acute cholecystitis: IV antibiotics + early laparoscopic cholecystectomy (within 72h preferred). Indications for cholecystectomy: symptomatic gallstones, acute cholecystitis, gallstone pancreatitis, porcelain gallbladder, gallbladder polyps >1cm. Tokyo Guidelines grade severity.',
'Early cholecystectomy (<72h) is safe and reduces hospital stay vs delayed surgery per Canadian and international guidelines. Percutaneous cholecystostomy is used for critically ill patients unfit for surgery. Intraoperative cholangiography or MRCP for suspected CBD stones.',4,'apply',['cholecystitis','cholecystectomy','gallstones','surgery']);

add('surg-acute-abdomen','How is perforated peptic ulcer diagnosed and managed?','Sudden-onset severe epigastric pain, rigid abdomen, free air on upright CXR (present in ~75%) or CT. Management: IV PPI, NPO, IV antibiotics, urgent surgical repair (Graham patch omentoplasty). H. pylori testing and eradication post-operatively.',
'CT has higher sensitivity than CXR for pneumoperitoneum. Non-operative management may be considered in stable patients with contained perforation. Most perforations are anterior duodenal ulcers. NSAID and H. pylori are the primary risk factors.',4,'apply',['perforated ulcer','pneumoperitoneum','surgery']);

add('surg-acute-abdomen','What is the management of acute diverticulitis by severity?','Uncomplicated: oral antibiotics (ciprofloxacin + metronidazole or amoxicillin-clavulanate) for 7-10 days, liquid diet, outpatient if tolerated. Complicated (abscess, perforation, fistula): IV antibiotics, CT-guided drainage for abscess >3cm, surgery for free perforation (Hartmann procedure or primary anastomosis).',
'Recent evidence (DIABOLO trial) suggests uncomplicated diverticulitis may be managed without antibiotics. Canadian guidelines still generally recommend antibiotics. Elective sigmoid colectomy after 2+ episodes is no longer routine-individualized based on severity and patient factors.',4,'apply',['diverticulitis','management algorithm','surgery']);

add('surg-acute-abdomen','What are the causes and management of upper GI bleeding?','Causes: peptic ulcer (most common), variceal, Mallory-Weiss, malignancy, AVM, Dieulafoy lesion. Management: resuscitation, IV PPI (pantoprazole 80mg bolus then 8mg/h infusion), transfuse if Hb <70 (restrictive), urgent EGD within 24h. Variceal: octreotide + antibiotics + urgent EGD with banding.',
'Glasgow-Blatchford score predicts need for intervention (score 0 = safe outpatient management). Canadian guidelines follow international consensus. Restrictive transfusion (Hb <70) improves outcomes vs liberal (Villanueva trial). H. pylori testing is mandatory if ulcer found.',4,'apply',['upper GI bleed','peptic ulcer','variceal bleeding','surgery']);

add('surg-acute-abdomen','What is the significance of Murphy sign and its role in acute abdomen assessment?','Murphy sign: inspiratory arrest during palpation of the RUQ (gallbladder). Positive Murphy = acute cholecystitis (sensitivity ~65%). Sonographic Murphy sign is more specific. Other key signs: McBurney (appendicitis), Rovsing (appendicitis), psoas sign, obturator sign.',
'Physical examination signs have moderate sensitivity individually but together guide clinical suspicion. RUQ ultrasound is the first-line imaging for suspected cholecystitis (thickened wall >3mm, pericholecystic fluid, sonographic Murphy). HIDA scan if US equivocal.',2,'recall',['Murphy sign','physical exam','acute abdomen','surgery']);

add('surg-acute-abdomen','What is the management of incarcerated inguinal hernia?','Attempt manual reduction (Trendelenburg, sedation, gentle sustained pressure). If successful: semi-elective surgical repair. If reduction fails or signs of strangulation (erythema, fever, peritonitis, tachycardia): emergent surgical exploration. Assess bowel viability intraoperatively.',
'Incarcerated hernias are a surgical emergency when strangulated. Femoral hernias have the highest risk of strangulation. In Canada, inguinal hernia repair is one of the most common general surgery procedures. Mesh repair (Lichtenstein) is standard for elective cases.',4,'apply',['inguinal hernia','incarcerated','strangulation','surgery']);

add('surg-acute-abdomen','How does acute appendicitis presentation differ in special populations?','Pregnancy: RUQ pain (displaced appendix), less peritoneal signs. Elderly: vague symptoms, less fever/leukocytosis, higher perforation rate (50-70%). Children: rapid progression to perforation, difficulty localizing pain. Retrocecal appendix: flank/back pain, psoas sign.',
'Atypical presentations lead to delayed diagnosis. MRI is preferred imaging in pregnancy (avoids radiation). In elderly, CT is essential as clinical assessment is unreliable. Perforation rate increases with diagnostic delay. Canadian guidelines recommend early imaging for equivocal cases.',4,'analyze',['appendicitis','special populations','atypical presentation','surgery']);

add('surg-acute-abdomen','What are the principles of damage control surgery?','Stage 1: Abbreviated laparotomy-control hemorrhage and contamination, temporary abdominal closure. Stage 2: ICU resuscitation-correct hypothermia, coagulopathy, acidosis (lethal triad). Stage 3: Planned re-laparotomy at 24-48h for definitive repair.',
'Damage control surgery is indicated when the lethal triad (hypothermia <35°C, coagulopathy, acidosis pH <7.2) develops intraoperatively. Temporary closure with negative pressure wound therapy. This approach reduces mortality in critically injured patients.',5,'apply',['damage control surgery','trauma','lethal triad','surgery']);

// SURG-TRAUMA (15)
add('surg-trauma','What is the ATLS primary survey and its sequence?','A: Airway with C-spine protection. B: Breathing and ventilation. C: Circulation with hemorrhage control. D: Disability (GCS, pupils). E: Exposure/Environmental control. Adjuncts: monitors, urinary catheter, gastric tube, X-rays (CXR, pelvis, C-spine), FAST exam.',
'ATLS is the standard trauma assessment protocol used in Canadian trauma centres. Life-threatening conditions are identified and treated in sequence. The primary survey should be completed within minutes. C-spine immobilization until cleared.',4,'recall',['ATLS','primary survey','trauma','surgery']);

add('surg-trauma','What is the ATLS secondary survey and when is it performed?','Complete head-to-toe physical examination performed after primary survey and initial resuscitation. Includes: detailed history (AMPLE: Allergies, Medications, Past history, Last meal, Events), complete physical exam of every body region, log roll, digital rectal exam if indicated, additional imaging (CT, angiography).',
'The secondary survey is only performed after the primary survey is complete and the patient is hemodynamically stable. Any deterioration requires returning to the primary survey. Canadian trauma centres use standardized documentation. Tertiary survey at 24h catches missed injuries.',3,'recall',['ATLS','secondary survey','trauma assessment','surgery']);

add('surg-trauma','What are the ATLS classes of hemorrhagic shock?','Class I: <750mL (<15%), normal vitals. Class II: 750-1500mL (15-30%), tachycardia, decreased pulse pressure. Class III: 1500-2000mL (30-40%), tachycardia, hypotension, altered mental status. Class IV: >2000mL (>40%), severe tachycardia, hypotension, lethargy/obtundation.',
'Hemorrhagic shock classification guides resuscitation strategy. Class III and IV require blood products. Massive transfusion protocol (1:1:1 PRBC:FFP:platelets) for uncontrolled hemorrhage. Canadian Blood Services guidelines support balanced resuscitation.',4,'recall',['hemorrhagic shock','ATLS classification','trauma','surgery']);

add('surg-trauma','What is the FAST exam and what does it assess?','Focused Assessment with Sonography in Trauma: 4 views-RUQ (Morison pouch/hepatorenal), LUQ (splenorenal), suprapubic (pelvis), subxiphoid (pericardium). Detects free intraperitoneal fluid (>200mL) and pericardial effusion. Extended FAST (eFAST) adds bilateral anterior chest for pneumothorax.',
'FAST sensitivity is 73-88% for hemoperitoneum. Positive FAST in unstable patient = emergent laparotomy. Negative FAST does not exclude injury-CT is needed if clinical suspicion remains. eFAST has 95% sensitivity for pneumothorax, superior to supine CXR.',4,'apply',['FAST exam','ultrasound','trauma assessment','surgery']);

add('surg-trauma','What is the management of hemodynamically unstable blunt abdominal trauma?','Positive FAST + unstable = emergent laparotomy. Negative FAST + unstable = consider other causes (chest, pelvis, external). If DPL positive (>10mL gross blood or RBC >100,000/mm3) = laparotomy. Splenic and liver injuries in unstable patients require surgical intervention.',
'Canadian trauma guidelines follow ATLS principles. Non-operative management of solid organ injuries is appropriate only in hemodynamically stable patients. Pelvic binder and angioembolization for pelvic hemorrhage. Permissive hypotension (SBP 80-90) until hemorrhage control.',5,'apply',['blunt abdominal trauma','unstable','laparotomy','surgery']);

add('surg-trauma','What are the indications for chest tube insertion in trauma?','Pneumothorax (especially tension or >15% on CXR), hemothorax, open pneumothorax (after sealing with three-sided occlusive dressing), flail chest with respiratory compromise, positive eFAST for pneumothorax in ventilated patient. Size: 28-32 Fr, inserted at 5th intercostal space, anterior axillary line.',
'Needle decompression (2nd ICS MCL or 5th ICS AAL) is the immediate treatment for tension pneumothorax, followed by chest tube. Massive hemothorax (>1500mL initial output or >200mL/h for 2-4h) requires thoracotomy. Autotransfusion can be used with hemothorax.',4,'apply',['chest tube','pneumothorax','hemothorax','trauma','surgery']);

add('surg-trauma','How is traumatic brain injury classified and initially managed?','GCS: Mild (13-15), Moderate (9-12), Severe (3-8). Severe TBI: intubate if GCS <=8. Prevent secondary injury: maintain SBP >100, PaO2 >60, normothermia, head of bed 30°. CT head emergently. Neurosurgical consult for epidural/subdural hematoma, depressed skull fracture. ICP monitoring if GCS <=8.',
'Canadian Head CT Rules guide imaging decisions for mild TBI. In severe TBI, ICP target <22 mmHg, CPP 60-70 mmHg. Mannitol (0.25-1g/kg) or hypertonic saline (3%) for raised ICP. Avoid hypotension-single episode of SBP <90 doubles mortality.',5,'apply',['TBI','traumatic brain injury','GCS','neurosurgery','surgery']);

add('surg-trauma','What are the Canadian CT Head Rules for minor head injury?','CT indicated if GCS <15 at 2h, suspected open/depressed skull fracture, signs of basal skull fracture (raccoon eyes, Battle sign, hemotympanum, CSF leak), >=2 vomiting episodes, age >=65, amnesia before impact >=30 min, dangerous mechanism.',
'The Canadian CT Head Rule was developed and validated in Canadian EDs and has 100% sensitivity for neurosurgical intervention. It reduces unnecessary CT scans by ~40% compared to clinical judgment alone. Applies to GCS 13-15 with witnessed LOC, amnesia, or confusion.',3,'apply',['Canadian CT Head Rule','minor head injury','imaging','surgery']);

add('surg-trauma','What is the management of splenic injury by grade?','Grade I-II (hemodynamically stable): non-operative management with bed rest, serial Hb, serial imaging. Grade III (stable): non-operative + consider angioembolization. Grade IV-V (unstable or failed NOM): splenectomy. Post-splenectomy: vaccinate against encapsulated organisms (pneumococcus, meningococcus, H. influenzae).',
'Non-operative management is successful in >90% of hemodynamically stable patients. Canadian trauma centres use serial abdominal exams and Hb monitoring. Post-splenectomy patients receive lifelong pneumococcal prophylaxis and are educated about overwhelming post-splenectomy infection (OPSI).',4,'apply',['splenic injury','non-operative management','splenectomy','trauma','surgery']);

add('surg-trauma','What is the approach to penetrating neck trauma?','Zone I (clavicle to cricoid): CTA + angiography, high mortality. Zone II (cricoid to angle of mandible): traditionally surgical exploration if platysma violated, now selective with CTA. Zone III (above angle of mandible): CTA + angiography, difficult surgical access.',
'Modern approach in Canadian trauma centres favours CTA for all zones (no-zone approach). Hard signs (active hemorrhage, expanding hematoma, airway compromise, air bubbling) require immediate surgical exploration regardless of zone.',5,'apply',['penetrating neck trauma','zones','CTA','surgery']);

add('surg-trauma','What is the management of pelvic fractures in trauma?','Unstable patient: pelvic binder (sheet or commercial device), massive transfusion protocol, angioembolization for arterial bleeding, preperitoneal packing if available. Tile classification: Type A (stable), B (rotationally unstable), C (rotationally + vertically unstable).',
'Pelvic fractures can cause life-threatening hemorrhage (venous plexus in 80%, arterial in 20%). Canadian trauma guidelines recommend early pelvic binder in the field. CT with angiography guides embolization. Definitive fixation after stabilization.',5,'apply',['pelvic fracture','pelvic binder','trauma','surgery']);

add('surg-trauma','What are the indications for ED thoracotomy?','Penetrating thoracic trauma with witnessed cardiac arrest or rapid deterioration (survival up to 35%). Blunt trauma with cardiac arrest has very poor outcomes (<2% survival). Performed to: release pericardial tamponade, control cardiac/great vessel hemorrhage, cross-clamp descending aorta, open cardiac massage.',
'ED thoracotomy (resuscitative thoracotomy) is a last resort. Best outcomes with penetrating cardiac injury (stab > GSW). Canadian trauma centres have protocols defining inclusion criteria. Futile if >15 min CPR in penetrating or >10 min in blunt trauma.',5,'apply',['ED thoracotomy','resuscitative','cardiac arrest','trauma','surgery']);

add('surg-trauma','How are burns assessed and initially managed?','Rule of 9s for BSA (adult): head 9%, each arm 9%, anterior trunk 18%, posterior trunk 18%, each leg 18%, perineum 1%. Fluid resuscitation: Parkland formula = 4mL x kg x %BSA (give half in first 8h). Intubate early if inhalation injury suspected. Refer to burn centre if: >10% BSA, face/hands/feet/genitalia, electrical, chemical, inhalation injury.',
'The Parkland formula uses lactated Ringer and titrates to urine output 0.5-1 mL/kg/h. Canadian burn referral criteria follow ABA guidelines. Circumferential full-thickness burns require escharotomy to prevent compartment syndrome.',4,'apply',['burns','rule of nines','Parkland formula','trauma','surgery']);

add('surg-trauma','What is the management of tension pneumothorax?','Clinical diagnosis (do NOT wait for imaging): tracheal deviation away, absent breath sounds, JVD, hypotension, hyperresonance. Immediate needle decompression at 2nd ICS MCL (or 5th ICS AAL) with large-bore needle, followed by chest tube insertion.',
'Tension pneumothorax is immediately life-threatening and a primary survey diagnosis. In Canadian EDs, needle decompression is performed at 5th ICS AAL in some protocols due to greater chest wall thickness at 2nd ICS. Chest tube is the definitive treatment.',5,'apply',['tension pneumothorax','needle decompression','emergency','trauma','surgery']);

add('surg-trauma','What is the approach to C-spine clearance in trauma?','Canadian C-Spine Rule: no imaging needed if: GCS 15, no high-risk factors (age >=65, dangerous mechanism, paresthesias), >=1 low-risk factor (simple rear-end MVC, ambulatory, delayed neck pain, midline tenderness absent), AND able to actively rotate neck 45° left and right.',
'The Canadian C-Spine Rule (CCR) was developed in Canadian EDs and is superior to NEXUS criteria. CT is the imaging modality of choice (not plain films). MRI is used for suspected ligamentous injury with normal CT. CCR has 100% sensitivity for clinically significant C-spine injury.',3,'apply',['C-spine clearance','Canadian C-Spine Rule','trauma','surgery']);

// SURG-BREAST (10)
add('surg-breast','What is the BIRADS classification system and its clinical implications?','BIRADS 0: incomplete. 1: negative. 2: benign. 3: probably benign (<2% malignancy, 6-month follow-up). 4: suspicious (4A: 2-10%, 4B: 10-50%, 4C: 50-95%-all need biopsy). 5: highly suggestive of malignancy (>95%, biopsy). 6: known biopsy-proven malignancy.',
'BIRADS (Breast Imaging Reporting and Data System) standardizes mammographic reporting. Canadian radiologists use BIRADS to guide management. All BIRADS 4 and 5 lesions require tissue diagnosis (core needle biopsy preferred over FNA for solid masses).',3,'recall',['BIRADS','mammography','breast imaging','surgery']);

add('surg-breast','What is the Canadian breast cancer screening recommendation?','Average risk: mammography every 2-3 years for women aged 50-74 (CTFPHC, though recently updated). High risk (BRCA, prior chest radiation, >25% lifetime risk): annual mammography + MRI starting at 30. Self-exam not recommended as screening. Clinical breast exam has insufficient evidence.',
'CTFPHC guidelines differ from some international bodies that recommend starting at 40. The 2024 update moved toward screening from age 40. High-risk screening with MRI has higher sensitivity (>90%) than mammography alone (40-60%) in dense breast tissue.',3,'recall',['breast cancer screening','mammography','CTFPHC','surgery']);

add('surg-breast','What is the triple assessment for a breast lump?','(1) Clinical examination, (2) Imaging (mammogram for age >=30, ultrasound for age <30 or dense breasts), (3) Tissue sampling (core needle biopsy preferred, or FNA). All three must be concordant to rule out malignancy.',
'Triple assessment is the standard Canadian approach to breast lumps. Core biopsy is preferred over FNA as it provides histological architecture and receptor status (ER, PR, HER2). Discordant results require excisional biopsy.',3,'apply',['triple assessment','breast lump','biopsy','surgery']);

add('surg-breast','What are the surgical options for breast cancer and their indications?','Breast-conserving surgery (lumpectomy + radiation): equivalent survival to mastectomy for Stage I-II. Contraindications to BCS: multicentric disease, prior chest radiation, large tumor relative to breast, positive margins after re-excision, first/second trimester pregnancy. Sentinel lymph node biopsy: standard for clinically node-negative.',
'NSABP B-06 established equivalence of lumpectomy + radiation to mastectomy. Canadian guidelines follow NCCN. SLNB replaced axillary dissection for staging (ACOSOG Z0011: no completion ALND for 1-2 positive SLNs with BCS and planned radiation).',4,'apply',['breast surgery','lumpectomy','mastectomy','SLNB','surgery']);

add('surg-breast','What are the prognostic and predictive markers in breast cancer?','ER/PR: positive predicts response to endocrine therapy. HER2: positive predicts response to trastuzumab. Ki-67: proliferation index. Oncotype DX (21-gene recurrence score): guides chemotherapy decision in ER+/HER2- node-negative. Luminal A (ER+/HER2-/low Ki-67) has best prognosis. Triple-negative (ER-/PR-/HER2-) has worst.',
'Molecular subtyping guides adjuvant therapy in Canadian oncology practice. Oncotype DX is funded in most Canadian provinces for ER+/HER2-/node-negative or limited node-positive disease. TAILORx trial established that RS <25 does not benefit from chemotherapy.',4,'analyze',['breast cancer markers','ER','PR','HER2','Oncotype DX','surgery']);

add('surg-breast','What are the common benign breast conditions and their management?','Fibroadenoma: rubbery, mobile, well-circumscribed; observe if <2cm and age <35, excise if growing. Fibrocystic changes: cyclical pain and lumpiness, reassurance. Breast cyst: aspiration (non-bloody = reassurance, bloody = cytology). Fat necrosis: post-trauma, may mimic cancer. Intraductal papilloma: bloody nipple discharge, ductogram, excision.',
'Fibrocystic changes are the most common breast condition. Phyllodes tumor (cystosarcoma phylloides) requires wide excision with margins. Proliferative lesions with atypia (ADH, ALH) increase cancer risk 4-5x and require annual screening.',3,'recall',['benign breast disease','fibroadenoma','breast cyst','surgery']);

add('surg-breast','What is the approach to nipple discharge?','Pathological discharge: unilateral, spontaneous, single duct, bloody/serous. Workup: mammogram + ultrasound, duct excision if suspicious. Most common cause of bloody discharge: intraductal papilloma. Physiological discharge: bilateral, multi-duct, non-bloody-check prolactin and TSH.',
'Nipple discharge accounts for 5% of breast clinic referrals. Galactorrhea (milky bilateral discharge) in non-lactating women requires evaluation for hyperprolactinemia. Canadian guidelines recommend surgical duct excision for persistent pathological discharge.',3,'apply',['nipple discharge','intraductal papilloma','breast evaluation','surgery']);

add('surg-breast','What are the indications for genetic testing and prophylactic mastectomy in breast cancer?','BRCA1/2 testing: early-onset breast cancer (<40), triple-negative breast cancer, bilateral breast cancer, ovarian cancer, male breast cancer, strong family history. BRCA1 carriers: 60-80% lifetime breast cancer risk. Prophylactic bilateral mastectomy reduces risk by >95%.',
'Canadian guidelines (SOGC, CCMG) recommend genetic counseling for high-risk patients. Prophylactic bilateral salpingo-oophorectomy reduces breast and ovarian cancer risk in BRCA carriers. Risk-reducing mastectomy is a personal decision with extensive counseling.',4,'analyze',['BRCA','genetic testing','prophylactic mastectomy','surgery']);

add('surg-breast','What is the role of neoadjuvant chemotherapy in breast cancer?','Indications: locally advanced (Stage III), inflammatory breast cancer, large tumors to enable BCS, HER2+ or triple-negative subtypes. Benefits: downstaging for surgical options, in vivo chemosensitivity assessment, pathological complete response (pCR) is a prognostic marker.',
'Canadian oncology guidelines recommend neoadjuvant chemotherapy for inflammatory and locally advanced breast cancer. Achieving pCR (particularly in HER2+ and triple-negative) predicts excellent long-term outcomes. Residual disease guides escalation of adjuvant therapy.',4,'apply',['neoadjuvant chemotherapy','breast cancer','downstaging','surgery']);

add('surg-breast','What is the management of ductal carcinoma in situ (DCIS)?','Wide local excision (lumpectomy) with clear margins + whole breast radiation. Mastectomy for extensive DCIS. SLNB for mastectomy or large DCIS (occult invasion in 10-20%). Endocrine therapy (tamoxifen) reduces ipsilateral and contralateral recurrence. Van Nuys Prognostic Index guides management.',
'DCIS accounts for 20-25% of screen-detected breast cancers in Canadian programs. Without treatment, 30-50% progress to invasive cancer over 10-20 years. Radiation after BCS reduces local recurrence by 50%. Observation alone may be considered for low-risk DCIS.',4,'apply',['DCIS','ductal carcinoma in situ','breast conservation','surgery']);

// SURG-PERIOP (10)
add('surg-periop','What is the ASA Physical Status classification?','ASA I: healthy. ASA II: mild systemic disease (e.g., controlled HTN, BMI 30-40, smoker). ASA III: severe systemic disease (e.g., poorly controlled DM, COPD, BMI >=40, active hepatitis, EF 20-40%). ASA IV: severe life-threatening disease (e.g., recent MI <3 months, sepsis, DIC). ASA V: moribund. ASA VI: brain-dead organ donor.',
'ASA classification is the most widely used preoperative risk stratification tool. It predicts perioperative mortality and complications. Canadian anesthesia guidelines use ASA class to guide monitoring requirements and postoperative disposition.',3,'recall',['ASA classification','preoperative assessment','perioperative','surgery']);

add('surg-periop','What is the Revised Cardiac Risk Index (RCRI) and how does it guide preoperative cardiac evaluation?','RCRI (Lee index): 6 factors each scoring 1 point: high-risk surgery, history of IHD, history of CHF, history of cerebrovascular disease, insulin-dependent DM, creatinine >177 umol/L. Score 0: 0.4% risk of MACE. 1: 0.9%. 2: 6.6%. >=3: 11% MACE risk.',
'RCRI guides whether additional cardiac testing is needed per CCS perioperative guidelines. Patients with RCRI >=1 having elevated-risk surgery should have NT-proBNP measured. If elevated, cardiac risk assessment and potentially further testing or management optimization.',4,'apply',['RCRI','cardiac risk','preoperative','perioperative','surgery']);

add('surg-periop','What are the current guidelines for perioperative VTE prophylaxis?','Low risk (minor surgery, mobile): early ambulation. Moderate risk (most general surgery): LMWH (enoxaparin 40mg SC daily) or UFH 5000U SC BID-TID. High risk (major orthopedic, cancer surgery): LMWH + mechanical prophylaxis (IPC). Duration: until fully mobile, or 28-35 days for hip/knee arthroplasty and cancer surgery.',
'Canadian guidelines (Thrombosis Canada) recommend pharmacological VTE prophylaxis for most surgical inpatients. DOACs (rivaroxaban) are alternatives for orthopedic prophylaxis. Bleeding risk must be balanced against thrombotic risk using Caprini or Padua scores.',4,'apply',['VTE prophylaxis','DVT prevention','enoxaparin','perioperative','surgery']);

add('surg-periop','How should anticoagulants and antiplatelets be managed perioperatively?','Warfarin: stop 5 days pre-op, bridge with LMWH if high thrombotic risk (mechanical valve, recent VTE). DOACs: stop 1-2 days (renal-dependent for dabigatran, up to 4 days if CrCl <50). ASA: continue for most surgeries unless high bleeding risk. DAPT: defer elective surgery until completed (6-12 months post-stent); if urgent, continue ASA, hold P2Y12 inhibitor 5-7 days.',
'CCS perioperative anticoagulation guidelines provide detailed bridging recommendations. High thrombotic risk patients (CHA2DS2-VASc >=7, mechanical mitral valve, VTE <3 months) warrant LMWH bridging. Most DOAC patients do not need bridging due to short half-lives.',5,'apply',['anticoagulation','perioperative','bridging','DOAC','surgery']);

add('surg-periop','What preoperative investigations are indicated for healthy patients undergoing elective surgery?','No routine preoperative testing for healthy patients (ASA I-II) undergoing low-risk surgery per Choosing Wisely Canada. Indicated tests based on clinical factors: ECG if cardiac risk factors, CBC if expected blood loss, Cr if nephrotoxic medications or renal disease, glucose if DM, coagulation if anticoagulant use or liver disease.',
'Choosing Wisely Canada specifically recommends against routine preoperative tests (CBC, electrolytes, CXR, ECG) in healthy patients undergoing low-risk surgery. This reduces healthcare costs and avoids false-positive results leading to unnecessary investigations.',3,'apply',['preoperative testing','Choosing Wisely','investigations','perioperative','surgery']);

add('surg-periop','What are the guidelines for perioperative management of diabetes?','Day of surgery: hold oral hypoglycemics and non-insulin injectables. Type 1 DM: never discontinue basal insulin (reduce to 60-80% of usual dose). Type 2 on insulin: reduce basal by 50-75%. Target glucose 6-10 mmol/L intraoperatively. Hold metformin day of surgery (restart when eating and renal function normal). Hold SGLT2 inhibitors 3 days pre-op (DKA risk).',
'Canadian Diabetes Association guidelines address perioperative glycemic management. SGLT2 inhibitor-associated euglycemic DKA is an increasingly recognized perioperative risk. Insulin infusion protocols are used for major surgeries. Hyperglycemia >10 mmol/L increases surgical site infection risk.',4,'apply',['diabetes perioperative','insulin management','SGLT2','surgery']);

add('surg-periop','What is enhanced recovery after surgery (ERAS) and its key components?','ERAS protocols include: preoperative-carbohydrate loading (clear fluids 2h pre-op), no routine bowel prep, multimodal analgesia planning. Intraoperative-goal-directed fluid therapy, normothermia, minimally invasive approach when possible. Postoperative-early oral intake, early mobilization, multimodal analgesia (minimize opioids), early catheter removal.',
'ERAS protocols reduce hospital stay by 2-3 days and reduce complications by 30-40%. Widely adopted in Canadian surgical centres, particularly for colorectal surgery. Key principle is reducing surgical stress response through evidence-based interventions at each phase.',3,'apply',['ERAS','enhanced recovery','perioperative care','surgery']);

add('surg-periop','What is the WHO Surgical Safety Checklist and when are its phases performed?','Three phases: (1) Sign-in (before induction): patient identity, procedure, consent, site marking, known allergies, airway assessment, blood loss risk. (2) Time-out (before incision): team introductions, confirm patient/procedure/site, antibiotic prophylaxis given, anticipated critical events. (3) Sign-out (before leaving OR): procedure name confirmed, instrument/sponge count, specimen labeling, equipment concerns, recovery plan.',
'The WHO Surgical Safety Checklist reduces surgical mortality by 47% and complications by 36% (Haynes et al). Mandatory in Canadian hospitals since adoption by CPSI. Based on aviation safety checklists. Non-compliance is a patient safety concern.',2,'recall',['WHO Surgical Safety Checklist','patient safety','perioperative','surgery']);

add('surg-periop','How should perioperative antibiotic prophylaxis be administered?','Within 60 minutes of incision (120 min for vancomycin/fluoroquinolones). Cefazolin 2g IV (3g if >120kg) is standard for most clean/clean-contaminated cases. Redose q3-4h if prolonged surgery. Discontinue within 24h post-op. Add metronidazole for colorectal. Vancomycin for MRSA risk or beta-lactam allergy.',
'Canadian guidelines (Bugs & Drugs) and Surgical Care Improvement Project (SCIP) metrics define appropriate prophylaxis. Timely antibiotic administration is the single most effective measure to reduce SSI. Weight-based dosing is essential for optimal tissue concentrations.',3,'apply',['antibiotic prophylaxis','surgical infection','cefazolin','perioperative','surgery']);

add('surg-periop','What are the risk factors and prevention strategies for postoperative complications?','SSI: obesity, diabetes, smoking, prolonged surgery-prevention with antibiotics, normothermia, glucose control. Pneumonia: age, COPD, upper abdominal surgery-prevention with incentive spirometry, early mobilization. Delirium: age >65, cognitive impairment, polypharmacy-prevention with orientation, sleep hygiene, avoid benzodiazepines.',
'Postoperative delirium occurs in 15-50% of elderly surgical patients and increases mortality, LOS, and institutionalization. Canadian Patient Safety Institute identifies SSI and VTE as key preventable surgical complications. Multimodal prehabilitation reduces complications.',4,'apply',['postoperative complications','SSI prevention','delirium','perioperative','surgery']);

fs.writeFileSync('C:/dev/srs-mccqe1/data/_surg_cards.json', JSON.stringify(cards, null, 2));
console.log('Surgery cards written:', cards.length);
