const crypto = require('crypto');
function id(q) { return 'card-' + crypto.createHash('sha256').update(q.trim().toLowerCase()).digest('hex').slice(0,12); }
const cards = [];
function add(topicId, question, answer, explanation, difficulty, bloomLevel, tags) {
  cards.push({ id: id(question), question, answer, explanation, difficulty, bloomLevel, tags, topicId });
}

// peds-neonate (need 27)
add('peds-neonate','What is the Apgar score and when is it assessed?','Scored at 1 and 5 minutes: Appearance (color), Pulse (HR), Grimace (reflex), Activity (tone), Respiration; each 0-2; total 0-10; 7-10 normal, 4-6 moderate depression, 0-3 severe','Apgar does not predict long-term outcome or guide resuscitation (NRP should begin before 1-min Apgar). Low 5-min Apgar correlates with neonatal mortality. Extended Apgar at 10, 15, 20 min for ongoing resuscitation.',1,'recall',['Apgar','neonatal-assessment','resuscitation','scoring']);
add('peds-neonate','What are the steps of neonatal resuscitation per NRP?','Warm, dry, stimulate → assess HR and breathing → if HR<100 or apneic: PPV with room air → if HR<60 after 30s PPV: chest compressions (3:1 ratio) → if HR<60 after 60s compressions: epinephrine (0.01-0.03 mg/kg IV)','NRP 2021: start with room air (21% FiO2) for term infants; 21-30% for preterm <35 weeks. Target SpO2: 60-65% at 1 min, 85-95% by 10 min. Most newborns respond to effective ventilation alone — ventilation is the most critical step.',3,'apply',['NRP','neonatal-resuscitation','PPV','epinephrine','room-air']);
add('peds-neonate','What is neonatal jaundice and when is it pathological?','Physiological: onset day 2-3, peaks day 3-5, resolves by 2 weeks; Pathological: onset <24 hours (hemolysis), bilirubin rising >85 µmol/L/day, total bilirubin exceeds phototherapy threshold, or persists >2 weeks','Causes of pathological jaundice: ABO/Rh incompatibility, G6PD deficiency, spherocytosis, sepsis, hypothyroidism, breast milk jaundice, biliary atresia (conjugated). Treatment: phototherapy or exchange transfusion per bilirubin nomogram.',3,'apply',['neonatal-jaundice','bilirubin','phototherapy','hemolysis','biliary-atresia']);
add('peds-neonate','What is the most dangerous cause of neonatal jaundice in the first 24 hours?','Hemolytic disease of the newborn (Rh or ABO incompatibility); can cause rapidly rising unconjugated bilirubin leading to kernicterus (bilirubin encephalopathy)','Rh disease: Rh-negative mother sensitized to Rh-positive fetal RBCs; prevented by RhIG (anti-D) at 28 weeks and within 72h of delivery. ABO incompatibility (mother O, baby A/B): usually milder. Direct Coombs test positive in both.',4,'analyze',['hemolytic-disease','Rh-incompatibility','kernicterus','Coombs-test','RhIG']);
add('peds-neonate','What is necrotizing enterocolitis (NEC) and which neonates are at highest risk?','Inflammatory bowel necrosis in neonates; presents with feeding intolerance, abdominal distension, bloody stools, pneumatosis intestinalis on X-ray; highest risk in premature infants <32 weeks','Risk factors: prematurity (strongest), formula feeding (breast milk is protective), hypoxia, sepsis. Treatment: NPO, IV antibiotics (ampicillin + gentamicin + metronidazole), NG decompression. Surgery for perforation (pneumoperitoneum) or clinical deterioration.',4,'analyze',['NEC','necrotizing-enterocolitis','prematurity','pneumatosis-intestinalis','breast-milk']);
add('peds-neonate','What is respiratory distress syndrome (RDS) in neonates?','Surfactant deficiency in premature lungs causing atelectasis, hypoxemia, and respiratory failure; CXR shows diffuse ground-glass opacities with air bronchograms; onset within hours of birth','Prevention: antenatal corticosteroids (betamethasone 12 mg IM × 2 doses, 24h apart) for preterm labor <34 weeks. Treatment: CPAP or intubation with exogenous surfactant (poractant alfa, beractant). More common at earlier gestational ages.',3,'apply',['RDS','surfactant','prematurity','antenatal-corticosteroids','CPAP']);
add('peds-neonate','What is transient tachypnea of the newborn (TTN)?','Delayed clearance of fetal lung fluid; presents within hours of birth with tachypnea (RR >60), mild retractions, and grunting; CXR shows fluid in fissures, perihilar streaking; resolves in 24-72h','TTN is most common in term/late preterm infants born by cesarean section (no thoracic squeeze). Self-limiting; supportive care (O2, feeding support). Distinguished from RDS (more severe, premature) and pneumonia (fever, WBC).',2,'recall',['TTN','transient-tachypnea','cesarean','fetal-lung-fluid','self-limiting']);
add('peds-neonate','What are the components of the newborn metabolic screening in Canada?','Heel-prick blood spot at 24-72 hours of age; screens for ~30 conditions including PKU, congenital hypothyroidism, galactosemia, cystic fibrosis, sickle cell disease, MCAD deficiency, CAH','Provincial programs vary slightly in conditions screened. Tandem mass spectrometry enables detection of amino acid, fatty acid oxidation, and organic acid disorders. Congenital hypothyroidism is most common (1:3000); treated with levothyroxine within 2 weeks to prevent intellectual disability.',2,'recall',['newborn-screening','PKU','congenital-hypothyroidism','heel-prick','metabolic']);
add('peds-neonate','What is meconium aspiration syndrome (MAS)?','Aspiration of meconium-stained amniotic fluid causing airway obstruction, chemical pneumonitis, and surfactant inactivation; presents with respiratory distress in term/post-term infants','CXR: patchy bilateral infiltrates, hyperinflation, pneumothorax risk. Management: intubation and suctioning only if vigorous (current NRP: routine suctioning not recommended even for non-vigorous); supportive care, surfactant, ECMO for severe cases.',3,'apply',['MAS','meconium','aspiration','post-term','NRP']);
add('peds-neonate','What is congenital hip dysplasia (DDH) and how is it screened?','Developmental dysplasia of the hip: spectrum from subluxation to complete dislocation; screen with Ortolani (reduces dislocated hip) and Barlow (dislocates unstable hip) maneuvers at birth and well-child visits','Risk factors: breech presentation, female sex, family history, first-born. Ultrasound at 6 weeks if risk factors or abnormal exam. Treatment: Pavlik harness (before 6 months) for immobilization in flexion/abduction. Late diagnosis: surgical reduction.',2,'recall',['DDH','hip-dysplasia','Ortolani','Barlow','Pavlik-harness']);
add('peds-neonate','What are the features of fetal alcohol spectrum disorder (FASD)?','Spectrum of effects from prenatal alcohol exposure: characteristic facial features (smooth philtrum, thin upper lip, short palpebral fissures), growth restriction, CNS dysfunction (intellectual disability, behavioral problems, learning difficulties)','FASD is the leading preventable cause of intellectual disability in Canada. No safe level of alcohol in pregnancy. Diagnosis requires documented prenatal alcohol exposure and clinical criteria. Multidisciplinary assessment. No cure — early intervention improves outcomes.',3,'apply',['FASD','fetal-alcohol','facial-features','intellectual-disability','prevention']);
add('peds-neonate','What is neonatal sepsis and how is it classified?','Early-onset (<72h): Group B Streptococcus, E. coli — acquired during delivery; Late-onset (>72h): CoNS, S. aureus, gram-negatives — nosocomial; presents with temperature instability, poor feeding, lethargy, respiratory distress','GBS screening at 35-37 weeks with intrapartum antibiotic prophylaxis (IAP) for positive carriers. Empiric treatment early-onset: ampicillin + gentamicin. Late-onset: vancomycin + gentamicin (or cefotaxime). Blood culture before antibiotics.',3,'apply',['neonatal-sepsis','GBS','early-onset','late-onset','ampicillin-gentamicin']);
add('peds-neonate','What is retinopathy of prematurity (ROP) and who should be screened?','Abnormal retinal vascular proliferation in premature infants due to oxygen exposure; can cause retinal detachment and blindness; screen all infants <31 weeks or <1500g birth weight','First exam at 4-6 weeks postnatal age or 31 weeks corrected gestational age. Stages 1-5 based on severity. Treatment: laser photocoagulation or intravitreal anti-VEGF (bevacizumab) for threshold disease. Controlled oxygen targeting reduces ROP.',3,'apply',['ROP','retinopathy','prematurity','screening','anti-VEGF']);
add('peds-neonate','What are the cardinal signs of congenital heart disease in neonates?','Cyanosis (especially not improving with O2), tachypnea, poor feeding, failure to thrive, heart murmur, differential oxygen saturation (pre/post-ductal); critical CHD may present with cardiovascular collapse at ductus closure','Pulse oximetry screening at 24-48h: SpO2 <95% or >3% difference between extremities is positive. Prostaglandin E1 (PGE1) infusion to maintain ductal patency in duct-dependent lesions (TGA, coarctation, HLHS). Echocardiography for diagnosis.',3,'apply',['congenital-heart-disease','cyanosis','pulse-oximetry','PGE1','duct-dependent']);
add('peds-neonate','What is hypoxic-ischemic encephalopathy (HIE) and how is it treated?','Brain injury from perinatal asphyxia; Sarnat staging: Stage 1 (mild — hyperalert), Stage 2 (moderate — lethargy, seizures), Stage 3 (severe — coma, absent reflexes); treatment: therapeutic hypothermia','Therapeutic hypothermia (33.5°C for 72 hours) within 6 hours of birth improves survival and neurodevelopmental outcomes in moderate-severe HIE. Criteria: gestational age ≥36 weeks, evidence of perinatal asphyxia, clinical encephalopathy.',4,'analyze',['HIE','perinatal-asphyxia','therapeutic-hypothermia','Sarnat','neonatal']);
add('peds-neonate','What is the management of neonatal hypoglycemia?','At-risk infants (LGA, SGA, IDM, preterm): check glucose at 2h of age then before feeds; symptomatic hypoglycemia (<2.6 mmol/L): IV dextrose (D10W 2 mL/kg bolus); asymptomatic: feed and recheck','Risk factors for neonatal hypoglycemia: infant of diabetic mother (IDM — fetal hyperinsulinism), SGA (decreased glycogen stores), LGA, preterm, cold stress, sepsis. Target glucose >2.6 mmol/L. Persistent hypoglycemia: evaluate for hyperinsulinism, metabolic/endocrine disorders.',3,'apply',['neonatal-hypoglycemia','IDM','dextrose','SGA','hyperinsulinism']);
add('peds-neonate','What are the differences between caput succedaneum and cephalohematoma?','Caput: edema of scalp crossing suture lines, present at birth, resolves 24-48h; Cephalohematoma: subperiosteal hemorrhage limited by suture lines, appears hours after birth, resolves weeks-months','Caput is benign and needs no treatment. Cephalohematoma may cause jaundice (as blood resorbs) and rarely calcifies. Subgaleal hemorrhage (between periosteum and aponeurosis) is an emergency — can cross sutures and accumulate massive blood loss.',2,'recall',['caput-succedaneum','cephalohematoma','subgaleal','birth-injury','suture-lines']);
add('peds-neonate','What is biliary atresia and how does it present?','Progressive obliteration of extrahepatic bile ducts; presents with prolonged conjugated jaundice (>2 weeks), pale/acholic stools, dark urine, hepatomegaly in an otherwise well infant','Biliary atresia is the most common indication for liver transplantation in children. Conjugated (direct) bilirubin >17 µmol/L or >20% of total is always pathological. Diagnose with ultrasound, HIDA scan, liver biopsy. Kasai portoenterostomy before 60 days of age improves outcomes.',4,'analyze',['biliary-atresia','conjugated-jaundice','acholic-stools','Kasai','liver-transplant']);
add('peds-neonate','What is the appropriate management of an infant born to an HBV-positive mother?','Hepatitis B immunoglobulin (HBIG) + first dose of hepatitis B vaccine within 12 hours of birth; complete the 3-dose series; check HBsAg and anti-HBs at 9-12 months to confirm protection','This regimen is 85-95% effective in preventing vertical HBV transmission. Breastfeeding is safe after immunoprophylaxis. If mother is HBeAg-positive (high viral load), consider maternal tenofovir in third trimester to reduce transmission further.',3,'apply',['hepatitis-B','vertical-transmission','HBIG','vaccination','neonatal']);
add('peds-neonate','What is pyloric stenosis and how does it present?','Hypertrophy of the pyloric sphincter causing gastric outlet obstruction; presents at 2-6 weeks with projectile non-bilious vomiting, hungry infant, palpable "olive" mass in RUQ; metabolic alkalosis','More common in firstborn males. Diagnosis: ultrasound showing pyloric muscle thickness >3 mm and length >15 mm. Lab: hypochloremic hypokalemic metabolic alkalosis. Treatment: correct electrolytes first, then pyloromyotomy (Ramstedt).',3,'apply',['pyloric-stenosis','projectile-vomiting','olive-mass','metabolic-alkalosis','pyloromyotomy']);
add('peds-neonate','What is the significance of single umbilical artery?','Normal: 2 arteries + 1 vein (AVA); single umbilical artery (SUA) found in 1% of births; associated with renal anomalies, cardiac defects, and chromosomal abnormalities; warrants renal ultrasound','SUA is often an isolated finding with good prognosis. However, when found with other anomalies, it increases risk of trisomy 18. Prenatal detection on ultrasound prompts detailed anatomical survey and postnatal renal ultrasound.',2,'recall',['single-umbilical-artery','SUA','renal-anomaly','chromosomal','umbilical-cord']);
add('peds-neonate','What are the features of neonatal abstinence syndrome (NAS)?','Withdrawal symptoms in neonates exposed to opioids in utero; onset 24-72h after birth; irritability, high-pitched cry, tremors, hypertonicity, poor feeding, sneezing, diarrhea, seizures (rare)','Scoring with Finnegan Neonatal Abstinence Scoring System guides treatment. First-line: supportive care (swaddling, reduced stimulation, breastfeeding if appropriate). Pharmacological: morphine or methadone for severe symptoms (Finnegan score consistently ≥8).',3,'apply',['NAS','neonatal-abstinence','opioid','Finnegan','withdrawal']);
add('peds-neonate','What is the normal weight loss pattern in a healthy term newborn?','Up to 7-10% weight loss in first 3-5 days is normal; should regain birth weight by 10-14 days; subsequent gain ~20-30 g/day for first 3 months','Weight loss >10% or failure to regain by 2 weeks warrants evaluation: feeding assessment, hydration status, underlying illness. Breastfed infants lose slightly more than formula-fed. Lactation consultant referral if breastfeeding difficulties.',1,'recall',['neonatal-weight','growth','breastfeeding','weight-loss','normal']);
add('peds-neonate','What congenital infections comprise the TORCH screen?','Toxoplasmosis, Other (syphilis, varicella, parvovirus B19), Rubella, Cytomegalovirus, Herpes simplex; present with IUGR, hepatosplenomegaly, jaundice, rash, microcephaly, intracranial calcifications','CMV is the most common congenital infection (1% of births); most are asymptomatic. Congenital syphilis: snuffles, rash, hepatosplenomegaly, osteochondritis. Congenital rubella: cataracts, deafness, PDA. HSV: vesicles, encephalitis, disseminated disease.',3,'apply',['TORCH','congenital-infection','CMV','syphilis','rubella']);
add('peds-neonate','What is the management of a term infant with persistent pulmonary hypertension (PPHN)?','Persistent elevation of pulmonary vascular resistance after birth causing right-to-left shunting through PDA/foramen ovale; hypoxemia resistant to O2; treatment: inhaled nitric oxide (iNO), ECMO for refractory cases','PPHN causes: MAS, RDS, sepsis, CDH, idiopathic. Diagnosis: >10% SpO2 difference between pre- and post-ductal measurements. Echocardiography confirms elevated PA pressures. Supportive: maintain systemic BP, correct acidosis, minimize stimulation.',4,'analyze',['PPHN','pulmonary-hypertension','inhaled-nitric-oxide','ECMO','right-to-left-shunt']);
add('peds-neonate','What are the indications for phototherapy in neonatal jaundice?','Based on total serum bilirubin (TSB) plotted against age in hours on the phototherapy nomogram (Bhutani/AAP); thresholds are lower for preterm, sick, or hemolysis-affected infants','Phototherapy converts unconjugated bilirubin to water-soluble photoisomers excreted without conjugation. Intensive phototherapy (30+ µW/cm²/nm): blue LED lights, maximize skin exposure. Exchange transfusion if bilirubin exceeds exchange threshold or rises despite intensive phototherapy.',3,'apply',['phototherapy','jaundice','bilirubin-nomogram','exchange-transfusion','Bhutani']);
add('peds-neonate','What is the vitamin K injection given at birth and why?','Vitamin K1 (phytonadione) 0.5-1 mg IM at birth to prevent hemorrhagic disease of the newborn (vitamin K deficiency bleeding — VKDB); neonates have low vitamin K stores and sterile gut','VKDB: early (<24h, maternal drugs), classic (days 2-7, GI/umbilical bleeding), late (2-12 weeks, intracranial hemorrhage). IM injection is preferred over oral (more reliable absorption). Refusal of vitamin K increases VKDB risk 80-fold.',2,'recall',['vitamin-K','VKDB','hemorrhagic-disease','phytonadione','prophylaxis']);

// peds-fever (need 29)
add('peds-fever','What is the definition of fever in pediatrics?','Temperature ≥38.0°C (100.4°F) rectally; rectal is gold standard in infants <3 months; tympanic and temporal acceptable in older children','Fever itself is rarely harmful (brain damage does not occur until >41.5°C). Fever phobia among parents is common. Antipyretics improve comfort but do not prevent febrile seizures. Alternating acetaminophen and ibuprofen is not routinely recommended.',1,'recall',['fever','pediatric','temperature','rectal-thermometer','definition']);
add('peds-fever','What is the approach to a febrile neonate (<28 days)?','Full septic workup (blood culture, urine culture via catheterization, LP with CSF analysis), IV antibiotics empirically (ampicillin + gentamicin or cefotaxime); hospitalize all febrile neonates','Neonates are immunologically immature and cannot localize infection. Serious bacterial infection (SBI) risk: 10-15% in febrile neonates. HSV should be considered (acyclovir if risk factors). Step-down clinical rules do NOT apply to <28 days.',4,'analyze',['febrile-neonate','septic-workup','LP','ampicillin','empiric-antibiotics']);
add('peds-fever','How does the approach to fever differ for infants 29-90 days old?','Apply validated clinical decision rules (Rochester, Philadelphia, Boston, or Step-by-Step); low-risk criteria: well-appearing, no focal infection, normal WBC (5-15), normal urinalysis; low-risk may be managed as outpatient with close follow-up','High-risk features: ill-appearing, prematurity, recent antibiotics, WBC <5 or >15, elevated procalcitonin (>0.5). UTI is the most common SBI in this age group. Blood and urine cultures for all; LP if any high-risk feature.',4,'analyze',['febrile-infant','Rochester-criteria','risk-stratification','SBI','procalcitonin']);
add('peds-fever','What is the most common serious bacterial infection in febrile infants 2-24 months?','Urinary tract infection (UTI) — prevalence 5-7% in febrile infants; higher in uncircumcised males <6 months and females','AAP guidelines: obtain urine (catheterization or suprapubic aspiration, NOT bag specimen for culture) in febrile infants <24 months with no identifiable source. Diagnosis: positive UA (pyuria, nitrites) + culture (>50,000 CFU/mL from catheter). E. coli most common.',3,'apply',['UTI','febrile-infant','urine-culture','E-coli','catheterization']);
add('peds-fever','What is Kawasaki disease and its diagnostic criteria?','Febrile vasculitis in children <5 years; ≥5 days fever PLUS ≥4 of: bilateral non-exudative conjunctivitis, oral changes (cracked lips, strawberry tongue), rash, extremity changes (edema, desquamation), cervical lymphadenopathy (≥1.5 cm)','Coronary artery aneurysms develop in 25% untreated (vs <5% with treatment). Treatment: IVIG 2 g/kg single dose + high-dose ASA; then low-dose ASA for 6-8 weeks. Echocardiography at diagnosis, 2 weeks, and 6-8 weeks. Incomplete Kawasaki possible with <4 criteria.',4,'analyze',['Kawasaki','vasculitis','coronary-aneurysm','IVIG','strawberry-tongue']);
add('peds-fever','What are febrile seizures and how are they classified?','Simple: generalized, <15 minutes, single in 24h, age 6 months-5 years; Complex: focal, >15 minutes, recurrent in 24h, or with postictal focal deficits; occur in 2-5% of children','Simple febrile seizures are benign — no increased epilepsy risk, no workup beyond identifying fever source. Complex febrile seizures: consider EEG. No anticonvulsant prophylaxis recommended for either type. LP only if meningitis suspected.',3,'apply',['febrile-seizure','simple','complex','children','benign']);
add('peds-fever','What is roseola (exanthem subitum) and how does it present?','HHV-6 infection in children 6 months-2 years; 3-5 days of high fever (up to 40.5°C) then sudden defervescence followed by diffuse macular/maculopapular rash lasting 1-2 days','Classic sequence: fever first, rash after fever breaks (distinguishing feature). Most common cause of febrile seizures in infancy (due to rapid temperature rise). Self-limiting, no treatment needed. Rash starts on trunk and spreads peripherally.',2,'recall',['roseola','HHV-6','exanthem-subitum','fever-then-rash','febrile-seizure']);
add('peds-fever','What is the approach to recurrent fever in children?','Consider: periodic fever syndromes (PFAPA — Periodic Fever, Aphthous stomatitis, Pharyngitis, Adenitis), familial Mediterranean fever, cyclic neutropenia, immunodeficiency, occult infections, malignancy','PFAPA is the most common periodic fever syndrome in children. Episodes last 3-6 days, occur every 3-8 weeks. Dramatic response to single dose of prednisone. Tonsillectomy is curative in many cases. FMF: colchicine prophylaxis.',3,'apply',['recurrent-fever','PFAPA','FMF','periodic-fever','children']);
add('peds-fever','What childhood exanthems are commonly associated with fever?','Measles (cough, coryza, conjunctivitis, Koplik spots → maculopapular rash), scarlet fever (sandpaper rash, pastia lines, strep), varicella (vesicular crops), fifth disease (parvovirus B19 — slapped cheek)','Hand-foot-mouth disease (Coxsackie A16, enterovirus 71): oral ulcers + vesicular rash on hands/feet. Rubella: maculopapular rash with lymphadenopathy. Measles: descending rash, high fever, vitamin A treatment.',2,'recall',['exanthems','measles','scarlet-fever','varicella','fifth-disease']);
add('peds-fever','What is the empiric antibiotic choice for bacterial meningitis in a child 1-3 months?','Ampicillin (for Listeria coverage) + cefotaxime (or ceftriaxone if >28 days); add dexamethasone if H. influenzae suspected; add acyclovir if HSV encephalitis suspected','Organisms: GBS, E. coli, Listeria (in neonates/young infants); S. pneumoniae, N. meningitidis (in older infants/children). LP before antibiotics if possible, but do not delay treatment. Dexamethasone 0.15 mg/kg q6h × 4 days for bacterial meningitis.',3,'apply',['meningitis','ampicillin','cefotaxime','empiric','pediatric']);
add('peds-fever','What is occult bacteremia and is it still a concern in the post-vaccine era?','Bacteremia without an obvious focus; historically S. pneumoniae in children 3-36 months with high fever; risk dramatically reduced by PCV13 and Hib vaccines; now rare (<0.5%)','Prior to conjugate vaccines, 3-5% of febrile children 3-36 months had occult bacteremia. PCV13 and Hib vaccines have made this uncommon. UTI is now the main concern for occult SBI. Blood cultures still indicated if high fever with no source in under-immunized children.',3,'apply',['occult-bacteremia','PCV13','conjugate-vaccine','febrile-child','blood-culture']);
add('peds-fever','What is the appropriate use of antipyretics in children?','Acetaminophen 15 mg/kg q4-6h (max 5 doses/day) or ibuprofen 10 mg/kg q6-8h (>6 months old); goal is comfort, not normalization of temperature; avoid ASA in children (Reye syndrome)','Ibuprofen is slightly more effective than acetaminophen for fever reduction. Alternating is not routinely recommended (confusion, dosing errors). Tepid sponging is not recommended. Cold baths are contraindicated. Dress lightly, maintain hydration.',2,'recall',['antipyretic','acetaminophen','ibuprofen','Reye-syndrome','pediatric-fever']);
add('peds-fever','What is periorbital vs. orbital cellulitis in children?','Periorbital (preseptal): eyelid erythema/swelling anterior to orbital septum, minimal pain, no proptosis; Orbital (postseptal): proptosis, pain with eye movement, ophthalmoplegia, decreased visual acuity — emergency','Orbital cellulitis is most commonly a complication of ethmoid sinusitis. CT orbit with contrast differentiates preseptal from orbital. Orbital cellulitis: IV antibiotics (ampicillin-sulbactam or ceftriaxone + metronidazole), ENT/ophthalmology consult, may need surgical drainage.',4,'analyze',['periorbital-cellulitis','orbital-cellulitis','sinusitis','CT-orbit','emergency']);
add('peds-fever','What is the presentation and management of pediatric urinary tract infection?','Infants: fever, irritability, poor feeding, vomiting; older children: dysuria, frequency, urgency, abdominal/flank pain; E. coli >80%; oral antibiotics (cephalexin, TMP-SMX) for uncomplicated; IV for pyelonephritis in young infants','Renal ultrasound after first febrile UTI in children <2 years. VCUG (voiding cystourethrogram) for recurrent UTIs or abnormal ultrasound to evaluate for vesicoureteral reflux (VUR). Antibiotic prophylaxis for high-grade VUR is debated.',3,'apply',['UTI','pediatric','E-coli','renal-ultrasound','VUR']);
add('peds-fever','What is the characteristic presentation of scarlet fever?','Group A Streptococcus pharyngitis with diffuse erythematous sandpaper-like rash (sparing face but with circumoral pallor), strawberry tongue, Pastia lines (accentuation in skin folds), desquamation during recovery','Treatment: penicillin V or amoxicillin for 10 days (prevents rheumatic fever). Rapid strep test + throat culture. Complications if untreated: rheumatic fever (2-4 weeks post), post-streptococcal glomerulonephritis (1-3 weeks post).',2,'recall',['scarlet-fever','GAS','sandpaper-rash','strawberry-tongue','penicillin']);
add('peds-fever','What is the evaluation of lymphadenopathy in a febrile child?','Most commonly reactive (viral URI); concerning features: node >2 cm, supraclavicular location, fixed/non-tender, persisting >4-6 weeks, systemic symptoms (weight loss, night sweats); biopsy if suspicious for malignancy','Common causes: viral URI (bilateral, small, tender), EBV/CMV (generalized), cat-scratch disease (Bartonella — unilateral, post-cat exposure), mycobacterial, lymphoma (painless, rubbery, supraclavicular). CBC, blood smear, LDH, ESR help narrow differential.',3,'apply',['lymphadenopathy','febrile-child','malignancy','EBV','cat-scratch']);
add('peds-fever','What is croup (laryngotracheobronchitis) and how is it managed?','Viral URI (parainfluenza most common) causing subglottic edema; 6 months-3 years; barking cough, inspiratory stridor, hoarse voice; steeple sign on AP neck X-ray; worse at night','Mild: cool mist, comfort measures. Moderate: single dose dexamethasone 0.6 mg/kg PO/IM (even mild croup benefits). Severe (stridor at rest): nebulized racemic epinephrine (temporary relief, observe 2-4h for rebound) + dexamethasone. Rarely requires intubation.',3,'apply',['croup','parainfluenza','stridor','dexamethasone','racemic-epinephrine']);
add('peds-fever','What is epiglottitis and how does it differ from croup?','Bacterial infection (H. influenzae type b — now rare with Hib vaccine) causing supraglottic swelling; toxic-appearing child with drooling, tripod position, muffled voice, high fever, sore throat; thumbprint sign on lateral neck X-ray','Epiglottitis is an emergency — do NOT examine oropharynx (can cause complete airway obstruction). Secure airway in OR with ENT/anesthesia present. IV antibiotics: ceftriaxone or cefotaxime. Hib vaccine has dramatically reduced incidence.',4,'analyze',['epiglottitis','H-influenzae','Hib-vaccine','airway-emergency','thumbprint-sign']);
add('peds-fever','What is the presentation of acute otitis media (AOM) in children?','Ear pain (pulling at ear in infants), fever, irritability, otorrhea; otoscopy: bulging, erythematous, opacified TM with decreased mobility; most common: S. pneumoniae, H. influenzae, M. catarrhalis','Treatment: amoxicillin 80-90 mg/kg/day in 2 divided doses × 10 days (first-line); observation for 48-72h acceptable for mild AOM in children >2 years. Second-line: amoxicillin-clavulanate. Tympanostomy tubes for recurrent AOM (≥3 in 6 months or ≥4 in 12 months).',3,'apply',['AOM','otitis-media','amoxicillin','S-pneumoniae','tympanostomy']);
add('peds-fever','What is bronchiolitis and how is it managed?','RSV-caused lower respiratory infection in infants <2 years; wheezing, tachypnea, nasal flaring, retractions, poor feeding; CXR shows hyperinflation, peribronchial cuffing','Management is supportive: supplemental O2 if SpO2 <90%, nasal suctioning, maintaining hydration. Bronchodilators, corticosteroids, and antibiotics are NOT routinely recommended. Hypertonic saline nebulization may help in admitted patients. Palivizumab (anti-RSV monoclonal) for high-risk infants.',3,'apply',['bronchiolitis','RSV','supportive-care','infants','palivizumab']);
add('peds-fever','What is the significance of petechiae in a febrile child?','Petechiae with fever raise concern for meningococcal septicemia — medical emergency; also consider DIC, ITP, leukemia, HSP, and viral causes (enterovirus, EBV)','Meningococcal disease can progress rapidly from fever to shock in hours. Any febrile child with non-blanching petechiae/purpura: immediate IV access, blood culture, empiric IV ceftriaxone, aggressive fluid resuscitation. Delay in treatment increases mortality.',4,'analyze',['petechiae','meningococcal','fever','DIC','emergency']);
add('peds-fever','What is the appropriate temperature for a sponge bath in a febrile child?','Sponge baths are generally NOT recommended for fever reduction — they cause discomfort, shivering (which raises temperature), and are not more effective than antipyretics alone','Tepid (not cold) water can be used if antipyretics are ineffective and the child is severely uncomfortable, but this is not standard practice. Cold water and alcohol baths are contraindicated. Focus on adequate fluid intake and antipyretics for comfort.',2,'recall',['sponge-bath','fever','antipyretic','pediatric','contraindicated']);
add('peds-fever','What is toxic shock syndrome (TSS) in children?','Toxin-mediated illness (S. aureus or GAS); fever >38.9°C, diffuse macular erythroderma, desquamation (1-2 weeks later), hypotension, involvement of ≥3 organ systems','Staphylococcal TSS: associated with tampon use, wound infections. Streptococcal TSS: often with necrotizing fasciitis. Treatment: aggressive fluids, vasopressors, clindamycin (reduces toxin production) + vancomycin/nafcillin, IVIG for refractory cases. Source control essential.',4,'analyze',['TSS','toxic-shock','S-aureus','GAS','clindamycin']);
add('peds-fever','What is the approach to prolonged fever (>5 days) in a child with no diagnosis?','Consider: Kawasaki disease (even incomplete), occult abscess, UTI, osteomyelitis, endocarditis, JIA (systemic onset), malignancy, EBV/CMV, drug fever, inflammatory conditions','Workup: CBC with differential, blood culture, CRP/ESR, urinalysis/culture, liver enzymes, LDH, peripheral smear, CXR. If still unclear: echocardiogram (Kawasaki, endocarditis), bone scan, CT abdomen, bone marrow biopsy.',3,'apply',['prolonged-fever','fever-of-unknown-origin','Kawasaki','malignancy','workup']);

process.stdout.write(JSON.stringify(cards));
