const fs = require('fs');
const cards = [];
let n = 1;
function add(topicId, q, a, ex, diff, bloom, tags) {
  cards.push({ id: `card-tn2-obgyn-${n++}`, question: q, answer: a, explanation: ex, difficulty: diff, bloomLevel: bloom, tags, topicId });
}

// OBGYN-OBSTETRIC-EMERG (15)
add('obgyn-obstetric-emerg','What are the diagnostic criteria for preeclampsia per SOGC guidelines?','New-onset hypertension (>=140/90) after 20 weeks gestation WITH >=1 of: proteinuria (>=0.3g/24h or PCR >=30mg/mmol), end-organ dysfunction (elevated creatinine, liver transaminases, thrombocytopenia <100, neurological symptoms, pulmonary edema). Severe features: SBP >=160 or DBP >=110, thrombocytopenia <100, liver transaminases >2x ULN, severe headache/visual changes, pulmonary edema, renal insufficiency.',
'SOGC 2022 guidelines removed the requirement for proteinuria to diagnose preeclampsia-any end-organ dysfunction with new hypertension qualifies. Proteinuria severity does not correlate with outcomes. HELLP syndrome (Hemolysis, Elevated Liver enzymes, Low Platelets) is a severe variant.',5,'recall',['preeclampsia','diagnostic criteria','SOGC','obstetrics']);

add('obgyn-obstetric-emerg','What is the management of severe preeclampsia?','IV magnesium sulfate (4g bolus over 20 min, then 1g/h infusion) for seizure prophylaxis. Antihypertensives: IV labetalol (20mg, then 40mg, 80mg escalating) or IV hydralazine or oral nifedipine for acute BP >=160/110. Delivery: definitive treatment. >=37 weeks: deliver. <34 weeks: stabilize, steroids, deliver if maternal/fetal deterioration. 34-37 weeks: individualized.',
'SOGC recommends MgSO4 for all women with severe preeclampsia (NNT 63 to prevent one eclamptic seizure per MAGPIE trial). Monitor for MgSO4 toxicity: loss of reflexes (therapeutic 4-7 mmol/L), respiratory depression, cardiac arrest. Antidote: calcium gluconate 1g IV.',5,'apply',['severe preeclampsia','magnesium sulfate','management','obstetrics']);

add('obgyn-obstetric-emerg','What is the management of eclampsia?','ABC stabilization, left lateral position, protect airway. MgSO4 4-6g IV bolus over 15-20 min then 1-2g/h maintenance. If seizures recur on MgSO4: additional 2g bolus. Avoid benzodiazepines and phenytoin. Control BP <160/110. Deliver after maternal stabilization regardless of gestational age.',
'Eclampsia can occur antepartum (38%), intrapartum (18%), or postpartum (44%). Postpartum eclampsia occurs up to 4 weeks after delivery. SOGC guidelines identify MgSO4 as superior to all other anticonvulsants for eclampsia (Collaborative Eclampsia Trial).',5,'apply',['eclampsia','seizure','magnesium sulfate','obstetrics']);

add('obgyn-obstetric-emerg','What is the management of postpartum hemorrhage?','PPH: blood loss >=500mL (vaginal) or >=1000mL (cesarean). 4 T causes: Tone (70%)-uterine atony. Trauma-lacerations, hematoma. Tissue-retained placenta. Thrombin-coagulopathy. Management: bimanual uterine massage, oxytocin 20-40U in 1L NS. Second-line: carboprost 250mcg IM (avoid in asthma), misoprostol 800-1000mcg PR, ergometrine 0.25mg IM (avoid in HTN). Tranexamic acid 1g IV within 3h. If refractory: Bakri balloon, B-Lynch suture, uterine artery embolization, hysterectomy.',
'PPH is the leading cause of maternal death worldwide. SOGC recommends active management of third stage (oxytocin 10U IM, controlled cord traction, uterine massage). WOMAN trial showed TXA reduces death from PPH if given within 3 hours. Massive transfusion protocol with 1:1:1 ratio.',5,'apply',['PPH','postpartum hemorrhage','uterine atony','obstetrics']);

add('obgyn-obstetric-emerg','What is the approach to shoulder dystocia?','HELPERR mnemonic: H-call for Help. E-Evaluate for episiotomy. L-Legs (McRoberts maneuver: hyperflexion of thighs). P-suprapubic Pressure (NOT fundal). E-Enter maneuvers (Rubin: posterior shoulder rotation; Woods corkscrew). R-Remove posterior arm. R-Roll patient to all-fours (Gaskin maneuver). Document time, maneuvers, and outcomes.',
'Shoulder dystocia occurs in 0.6-1.4% of vaginal deliveries. Risk factors: macrosomia, GDM, previous shoulder dystocia, prolonged second stage. McRoberts + suprapubic pressure resolves >90% of cases. Complications: brachial plexus injury (Erb palsy), clavicle fracture, hypoxic injury. SOGC recommends regular simulation drills.',5,'apply',['shoulder dystocia','HELPERR','McRoberts','obstetrics']);

add('obgyn-obstetric-emerg','What is the management of umbilical cord prolapse?','EMERGENCY: elevate presenting part (hand in vagina, fingers off cord), fill bladder (500mL NS via Foley to elevate presenting part), knee-chest or Trendelenburg position, emergent cesarean section. Do NOT attempt to replace cord. Keep cord warm and moist. Avoid handling cord to prevent vasospasm.',
'Cord prolapse occurs in ~0.3% of deliveries. Risk factors: non-cephalic presentation, polyhydramnios, AROM with high presenting part, multiparity. Time to delivery is critical-fetal mortality increases with delay. SOGC recommends immediate cesarean with ongoing digital elevation.',5,'apply',['cord prolapse','emergency','cesarean','obstetrics']);

add('obgyn-obstetric-emerg','What are the types and management of placental abruption?','Classification: Grade 1 (mild)-marginal bleed, no fetal compromise. Grade 2 (moderate)-fetal distress, painful contractions, tender uterus. Grade 3 (severe)-fetal death, maternal DIC. Management: stabilize (2 large-bore IVs, crossmatch, coagulation studies). Grade 1: observation, monitor. Grade 2-3 with fetal distress: emergent cesarean. Grade 3 with fetal demise: vaginal delivery if maternal condition allows, correct coagulopathy.',
'Abruption complicates 1% of pregnancies. Risk factors: hypertension (most common), cocaine use, trauma, previous abruption. Concealed hemorrhage can be more dangerous than revealed. SOGC recommends RhIg for Rh-negative women with abruption. Kleihauer-Betke test quantifies fetomaternal hemorrhage.',5,'apply',['placental abruption','hemorrhage','DIC','obstetrics']);

add('obgyn-obstetric-emerg','What is the management of placenta previa?','No vaginal exam until placenta location confirmed by ultrasound. Asymptomatic: serial US, delivery by planned cesarean at 36-37 weeks (after steroids if <37). Active bleeding: admit, type and crossmatch, IV access, steroids if <34 weeks. Massive hemorrhage: emergent cesarean regardless of gestational age. Avoid digital vaginal exam-may precipitate catastrophic hemorrhage.',
'Placenta previa occurs in 0.3-0.5% of pregnancies. Risk factors: previous cesarean (strongest), multiparity, advanced maternal age, multiple gestation. Vasa previa (fetal vessels crossing internal os) has high fetal mortality if membranes rupture. SOGC recommends screening for vasa previa with transvaginal US.',4,'apply',['placenta previa','antepartum hemorrhage','cesarean','obstetrics']);

add('obgyn-obstetric-emerg','What are the clinical features and management of amniotic fluid embolism?','Sudden cardiovascular collapse, hypoxia, DIC, and altered mental status during labor or immediately postpartum. Classic triad: hypotension, respiratory distress, coagulopathy. Management: supportive-intubation, vasopressors, massive transfusion for DIC, prepare for perimortem cesarean within 4-5 minutes if cardiac arrest.',
'AFE is rare (~1/40,000) but has 60-80% mortality. Pathophysiology involves anaphylactoid reaction to fetal material in maternal circulation. No specific treatment exists. Perimortem cesarean improves both maternal and fetal outcomes. Canadian MOREOB program includes AFE simulation scenarios.',5,'apply',['amniotic fluid embolism','obstetric emergency','DIC','obstetrics']);

add('obgyn-obstetric-emerg','What is uterine rupture, its risk factors, and management?','Presentation: sudden severe abdominal pain, loss of contraction pattern on CTG, fetal heart rate abnormalities (prolonged deceleration), vaginal bleeding, palpable fetal parts abdominally, hemodynamic instability. Risk factors: previous cesarean (classical > low transverse), uterine surgery, oxytocin augmentation, obstructed labor. Management: emergent laparotomy, repair or hysterectomy.',
'Uterine rupture risk with TOLAC (trial of labor after cesarean): 0.5-0.7% with one prior low-transverse CS. Contraindications to TOLAC: previous classical incision, prior rupture, >2 prior cesareans (relative). SOGC guidelines outline TOLAC eligibility and intrapartum monitoring requirements.',5,'apply',['uterine rupture','TOLAC','VBAC','obstetrics']);

add('obgyn-obstetric-emerg','What is the management of ectopic pregnancy?','Expectant management: stable, declining hCG, hCG <1000. Medical: methotrexate 50mg/m2 IM single dose (criteria: hemodynamically stable, no fetal cardiac activity, hCG <5000, ectopic <4cm, no contraindications). Surgical: laparoscopic salpingostomy or salpingectomy (unstable, ruptured, failed medical, contraindication to MTX). Follow hCG to zero.',
'SOGC guidelines recommend methotrexate for appropriate candidates. Contraindications to MTX: breastfeeding, immunodeficiency, liver/renal disease, blood dyscrasias, active pulmonary disease. Check CBC, renal function, liver enzymes, blood type, hCG before MTX. Monitor hCG on days 4 and 7 (should drop >=15%).',4,'apply',['ectopic pregnancy','methotrexate','salpingectomy','obstetrics']);

add('obgyn-obstetric-emerg','What is the approach to a patient with second-trimester vaginal bleeding?','Differential: placenta previa, placental abruption, vasa previa, cervical causes (cervicitis, polyp, cancer), preterm labor with bloody show. Do NOT perform digital vaginal exam until previa excluded by US. Investigations: speculum exam (after previa excluded), ultrasound (placental location, amniotic fluid), CBC, coagulation, crossmatch, Kleihauer-Betke if Rh-negative.',
'Transvaginal ultrasound is safe in placenta previa (probe does not reach internal os). Vasa previa has pathognomonic sinusoidal fetal heart rate pattern when membranes rupture. SOGC recommends Apt test to differentiate fetal from maternal blood in vaginal bleeding.',4,'apply',['antepartum hemorrhage','second trimester','differential diagnosis','obstetrics']);

add('obgyn-obstetric-emerg','What are the criteria for perimortem cesarean section?','Maternal cardiac arrest with gravid uterus >=20 weeks. Initiate within 4 minutes of cardiac arrest, deliver by 5 minutes. Improves maternal resuscitation (relieves aortocaval compression) AND fetal outcomes. Do NOT delay for consent, OR transfer, or sterile technique. Perform at bedside during ongoing CPR.',
'Perimortem cesarean is for maternal benefit primarily (improved venous return and CPR efficacy). Canadian Resuscitation guidelines (CRC) incorporate this into maternal cardiac arrest algorithms. Neonatal team should be present. Survival is possible even with prolonged arrest if delivery is timely.',5,'apply',['perimortem cesarean','maternal cardiac arrest','resuscitation','obstetrics']);

add('obgyn-obstetric-emerg','What is the management of preterm premature rupture of membranes (PPROM)?','<24 weeks: counsel on prognosis, expectant vs termination. 24-34 weeks: admit, GBS prophylaxis, antenatal corticosteroids, latency antibiotics (ampicillin IV 48h then amoxicillin PO x 5 days + azithromycin), magnesium for neuroprotection if <32 weeks. Monitor for chorioamnionitis. Deliver for infection, abruption, fetal distress, or at 34 weeks. 34-37 weeks: consider delivery after steroids.',
'SOGC guidelines recommend expectant management from 24-34 weeks with close monitoring. Latency antibiotics prolong pregnancy and reduce neonatal morbidity. Chorioamnionitis (maternal fever, tachycardia, uterine tenderness, fetal tachycardia) mandates delivery. ORACLE trial established the antibiotic regimen.',5,'apply',['PPROM','premature rupture','latency antibiotics','obstetrics']);

add('obgyn-obstetric-emerg','What is the management of obstetric DIC?','Treat underlying cause (abruption, AFE, sepsis, HELLP, retained dead fetus). Massive transfusion: PRBC:FFP:platelets in 1:1:1 ratio. Target: platelets >50, fibrinogen >2g/L (higher threshold in obstetrics than general DIC), INR <1.5. Cryoprecipitate for fibrinogen replacement. Tranexamic acid 1g IV. Consider recombinant factor VIIa as last resort.',
'Fibrinogen is consumed early in obstetric DIC and is the best predictor of severity. Normal fibrinogen in pregnancy is 4-6 g/L so values of 2g/L already indicate significant consumption. SOGC recommends fibrinogen replacement to maintain >2g/L. Point-of-care testing (ROTEM/TEG) guides targeted transfusion.',5,'apply',['DIC','coagulopathy','massive transfusion','obstetrics']);

// OBGYN-ANTENATAL (15)
add('obgyn-antenatal','What is the recommended screening approach for gestational diabetes mellitus in Canada?','SOGC/Diabetes Canada: screen ALL pregnant women at 24-28 weeks. Preferred approach: 50g glucose challenge test (GCT). If 1h value 7.8-11.0 mmol/L: proceed to 75g 2h OGTT. GDM diagnosed if ANY of: fasting >=5.3, 1h >=10.6, 2h >=9.0 mmol/L. If GCT >=11.1: GDM diagnosed (no need for OGTT). Screen earlier if high risk (BMI >30, previous GDM, ethnicity).',
'SOGC 2019 GDM guidelines offer two approaches. Alternative: one-step 75g OGTT (IADPSG criteria: fasting >=5.1, 1h >=10.0, 2h >=8.5). Canadian provinces vary in preferred approach. GDM affects 5-12% of Canadian pregnancies and is increasing with obesity prevalence.',4,'apply',['GDM','gestational diabetes','screening','OGTT','obstetrics']);

add('obgyn-antenatal','What is the management of gestational diabetes?','Step 1: Nutritional counseling (dietitian referral) + glucose monitoring (fasting <5.3, 1h postprandial <7.8, 2h <6.7 mmol/L) + exercise. Step 2 (if targets not met in 1-2 weeks): insulin (first-line per SOGC) or metformin (second-line). Glyburide is less preferred (higher neonatal hypoglycemia). Fetal surveillance: growth ultrasound q4 weeks, NST starting 36 weeks. Delivery: 38-39 weeks if insulin-requiring, 39-40 weeks if diet-controlled.',
'SOGC recommends insulin as first-line pharmacotherapy for GDM. Metformin crosses the placenta but is an acceptable alternative per SOGC. Postpartum: glucose tolerance test at 6 weeks to 6 months (50% of GDM women develop type 2 DM within 5-10 years).',4,'apply',['GDM management','insulin','glucose monitoring','obstetrics']);

add('obgyn-antenatal','What are the routine antenatal investigations at the first prenatal visit?','CBC, blood type and Rh, antibody screen, rubella immunity, syphilis (RPR/VDRL), HIV, HBsAg, urine culture and urinalysis, cervical cytology (if due), GC/chlamydia NAAT. Consider: HCV screening, TSH if symptomatic, varicella immunity if unknown, 50g GCT if high-risk for GDM. Offer first-trimester screening (11-14 weeks): NT + PAPP-A + free hCG.',
'SOGC guidelines recommend HIV and syphilis screening for ALL pregnant women. Universal prenatal screening is a cornerstone of Canadian perinatal care. Congenital syphilis is resurging in Canada-repeat RPR in third trimester in high-risk populations. Group B Strep screening at 35-37 weeks.',3,'recall',['antenatal screening','prenatal investigations','SOGC','obstetrics']);

add('obgyn-antenatal','What prenatal genetic screening options are available in Canada?','First trimester (11-14w): NT + PAPP-A + free beta-hCG (FTS). Second trimester (15-20w): quad screen (AFP, hCG, estriol, inhibin A). Integrated: FTS + quad. Cell-free fetal DNA (NIPT): sensitivity >99% for trisomy 21, available >=10 weeks. NIPT is not diagnostic-abnormal results require confirmatory diagnostic testing (CVS 10-12w or amniocentesis 15-20w).',
'SOGC recommends offering prenatal screening to all women. NIPT (cell-free DNA) has rapidly become widely available in Canada but is not publicly funded in all provinces except for high-risk populations. CVS carries ~0.1% miscarriage risk, amniocentesis ~0.1%. Results include karyotype and microarray.',4,'apply',['prenatal screening','NIPT','trisomy 21','genetic screening','obstetrics']);

add('obgyn-antenatal','What medications are safe, conditionally safe, and contraindicated in pregnancy?','Safe: acetaminophen, penicillins, cephalosporins, erythromycin (not estolate), metformin, labetalol, methyldopa, ondansetron. Conditionally safe: SSRIs (paroxetine avoid first trimester), insulin, azithromycin. Contraindicated: ACE inhibitors/ARBs, warfarin, isotretinoin, valproate, methotrexate, tetracyclines, fluoroquinolones, statins, misoprostol, lithium (relative).',
'SOGC and Motherisk (though now closed, legacy resources exist) provided Canadian-specific guidance on medication safety. ACE inhibitors cause renal dysgenesis. Warfarin causes nasal hypoplasia and CNS abnormalities (6-12 weeks). Category X drugs are absolutely contraindicated regardless of benefit.',4,'recall',['teratogenic drugs','medication safety','pregnancy','obstetrics']);

add('obgyn-antenatal','What is the recommended folic acid supplementation for pregnancy?','Low risk: folic acid 0.4-1.0 mg/day starting >=3 months preconception through 12 weeks, then continue throughout pregnancy. High risk (previous NTD, epilepsy on AEDs, diabetes, BMI >35, family history of NTD): folic acid 4-5 mg/day starting >=3 months preconception through 12 weeks, then 0.4-1.0mg.',
'SOGC guidelines emphasize preconception folic acid. Neural tube closure occurs by day 28 (often before pregnancy is recognized). Canadian flour is fortified with folic acid since 1998, which reduced NTD rates by 46%. High-dose folic acid is specifically indicated for women on valproate or carbamazepine.',3,'recall',['folic acid','NTD prevention','preconception','obstetrics']);

add('obgyn-antenatal','What is the schedule of routine prenatal visits and what is assessed at each?','Visits: q4 weeks until 28w, q2 weeks 28-36w, weekly 36w-delivery. Each visit: BP, weight, urinalysis, fundal height (from 20w, cm=weeks ±2), fetal heart tones (Doppler from 12w). 20w: anatomy ultrasound. 24-28w: GDM screening. 28w: Rh antibody screen (give RhIg 300mcg if Rh-negative). 35-37w: GBS swab.',
'SOGC guidelines outline the schedule. Dating ultrasound (ideally 11-14w) is the most accurate for gestational age assessment. Fundal height discrepancy >3cm warrants ultrasound for growth assessment. Serial growth scans for high-risk pregnancies (IUGR, GDM, multiple gestation).',3,'recall',['prenatal visits','schedule','routine care','obstetrics']);

add('obgyn-antenatal','What is Rh alloimmunization and how is it prevented?','Rh-negative mother exposed to Rh-positive fetal blood produces anti-D antibodies affecting subsequent pregnancies. Prevention: RhIg (Rh immune globulin, WinRho) 300mcg IM at 28 weeks AND within 72h postpartum if baby Rh-positive. Also give RhIg after: miscarriage, ectopic, amniocentesis, CVS, trauma, abruption, version.',
'SOGC recommends routine RhIg prophylaxis at 28 weeks for all Rh-negative women. Kleihauer-Betke test determines if additional RhIg is needed (>30mL fetomaternal hemorrhage requires additional doses). Anti-D titer monitoring in sensitized pregnancies guides management timing.',4,'apply',['Rh alloimmunization','RhIg','prevention','obstetrics']);

add('obgyn-antenatal','What are the types and management of hypertensive disorders of pregnancy?','Chronic HTN: pre-existing or <20 weeks. Gestational HTN: new HTN >=20 weeks without proteinuria/end-organ dysfunction. Preeclampsia: HTN + proteinuria or end-organ dysfunction >=20 weeks. Chronic HTN + superimposed preeclampsia. SOGC treatment targets: SBP 110-140, DBP 85-90. Medications: labetalol (first-line), nifedipine, methyldopa.',
'SOGC 2022 HDP guidelines recommend tighter BP control (target 135/85) per CHIPS trial showing reduced severe HTN episodes. Low-dose ASA (162mg/day from 12-16 weeks) prevents preeclampsia in high-risk women (NNT 72). Calcium supplementation (>=1g/day) if low intake.',4,'apply',['hypertensive disorders','gestational hypertension','preeclampsia classification','obstetrics']);

add('obgyn-antenatal','What constitutes a high-risk pregnancy and what additional surveillance is needed?','High-risk factors: advanced maternal age (>=35), BMI >=30, previous cesarean, multiple gestation, preexisting conditions (DM, HTN, thyroid, renal, autoimmune), previous adverse outcomes (preeclampsia, PTB, stillbirth, IUGR), substance use. Surveillance: more frequent visits, serial growth US, NST/BPP from 32-34 weeks, early GDM screening, specialist consultation.',
'High-risk pregnancies in Canada are often co-managed between family physicians and obstetricians or maternal-fetal medicine specialists. Biophysical profile (BPP) assesses fetal breathing, movement, tone, amniotic fluid, and NST (score 0-10). BPP <=4 requires delivery consideration.',3,'apply',['high-risk pregnancy','surveillance','BPP','obstetrics']);

add('obgyn-antenatal','What is the management of intrauterine growth restriction (IUGR)?','Diagnosis: estimated fetal weight <10th percentile (severe <3rd). Workup: detailed anatomy US, umbilical artery Doppler, maternal infections (TORCH), karyotype if anomalies. Monitoring: serial growth US q2 weeks, umbilical artery Doppler (absent/reversed end-diastolic flow is ominous), NST/BPP. Delivery: 37 weeks if stable, earlier if deteriorating Doppler, oligohydramnios, or abnormal NST/BPP. Steroids if <34 weeks.',
'SOGC guidelines use umbilical artery Doppler as the primary surveillance tool for IUGR. Absent end-diastolic flow increases perinatal mortality 4x; reversed end-diastolic flow increases it 10x. Timing of delivery balances prematurity risk against intrauterine demise. MgSO4 for neuroprotection if <32 weeks.',4,'apply',['IUGR','growth restriction','Doppler','fetal surveillance','obstetrics']);

add('obgyn-antenatal','What are the indications for antenatal corticosteroids?','Single course of betamethasone (12mg IM x 2 doses, 24h apart) or dexamethasone (6mg IM x 4 doses, 12h apart) for women at risk of preterm delivery between 24+0 and 34+6 weeks. Reduces RDS (50%), IVH, NEC, and neonatal death. Rescue course may be considered if >=7 days since first course and <34 weeks. Not recommended routinely at >=35 weeks.',
'SOGC guidelines recommend antenatal corticosteroids as one of the most effective perinatal interventions (NNT 12 to prevent one case of RDS). Benefit is maximal 24h-7d after administration. Late preterm steroids (34-36 weeks) may reduce transient tachypnea but increase neonatal hypoglycemia.',4,'apply',['antenatal corticosteroids','betamethasone','preterm labor','obstetrics']);

add('obgyn-antenatal','What are the methods and indications for cervical ripening and labor induction?','Indications: post-dates (>=41 weeks), PROM at term, preeclampsia, GDM, IUGR, oligohydramnios, chorioamnionitis. Bishop score <6: cervical ripening needed. Methods: prostaglandin E2 (dinoprostone vaginal insert/gel), misoprostol (PGE1) 25mcg vaginal, Foley catheter (mechanical). Bishop >=6: oxytocin induction (start 1-2 mU/min, increase q30min).',
'SOGC guidelines recommend cervical ripening for unfavorable cervix (Bishop <6). ARRIVE trial showed induction at 39 weeks in nulliparas reduces cesarean rate. Misoprostol is contraindicated with previous cesarean (uterine rupture risk). Oxytocin protocols are standardized in Canadian hospitals.',4,'apply',['labor induction','cervical ripening','Bishop score','obstetrics']);

add('obgyn-antenatal','What is the Group B Streptococcus (GBS) prevention strategy in Canada?','Universal screening: rectovaginal swab at 35-37 weeks. Intrapartum antibiotic prophylaxis (IAP) for: GBS positive, GBS bacteriuria this pregnancy, previous GBS-affected infant, unknown GBS status with risk factors (preterm <37w, ROM >18h, intrapartum fever >=38°C). IAP: penicillin G 5 million U IV then 2.5-3 million U q4h until delivery (alternative: ampicillin). PCN allergy: cefazolin if low-risk allergy, clindamycin or vancomycin if high-risk.',
'SOGC recommends universal culture-based screening (not risk-based approach). GBS causes early-onset neonatal sepsis (within 7 days) with 4% mortality. IAP reduces early-onset GBS disease by 80%. GBS status should be re-screened if >5 weeks since initial screen at time of delivery.',4,'apply',['GBS','Group B Strep','intrapartum antibiotics','obstetrics']);

add('obgyn-antenatal','What are the key elements of postpartum care in Canada?','Immediate: fundal massage, monitor for hemorrhage, initiate breastfeeding within 1h. Hospital stay: 24-48h vaginal, 48-72h cesarean. Postpartum visit at 6 weeks. Screen for: postpartum depression (Edinburgh Postnatal Depression Scale), contraception, breastfeeding issues, wound complications, VTE symptoms. RhIg if indicated. Vaccination (rubella, varicella, Tdap, COVID) if not immune.',
'CPS and SOGC emphasize the fourth trimester as a critical period. Edinburgh Postnatal Depression Scale (EPDS) score >=13 warrants further assessment. Postpartum depression affects 10-15% of Canadian women. SOGC recommends contraception counseling before discharge as ovulation can occur by 3 weeks postpartum.',3,'apply',['postpartum care','EPDS','breastfeeding','obstetrics']);

// OBGYN-GYN (15)
add('obgyn-gyn','What is the Canadian cervical cancer screening guideline?','Age 25-69: cytology (Pap) every 3 years OR HPV primary screening every 5 years (where available). Start at age 25 (not at onset of sexual activity). Stop at 70 if adequate recent negative screening. Post-hysterectomy (with cervix removal for benign indication): stop screening. Immunocompromised: annual screening.',
'CTFPHC 2013 guidelines recommended starting screening at 25, which differs from some US guidelines that start at 21. The shift to HPV primary screening reflects evidence that HPV testing is more sensitive than cytology. Several Canadian provinces are transitioning to HPV-based screening programs.',3,'recall',['cervical cancer screening','Pap test','HPV screening','gynecology']);

add('obgyn-gyn','What is the management algorithm for abnormal cervical cytology?','ASCUS: HPV co-testing (if HPV negative, return to routine; if HPV positive, colposcopy) OR repeat cytology in 12 months. LSIL: colposcopy. HSIL: colposcopy + ECC. AGC: colposcopy + ECC + endometrial biopsy (if >=35 or abnormal bleeding). CIN1: observation (70% regress). CIN2: treat if persistent >2 years or excision. CIN3: excision (LEEP or cold knife cone).',
'SOGC colposcopy guidelines outline management algorithms. LEEP (loop electrosurgical excision procedure) is the most common treatment for CIN2/3 in Canada. CIN2 in women <25 may be observed due to high regression rates. HPV vaccination does not change screening recommendations.',4,'apply',['abnormal Pap','CIN','colposcopy','LEEP','gynecology']);

add('obgyn-gyn','What is the approach to abnormal uterine bleeding (AUB)?','PALM-COEIN classification: Structural (PALM): Polyp, Adenomyosis, Leiomyoma, Malignancy/hyperplasia. Non-structural (COEIN): Coagulopathy, Ovulatory dysfunction, Endometrial, Iatrogenic, Not yet classified. Workup: pregnancy test, CBC, TSH, pelvic US, endometrial biopsy (age >=40 or risk factors for hyperplasia). Management by cause: OCPs/IUS for ovulatory dysfunction, resection for polyps/fibroids, progestins for hyperplasia.',
'SOGC guidelines use the FIGO PALM-COEIN classification system. Endometrial biopsy is recommended for AUB in women >=40 years or <40 with risk factors (obesity, anovulation, tamoxifen). Levonorgestrel IUS (Mirena) is first-line medical treatment for HMB.',4,'apply',['AUB','abnormal uterine bleeding','PALM-COEIN','gynecology']);

add('obgyn-gyn','What are the types of uterine fibroids and their management options?','Types (FIGO): submucosal (Type 0-2, cause heavy bleeding), intramural (Type 3-5), subserosal (Type 6-7, cause bulk symptoms). Medical: tranexamic acid, OCPs, LNG-IUS, GnRH agonists (preoperative shrinkage), ulipristal acetate. Surgical: myomectomy (fertility-preserving), hysterectomy (definitive), uterine artery embolization (UAE), MRI-guided focused US.',
'SOGC guidelines recommend medical management first-line for symptomatic fibroids. GnRH agonists cause temporary menopause (max 6 months due to bone loss). UAE is effective but not recommended for women desiring future fertility. Hysterectomy is the only definitive treatment.',4,'apply',['fibroids','leiomyoma','myomectomy','hysterectomy','gynecology']);

add('obgyn-gyn','What is the workup and management of an adnexal mass?','Premenopausal: most are functional cysts (<6cm, simple-observe, repeat US in 6-8 weeks). Concern for malignancy: complex/solid, >6cm, ascites, elevated CA-125, postmenopausal. Postmenopausal: any adnexal mass warrants investigation. Tumor markers: CA-125 (epithelial ovarian), AFP/hCG/LDH (germ cell), inhibin (granulosa cell). Imaging: pelvic US first, CT/MRI for characterization.',
'SOGC guidelines and IOTA (International Ovarian Tumor Analysis) simple rules guide management. CA-125 is not specific (elevated in endometriosis, PID, pregnancy, peritoneal irritation). Postmenopausal women with complex mass and elevated CA-125 should be referred to gynecologic oncology. Risk of Malignancy Index (RMI) combines US, menopausal status, and CA-125.',4,'apply',['adnexal mass','ovarian cyst','CA-125','gynecology']);

add('obgyn-gyn','What are the causes and workup of secondary amenorrhea?','Definition: absence of menses for >=3 cycles or >=6 months. Most common cause: pregnancy (always test first). Other causes: hypothalamic (stress, weight loss, exercise), PCOS, thyroid dysfunction, hyperprolactinemia, premature ovarian insufficiency, Asherman syndrome, medication (OCPs, depot medroxyprogesterone). Workup: pregnancy test, TSH, prolactin, FSH, estradiol. Progestin challenge test.',
'SOGC guidelines recommend systematic evaluation. Elevated FSH (>40) suggests premature ovarian insufficiency (karyotype if <40 for Turner mosaicism). Elevated prolactin requires MRI sella for prolactinoma. Hypothalamic amenorrhea (low FSH, low estradiol) warrants bone density assessment due to estrogen deficiency.',4,'apply',['amenorrhea','PCOS','workup','gynecology']);

add('obgyn-gyn','What are the diagnostic criteria for polycystic ovary syndrome (PCOS)?','Rotterdam criteria (>=2 of 3): (1) oligo/anovulation, (2) clinical or biochemical hyperandrogenism, (3) polycystic ovaries on US (>=12 follicles 2-9mm in one ovary or ovarian volume >10mL). Exclude: thyroid disease, CAH (17-OHP), hyperprolactinemia, Cushing syndrome.',
'SOGC guidelines use Rotterdam criteria. PCOS affects 6-10% of reproductive-age women and is the most common cause of anovulatory infertility. Management: weight loss if overweight, OCPs for cycle regulation and hyperandrogenism, metformin for metabolic features, letrozole for ovulation induction (first-line over clomiphene).',3,'recall',['PCOS','Rotterdam criteria','hyperandrogenism','gynecology']);

add('obgyn-gyn','What is the approach to endometriosis diagnosis and management?','Clinical diagnosis: cyclic pelvic pain, dysmenorrhea, dyspareunia, dyschezia, infertility. Gold standard diagnosis: laparoscopy with histological confirmation. US may show endometriomas (chocolate cysts). Medical: NSAIDs, combined OCPs (continuous), progestins, GnRH agonists (with add-back therapy), dienogest. Surgical: laparoscopic excision/ablation of implants, adhesiolysis.',
'SOGC guidelines recommend empiric medical treatment before laparoscopy in suspected endometriosis. Dienogest is a newer progestin specifically approved for endometriosis in Canada. Deep infiltrating endometriosis requires expert surgical management. Endometriosis affects 6-10% of reproductive-age women.',4,'apply',['endometriosis','dysmenorrhea','laparoscopy','gynecology']);

add('obgyn-gyn','What is the assessment and management of pelvic organ prolapse?','POP-Q staging: Stage 0-IV based on descent relative to hymen. Presentation: vaginal bulge, pressure, urinary symptoms (incomplete emptying, stress incontinence), bowel symptoms. Types: cystocele (anterior), rectocele (posterior), uterine prolapse, vault prolapse. Conservative: pelvic floor physiotherapy, pessary. Surgical: anterior/posterior colporrhaphy, sacrocolpopexy, hysterectomy + vault suspension.',
'SOGC guidelines recommend pessary as first-line for symptomatic prolapse. Pelvic floor physiotherapy (Kegel exercises) can improve Stage I-II prolapse. Surgical mesh for transvaginal prolapse repair carries significant complication risk. In Canada, vaginal mesh for prolapse has been largely restricted.',3,'apply',['pelvic organ prolapse','pessary','POP-Q','gynecology']);

add('obgyn-gyn','What is the approach to a postmenopausal woman with vaginal bleeding?','ALWAYS investigate-endometrial cancer until proven otherwise. Workup: pelvic exam, transvaginal ultrasound (endometrial thickness <4-5mm has high NPV), endometrial biopsy (Pipelle). If biopsy insufficient: hysteroscopy with D&C. Causes: atrophic vaginitis (most common), endometrial polyp, endometrial hyperplasia/cancer, cervical pathology, HRT.',
'SOGC guidelines recommend endometrial biopsy for all postmenopausal bleeding. Endometrial thickness >4mm on TVUS requires tissue sampling. Endometrial cancer is the most common gynecologic malignancy in Canada. Risk factors: obesity, unopposed estrogen, nulliparity, late menopause, tamoxifen, PCOS.',4,'apply',['postmenopausal bleeding','endometrial cancer','endometrial biopsy','gynecology']);

add('obgyn-gyn','What are the SOGC guidelines for menopause management and hormone replacement therapy?','Vasomotor symptoms: HRT is most effective treatment. Oral or transdermal estrogen + progestogen (if uterus present). Transdermal preferred (lower VTE risk). Lowest effective dose for shortest duration needed. Contraindications: breast cancer, active VTE, active liver disease, unexplained vaginal bleeding, coronary heart disease. Alternatives: venlafaxine, paroxetine, gabapentin for vasomotor symptoms.',
'SOGC Menopause guidelines state HRT initiated <60 years or within 10 years of menopause (window of opportunity) is safe for most women and may reduce cardiovascular risk. WHI data reinterpreted: risks primarily in older women (>60). Vaginal estrogen for genitourinary syndrome of menopause is safe even in breast cancer survivors.',4,'apply',['menopause','HRT','hormone therapy','SOGC','gynecology']);

add('obgyn-gyn','What is the approach to female infertility?','Definition: failure to conceive after 12 months of regular unprotected intercourse (6 months if >=35 years). Workup: ovulatory assessment (day 3 FSH/estradiol, day 21 progesterone, AMH), tubal patency (HSG or laparoscopy), semen analysis (male factor 40%). Treatment by cause: anovulation-letrozole (first-line), tubal-IVF, unexplained-IUI with ovulation induction then IVF.',
'SOGC infertility guidelines recommend simultaneous evaluation of both partners. Letrozole replaced clomiphene as first-line ovulation induction (NEJM trial 2014). AMH (anti-Mullerian hormone) predicts ovarian reserve. IVF is publicly funded in some Canadian provinces (Ontario, Quebec) with specific criteria.',4,'apply',['infertility','ovulation induction','IVF','gynecology']);

add('obgyn-gyn','What are the types of ovarian cancer and their staging?','Epithelial (90%): serous (most common, high-grade associated with BRCA), mucinous, endometrioid, clear cell. Germ cell (5%): dysgerminoma, teratoma, yolk sac tumor. Sex cord-stromal (5%): granulosa cell, Sertoli-Leydig. Staging: I-confined to ovary, II-pelvic extension, III-peritoneal spread/nodes, IV-distant metastases. Treatment: cytoreductive surgery + platinum-based chemotherapy.',
'Ovarian cancer is the most lethal gynecologic cancer. No effective screening exists for average-risk women (CA-125 + TVUS screening does NOT reduce mortality). BRCA1 carriers: 40-50% lifetime ovarian cancer risk; BRCA2: 15-20%. SOGC recommends risk-reducing bilateral salpingo-oophorectomy by age 40-45 for BRCA1 carriers.',4,'recall',['ovarian cancer','staging','BRCA','gynecology']);

add('obgyn-gyn','What is the management of ectopic pregnancy vs miscarriage in early pregnancy bleeding?','Key distinguishing features: ectopic-adnexal mass, peritoneal signs, hCG rising abnormally (<35% increase in 48h). Miscarriage types: threatened (cervix closed, ongoing pregnancy), inevitable (cervix open, membranes intact), incomplete (cervix open, partial tissue passage), complete (tissue passed, cervix closing), missed (no cardiac activity, cervix closed). Management of miscarriage: expectant, medical (misoprostol 800mcg vaginal), or surgical (suction D&C).',
'SOGC guidelines define miscarriage management options. Discriminatory zone: hCG level (typically 1500-3000 IU/L) above which a viable IUP should be seen on TVUS. If hCG above discriminatory zone with empty uterus: ectopic until proven otherwise. Rh-negative women receive RhIg for any early pregnancy bleeding.',4,'apply',['ectopic vs miscarriage','early pregnancy bleeding','hCG','obstetrics']);

// OBGYN-CONTRACEPTION (10)
add('obgyn-contraception','What are the available contraceptive methods ranked by effectiveness?','Most effective (>99%): IUD (copper and LNG), implant (Nexplanon), sterilization. Very effective (91-99% typical use): DMPA injection, combined OCP, patch, ring. Moderate (80-91%): condoms, diaphragm, withdrawal, fertility awareness. Emergency: copper IUD (most effective), ulipristal (ella, up to 5 days), levonorgestrel (Plan B, up to 3 days).',
'SOGC contraception guidelines emphasize long-acting reversible contraception (LARC: IUD, implant) as first-line due to highest effectiveness and no adherence issues. Canadian data shows 9% typical-use failure rate for OCPs. Contraceptive counseling should use shared decision-making approach.',3,'recall',['contraception effectiveness','LARC','IUD','gynecology']);

add('obgyn-contraception','What are the absolute and relative contraindications to combined hormonal contraception (CHC)?','Absolute (WHO Category 4): migraine with aura, VTE history/active, known thrombophilia, SLE with antiphospholipid antibodies, breast cancer, smoking >=15 cig/day AND age >=35, uncontrolled HTN, major surgery with prolonged immobilization, <21 days postpartum. Relative (Category 3): controlled HTN, migraine without aura in >=35, obesity, smoking <15 cig/day AND >=35.',
'SOGC uses WHO Medical Eligibility Criteria (MEC) framework. Category 1: no restriction. 2: generally use. 3: risks usually outweigh benefits. 4: unacceptable risk. CHC is safe for most women. Estrogen component increases VTE risk 3-4x (absolute risk still low: 3-9 per 10,000 woman-years).',4,'apply',['CHC contraindications','WHO MEC','OCP','gynecology']);

add('obgyn-contraception','What are the types of IUDs available in Canada and their key features?','Copper IUD (Mona Lisa, Flexi-T): hormone-free, effective for 5-10 years, may increase menstrual bleeding/cramping, can be used for emergency contraception. LNG-IUS 52mg (Mirena): 5 years, reduces menstrual bleeding (therapeutic for HMB), amenorrhea in 20-50%. LNG-IUS 19.5mg (Kyleena): 5 years, smaller, less amenorrhea. LNG-IUS 13.5mg (Jaydess): 3 years, smallest.',
'SOGC recommends IUDs as first-line contraception for all ages including nulliparous women and adolescents. IUDs do NOT increase PID risk (only slightly elevated in first 20 days after insertion). IUDs can be inserted at any time in the cycle. Expulsion rate: 2-10% in first year.',3,'recall',['IUD','copper IUD','LNG-IUS','Mirena','gynecology']);

add('obgyn-contraception','What is the approach to emergency contraception in Canada?','Copper IUD: most effective (>99%), can insert up to 7 days post-intercourse. Ulipristal acetate (ella) 30mg: effective up to 5 days, progesterone receptor modulator, more effective than LNG for BMI >26. Levonorgestrel (Plan B) 1.5mg: available OTC, effective up to 3 days (best <24h), less effective with BMI >25. Yuzpe method: less effective, more side effects.',
'SOGC emergency contraception guidelines recommend copper IUD as most effective option. Ulipristal requires prescription in Canada. LNG (Plan B) is available without prescription. After LNG, hormonal contraception can start next day. After ulipristal, wait 5 days before starting hormonal contraception.',3,'apply',['emergency contraception','copper IUD','Plan B','ulipristal','gynecology']);

add('obgyn-contraception','What is the quick-start method for initiating contraception?','Start hormonal contraception on the day of the visit regardless of cycle day (not waiting for next menses). Requirements: reasonably exclude pregnancy (negative urine hCG, no intercourse since last period, or consistent contraception use). Use backup method (condoms) for first 7 days. Preferred approach per SOGC for improving uptake and continuation.',
'SOGC guidelines endorse quick-start to reduce unintended pregnancy during the waiting period. Traditional Sunday-start or first-day-of-period start methods lead to unnecessary delays and missed opportunities. Same-day IUD insertion is also recommended when pregnancy is reasonably excluded.',3,'apply',['quick-start','contraception initiation','SOGC','gynecology']);

add('obgyn-contraception','What is the management of a missed combined oral contraceptive pill?','1 missed pill: take immediately, continue pack, no backup needed. 2 missed pills (or 1 missed in first week): take most recent missed pill, continue pack, use backup x 7 days, consider EC if unprotected intercourse in past 5 days. >=3 missed pills (or >=2 in first week): take most recent, continue pack, backup x 7 days, EC if indicated, skip placebo if in week 3.',
'SOGC missed pill guidelines simplified in 2015. First-week missed pills are highest risk due to extending the hormone-free interval. The 7-day rule (backup for 7 days after any significant disruption) is the unifying principle. Extended or continuous regimens reduce missed-pill risk.',3,'apply',['missed pill','OCP management','gynecology']);

add('obgyn-contraception','What postpartum contraception options are available and when can they be started?','Immediately postpartum: copper IUD or LNG-IUS (within 10 min of placenta delivery or within 48h). Progestin-only methods (POP, implant, DMPA): anytime postpartum. CHC (estrogen-containing): NOT before 21 days postpartum (VTE risk), not before 42 days if additional VTE risk factors. Breastfeeding: progestin-only preferred; CHC may reduce milk supply (avoid <6 weeks).',
'SOGC recommends postpartum contraception counseling antenatally and before hospital discharge. Immediate postpartum IUD insertion has higher expulsion rates (10-20%) but improves contraception uptake. Ovulation can occur as early as 21 days postpartum in non-breastfeeding women.',3,'apply',['postpartum contraception','breastfeeding','IUD timing','gynecology']);

add('obgyn-contraception','What contraceptive counseling is needed for women with medical comorbidities?','Epilepsy on enzyme-inducers: avoid CHC or use higher-dose, consider IUD/DMPA. Migraine with aura: no estrogen (IUD, POP, implant, DMPA). Diabetes: CHC acceptable if no vascular complications. HTN: progestin-only if uncontrolled. VTE history: no estrogen (IUD, POP, implant). Breast cancer: IUD copper only (no hormonal).',
'SOGC uses WHO MEC criteria for medical eligibility. The copper IUD has no medical contraindications except active PID, uterine anomalies, or Wilson disease. LNG-IUS has fewer systemic effects than other hormonal methods. DMPA may decrease bone density with long-term use.',4,'apply',['contraception comorbidities','WHO MEC','medical eligibility','gynecology']);

add('obgyn-contraception','What are the non-contraceptive benefits of hormonal contraception?','CHC: reduces dysmenorrhea, menorrhagia, acne, hirsutism, ovarian cysts, endometrial and ovarian cancer risk (50% reduction with 5 years use), PMS/PMDD. LNG-IUS: treats menorrhagia (90% reduction), endometrial hyperplasia protection, dysmenorrhea. DMPA: reduces endometriosis pain, menorrhagia, sickle cell crises.',
'SOGC and CFPC guidelines encourage discussion of non-contraceptive benefits. Ovarian cancer risk reduction persists 30+ years after CHC discontinuation. LNG-IUS is first-line treatment for heavy menstrual bleeding per SOGC guidelines. Continuous OCP use eliminates withdrawal bleeding and associated symptoms.',3,'recall',['non-contraceptive benefits','CHC','LNG-IUS','gynecology']);

add('obgyn-contraception','What is the approach to contraception in adolescents?','All methods are safe for adolescents. SOGC recommends LARC (IUD, implant) as first-line. Confidentiality is paramount-mature minor doctrine applies in most Canadian provinces. Dual protection (hormonal + condoms for STI prevention) recommended. DMPA: use with caution in <18 due to bone density effects. Emergency contraception: should be discussed proactively.',
'Canadian law generally allows minors to consent to contraception without parental involvement if they understand the risks and benefits (mature minor doctrine). School-based health centres in many Canadian provinces provide contraception. SOGC emphasizes removing barriers to adolescent contraception access.',3,'apply',['adolescent contraception','LARC','confidentiality','gynecology']);

fs.writeFileSync('C:/dev/srs-mccqe1/data/_obgyn_cards.json', JSON.stringify(cards, null, 2));
console.log('OB/GYN cards written:', cards.length);
