const fs = require("fs");
const prev = JSON.parse(fs.readFileSync("C:/dev/srs-mccqe1/data/_parts1234.json","utf8"));
const cards = [...prev];
let n = 166;
function c(id,q,a,ex,d,bl,tags,tid){return{id,question:q,answer:a,explanation:ex,difficulty:d,bloomLevel:bl,tags,topicId:tid};}

// DERMATOLOGY - COMMON (10)
cards.push(c("card-tn3-derm-"+n++,"How do eczema and psoriasis differ clinically?","Eczema: poorly defined, weeping/crusting, flexural, intensely pruritic, atopic triad. Psoriasis: well-defined silvery scale, extensor surfaces, Auspitz sign, nail pitting, Koebner phenomenon","Eczema: filaggrin mutation, Th2-mediated. Psoriasis: Th17-mediated. Eczema Rx: moisturizers+topical steroids+calcineurin inhibitors. Psoriasis Rx: topical steroids+vitamin D+phototherapy+biologics for moderate-severe.",3,"analyze",["eczema","psoriasis","differential"],"derm-common"));
cards.push(c("card-tn3-derm-"+n++,"What is the stepwise management of atopic dermatitis?","1) Daily moisturizers + trigger avoidance. 2) Topical steroids (low-potency face, moderate body). 3) Calcineurin inhibitors (tacrolimus). 4) Phototherapy. 5) Systemic: dupilumab, MTX, cyclosporine","Moisturize within 3min of bath. Avoid soap. Wet wraps for flares. Dupilumab (anti-IL4/13) transformed severe AD. Avoid systemic steroids (rebound). Steroid phobia common - educate patients/parents.",4,"apply",["atopic dermatitis","management"],"derm-common"));
cards.push(c("card-tn3-derm-"+n++,"What is the management of moderate-severe plaque psoriasis?","Topical: steroids + calcipotriol. Phototherapy: nbUVB. Systemic: MTX, cyclosporine, acitretin, apremilast. Biologics: TNFi, IL-17i (secukinumab), IL-23i (guselkumab), IL-12/23i (ustekinumab)","Screen for PsA, metabolic syndrome, depression, CV risk. Biologics achieve PASI 75-90 in >80%. Pre-biologic: TB/HBV screen, vaccines. MTX: monitor CBC/LFTs. Acitretin: teratogenic 3 years.",4,"apply",["psoriasis","biologics","phototherapy"],"derm-common"));
cards.push(c("card-tn3-derm-"+n++,"What is the stepwise management of acne vulgaris?","Mild comedonal: topical retinoid +/- BPO. Moderate papulopustular: + topical clindamycin with BPO. Moderate-severe: + oral doxycycline x3mo. Severe nodular/scarring: isotretinoin","Isotretinoin: teratogenic (iPLEDGE, 2 contraception, pregnancy tests). SE: dryness, lipids, LFTs. OCP/spironolactone for female hormonal acne. Never use topical antibiotic monotherapy (resistance).",4,"apply",["acne","isotretinoin","retinoid"],"derm-common"));
cards.push(c("card-tn3-derm-"+n++,"How is chronic urticaria managed?","Acute <6wk: 2nd-gen antihistamine. Chronic >6wk: step up antihistamine to 4x dose, then add omalizumab (anti-IgE). Avoid ASA/NSAIDs (worsen 30%). CSU is autoimmune, rarely allergic","No allergy testing for CSU. Lesions lasting >24h with bruising: consider urticarial vasculitis (biopsy). Omalizumab very effective for antihistamine-refractory CSU. Cyclosporine as last resort.",3,"apply",["urticaria","antihistamine","omalizumab"],"derm-common"));
cards.push(c("card-tn3-derm-"+n++,"What dermatological emergencies require urgent recognition?","SJS/TEN (skin pain, mucosal erosions, Nikolsky+, >30% BSA=TEN). Necrotizing fasciitis (pain out of proportion, systemic toxicity). Pemphigus vulgaris (flaccid blisters)","SJS/TEN drugs: allopurinol, carbamazepine, sulfonamides, phenytoin. Immediate drug withdrawal + burn unit. TEN mortality 25-30%. SCORTEN predicts. NF: surgical emergency + broad-spectrum abx.",5,"recall",["SJS","TEN","necrotizing fasciitis"],"derm-common"));
cards.push(c("card-tn3-derm-"+n++,"How are fungal skin infections diagnosed and treated?","Tinea: KOH shows hyphae. Topical terbinafine/clotrimazole 2-4wk. Tinea capitis: oral terbinafine 6-8wk (topical insufficient). Onychomycosis: oral terbinafine 12wk toes, 6wk fingers","Tinea versicolor (Malassezia): spaghetti-and-meatballs KOH. ID reaction: distant eczematous reaction to fungal infection. Tinea capitis: kerion is inflammatory mass requiring oral antifungal + pred.",3,"apply",["tinea","fungal","terbinafine"],"derm-common"));
cards.push(c("card-tn3-derm-"+n++,"What is the ABCDE approach to evaluating pigmented lesions?","A: Asymmetry. B: Border irregularity. C: Color variation. D: Diameter >6mm. E: Evolution (most important). Ugly duckling sign. Any concerning lesion: excisional biopsy (not shave)","Nodular melanoma may not follow ABCDE (EFG: elevated, firm, growing). New changing pigmented lesion in >30 needs evaluation. Dermoscopy reduces unnecessary biopsies by 42%.",3,"apply",["ABCDE","melanoma","pigmented lesion"],"derm-common"));
cards.push(c("card-tn3-derm-"+n++,"What are common bacterial skin infections and their treatment?","Impetigo: mupirocin (local) or cephalexin. Cellulitis: cephalexin/cloxacillin. Abscess: I&D +/- antibiotics. MRSA: TMP-SMX or doxycycline. Erysipelas: penicillin/amoxicillin","Purulent cellulitis: cover MRSA. Non-purulent: streptococcal. Mark borders. Recurrent cellulitis: treat predisposing factors (edema, tinea pedis). Bullous impetigo always S.aureus.",3,"apply",["cellulitis","impetigo","MRSA"],"derm-common"));
cards.push(c("card-tn3-derm-"+n++,"What are the topical corticosteroid potency classes?","Superpotent (I): clobetasol. Potent (II-III): betamethasone dipropionate. Moderate (IV-V): triamcinolone. Mild (VI-VII): hydrocortisone 1%. Face/groin: mild only. Trunk: moderate-potent","SE: atrophy, striae (irreversible), telangiectasia, perioral dermatitis. Limit potent to 2-4wk. Ointments > creams in potency. Weekend-only maintenance reduces SE. Steroid holidays prevent tachyphylaxis.",3,"recall",["topical steroids","potency"],"derm-common"));

// DERMATOLOGY - CANCER (10)
cards.push(c("card-tn3-derm-"+n++,"What are the types of skin cancer and clinical features?","BCC (80%): pearly papule, telangiectasia, rolled borders. SCC (15%): scaly keratotic plaque on sun-damaged skin. Melanoma (5%): ABCDE features, most lethal","BCC subtypes: nodular, superficial, morpheaform (aggressive). SCC risk: UV, immunosuppression, chronic wounds. AK precursor to SCC. Transplant recipients: 65-250x SCC risk.",3,"recall",["skin cancer","BCC","SCC","melanoma"],"derm-cancer"));
cards.push(c("card-tn3-derm-"+n++,"How does Breslow thickness guide melanoma management?","In situ: 0.5cm margin. <=1mm: 1cm. 1-2mm: 1-2cm. >2mm: 2cm margin. SLNB for >=0.8mm or ulcerated. Breslow is strongest prognostic factor","Clark level less important. Stage I (thin, node-neg): 95% 5yr survival. Stage IV: immunotherapy transformed prognosis. SLNB positive: adjuvant immunotherapy considered.",5,"apply",["melanoma","Breslow","excision margins"],"derm-cancer"));
cards.push(c("card-tn3-derm-"+n++,"What are the indications for Mohs surgery?","BCC/SCC in critical areas (face, ears, hands, genitals), recurrent tumors, ill-defined borders, aggressive subtypes (morpheaform BCC, perineural SCC), immunosuppressed","99% cure BCC primary, 95% recurrent. 100% margin examination in real-time. Tissue-sparing for cosmetic sites. Standard excision with margins appropriate for trunk/extremity low-risk tumors.",4,"apply",["Mohs surgery","BCC","SCC"],"derm-cancer"));
cards.push(c("card-tn3-derm-"+n++,"How are actinic keratoses managed?","Individual: cryotherapy. Field: 5-FU topical 4wk, imiquimod 4-16wk, PDT. Sun protection to prevent recurrence. SCC transformation <1%/yr per lesion but cumulative risk significant","Field cancerization: entire sun-damaged area at risk. SCC arising in AK: hard, thickened, non-healing - biopsy. Multiple AKs warrant field therapy. Diclofenac gel is gentler alternative.",3,"apply",["actinic keratosis","cryotherapy","5-FU"],"derm-cancer"));
cards.push(c("card-tn3-derm-"+n++,"What melanoma follow-up is recommended after treatment?","Stage IA-IIA: exam q6-12mo x5yr then annually. IIB+: q3-6mo x3yr, then q6-12mo to 5yr, then annually. Imaging for IIB+. Lifelong skin surveillance. Self-skin exam education","80% recurrence within 3yr. Adjuvant pembrolizumab for IIB-IIIC. Family: 2-3x risk increase, consider genetics if multiple melanomas or CDKN2A pattern.",4,"apply",["melanoma","follow-up","surveillance"],"derm-cancer"));
cards.push(c("card-tn3-derm-"+n++,"What is dermoscopy and how does it aid diagnosis?","10x magnification with polarized light. BCC: arborizing vessels, blue-gray nests. Melanoma: irregular network, blue-white veil, irregular dots. Improves melanoma sensitivity 70%->90%+","Two-step: 1) melanocytic? 2) benign or suspicious? Reduces unnecessary biopsies 42%. Requires training. Structured approaches: pattern analysis, ABCD dermoscopy score.",3,"recall",["dermoscopy","diagnosis","skin cancer"],"derm-cancer"));
cards.push(c("card-tn3-derm-"+n++,"What systemic treatments exist for advanced melanoma?","Immunotherapy: anti-PD1 (nivolumab, pembrolizumab) +/- anti-CTLA4 (ipilimumab). Targeted: BRAFi (dabrafenib) + MEKi (trametinib) for BRAF V600E. Combination immunotherapy ~60% response","5yr survival metastatic now ~50% with immunotherapy (was <10%). BRAF mutation in ~50%. Immune-related AE: colitis, pneumonitis, hepatitis, endocrinopathies - prompt recognition essential.",5,"apply",["melanoma","immunotherapy","BRAF"],"derm-cancer"));
cards.push(c("card-tn3-derm-"+n++,"How is BCC managed by risk level?","Low-risk nodular/superficial: excision (4mm margin) or C&E. High-risk (morpheaform, recurrent, facial): Mohs. Superficial: imiquimod/5-FU/PDT options. Advanced: vismodegib (hedgehog inhibitor)","BCC rarely metastasizes (<0.5%) but locally destructive. Gorlin syndrome: multiple BCCs, PTCH1 mutation. Vismodegib for unresectable. 5yr recurrence: standard 5-8%, Mohs 1%.",3,"apply",["BCC","management","vismodegib"],"derm-cancer"));
cards.push(c("card-tn3-derm-"+n++,"What melanoma screening/prevention is recommended for transplant recipients?","Annual dermatology from 1yr post-transplant. Monthly self-exam. SCC 65-250x, BCC 10x, melanoma 2-5x risk. Aggressive sun protection. Consider acitretin for SCC chemoprevention","Skin cancer most common malignancy in transplant. SCC>BCC (reverse of general population). HPV contributes. Consider mTOR inhibitor (sirolimus) switch to reduce skin cancer risk.",4,"apply",["transplant","skin cancer","screening"],"derm-cancer"));
cards.push(c("card-tn3-derm-"+n++,"What is the approach to a suspected SCC?","Biopsy any non-healing, keratotic nodule/plaque on sun-damaged skin. Staging for high-risk: >2cm, >2mm depth, perineural invasion, immunosuppressed. Excision with 4-6mm margins or Mohs for high-risk","SCC metastatic potential 2-5% (higher in immunosuppressed, lip, ear). High-risk SCC: consider adjuvant radiation. Cemiplimab (anti-PD1) for advanced/unresectable SCC. Differentiate from keratoacanthoma (rapid growth, keratin plug).",4,"apply",["SCC","biopsy","management"],"derm-cancer"));

// HEMATOLOGY - ANEMIA (15)
cards.push(c("card-tn3-hem-"+n++,"How is anemia classified by MCV and what are common causes?","Microcytic (MCV<80): iron deficiency, thalassemia, chronic disease, sideroblastic. Normocytic (80-100): chronic disease, renal, acute blood loss, hemolysis, bone marrow failure. Macrocytic (>100): B12/folate, liver disease, hypothyroid, MDS, drugs","First step: check MCV. Reticulocyte count distinguishes production (low retic) from destruction/loss (high retic). Iron deficiency is most common cause worldwide. Always investigate cause - never just treat the number.",3,"recall",["anemia","MCV","classification"],"hem-anemia"));
cards.push(c("card-tn3-hem-"+n++,"How are iron studies interpreted in iron deficiency vs anemia of chronic disease?","IDA: low ferritin (<30), low iron, high TIBC, low transferrin sat (<20%). ACD: normal/high ferritin (acute phase reactant), low iron, low TIBC, low transferrin sat. Combined: low ferritin settles it","Ferritin <30 is diagnostic of IDA (most useful single test). Ferritin 30-100 is indeterminate (may have coexistent IDA+ACD). Ferritin >100 essentially excludes IDA. Soluble transferrin receptor elevated in IDA, normal in ACD.",4,"apply",["iron studies","IDA","anemia of chronic disease"],"hem-anemia"));
cards.push(c("card-tn3-hem-"+n++,"What is the workup and management of iron deficiency anemia?","Workup: identify cause (menstrual loss, GI loss - scope if male or postmenopausal). Treatment: oral ferrous sulfate 300mg daily-TID (elemental iron 60-200mg/d) on empty stomach. IV iron if intolerant/malabsorption/severe","Take oral iron with vitamin C, avoid with tea/coffee/calcium/antacids. GI side effects common - try alternate-day dosing (better absorbed anyway per recent evidence). Check reticulocyte response at 1wk, Hb at 4-6wk. Continue 3-6mo to replete stores.",3,"apply",["IDA","iron replacement","management"],"hem-anemia"));
cards.push(c("card-tn3-hem-"+n++,"How is B12 deficiency diagnosed and treated?","Diagnosis: low serum B12 (<148 pmol/L), elevated methylmalonic acid (more specific), elevated homocysteine. Causes: pernicious anemia, vegan diet, metformin, malabsorption. Treat: IM B12 1000mcg daily x7, then weekly x4, then monthly","Neurological symptoms (subacute combined degeneration: dorsal columns + corticospinal tracts) may be irreversible if treatment delayed. Check folate simultaneously. Do NOT give folate alone if B12 deficient (worsens neuro). Oral B12 1000-2000mcg daily is acceptable if adherent.",4,"apply",["B12 deficiency","pernicious anemia","treatment"],"hem-anemia"));
cards.push(c("card-tn3-hem-"+n++,"What is the approach to hemolytic anemia?","Suspect if: normocytic anemia + high reticulocytes + high LDH + high indirect bilirubin + low haptoglobin. DAT (Coombs) positive: autoimmune. DAT negative: consider mechanical, intrinsic RBC defects","Intravascular: hemoglobinuria, very low haptoglobin (TTP/HUS, PNH, mechanical valves). Extravascular: splenomegaly (autoimmune, spherocytosis). Peripheral smear: schistocytes (MAHA), spherocytes (AIHA/HS), sickle cells, target cells (thalassemia).",4,"analyze",["hemolytic anemia","DAT","reticulocyte"],"hem-anemia"));
cards.push(c("card-tn3-hem-"+n++,"What are the causes and management of autoimmune hemolytic anemia?","Warm AIHA (IgG, 70%): idiopathic, lymphoma, SLE, drugs. Treat: prednisone 1mg/kg, rituximab, splenectomy. Cold agglutinin (IgM): infections (mycoplasma, EBV), lymphoma. Treat: avoid cold, rituximab","DAT positive confirms autoimmune etiology. Warm AIHA: do not transfuse unless life-threatening (crossmatch difficult). Cold AIHA: warm blood products through warmer. Corticosteroids less effective in cold AIHA. Always investigate for underlying lymphoma or SLE.",4,"apply",["AIHA","warm","cold agglutinin"],"hem-anemia"));
cards.push(c("card-tn3-hem-"+n++,"What is thalassemia and how does it differ from iron deficiency?","Both microcytic. Thalassemia: normal/high ferritin, target cells, elevated RBC count (elevated RDW in IDA), Mentzer index <13 (MCV/RBC). Alpha-thal: Hb electrophoresis may be normal. Beta-thal minor: elevated HbA2 >3.5%","Thalassemia trait: mild anemia, NO iron deficiency. Do NOT give iron (risk of overload). Beta-thal major: transfusion-dependent, chelation needed. Beta-thal intermedia: variable. HbH disease (3 alpha deletions): moderate anemia, Hb Bart in neonates.",3,"analyze",["thalassemia","iron deficiency","MCV"],"hem-anemia"));
cards.push(c("card-tn3-hem-"+n++,"What is the approach to pancytopenia?","DDx: aplastic anemia, MDS, leukemia (marrow infiltration), megaloblastic anemia, hypersplenism, infections (HIV, TB), medications. Workup: CBC with smear, reticulocytes, B12/folate, HIV, bone marrow biopsy","Aplastic anemia: hypocellular marrow. MDS: dysplastic marrow. Leukemia: blast infiltration. Megaloblastic: hypersegmented neutrophils, oval macrocytes. Drug causes: MTX, phenytoin, chemotherapy. Refer hematology urgently for suspected marrow failure.",4,"analyze",["pancytopenia","aplastic anemia","MDS"],"hem-anemia"));
cards.push(c("card-tn3-hem-"+n++,"What is thrombotic thrombocytopenic purpura (TTP) and how is it managed?","Pentad: MAHA (schistocytes), thrombocytopenia, renal dysfunction, neuro symptoms, fever. ADAMTS13 <10% diagnostic. Treatment: EMERGENT plasma exchange + steroids + caplacizumab. Do NOT transfuse platelets","TTP is a hematologic emergency (untreated mortality >90%). PLASMIC score predicts ADAMTS13 deficiency. Plasma exchange removes autoantibodies and replenishes ADAMTS13. Platelet transfusion WORSENS thrombosis. Caplacizumab (anti-vWF) reduces time to remission.",5,"apply",["TTP","ADAMTS13","plasma exchange"],"hem-anemia"));
cards.push(c("card-tn3-hem-"+n++,"How is sickle cell disease managed in Canada?","Hydroxyurea (first-line disease-modifying): increases HbF. Voxelotor (Hb S polymerization inhibitor). Crizanlizumab (anti-P-selectin). Transfusion for severe anemia/stroke prevention. Curative: bone marrow transplant","Acute crises: pain (IV fluids, opioids, NSAIDs), chest (antibiotics, transfusion, O2), stroke (exchange transfusion), splenic sequestration (transfusion). Penicillin prophylaxis until age 5. Pneumococcal vaccine. Newborn screening in all Canadian provinces.",4,"apply",["sickle cell","hydroxyurea","management"],"hem-anemia"));
cards.push(c("card-tn3-hem-"+n++,"When should anemia be investigated vs monitored in primary care?","Investigate immediately: symptomatic, Hb <100, rapid decline, unexpected. Refer hematology: unexplained cytopenias, suspected marrow failure, hemolysis, suspected malignancy. Transfuse: Hb <70 (restrictive strategy)","TRICC trial: restrictive transfusion (Hb<70) equivalent or superior to liberal (Hb<100) in most patients. Exception: ACS threshold Hb<80. Each unit raises Hb ~10g/L. Type and screen before transfusion. Monitor for transfusion reactions.",3,"apply",["anemia","transfusion","investigation"],"hem-anemia"));
cards.push(c("card-tn3-hem-"+n++,"What peripheral blood smear findings are diagnostic?","Schistocytes: MAHA (TTP/HUS/DIC). Spherocytes: AIHA, hereditary spherocytosis. Target cells: thalassemia, liver disease. Teardrop: myelofibrosis. Rouleaux: myeloma. Hypersegmented neutrophils: megaloblastic","Smear is often the most informative single test in anemia workup. Also look for: blasts (leukemia), Howell-Jolly bodies (asplenia), basophilic stippling (lead, thalassemia), bite cells (G6PD). Always correlate with clinical context.",3,"recall",["blood smear","schistocytes","hematology"],"hem-anemia"));
cards.push(c("card-tn3-hem-"+n++,"What are the causes and workup of macrocytic anemia?","Megaloblastic: B12/folate deficiency (hypersegmented neutrophils, oval macrocytes). Non-megaloblastic: liver disease, hypothyroid, MDS, reticulocytosis, drugs (MTX, hydroxyurea, AZT), alcohol","Check B12, folate, TSH, LFTs, reticulocyte count. If B12/folate normal and no obvious cause: bone marrow biopsy to evaluate for MDS. Alcohol causes macrocytosis even without anemia. MCV >115 strongly suggests megaloblastic or MDS.",3,"analyze",["macrocytic anemia","B12","MDS"],"hem-anemia"));
cards.push(c("card-tn3-hem-"+n++,"What is G6PD deficiency and how does it present?","X-linked recessive. Episodic hemolysis triggered by oxidative stress: infections, fava beans, drugs (dapsone, primaquine, sulfonamides, nitrofurantoin). Smear: bite cells, Heinz bodies","G6PD level may be NORMAL during acute hemolysis (young RBCs have higher G6PD). Retest 2-3 months after episode. Self-limited episode. Avoid known triggers. Common in Mediterranean, African, Asian descent.",3,"recall",["G6PD","hemolytic anemia","oxidative stress"],"hem-anemia"));
cards.push(c("card-tn3-hem-"+n++,"What is the approach to an elevated ferritin?","DDx: iron overload (hereditary hemochromatosis, transfusional), inflammation/infection, liver disease, malignancy, metabolic syndrome, hyperthyroidism. Check transferrin saturation: if >45% suspect hemochromatosis (HFE gene testing)","Ferritin is an acute phase reactant - elevated in inflammation. Hemochromatosis: autosomal recessive C282Y HFE mutation. Screen first-degree relatives. Treatment: phlebotomy targeting ferritin <50. Complications: cirrhosis, DM, cardiomyopathy, arthropathy, bronze skin.",3,"apply",["ferritin","hemochromatosis","iron overload"],"hem-anemia"));

// HEMATOLOGY - COAGULATION (10)
cards.push(c("card-tn3-hem-"+n++,"What are the DIC diagnostic criteria and management?","ISTH DIC score: platelets, fibrin markers (D-dimer), PT prolongation, fibrinogen level. Score >=5 = overt DIC. Management: treat underlying cause + supportive (platelets if <50k+bleeding, cryo if fibrinogen <1.5, FFP if PT prolonged+bleeding)","DIC is always secondary: sepsis, trauma, malignancy, obstetric (abruption, AFE), transfusion. Schistocytes on smear. Lab: low platelets, low fibrinogen, prolonged PT/PTT, elevated D-dimer. Do NOT give heparin routinely (only for thrombotic-predominant DIC).",5,"apply",["DIC","coagulopathy","fibrinogen"],"hem-coag"));
cards.push(c("card-tn3-hem-"+n++,"How is heparin-induced thrombocytopenia (HIT) diagnosed and managed?","4T score: Thrombocytopenia (>50% drop), Timing (5-10d), Thrombosis, no oTher cause. Confirm: anti-PF4/heparin ELISA then serotonin release assay. Manage: STOP all heparin, start non-heparin anticoagulant (argatroban, fondaparinux, DOAC)","HIT is prothrombotic despite low platelets - do NOT transfuse platelets. Occurs with both UFH and LMWH (more common UFH). 4T score low probability: continue heparin. Intermediate/high: stop heparin and test. Transition to warfarin only after platelets recover >150k.",5,"apply",["HIT","heparin","thrombocytopenia"],"hem-coag"));
cards.push(c("card-tn3-hem-"+n++,"What is the approach to an elevated INR/bleeding on warfarin?","INR 4.5-10 no bleeding: hold warfarin. INR >10 no bleeding: hold + oral vitamin K 2.5-5mg. Serious bleeding: hold warfarin + IV vitamin K 10mg + PCC (4-factor preferred) or FFP","Kcentra (4-factor PCC) reverses warfarin faster than FFP with lower volume. Fresh frozen plasma: 15mL/kg. Vitamin K IV onset 6-8h, PO 12-24h. For DOAC reversal: idarucizumab for dabigatran, andexanet alfa for factor Xa inhibitors, or PCC.",4,"apply",["warfarin","INR","vitamin K","PCC"],"hem-coag"));
cards.push(c("card-tn3-hem-"+n++,"What is the approach to a prolonged PTT with normal PT?","DDx: heparin contamination (most common), factor VIII/IX/XI/XII deficiency, von Willebrand disease, lupus anticoagulant. Mixing study: corrects = factor deficiency; does not correct = inhibitor (LA or factor inhibitor)","vWD is most common inherited bleeding disorder (1%). Type 1 (80%): quantitative. Type 2: qualitative. Type 3: absent. Treatment: DDAVP (type 1), vWF concentrate. Lupus anticoagulant paradoxically causes thrombosis not bleeding.",4,"analyze",["PTT","coagulation","mixing study"],"hem-coag"));
cards.push(c("card-tn3-hem-"+n++,"How is von Willebrand disease diagnosed and managed?","Diagnosis: bleeding history + low vWF antigen and/or activity (ristocetin cofactor) + low factor VIII. Type 1: DDAVP trial (desmopressin 0.3mcg/kg IV). Type 2/3: vWF-containing concentrate. Avoid ASA/NSAIDs","vWD most common inherited bleeding (affects 1%). Symptoms: mucocutaneous bleeding (menorrhagia, epistaxis, bruising, post-procedural). Perioperative: DDAVP 30min pre-procedure for Type 1 or vWF concentrate. Tranexamic acid as adjunct for mucosal bleeding.",3,"apply",["von Willebrand","DDAVP","bleeding disorder"],"hem-coag"));
cards.push(c("card-tn3-hem-"+n++,"What is the approach to suspected DVT/PE?","DVT: Wells score then D-dimer (if low probability) or US. PE: Wells/Geneva score then D-dimer or CTPA. Treatment: DOAC first-line (apixaban or rivaroxaban no bridging needed) x3-6mo. Provoked vs unprovoked determines duration","DOAC preferred over warfarin (no INR monitoring, fewer interactions). Exceptions: APS (warfarin), severe renal (warfarin), pregnancy (LMWH), cancer (LMWH or DOAC). Unprovoked VTE: consider extended anticoagulation. Massive PE: thrombolysis or embolectomy.",4,"apply",["DVT","PE","anticoagulation","DOAC"],"hem-coag"));
cards.push(c("card-tn3-hem-"+n++,"What are the indications for thrombophilia testing?","Consider testing: unprovoked VTE <50yr, recurrent VTE, unusual site (cerebral, splanchnic, hepatic), strong family history, recurrent pregnancy loss. Do NOT test: provoked VTE, acute VTE (false results), on anticoagulation","Common thrombophilias: Factor V Leiden (most common), prothrombin G20210A, protein C/S deficiency, antithrombin deficiency, antiphospholipid syndrome. Testing rarely changes management. Do not test the general population or before OCP use routinely.",3,"recall",["thrombophilia","VTE","Factor V Leiden"],"hem-coag"));
cards.push(c("card-tn3-hem-"+n++,"How is immune thrombocytopenia (ITP) managed?","Adults: observation if PLT>30k and no bleeding. Treatment if <30k or bleeding: prednisone 1mg/kg x2-4wk, IVIG for rapid rise (pre-procedure), rituximab, TPO-RA (eltrombopag, romiplostim). Splenectomy for refractory","ITP is diagnosis of exclusion: isolated thrombocytopenia, normal smear (except large platelets), no other cause. Rule out pseudothrombocytopenia (EDTA-dependent clumping). In adults consider secondary causes: HIV, HCV, SLE, CLL. Platelet transfusion only for life-threatening bleeding.",4,"apply",["ITP","thrombocytopenia","management"],"hem-coag"));
cards.push(c("card-tn3-hem-"+n++,"What transfusion reactions should be recognized and how are they managed?","Acute hemolytic: ABO incompatibility, fever/chills/flank pain/hemoglobinuria. STOP transfusion, IV NS, send samples. Febrile non-hemolytic: most common, premedicate. Allergic: urticaria (antihistamine). Anaphylactic: IgA deficiency. TRALI: respiratory distress 6h","TRALI: non-cardiogenic pulmonary edema within 6h, supportive care. TACO: volume overload, diuretics. Delayed hemolytic: 3-28 days, extravascular hemolysis from anamnestic response. Bacterial contamination: platelets > RBCs. Report all reactions to blood bank.",4,"recall",["transfusion reaction","TRALI","TACO"],"hem-coag"));
cards.push(c("card-tn3-hem-"+n++,"What is the perioperative management of anticoagulation?","Warfarin: stop 5d before, bridge with LMWH if high-risk (mechanical valve, recent VTE). DOACs: stop 2-3d before (renal-dependent). Restart 24-72h post-op depending on bleeding risk. ASA: continue for most procedures","BRIDGE trial: no bridging needed for most AF patients on warfarin (lower bleeding, similar stroke). High-risk bridging: mechanical mitral valve, recent VTE <3mo. PAUSE trial guides DOAC timing by CrCl and procedure bleeding risk.",4,"apply",["perioperative","anticoagulation","bridging"],"hem-coag"));

// HEMATOLOGY - LYMPHOMA (10)
cards.push(c("card-tn3-hem-"+n++,"What is the Ann Arbor staging system for lymphoma?","Stage I: single lymph node region. II: >=2 regions same side of diaphragm. III: both sides of diaphragm. IV: disseminated extranodal (bone marrow, liver). B symptoms: fever >38, night sweats, >10% weight loss 6mo","Staging determines treatment approach. PET-CT is standard for FDG-avid lymphomas (most HL, DLBCL). CT for low-grade NHL. B symptoms confer worse prognosis. Lugano classification has replaced Ann Arbor for response assessment.",4,"recall",["Ann Arbor","staging","lymphoma"],"hem-lymphoma"));
cards.push(c("card-tn3-hem-"+n++,"How is Hodgkin lymphoma diagnosed and treated?","Diagnosis: Reed-Sternberg cells (owl-eye) on biopsy, CD15+/CD30+. Treatment: early favorable: ABVD x2 + radiation. Early unfavorable/advanced: ABVD x4-6. PET-adapted: escalate to BEACOPP if PET+ after 2 cycles","HL: bimodal age (20s and >60). Excellent prognosis: early stage >90% cure. Contiguous spread pattern. ABVD: doxorubicin, bleomycin, vinblastine, dacarbazine. Bleomycin pulmonary toxicity: monitor PFTs. Long-term: secondary malignancies, CV disease from radiation.",4,"apply",["Hodgkin lymphoma","ABVD","Reed-Sternberg"],"hem-lymphoma"));
cards.push(c("card-tn3-hem-"+n++,"What are the major subtypes of non-Hodgkin lymphoma and their management?","Aggressive: DLBCL (most common NHL) - treat with R-CHOP x6, curable in ~60%. Indolent: follicular lymphoma - watch-and-wait if asymptomatic, BR or R-CHOP when symptomatic. Very aggressive: Burkitt - urgent intensive chemo + CNS prophylaxis","NHL is much more common than HL. Non-contiguous spread (any stage at presentation). Aggressive NHL is potentially curable with chemo. Indolent NHL is generally incurable but has long natural history. Transformation of indolent to aggressive is a feared complication.",4,"apply",["NHL","DLBCL","R-CHOP","follicular"],"hem-lymphoma"));
cards.push(c("card-tn3-hem-"+n++,"What is the approach to a patient presenting with lymphadenopathy?","Red flags: >2cm, supraclavicular, fixed/hard, >4-6wk, B symptoms, weight loss, hepatosplenomegaly. Workup: CBC, LDH, imaging (CT), excisional biopsy (NOT FNA for suspected lymphoma)","Most lymphadenopathy is reactive/infectious. Supraclavicular (especially left/Virchow) highly suspicious for malignancy. Excisional biopsy preserves architecture for diagnosis. FNA insufficient for lymphoma subtyping. Generalized: consider HIV, SLE, lymphoma, infections.",3,"apply",["lymphadenopathy","biopsy","workup"],"hem-lymphoma"));
cards.push(c("card-tn3-hem-"+n++,"What is tumor lysis syndrome and how is it prevented?","Lab: hyperuricemia, hyperkalemia, hyperphosphatemia, hypocalcemia, elevated LDH, elevated Cr. Prevention: IV hydration + allopurinol (moderate risk) or rasburicase (high risk). Treat: aggressive hydration, rasburicase, cardiac monitoring, dialysis if needed","TLS risk highest in rapidly proliferating tumors: Burkitt, ALL, high tumor burden. Can be spontaneous. Cairo-Bishop criteria for diagnosis. Rasburicase (recombinant urate oxidase) rapidly reduces uric acid. CI in G6PD deficiency. Monitor labs q6-8h during treatment.",5,"apply",["tumor lysis syndrome","rasburicase","prevention"],"hem-lymphoma"));
cards.push(c("card-tn3-hem-"+n++,"What is the approach to chronic lymphocytic leukemia (CLL)?","Diagnosis: lymphocytosis >5x10^9/L with clonal B-cells (CD5+/CD19+/CD23+). Rai/Binet staging. Many patients watch-and-wait. Treat indications: cytopenias, B symptoms, rapid doubling, bulky nodes. First-line: BTKi (ibrutinib) or venetoclax-based","CLL most common adult leukemia. Smudge cells on smear. Richter transformation to DLBCL in 5-10%. Hypogammaglobulinemia increases infection risk. AIHA and ITP can complicate CLL. Del(17p)/TP53 mutation: poor prognosis, BTKi or venetoclax preferred.",4,"apply",["CLL","ibrutinib","venetoclax"],"hem-lymphoma"));
cards.push(c("card-tn3-hem-"+n++,"What is multiple myeloma: diagnosis, staging, and treatment?","Diagnostic criteria: clonal BM plasma cells >=10% + myeloma-defining event (CRAB: Calcium elevated, Renal failure, Anemia, Bone lesions) or biomarker (>=60% BM plasma cells, FLC ratio >=100, >1 MRI lesion)","SPEP/UPEP, serum free light chains, BM biopsy. Staging: R-ISS. Treatment: induction with triplet (VRd: bortezomib, lenalidomide, dex) then autologous SCT if eligible. Bone protection: zoledronic acid. Avoid nephrotoxins. Skeletal survey or low-dose whole-body CT (not bone scan).",5,"apply",["multiple myeloma","CRAB","VRd"],"hem-lymphoma"));
cards.push(c("card-tn3-hem-"+n++,"What oncologic emergencies should be recognized in hematologic malignancies?","Febrile neutropenia (ANC<0.5+fever): blood cultures + empiric broad-spectrum abx immediately (piperacillin-tazobactam or meropenem). Tumor lysis syndrome. Hyperviscosity (myeloma): plasmapheresis. Leukostasis (WBC>100k): leukapheresis","Febrile neutropenia: mortality risk. Do NOT wait for cultures to start antibiotics. Door-to-antibiotic time <60min. SVC syndrome: urgent radiation or stenting. Spinal cord compression: urgent MRI + dexamethasone + radiation/surgery.",5,"apply",["oncologic emergency","febrile neutropenia","leukostasis"],"hem-lymphoma"));
cards.push(c("card-tn3-hem-"+n++,"What is the approach to an incidental finding of elevated WBC?","Reactive leukocytosis (most common): infection, stress, steroids, smoking. If persistent or very high (>50k): check peripheral smear for blasts. CLL: mature lymphocytes >5k. CML: left shift with all stages of myeloid maturation, BCR-ABL+","CML: Philadelphia chromosome BCR-ABL. Treatment: TKI (imatinib) with excellent prognosis. AML: blasts >20% in marrow, Auer rods. ALL: blasts, more common in children. Leukemoid reaction: very high WBC from infection/inflammation, LAP score high (low in CML).",3,"analyze",["leukocytosis","CML","leukemia"],"hem-lymphoma"));
cards.push(c("card-tn3-hem-"+n++,"What is monoclonal gammopathy of undetermined significance (MGUS)?","MGUS: M-protein <30g/L, BM plasma cells <10%, no CRAB criteria, no amyloidosis. 1% per year risk of progression to myeloma. Monitor annually: SPEP, CBC, calcium, creatinine","MGUS is common (3% of >50yr). Smouldering myeloma: M-protein 30g/L or 10-60% BM plasma cells, no CRAB. Higher risk of progression (10%/yr for first 5yr). Risk stratification: M-protein size, non-IgG type, abnormal FLC ratio predict progression.",3,"recall",["MGUS","myeloma","monoclonal"],"hem-lymphoma"));

console.log("Derm+Hem cards added. Total: " + cards.length);
fs.writeFileSync("C:/dev/srs-mccqe1/data/_parts12345.json", JSON.stringify(cards));
console.log("Saved");
