const fs = require('fs');
const cards = [];
let n = 1;
function add(topicId, q, a, ex, diff, bloom, tags) {
  cards.push({ id: `card-tn2-peds-${n++}`, question: q, answer: a, explanation: ex, difficulty: diff, bloomLevel: bloom, tags, topicId });
}

// PEDS-DEVELOPMENT (15)
add('peds-development','What are the key Denver developmental milestones at 2, 4, 6, 9, and 12 months?','2mo: social smile, lifts head prone. 4mo: reaches for objects, rolls front-to-back, laughs. 6mo: sits unsupported, transfers objects, babbles. 9mo: pulls to stand, pincer grasp developing, stranger anxiety, says mama/dada nonspecific. 12mo: walks with one hand held, 1-3 words, pincer grasp mature.',
'The Denver Developmental Screening Test (DDST-II) assesses gross motor, fine motor-adaptive, language, and personal-social domains. Canadian Paediatric Society recommends developmental surveillance at every well-child visit with standardized screening at 18 and 24 months.',3,'recall',['Denver milestones','development','screening','pediatrics']);

add('peds-development','What are the developmental milestones at 18 months, 2 years, 3 years, and 4 years?','18mo: walks alone, stacks 2-4 blocks, 10-25 words, feeds with spoon, points. 2yr: runs, kicks ball, stacks 6 blocks, 2-word phrases, 50+ words, parallel play. 3yr: tricycle, copies circle, 3-word sentences, knows name/age, group play. 4yr: hops, copies cross, tells stories, cooperative play, dresses independently.',
'Language development is the most sensitive indicator of overall development. Failure to produce single words by 18 months or 2-word phrases by 24 months warrants referral. CPS recommends M-CHAT-R/F screening for autism at 18 and 24 months.',3,'recall',['developmental milestones','language development','pediatrics']);

add('peds-development','What are the red flags for autism spectrum disorder and when should screening occur?','Red flags: no babbling by 12 months, no pointing/gesturing by 12 months, no single words by 16 months, no 2-word phrases by 24 months, loss of previously acquired skills at any age, lack of joint attention, no pretend play by 18 months. Screen with M-CHAT-R/F at 18 and 24 months.',
'CPS and AAP recommend universal ASD screening at 18 and 24 months. Early intervention (before age 3) significantly improves outcomes. DSM-5 criteria: persistent deficits in social communication AND restricted/repetitive behaviors, present from early childhood.',4,'apply',['autism','ASD','screening','red flags','pediatrics']);

add('peds-development','What is the approach to a child with global developmental delay?','Defined as significant delay (>=2 SD below mean) in >=2 developmental domains. Workup: detailed history (prenatal, birth, family), physical exam (dysmorphology, neurocutaneous signs), genetic testing (chromosomal microarray first-line), metabolic screen (TSH, amino acids, organic acids), MRI brain, hearing and vision testing.',
'Chromosomal microarray has replaced karyotype as first-line genetic test (diagnostic yield 15-20%). Fragile X testing in all males with unexplained GDD. Inborn errors of metabolism are rare but treatable causes. Canadian guidelines recommend early referral to developmental pediatrics.',4,'apply',['global developmental delay','workup','genetic testing','pediatrics']);

add('peds-development','What is the differential diagnosis for speech delay in a toddler?','Hearing loss (most important to exclude), autism spectrum disorder, intellectual disability, environmental deprivation/bilingualism (expressive only, receptive normal), expressive language disorder, oral motor dysfunction (dysarthria), selective mutism, genetic syndromes (Down, Fragile X).',
'CPS recommends audiological assessment for any child with speech delay. Universal Newborn Hearing Screening (UNHS) is standard in Canadian provinces. Bilingualism does NOT cause language delay-total vocabulary across both languages should be considered.',3,'analyze',['speech delay','hearing loss','differential diagnosis','pediatrics']);

add('peds-development','What are the primitive reflexes, when do they appear, and when should they disappear?','Moro: birth-4mo. Palmar grasp: birth-6mo. Rooting: birth-4mo. Tonic neck (ATNR): birth-6mo. Parachute reflex: appears 8-9mo, persists. Babinski: birth-12mo (up to 2yr normal). Persistence beyond expected age suggests upper motor neuron pathology.',
'Persistence of primitive reflexes beyond normal timeframes suggests cerebral palsy or other CNS pathology. Absence at birth suggests CNS depression. The parachute reflex (protective extension) is unique in that it appears and persists-its absence by 12 months is concerning.',3,'recall',['primitive reflexes','Moro','neurological development','pediatrics']);

add('peds-development','What is cerebral palsy, its classification, and management approach?','CP: non-progressive motor disorder from injury to developing brain. Classification by motor type: spastic (70-80%), dyskinetic, ataxic, mixed. By distribution: hemiplegia, diplegia, quadriplegia. Management: multidisciplinary (PT, OT, speech), botulinum toxin for spasticity, orthopedic surgery, baclofen pump for generalized spasticity.',
'CP is the most common physical disability in children (2-3 per 1000). Prematurity is the strongest risk factor. MRI shows periventricular leukomalacia in premature and hypoxic-ischemic injury in term infants. Canadian CP registries track outcomes. Early intervention improves function.',4,'apply',['cerebral palsy','spasticity','classification','pediatrics']);

add('peds-development','What growth parameters are monitored in well-child visits and when are they concerning?','Weight, length/height, head circumference (until 2 years), BMI (after 2 years). Concerning: crossing 2 major percentile lines, weight <3rd or >97th percentile, head circumference >97th (hydrocephalus, megalencephaly) or <3rd (microcephaly). Weight faltering: weight-for-age <2nd percentile or crossing down 2 lines.',
'Canadian Paediatric Society recommends WHO growth charts for children 0-5 years and CDC charts for 5-19 years. Failure to thrive is a clinical sign, not a diagnosis-workup includes feeding history, caloric intake, organic causes (celiac, CF, GERD), and psychosocial assessment.',3,'apply',['growth monitoring','growth charts','failure to thrive','pediatrics']);

add('peds-development','What is the Rourke Baby Record and what does it cover?','The Rourke Baby Record is a Canadian evidence-based health supervision guide for well-baby/child visits from birth to 5 years. It covers: growth monitoring, nutrition, developmental milestones, immunizations, physical exam, screening (hearing, vision, dental, anemia, lead), anticipatory guidance, and parental concerns.',
'The Rourke Baby Record is updated regularly and used across Canada as the standard well-child visit template. It integrates CPS, Dietitians of Canada, and CFPC recommendations. Key screening: hemoglobin at 9-12 months, dental assessment by 12 months, vision screening at 3-5 years.',2,'recall',['Rourke Baby Record','well-child visit','screening','pediatrics']);

add('peds-development','What are the screening recommendations for iron deficiency in Canadian infants?','Screen hemoglobin at 9-12 months for all infants. Risk factors: prematurity, low birth weight, exclusive breastfeeding beyond 6 months without iron supplementation, cow milk before 9-12 months, low socioeconomic status, Indigenous populations. Iron supplementation 1mg/kg/day recommended for exclusively breastfed infants starting at 4-6 months.',
'Iron deficiency is the most common nutritional deficiency in Canadian infants. CPS recommends iron-fortified cereals as first complementary food. Iron deficiency (even without anemia) affects neurodevelopment. Cow milk before 9 months increases risk due to low iron content and occult GI blood loss.',3,'apply',['iron deficiency','anemia','infant nutrition','pediatrics']);

add('peds-development','What are the key features of fetal alcohol spectrum disorder (FASD)?','Sentinel facial features: short palpebral fissures, smooth philtrum, thin upper lip. CNS: microcephaly, structural brain abnormalities, cognitive impairment, behavioral issues (ADHD-like, executive dysfunction). Growth: prenatal and/or postnatal growth deficiency. Confirmed maternal alcohol exposure. Canadian Diagnostic Guidelines use 4-digit code.',
'FASD prevalence in Canada is estimated at 1-5% (higher in some Indigenous communities). The 2016 Canadian FASD Diagnostic Guidelines require multidisciplinary assessment. No safe level of alcohol in pregnancy. Prevention through public health messaging is the primary strategy.',4,'recall',['FASD','fetal alcohol syndrome','teratogen','pediatrics']);

add('peds-development','When should a child be referred for developmental assessment vs monitored?','Refer immediately: any loss of milestones (regression), no babbling/gestures by 12 months, no words by 18 months, no 2-word phrases by 24 months, not walking by 18 months. Monitor with closer follow-up: mild delay in one domain, family history of late talkers, environmental factors identified.',
'CPS recommends a low threshold for referral. Developmental regression at any age is a red flag for neurodegenerative disease, ASD, or Rett syndrome and warrants urgent investigation including metabolic and genetic workup. Wait-and-see approach is inappropriate for regression.',4,'apply',['developmental referral','regression','red flags','pediatrics']);

add('peds-development','What anticipatory guidance should be provided at key well-child visits?','Newborn: safe sleep (back to sleep, firm mattress, no co-sleeping), breastfeeding support. 2-6mo: tummy time, car seat safety. 6-12mo: choking hazards, water safety, introduction of solids. 1-2yr: dental care, limit screen time, poison prevention. 3-5yr: helmet use, stranger safety, school readiness.',
'CPS Caring for Kids provides evidence-based anticipatory guidance. Screen time recommendations: avoid for <2 years, limit to <1 hour/day ages 2-5. Safe sleep practices reduce SIDS risk. Canadian car seat guidelines: rear-facing as long as possible (minimum to 2 years/weight limit).',2,'recall',['anticipatory guidance','well-child','safety','pediatrics']);

add('peds-development','What is the approach to a child with short stature?','Evaluate growth velocity (most important), bone age, mid-parental height. Investigations: CBC, ESR, electrolytes, creatinine, TSH, celiac screen (TTG-IgA), IGF-1, bone age X-ray. Most common causes: familial short stature (normal growth velocity, bone age = chronological age) and constitutional delay (delayed bone age, delayed puberty, catches up).',
'Pathological short stature: growth velocity <25th percentile, height >2 SD below mid-parental target, crossing percentiles downward. Consider: GH deficiency, Turner syndrome (karyotype in all short girls), hypothyroidism, celiac disease, chronic disease. Canadian Pediatric Endocrine Group guidelines address GH therapy indications.',4,'apply',['short stature','growth','endocrine','pediatrics']);

add('peds-development','What are the key differences between ADHD, ASD, and intellectual disability in presentation?','ADHD: inattention, hyperactivity, impulsivity; normal social skills; age-appropriate cognitive function. ASD: social communication deficits, restricted/repetitive behaviors; may have normal or impaired IQ; onset <3 years. ID: significant cognitive impairment (IQ <70) with adaptive function deficits; may have social interest. Comorbidity is common (30% overlap).',
'DSM-5 allows dual diagnosis of ADHD + ASD (previously exclusive). Canadian guidelines recommend comprehensive psychoeducational assessment. ADHD affects 5-7% of Canadian children. First-line treatment: methylphenidate or amphetamine for ADHD; behavioral interventions for ASD.',3,'analyze',['ADHD','ASD','intellectual disability','differential','pediatrics']);

// PEDS-FEVER (15)
add('peds-fever','What is the approach to fever in infants <3 months (step-by-step)?','0-28 days: ALL febrile neonates (>=38°C rectal) need full septic workup (blood culture, urine, LP, CXR if respiratory symptoms) + empiric IV antibiotics (ampicillin + gentamicin or cefotaxime). 29-60 days: septic workup, consider low-risk criteria (Rochester/Philadelphia) for observation. 61-90 days: risk stratify-well-appearing with normal urinalysis may be managed with close follow-up.',
'Serious bacterial infection (SBI) rate in febrile neonates <28 days is 10-15%, making full workup mandatory. UTI is the most common SBI in febrile infants. CPS guidelines recommend LP for all febrile neonates <30 days. HSV should be considered (acyclovir if risk factors).',5,'apply',['febrile infant','neonatal sepsis','workup','pediatrics']);

add('peds-fever','What are the Rochester criteria for identifying low-risk febrile infants?','Low risk if ALL present: previously healthy term infant, no focal infection on exam, well-appearing, WBC 5,000-15,000, band count <1,500, urinalysis normal (<=10 WBC/HPF), stool <=5 WBC/HPF if diarrhea. Low-risk infants (29-60 days) may be managed as outpatient with close follow-up in 24h.',
'Rochester criteria have 98-99% NPV for SBI. These criteria do NOT apply to neonates <28 days. Canadian practice varies-some centres still admit all febrile infants <60 days. Newer biomarkers (procalcitonin) are being integrated into risk stratification algorithms.',4,'apply',['Rochester criteria','low-risk febrile infant','risk stratification','pediatrics']);

add('peds-fever','What is the management of simple vs complex febrile seizures?','Simple: generalized, <15 min, single episode in 24h, age 6mo-5yr. No workup needed (no EEG, no imaging, no LP unless meningitis suspected). Reassurance, fever management education. Complex: focal, >15 min, recurrent in 24h, or age <6 months. Requires investigation: LP (especially if <12mo), consider EEG and MRI.',
'CPS guidelines state simple febrile seizures do not increase epilepsy risk above baseline (1%). Risk of recurrence: 30% overall, 50% if first seizure <12 months. Antipyretics do NOT prevent febrile seizures. Intermittent diazepam can be considered for recurrent febrile seizures with high parental anxiety.',3,'apply',['febrile seizure','simple','complex','management','pediatrics']);

add('peds-fever','What are the common causes of fever and rash in pediatric patients and their key distinguishing features?','Measles: cough/coryza/conjunctivitis, Koplik spots, cephalocaudal maculopapular rash. Roseola (HHV-6): high fever 3-5 days then rash appears as fever breaks. Scarlet fever: sandpaper rash, pastia lines, strawberry tongue, GAS pharyngitis. Varicella: crops of vesicles in different stages. Kawasaki: fever >5 days, conjunctivitis, rash, extremity changes, oral changes, lymphadenopathy.',
'Kawasaki disease is the most important not to miss due to coronary artery aneurysm risk (25% untreated). Treatment with IVIG within 10 days reduces aneurysm risk to <5%. Canadian Paediatric Society guidelines outline diagnostic criteria (fever >=5 days + 4/5 features, or incomplete KD with echo findings).',4,'analyze',['fever and rash','exanthem','Kawasaki','pediatrics']);

add('peds-fever','What is the definition and management of Kawasaki disease?','Diagnostic criteria: fever >=5 days + >=4 of 5: bilateral non-exudative conjunctivitis, oral changes (strawberry tongue, cracked lips), polymorphous rash, extremity changes (edema, erythema, desquamation), cervical lymphadenopathy (>=1.5cm unilateral). Treatment: IVIG 2g/kg single dose + high-dose ASA (80-100mg/kg/day until afebrile, then 3-5mg/kg/day for 6-8 weeks).',
'Incomplete Kawasaki (fever >=5 days + 2-3 criteria) is diagnosed with supporting lab/echo findings. Echocardiogram at diagnosis, 2 weeks, and 6-8 weeks. Coronary aneurysm risk: 25% untreated, <5% with IVIG. CPS guidelines recommend retreatment with IVIG or IV methylprednisolone for IVIG-resistant cases.',5,'apply',['Kawasaki disease','IVIG','coronary aneurysm','pediatrics']);

add('peds-fever','What is the approach to the child with recurrent fever?','Differential: periodic fever syndromes (PFAPA: periodic fever, aphthous stomatitis, pharyngitis, adenitis-most common in children), cyclic neutropenia, familial Mediterranean fever, immunodeficiency, occult infections, malignancy. Workup: CBC with differential, ESR, CRP during episodes, genetic testing for autoinflammatory syndromes.',
'PFAPA is the most common periodic fever syndrome in childhood, with clockwork febrile episodes every 3-6 weeks responding dramatically to single-dose corticosteroids. CPS recommends referral to pediatric rheumatology or immunology for recurrent unexplained fevers.',3,'analyze',['recurrent fever','PFAPA','periodic fever','pediatrics']);

add('peds-fever','What are the indications for blood cultures in febrile children?','All febrile neonates <28 days. Febrile infants 1-3 months with risk factors. Children with toxic appearance, petechial rash, indwelling lines/devices, immunocompromised, sickle cell disease, unimmunized, prolonged fever >5 days without source, or suspected endocarditis/osteomyelitis.',
'Blood culture yield in well-appearing febrile children >3 months is low (<2%) and not routinely indicated if immunized. Occult bacteremia has declined dramatically with pneumococcal and Hib conjugate vaccination. Canadian microbiology guidelines recommend appropriate volume collection.',3,'apply',['blood cultures','febrile child','bacteremia','pediatrics']);

add('peds-fever','How does the approach to fever differ in immunocompromised children?','Febrile neutropenia (ANC <500 + temp >=38.3°C once or >=38°C sustained 1h): EMERGENCY. Immediate blood cultures (peripheral + central line if present), empiric broad-spectrum antibiotics within 1 hour (piperacillin-tazobactam or cefepime). Do NOT wait for culture results. Add vancomycin if line infection suspected.',
'Febrile neutropenia carries 5-10% mortality if antibiotics are delayed. Canadian Paediatric Cancer guidelines mandate antibiotic administration within 60 minutes of triage. Fungal coverage (caspofungin or amphotericin) added if fever persists >96h on broad-spectrum antibiotics.',5,'apply',['febrile neutropenia','immunocompromised','oncology','pediatrics']);

add('peds-fever','What is the recommended approach to UTI in febrile infants and children?','Febrile infants <2 years with no clear fever source: catheterized urine sample (bag specimens are unreliable). Diagnosis: positive urinalysis (LE, nitrites, pyuria) + positive culture (>50,000 CFU/mL single organism catheter specimen). Treatment: IV antibiotics for toxic/young infants, oral cephalosporin for well-appearing >2 months. Renal ultrasound after first febrile UTI. VCUG for recurrent UTI or abnormal US.',
'UTI is the most common SBI in febrile infants. CPS guidelines recommend catheterized specimen for diagnosis. E. coli causes 80% of pediatric UTIs. RIVUR trial showed antibiotic prophylaxis reduces recurrence in VUR but with antibiotic resistance concerns. DMSA scan for renal scarring assessment.',4,'apply',['UTI','febrile infant','urine culture','VCUG','pediatrics']);

add('peds-fever','What are the clinical features and management of meningitis in children?','Bacterial meningitis: fever, headache, neck stiffness, altered consciousness, petechial rash (meningococcal). Infants: irritability, bulging fontanelle, poor feeding. LP: elevated WBC (PMN predominant), low glucose (<2.2 or <40% serum), elevated protein. Empiric treatment: ceftriaxone + vancomycin (add ampicillin if <3 months for Listeria). Dexamethasone before/with first antibiotics (reduces hearing loss for H. influenzae).',
'Common pathogens by age: neonate (GBS, E. coli, Listeria), 1-3mo (GBS, E. coli, S. pneumoniae), >3mo (S. pneumoniae, N. meningitidis). Dexamethasone 0.15mg/kg q6h x 4 days given before or with first dose of antibiotics. CPS guidelines recommend close contacts receive chemoprophylaxis for meningococcal disease.',5,'apply',['meningitis','CSF analysis','empiric antibiotics','pediatrics']);

add('peds-fever','What is the differential diagnosis of prolonged fever (>7 days) in a child?','Infection (30%): endocarditis, osteomyelitis, abscess, TB, EBV, CMV, cat-scratch disease. Autoimmune (20%): juvenile idiopathic arthritis (systemic), SLE, Kawasaki, inflammatory bowel disease. Malignancy (10%): leukemia, lymphoma, neuroblastoma. Other: drug fever, factitious.',
'Fever of unknown origin in children (>8 days, no diagnosis after initial workup) is more commonly infectious than in adults. Systemic JIA (Still disease) presents with quotidian fever and salmon-colored evanescent rash. CPS recommends systematic stepwise investigation rather than shotgun approach.',4,'analyze',['prolonged fever','FUO','differential diagnosis','pediatrics']);

add('peds-fever','What antipyretic dosing is recommended in children?','Acetaminophen: 15 mg/kg/dose q4-6h (max 75 mg/kg/day or 4g/day). Ibuprofen: 10 mg/kg/dose q6-8h (max 40 mg/kg/day), approved for age >=6 months. Do NOT alternate routinely (risk of dosing errors). ASA is CONTRAINDICATED in children (Reye syndrome).',
'CPS emphasizes that fever itself is not harmful and antipyretics are for comfort, not to normalize temperature. Alternating acetaminophen and ibuprofen is not recommended due to caregiver confusion and dosing errors. Tepid sponge baths are not recommended.',2,'apply',['antipyretics','acetaminophen','ibuprofen','fever management','pediatrics']);

add('peds-fever','What are the key features differentiating viral from bacterial pharyngitis in children?','Bacterial (GAS): sudden onset, fever >38.5°C, tonsillar exudates, tender anterior cervical lymphadenopathy, absence of cough. Centor/McIsaac score guides testing. Viral: cough, rhinorrhea, conjunctivitis, hoarseness, diarrhea, oral ulcers. Rapid strep test + throat culture for confirmation.',
'Modified Centor (McIsaac) score: age 3-14 (+1), fever >38°C (+1), no cough (+1), tender anterior cervical nodes (+1), tonsillar exudates (+1). Score >=3: test and treat. Score <3: no testing needed. Canadian guidelines recommend treating confirmed GAS with penicillin V or amoxicillin x 10 days.',3,'apply',['pharyngitis','GAS','McIsaac score','pediatrics']);

add('peds-fever','What is the evaluation and management of a child with petechiae and fever?','Petechiae + fever = meningococcemia until proven otherwise. Immediate: IV access, blood cultures, CBC with differential, coagulation studies, empiric IV ceftriaxone. If well-appearing with petechiae above nipple line only (mechanical) and normal labs-may observe. Below nipple line or diffuse petechiae with ill appearance mandates full sepsis workup.',
'N. meningitidis is the most feared cause. Purpura fulminans indicates DIC and carries high mortality. Canadian public health guidelines require reporting of meningococcal disease and contact tracing with chemoprophylaxis (rifampin, ciprofloxacin, or ceftriaxone).',5,'apply',['petechiae','meningococcemia','sepsis','emergency','pediatrics']);

add('peds-fever','What are the common causes of cervical lymphadenopathy in children?','Reactive (most common): viral URI, EBV, CMV. Bacterial: GAS pharyngitis, Staph/Strep lymphadenitis, cat-scratch (Bartonella). Mycobacterial: TB or non-tuberculous mycobacterial. Malignancy: lymphoma (firm, fixed, supraclavicular, >2cm persistent >4-6 weeks). Autoimmune: Kawasaki, SLE, JIA.',
'Most pediatric cervical lymphadenopathy is reactive and self-limited. Red flags for malignancy: supraclavicular location, firm/fixed, >2cm, persistent >4-6 weeks, associated B symptoms (weight loss, night sweats). Canadian guidelines recommend observation for 4-6 weeks before biopsy unless red flags present.',3,'analyze',['lymphadenopathy','cervical','differential diagnosis','pediatrics']);

// PEDS-NEONATE (15)
add('peds-neonate','What are the components of the APGAR score and the scoring intervals?','A: Appearance (0=blue, 1=acrocyanosis, 2=pink). P: Pulse (0=absent, 1=<100, 2=>=100). G: Grimace/reflex (0=none, 1=grimace, 2=cough/sneeze). A: Activity/tone (0=limp, 1=some flexion, 2=active). R: Respirations (0=absent, 1=weak cry, 2=strong cry). Scored at 1 and 5 minutes (continue q5min if <7). Max score 10.',
'APGAR score guides neonatal resuscitation decisions but does NOT predict long-term outcomes. Score 7-10 is normal. <3 at 5 minutes is concerning. Neonatal resuscitation should not be delayed for APGAR scoring. Canadian NRP (Neonatal Resuscitation Program) certification is mandatory for delivery attendants.',3,'recall',['APGAR','neonatal assessment','resuscitation','pediatrics']);

add('peds-neonate','What is the approach to neonatal jaundice and when is it pathological?','Physiological: appears day 2-3, peaks day 4-5, resolves by day 14 (21 in preterm). Pathological: jaundice within first 24 hours, total serum bilirubin (TSB) >95th percentile on Bhutani nomogram, rising >85 umol/L/day, conjugated bilirubin >34 umol/L, jaundice >2 weeks. Management: phototherapy (blue-green light, 430-490nm) based on CPS hour-specific nomogram. Exchange transfusion for extreme hyperbilirubinemia.',
'CPS guidelines provide hour-specific phototherapy and exchange transfusion thresholds. Risk factors for severe jaundice: ABO incompatibility, G6PD deficiency, prematurity, exclusive breastfeeding with poor intake, cephalohematoma. Universal bilirubin screening (transcutaneous) before discharge is recommended in Canada.',4,'apply',['neonatal jaundice','hyperbilirubinemia','phototherapy','pediatrics']);

add('peds-neonate','What are the causes of neonatal jaundice by timing of onset?','<24h: hemolytic (ABO/Rh incompatibility, G6PD deficiency, spherocytosis). Day 2-5: physiological, breastfeeding jaundice (inadequate intake), infection/sepsis. >2 weeks: breast milk jaundice (unconjugated, benign), biliary atresia (conjugated-pale stools, dark urine), hypothyroidism.',
'Jaundice in the first 24 hours is always pathological and requires urgent evaluation. Conjugated hyperbilirubinemia (direct >34 umol/L or >20% of total) is always pathological and suggests biliary atresia, which requires Kasai portoenterostomy before 60 days of age. CPS recommends urgent referral.',4,'analyze',['neonatal jaundice','hemolytic disease','biliary atresia','pediatrics']);

add('peds-neonate','What is the Neonatal Resuscitation Program (NRP) algorithm?','Initial steps (30 sec): warm, dry, stimulate, position airway, clear secretions if needed. If HR <100 or gasping: PPV with 21% O2 (term) or 21-30% (preterm) at 40-60 breaths/min for 30 sec. If HR <60: intubate if not already, chest compressions 3:1 ratio with ventilation. If HR still <60: epinephrine 0.01-0.03 mg/kg IV/UVC.',
'NRP certification is standard in Canadian delivery rooms. Initial FiO2 is 21% for term (no longer 100%). Most neonates respond to effective ventilation alone. Canadian Paediatric Society updated NRP guidelines emphasize delayed cord clamping (>=30 seconds for vigorous term infants).',5,'apply',['NRP','neonatal resuscitation','algorithm','pediatrics']);

add('peds-neonate','What is the newborn metabolic screening panel in Canada?','Varies by province but typically includes: PKU, congenital hypothyroidism, galactosemia, maple syrup urine disease, medium-chain acyl-CoA dehydrogenase deficiency (MCADD), sickle cell disease, congenital adrenal hyperplasia, cystic fibrosis, biotinidase deficiency. Blood spot (Guthrie card) collected at 24-72 hours of life.',
'Ontario screens for ~30 conditions via the Newborn Screening Ontario program. Congenital hypothyroidism is the most common treatable condition detected (~1/3000). Early treatment of PKU with dietary restriction prevents intellectual disability. Parents should be informed about the screening program.',3,'recall',['newborn screening','metabolic','PKU','hypothyroidism','pediatrics']);

add('peds-neonate','What are the common congenital heart defects presenting in the neonatal period and their presentations?','Cyanotic (duct-dependent): TGA (cyanosis within hours, single loud S2), tetralogy of Fallot (cyanotic spells), TAPVR, truncus arteriosus, hypoplastic left heart. Acyanotic: VSD (murmur at 2-6 weeks), ASD, PDA (continuous murmur), coarctation (differential BP upper/lower extremities, weak femoral pulses).',
'Duct-dependent lesions require prostaglandin E1 (PGE1) infusion to maintain PDA. Critical congenital heart disease screening with pulse oximetry is recommended for all newborns in Canada (pre- and post-ductal SpO2 at 24-48h). Echocardiography is the diagnostic standard.',4,'recall',['congenital heart disease','cyanotic','duct-dependent','pediatrics']);

add('peds-neonate','What is the management of neonatal hypoglycemia?','Definition: plasma glucose <2.6 mmol/L in symptomatic neonate. Risk factors: SGA, LGA, IDM, prematurity, perinatal stress. Asymptomatic at-risk: feed within 1h, check glucose at 2h, target >2.6 mmol/L. Symptomatic (jitteriness, seizures, lethargy): IV dextrose bolus (D10W 2mL/kg = 200mg/kg) followed by D10W infusion at 5-8 mg/kg/min.',
'CPS screening guidelines target at-risk newborns (IDM, SGA, LGA, preterm). Persistent hypoglycemia (>48h) warrants investigation for hyperinsulinism, cortisol deficiency, or metabolic disease. Bedside glucose meters may underestimate true glucose; confirm with lab value if borderline.',4,'apply',['neonatal hypoglycemia','glucose','IDM','pediatrics']);

add('peds-neonate','What are the components of the routine newborn examination?','General: weight, length, head circumference, gestational age assessment. Head: fontanelles, sutures, cephalohematoma, caput. Eyes: red reflex (retinoblastoma). Heart: murmurs, femoral pulses. Abdomen: organomegaly, umbilicus (2 arteries, 1 vein). Hips: Barlow (dislocatable) and Ortolani (reducible) maneuvers for DDH. Genitalia: testes descended. Spine: sacral dimple, tuft of hair. Reflexes: Moro, grasp, suck.',
'CPS guidelines recommend complete newborn exam within 24 hours. Red reflex testing detects retinoblastoma (most common childhood intraocular malignancy). DDH screening with Barlow/Ortolani maneuvers-risk factors: female, breech, family history. Ultrasound hip screening at 6 weeks if risk factors present.',3,'recall',['newborn exam','Barlow','Ortolani','red reflex','pediatrics']);

add('peds-neonate','What are the causes and management of neonatal seizures?','Causes: hypoxic-ischemic encephalopathy (most common, 60%), intracranial hemorrhage, metabolic (hypoglycemia, hypocalcemia, hyponatremia), infections (meningitis, encephalitis, TORCH), developmental malformations, pyridoxine-dependent seizures. Management: treat underlying cause, phenobarbital (20mg/kg IV loading) is first-line AED.',
'Neonatal seizures are often subtle (lip smacking, eye deviation, cycling, apnea) and may require EEG for detection. HIE is the most common cause in term neonates. Therapeutic hypothermia (33.5°C for 72h) for moderate-severe HIE reduces mortality and disability. Canadian neonatal cooling protocols are standardized.',5,'apply',['neonatal seizures','HIE','therapeutic hypothermia','pediatrics']);

add('peds-neonate','What are the TORCH infections and their key neonatal manifestations?','T: Toxoplasmosis (intracranial calcifications, hydrocephalus, chorioretinitis). O: Other (syphilis, varicella, parvovirus). R: Rubella (cataracts, deafness, PDA, blueberry muffin rash). C: CMV (most common congenital infection; periventricular calcifications, microcephaly, hepatosplenomegaly, sensorineural hearing loss). H: Herpes (vesicular lesions, encephalitis, disseminated disease).',
'CMV is the leading infectious cause of sensorineural hearing loss and neurodevelopmental disability. Congenital CMV testing (urine or saliva PCR within 21 days of birth) is recommended for infants who fail newborn hearing screening. Treatment: IV ganciclovir or oral valganciclovir for 6 months for symptomatic disease.',4,'recall',['TORCH infections','CMV','congenital infections','pediatrics']);

add('peds-neonate','What are the types of respiratory distress in the newborn and their management?','Transient tachypnea (TTN): term/near-term, cesarean delivery, resolves 24-72h, supportive. Respiratory distress syndrome (RDS): preterm, surfactant deficiency, ground-glass CXR-surfactant replacement + CPAP. Meconium aspiration (MAS): post-term, meconium-stained fluid, patchy CXR-supportive ± surfactant. Pneumothorax: consider in sudden deterioration-needle decompression then chest tube.',
'Antenatal betamethasone (2 doses, 12mg IM 24h apart) for mothers 24-34 weeks gestation reduces RDS by 50%. CPS/NRP no longer recommend routine endotracheal suctioning for vigorous meconium-stained neonates. CPAP is first-line for preterm RDS with selective surfactant administration.',4,'apply',['neonatal respiratory distress','RDS','surfactant','TTN','pediatrics']);

add('peds-neonate','What are the key aspects of prematurity management?','<28 weeks: extreme prematurity-RDS, IVH, NEC, BPD, ROP. 28-32 weeks: moderate prematurity-surfactant may be needed, less IVH risk. 32-37 weeks: late preterm-feeding difficulties, jaundice, temperature instability. Key interventions: antenatal steroids (24-34w), magnesium sulfate for neuroprotection (<32w), delayed cord clamping, kangaroo care, breast milk promotion.',
'Canada-wide perinatal networks (e.g., CNN-Canadian Neonatal Network) track outcomes. Antenatal magnesium sulfate before 32 weeks reduces cerebral palsy (NNT 63). ROP screening begins at 31 weeks postmenstrual age or 4 weeks chronological age. CPS provides follow-up guidelines for preterm infants.',4,'apply',['prematurity','RDS','antenatal steroids','neonatal care','pediatrics']);

add('peds-neonate','What are the causes and evaluation of neonatal cyanosis?','Central cyanosis DDx: cardiac (cyanotic CHD), pulmonary (RDS, pneumonia, PPHN, pneumothorax), neurological (CNS depression, apnea), hematological (methemoglobinemia). Hyperoxia test: give 100% O2 for 10 min-PaO2 >150mmHg suggests pulmonary cause; PaO2 remains <100mmHg suggests cardiac cause. Echocardiography is definitive for CHD.',
'The hyperoxia test helps differentiate cardiac from pulmonary causes of cyanosis. Critical congenital heart disease pulse oximetry screening in Canadian nurseries detects duct-dependent lesions before clinical deterioration. PGE1 infusion is a life-saving bridge to definitive management.',4,'apply',['neonatal cyanosis','hyperoxia test','CHD','pediatrics']);

add('peds-neonate','What are the key features of necrotizing enterocolitis (NEC)?','Presentation: preterm infant with feeding intolerance, abdominal distension, bloody stools, temperature instability, apnea/bradycardia. X-ray: pneumatosis intestinalis (pathognomonic), portal venous gas, pneumoperitoneum (perforation). Modified Bell staging. Treatment: NPO, gastric decompression, IV antibiotics (ampicillin + gentamicin + metronidazole), surgical consultation.',
'NEC is the most common GI surgical emergency in neonates with 20-30% mortality. Breast milk feeding is the strongest protective factor. Pneumoperitoneum indicates perforation requiring surgical intervention. Canadian neonatal units use standardized feeding advancement protocols to reduce NEC risk.',5,'apply',['NEC','necrotizing enterocolitis','prematurity','pediatrics']);

add('peds-neonate','What is the evaluation of a newborn with ambiguous genitalia?','EMERGENCY: risk of salt-wasting CAH crisis. Do NOT assign gender immediately. Urgent investigations: 17-hydroxyprogesterone (CAH is most common cause), karyotype, electrolytes (hyponatremia, hyperkalemia in salt-wasting CAH), pelvic ultrasound (mullerian structures), cortisol, testosterone, LH/FSH.',
'Congenital adrenal hyperplasia (21-hydroxylase deficiency) accounts for >90% of ambiguous genitalia. Salt-wasting crisis presents at 1-2 weeks with hyponatremia, hyperkalemia, and shock. CPS recommends multidisciplinary team (endocrine, urology, genetics, psychology) for gender assignment and management.',5,'apply',['ambiguous genitalia','CAH','intersex','endocrine','pediatrics']);

// PEDS-ASTHMA (10)
add('peds-asthma','What are the diagnostic criteria for asthma in children <6 years vs >=6 years?','<6 years: clinical diagnosis based on pattern of symptoms (recurrent wheeze, cough, dyspnea triggered by viral infections, exercise, allergens), response to bronchodilators, and exclusion of alternatives. >=6 years: confirmed by spirometry showing reversible airflow obstruction (FEV1 increase >=12% post-bronchodilator or positive methacholine challenge).',
'CPS and Canadian Thoracic Society guidelines note that formal diagnosis with spirometry is difficult in children <6 years. The Asthma Predictive Index (API) helps predict persistence: major criteria (parental asthma, eczema) or minor criteria (allergic rhinitis, wheezing apart from colds, eosinophilia >=4%).',3,'apply',['asthma diagnosis','pediatric','spirometry','pediatrics']);

add('peds-asthma','What is the stepwise approach to asthma management in children?','Step 1: SABA as needed. Step 2: low-dose ICS (e.g., fluticasone 100mcg/day). Step 3: medium-dose ICS or low-dose ICS + LABA (>=6yr) or LTRA. Step 4: medium-dose ICS + LABA. Step 5: high-dose ICS + LABA, consider biologic (omalizumab). Before stepping up: verify technique, adherence, trigger avoidance, and diagnosis.',
'CTS Pediatric Asthma guidelines recommend ICS as cornerstone of controller therapy. LABA monotherapy is contraindicated in children. Montelukast (LTRA) is second-line to ICS. Step-down therapy attempted after 3 months of good control. Action plans should be provided to all families.',4,'apply',['asthma stepwise','ICS','controller therapy','pediatrics']);

add('peds-asthma','How is acute pediatric asthma exacerbation classified and managed?','Mild: talks in sentences, SpO2 >94%. Moderate: talks in phrases, SpO2 90-94%. Severe: talks in words, SpO2 <90%, accessory muscles, HR >200 (<3yr) or >180 (4-5yr). Management: salbutamol MDI + spacer (or nebulized) q20min x 3, ipratropium for moderate-severe, systemic corticosteroids (prednisone/prednisolone 1-2mg/kg, max 50mg x 3-5 days). Add IV MgSO4 50mg/kg for severe refractory.',
'CPS and CTS guidelines emphasize MDI + spacer over nebulization for most children (equivalent efficacy, better drug delivery). Oral steroids given early reduce hospitalization (NNT 8). Chest X-ray is NOT routine-only if suspecting complication. Discharge with action plan and ICS if not already prescribed.',4,'apply',['asthma exacerbation','acute management','salbutamol','pediatrics']);

add('peds-asthma','What are the ICS dose equivalences in children and the side effects to monitor?','Low dose: fluticasone 100-200mcg/day, budesonide 200-400mcg/day, beclomethasone 200-400mcg/day. Medium: fluticasone 200-500mcg, budesonide 400-800mcg. High: fluticasone >500mcg, budesonide >800mcg. Side effects: oral thrush (use spacer, rinse mouth), growth suppression (~1cm in first year, catch-up later), adrenal suppression at high doses.',
'CTS guidelines recommend the lowest effective ICS dose. Growth monitoring is essential. ICS at low-moderate doses cause minimal growth effect (~0.5-1cm reduction in final adult height per CAMP trial). Benefits of asthma control far outweigh this risk. Always prescribe spacer with MDI.',3,'apply',['ICS dosing','inhaled corticosteroids','side effects','pediatrics']);

add('peds-asthma','What is the approach to exercise-induced bronchospasm (EIB) in children?','Diagnosis: FEV1 drop >=10% post-exercise challenge. Prevention: SABA 15-20 minutes before exercise (most effective). Alternatives: daily LTRA, warm-up exercises. If EIB occurs despite pre-treatment SABA, indicates uncontrolled underlying asthma requiring controller therapy assessment.',
'EIB affects 40-90% of children with asthma. CTS guidelines recommend that children with asthma should be encouraged to exercise. Persistent EIB despite pre-treatment SABA should prompt reassessment of overall asthma control and controller therapy optimization.',3,'apply',['exercise-induced bronchospasm','EIB','SABA','pediatrics']);

add('peds-asthma','What are the differential diagnoses for wheezing in infants and young children?','Viral-induced wheeze (most common), bronchiolitis (RSV), asthma, foreign body aspiration (sudden onset, unilateral), tracheomalacia/bronchomalacia, cystic fibrosis, GERD, vascular ring, congenital heart disease, primary ciliary dyskinesia.',
'Not all that wheezes is asthma. CPS guidelines emphasize that wheezing in infants <12 months is most commonly bronchiolitis (RSV). Foreign body aspiration should be suspected with sudden onset and unilateral wheeze. CXR (inspiratory/expiratory) and bronchoscopy for suspected foreign body.',3,'analyze',['wheezing differential','bronchiolitis','foreign body','pediatrics']);

add('peds-asthma','What is the management of bronchiolitis?','Supportive care only: nasal suctioning, supplemental O2 if SpO2 <90%, hydration (oral or IV). Hypertonic saline nebulization may be used in admitted patients. NOT recommended: bronchodilators, corticosteroids, antibiotics, chest physiotherapy. Admit if: age <3 months, significant respiratory distress, SpO2 <90%, dehydration, apnea history, prematurity.',
'CPS bronchiolitis guidelines emphasize minimal intervention. Trial of bronchodilator is no longer routinely recommended. Palivizumab (RSV monoclonal antibody) for prophylaxis in high-risk infants (preterm <33 weeks, hemodynamically significant CHD, chronic lung disease) during RSV season.',3,'apply',['bronchiolitis','RSV','supportive care','pediatrics']);

add('peds-asthma','What are the indications for referral to a pediatric respirologist for asthma?','Uncontrolled asthma despite medium-dose ICS + LABA, frequent severe exacerbations, diagnostic uncertainty, age <2 years with recurrent wheeze, suspected comorbid conditions (VCD, allergic bronchopulmonary aspergillosis), consideration of biologic therapy, life-threatening exacerbation.',
'Canadian Thoracic Society recommends specialist referral when asthma is not controlled at Step 3 therapy. Biologic therapies (omalizumab for IgE-mediated, mepolizumab for eosinophilic) require specialist initiation. Most pediatric asthma can be managed in primary care with proper education.',3,'apply',['asthma referral','specialist','uncontrolled asthma','pediatrics']);

add('peds-asthma','What is an asthma action plan and what should it include?','Written plan with zones: GREEN (well controlled)-continue maintenance therapy. YELLOW (worsening)-increase SABA frequency, double ICS dose or start prednisone 1mg/kg x 3-5 days. RED (emergency)-SABA q4h, start oral steroids, seek immediate medical attention if no improvement. Include triggers, medications with doses, and when to go to ED.',
'CPS and CTS mandate written action plans for all pediatric asthma patients. Studies show action plans reduce ED visits by 70% and hospitalizations by 40%. Plans should be reviewed at every visit. School copies should include permission for self-administration of SABA.',3,'apply',['asthma action plan','self-management','pediatrics']);

add('peds-asthma','What are the risk factors for fatal asthma in children?','Previous near-fatal exacerbation (intubation/ICU), frequent ED visits/hospitalizations, poor adherence to controller therapy, overuse of SABA (>=1 canister/month), food allergy (especially peanut), psychosocial factors (depression, family dysfunction), lack of written action plan, recent oral corticosteroid use.',
'These risk factors identify children needing intensive follow-up and asthma education. CTS recommends flagging high-risk patients in medical records. SABA overuse (dispensing >=3 canisters/year) is a marker of uncontrolled asthma and should trigger reassessment.',4,'apply',['fatal asthma risk','SABA overuse','risk factors','pediatrics']);

// PEDS-VACCINES (10)
add('peds-vaccines','What is the Canadian publicly funded immunization schedule for infants (0-12 months)?','Birth: HepB (some provinces). 2mo: DTaP-IPV-Hib + PCV13 + rotavirus. 4mo: DTaP-IPV-Hib + PCV13 + rotavirus. 6mo: DTaP-IPV-Hib + (PCV13 in some provinces) + influenza (>=6mo annually). 12mo: MMR + varicella (or MMRV) + PCV13 + meningococcal C conjugate + HepB (if not given at birth).',
'The National Advisory Committee on Immunization (NACI) provides recommendations, but schedules are implemented provincially. The schedule varies slightly between provinces. DTaP-IPV-Hib is a combination vaccine reducing injection burden. Rotavirus is oral, not injectable.',3,'recall',['immunization schedule','infant vaccines','NACI','pediatrics']);

add('peds-vaccines','What are the live vaccines and why are they important to distinguish?','Live attenuated: MMR, varicella, MMRV, rotavirus, BCG, live attenuated influenza (LAIV/FluMist), oral polio (OPV-not used in Canada), yellow fever. Key implications: contraindicated in immunocompromised patients, must wait 28 days between two live vaccines (or give simultaneously), may need to delay after blood products.',
'NACI guidelines specify that live vaccines are contraindicated in severe immunodeficiency (HIV with CD4 <15%, chemotherapy, high-dose steroids >=2mg/kg/day x >=14 days). Household contacts of immunocompromised patients SHOULD receive live vaccines (except OPV). IPV is used exclusively in Canada.',3,'recall',['live vaccines','contraindications','immunocompromised','pediatrics']);

add('peds-vaccines','What are the true contraindications vs common misconceptions about vaccines?','True contraindications: anaphylaxis to previous dose or vaccine component, encephalopathy within 7 days of pertussis vaccine. NOT contraindications: mild illness with/without fever, current antibiotic therapy, mild local reaction to previous dose, prematurity, breastfeeding, family history of adverse events, egg allergy for MMR.',
'Vaccine hesitancy is a growing concern in Canada. NACI and CPS emphasize that missed opportunities due to false contraindications are more harmful than the theoretical risks. Egg allergy is not a contraindication for MMR (grown in fibroblast culture) or current influenza vaccines.',3,'recall',['vaccine contraindications','misconceptions','safety','pediatrics']);

add('peds-vaccines','What is the catch-up immunization approach for a child with unknown or incomplete vaccination history?','Assume unvaccinated unless documented proof exists. Start age-appropriate schedule from the beginning. Minimum intervals between doses (not maximum-no need to restart series). Simultaneous administration of multiple vaccines at different sites is safe and recommended. Serologic testing may be helpful for certain antigens (Hep B, measles, varicella).',
'NACI provides detailed catch-up schedules. This is common with immigrant/refugee children in Canada. Each province has a catch-up guide. Key principle: every visit is an opportunity to vaccinate. School immunization requirements vary by province (Ontario mandates documentation).',3,'apply',['catch-up vaccination','incomplete vaccination','pediatrics']);

add('peds-vaccines','What are the vaccines recommended for adolescents in Canada?','Grade 7-8 (age 12-13): HPV (2-dose series, Gardasil 9), Meningococcal ACWY conjugate, HepB (if not completed), Tdap booster. Annually: influenza. Additional: varicella (2nd dose if not received), catch-up of any missing childhood vaccines.',
'NACI recommends gender-neutral HPV vaccination (Gardasil 9 covers types 6,11,16,18,31,33,45,52,58). Two-dose schedule for ages 9-14, three-dose for >=15. Meningococcal B vaccine (Bexsero) is recommended by NACI but not publicly funded in all provinces.',3,'recall',['adolescent vaccines','HPV','meningococcal','pediatrics']);

add('peds-vaccines','What are the special immunization considerations for preterm infants?','Immunize at chronological age (NOT corrected age) with full doses. All routine vaccines given on schedule. Additional: palivizumab for RSV prophylaxis in eligible preterm infants, annual influenza from 6 months. HepB at birth if mother HBsAg+. Monitor for apnea/bradycardia 48h after first vaccination in hospitalized preterm <31 weeks.',
'CPS and NACI emphasize that prematurity is NOT a reason to delay vaccination. Immune response may be slightly lower but is still protective. All routine vaccines including rotavirus should be given at 2 months chronological age even if still in NICU.',3,'apply',['preterm vaccination','immunization','neonatal','pediatrics']);

add('peds-vaccines','What are the post-exposure prophylaxis protocols for key vaccine-preventable diseases?','Measles: MMR within 72h or Ig within 6 days for susceptible contacts. Varicella: vaccine within 5 days or VZIG for high-risk (immunocompromised, pregnant, newborns). Pertussis: azithromycin for close contacts regardless of immunization status. Hepatitis B: HBIG + vaccine within 12h for neonates of HBsAg+ mothers. Rabies: wound care + HRIG + vaccine series.',
'Post-exposure protocols are critical for public health in Canada. Measles outbreaks require rapid contact tracing. Healthcare workers with uncertain immunity should receive post-exposure vaccination. CPS and NACI provide detailed post-exposure algorithms for each pathogen.',4,'apply',['post-exposure prophylaxis','PEP','contact tracing','pediatrics']);

add('peds-vaccines','What adverse events following immunization (AEFI) should be reported?','Report: anaphylaxis, seizures, encephalopathy, intussusception (post-rotavirus), Guillain-Barre, thrombocytopenia, severe local reaction, any hospitalization or death temporally associated with vaccination. Reporting is through the Canadian Adverse Events Following Immunization Surveillance System (CAEFISS). Anaphylaxis rate: ~1/million doses.',
'CAEFISS collects national AEFI data. Healthcare providers are legally required to report AEFIs in most provinces. The National Vaccine Injury Compensation Program was established in Canada in 2021. Vaccine-associated anaphylaxis requires 15-minute observation post-vaccination.',3,'recall',['AEFI','adverse events','vaccine safety','reporting','pediatrics']);

add('peds-vaccines','What is the meningococcal vaccination strategy in Canada?','Routine: Meningococcal C conjugate at 12 months, Meningococcal ACWY conjugate in adolescence. Meningococcal B (Bexsero, Trumenba): recommended by NACI for high-risk groups, funded in some provinces. High-risk requiring both MenACWY + MenB: asplenia, complement deficiency, outbreaks, travel to endemic areas.',
'N. meningitidis serogroups B and W are emerging concerns in Canada. MenB vaccine is not yet universally publicly funded despite NACI recommendation. Healthcare providers should discuss MenB with parents as it may require private purchase in some provinces.',3,'apply',['meningococcal vaccine','serogroups','NACI','pediatrics']);

add('peds-vaccines','How should COVID-19 vaccination be approached in Canadian pediatric populations?','NACI recommendations evolve with evidence. Currently: mRNA vaccines recommended for children >=6 months. Primary series + boosters based on age and risk. Higher priority for high-risk children (immunocompromised, chronic conditions). Can be co-administered with other routine vaccines.',
'NACI updates COVID-19 pediatric vaccine recommendations as evidence evolves. Myocarditis/pericarditis is a rare adverse event more common in males 12-29 years after mRNA vaccines (especially after 2nd dose). Benefits exceed risks at the population level per NACI risk-benefit analysis.',3,'apply',['COVID-19 vaccine','pediatric','mRNA','NACI','pediatrics']);

fs.writeFileSync('C:/dev/srs-mccqe1/data/_peds_cards.json', JSON.stringify(cards, null, 2));
console.log('Pediatrics cards written:', cards.length);
