const fs = require("fs");
const prev = JSON.parse(fs.readFileSync("C:/dev/srs-mccqe1/data/_parts12345.json","utf8"));
const cards = [...prev];
let n = 221;
function c(id,q,a,ex,d,bl,tags,tid){return{id,question:q,answer:a,explanation:ex,difficulty:d,bloomLevel:bl,tags,topicId:tid};}

// ENT - EAR (10)
cards.push(c("card-tn3-ent-"+n++,"How is acute otitis media diagnosed and managed in children?","Diagnosis: moderate-severe bulging of TM or new otorrhea or mild bulging+recent ear pain/erythema. First-line: amoxicillin 75-90mg/kg/d divided BID x5-10d. Watch-and-wait option if >2yr, unilateral, non-severe","CPS guidelines. High-dose amox overcomes pneumococcal resistance. Second-line if failure at 48-72h: amox-clav 90mg/kg/d. Tympanostomy tubes for recurrent AOM (>=3 in 6mo or >=4 in 12mo). Complications: mastoiditis (post-auricular swelling/erythema), meningitis.",3,"apply",["otitis media","AOM","amoxicillin","pediatric"],"ent-ear"));
cards.push(c("card-tn3-ent-"+n++,"How does otitis externa differ from otitis media and how is it managed?","OE: ear canal pain worse with tragal pressure/pinna traction, canal edema/debris. TM intact. Treat: topical antibiotic+steroid drops (ciprofloxacin-dexamethasone). Keep ear dry. Wick if canal very swollen","OE risk: swimming, hearing aids, cotton swabs. Malignant OE in diabetics/immunocompromised: Pseudomonas, skull base osteomyelitis - requires IV antipseudomonal + CT scan. Fungal OE (otomycosis): fluffy/spore debris, treat with topical antifungal.",3,"apply",["otitis externa","ear drops","management"],"ent-ear"));
cards.push(c("card-tn3-ent-"+n++,"What are the causes and management of sudden sensorineural hearing loss?","SSNHL: >=30dB loss over <=3 days in >=3 consecutive frequencies. Causes: idiopathic (viral), vascular, autoimmune, Meniere, acoustic neuroma. Treatment: oral prednisone 1mg/kg x14d taper. Urgent ENT referral + audiogram","SSNHL is an otologic EMERGENCY. Rule out: acoustic neuroma (MRI with gadolinium). Prognosis: 65% partial recovery. Intratympanic steroids if oral fails. Always differentiate from conductive loss (tuning fork: Weber lateralizes to affected ear in conductive, away in SNHL).",4,"apply",["SSNHL","hearing loss","prednisone"],"ent-ear"));
cards.push(c("card-tn3-ent-"+n++,"How is benign paroxysmal positional vertigo (BPPV) diagnosed and treated?","Diagnosis: Dix-Hallpike test positive (upbeat-torsional nystagmus with 5-20s latency, fatigable, <60s). Posterior canal most common. Treatment: Epley maneuver (canalith repositioning). Avoid meclizine (delays compensation)","BPPV caused by otoconia dislodged into semicircular canal. Dix-Hallpike: head turned 45 degrees, rapidly lie back with head extended. Epley: 93% effective after 1-2 treatments. Horizontal canal BPPV: supine roll test, Lempert maneuver.",3,"apply",["BPPV","Dix-Hallpike","Epley","vertigo"],"ent-ear"));
cards.push(c("card-tn3-ent-"+n++,"What is the differential diagnosis of vertigo?","Peripheral (ENT): BPPV (brief, positional), Meniere (hours, hearing loss, tinnitus, fullness), vestibular neuritis (days, post-viral). Central (neurology): stroke (HINTS exam abnormal), MS, tumor","HINTS exam for acute vestibular syndrome: Head Impulse (normal=central), Nystagmus (direction-changing=central), Test of Skew (present=central). >90% sensitive for stroke. Peripheral: horizontal nystagmus, unidirectional, suppressed by fixation.",4,"analyze",["vertigo","BPPV","Meniere","HINTS"],"ent-ear"));
cards.push(c("card-tn3-ent-"+n++,"How is Meniere disease diagnosed and managed?","Diagnosis: >=2 episodes of vertigo 20min-12h + low-mid frequency SNHL + aural fullness/tinnitus. Management: sodium restriction <2g/d, diuretic (hydrochlorothiazide), betahistine, acute: dimenhydrinate/benzodiazepine","Endolymphatic hydrops is the pathological finding. Hearing loss is fluctuating initially, progressive over years. Intratympanic gentamicin or dexamethasone for refractory cases. Endolymphatic sac surgery. Avoid caffeine and alcohol.",3,"apply",["Meniere","vertigo","hearing loss"],"ent-ear"));
cards.push(c("card-tn3-ent-"+n++,"What is cholesteatoma and how is it managed?","Abnormal keratinizing squamous epithelium in middle ear. Presents: chronic otorrhea, conductive hearing loss, TM retraction pocket with debris. Complications: ossicular erosion, facial nerve palsy, intracranial abscess","Acquired >> congenital. CT temporal bone for extent. Treatment: SURGICAL (tympanomastoidectomy). Not curable with antibiotics alone. Complications from erosion: labyrinthine fistula (vertigo), sigmoid sinus thrombosis, brain abscess. Lifelong surveillance for recurrence.",4,"apply",["cholesteatoma","ear","surgery"],"ent-ear"));
cards.push(c("card-tn3-ent-"+n++,"How is conductive vs sensorineural hearing loss differentiated?","Weber: lateralizes to affected ear (conductive) or normal ear (SNHL). Rinne: BC>AC = conductive loss (negative Rinne). AC>BC normal (positive Rinne). Audiogram confirms type and severity","Conductive: cerumen, effusion, TM perforation, ossicular chain, otosclerosis. Sensorineural: noise, presbycusis, ototoxic drugs, Meniere, acoustic neuroma, congenital. Mixed: chronic otitis media. Audiogram is essential investigation.",3,"recall",["hearing loss","Weber","Rinne","audiogram"],"ent-ear"));
cards.push(c("card-tn3-ent-"+n++,"What are the indications for tympanostomy tubes?","Recurrent AOM: >=3 in 6mo or >=4 in 12mo. Chronic OME: >=3 months bilateral with hearing loss. Chronic OME unilateral >=6mo. Complicated AOM. Eustachian tube dysfunction causing recurrent symptoms","Tubes ventilate middle ear and allow topical treatment. Usually extrude spontaneously in 6-18mo. Water precautions controversial (surface swimming generally OK). Otorrhea through tubes: topical ciprofloxacin-dex drops. Risks: persistent perforation 2%, tympanosclerosis.",3,"recall",["tympanostomy tubes","AOM","OME"],"ent-ear"));
cards.push(c("card-tn3-ent-"+n++,"What ototoxic drugs should be monitored?","Aminoglycosides (vestibulotoxic>cochleotoxic): gentamicin. Cisplatin (cochleotoxic, permanent, high-frequency). Loop diuretics (usually reversible). ASA at high doses (tinnitus, reversible). Vancomycin (especially with aminoglycosides)","Baseline audiogram before ototoxic drugs. Monitor during treatment. Aminoglycoside: once-daily dosing with trough monitoring reduces toxicity. Risk factors: renal impairment, prolonged treatment, concurrent ototoxins. Hearing loss from cisplatin is irreversible.",3,"recall",["ototoxicity","aminoglycoside","cisplatin"],"ent-ear"));

// ENT - URGENT (10)
cards.push(c("card-tn3-ent-"+n++,"How is anterior epistaxis managed?","1) Sit forward, pinch soft nose 15min continuous. 2) Topical vasoconstrictor (oxymetazoline). 3) Silver nitrate cautery if bleeding point visible. 4) Anterior nasal packing (Merocel/Rapid Rhino). 5) ENT if refractory","90% epistaxis is anterior (Kiesselbach plexus/Little area). Posterior epistaxis: posterior pack or balloon, admit. Check BP, coagulation, medications (anticoagulants, antiplatelets). Do NOT cauterize both sides of septum (perforation risk).",3,"apply",["epistaxis","nasal packing","management"],"ent-urg"));
cards.push(c("card-tn3-ent-"+n++,"How is peritonsillar abscess (PTA) diagnosed and treated?","Presentation: severe sore throat, trismus, hot-potato voice, uvular deviation, unilateral tonsillar swelling. Diagnosis: clinical +/- CT or US. Treatment: needle aspiration or I&D + antibiotics (amox-clav or clindamycin). IV fluids","PTA is most common deep neck space infection. Complication: parapharyngeal abscess, airway compromise, Lemierre syndrome (IJV thrombophlebitis from Fusobacterium). Tonsillectomy recommended if recurrent PTA (>2). Always assess airway before instrumentation.",4,"apply",["peritonsillar abscess","PTA","drainage"],"ent-urg"));
cards.push(c("card-tn3-ent-"+n++,"What is the approach to a patient with stridor?","Inspiratory stridor: supraglottic/glottic obstruction (croup, epiglottitis, foreign body, anaphylaxis). Biphasic: glottic/subglottic (croup, subglottic stenosis). Expiratory: lower airway (asthma, bronchiolitis). Assess severity: can they speak, drooling, position?","Croup (6mo-3yr): barky cough, viral, dexamethasone 0.6mg/kg PO single dose + nebulized epinephrine if severe. Epiglottitis: drooling, toxic, do NOT examine throat, urgent anesthesia/ENT for intubation. Adult epiglottitis still occurs.",4,"analyze",["stridor","croup","epiglottitis","airway"],"ent-urg"));
cards.push(c("card-tn3-ent-"+n++,"How is acute sinusitis managed?","Viral (most common, <10d): supportive (saline irrigation, analgesics, intranasal corticosteroids). Bacterial (symptoms >10d, or worsening after 5-7d, or severe onset): amoxicillin 500mg TID x5-7d. Second-line: amox-clav","CTFPHC recommends delayed antibiotics for most sinusitis. Bacterial signs: purulent discharge, unilateral facial pain/pressure, fever, double sickening. Imaging NOT needed for uncomplicated. CT only for complications or chronic. Complications: orbital cellulitis, intracranial abscess.",3,"apply",["sinusitis","amoxicillin","management"],"ent-urg"));
cards.push(c("card-tn3-ent-"+n++,"What are the red flags for serious causes of sore throat?","Drooling/unable to swallow (PTA, epiglottitis, retropharyngeal abscess). Trismus. Respiratory distress/stridor. Neck swelling/erythema (Ludwig angina). Unilateral swelling. Hot-potato voice. Toxic appearance","Ludwig angina: bilateral submandibular space infection, floor of mouth elevation, potential airway emergency. Lemierre syndrome: sore throat + septic thrombophlebitis of IJV (Fusobacterium). Retropharyngeal abscess: neck stiffness, dysphagia, CT confirms.",4,"recall",["sore throat","red flags","Ludwig angina"],"ent-urg"));
cards.push(c("card-tn3-ent-"+n++,"How is group A strep pharyngitis diagnosed and managed?","Centor/McIsaac criteria: fever>38, tonsillar exudate, tender anterior cervical LAD, no cough (+1 if age 3-14, -1 if >45). Score 0-1: no test. 2-3: rapid strep then culture. 4+: empiric abx. Treat: penicillin V 600mg BID x10d or amoxicillin","Treatment prevents rheumatic fever (rare in Canada) and reduces symptoms by ~1 day. Alternatives: cephalexin, azithromycin if penicillin allergic. Complications: PTA, rheumatic fever, PSGN (not prevented by antibiotics), scarlet fever.",3,"apply",["strep pharyngitis","Centor","penicillin"],"ent-urg"));
cards.push(c("card-tn3-ent-"+n++,"What is the approach to a foreign body in the ear or nose?","Ear: irrigation if not button battery or live insect (kill insect first with mineral oil). Nose: positive pressure (parent blow or Katz extractor). Button battery: EMERGENCY removal (mucosal necrosis in 2h)","Button battery in nose or esophagus is a TRUE EMERGENCY - causes liquefactive necrosis rapidly. Do not delay for imaging. Nasal FB: occlude unaffected nostril, parent blows into mouth. Ear FB: do not push deeper. ENT referral if failed removal.",3,"apply",["foreign body","ear","nose","emergency"],"ent-urg"));
cards.push(c("card-tn3-ent-"+n++,"How is a nasal fracture assessed and managed?","Assess: deformity, crepitus, epistaxis, septal hematoma (fluctuant swelling - drain immediately to prevent necrosis/saddle nose). XR not needed. Closed reduction if displaced (within 7-10 days for adults)","Septal hematoma is a surgical EMERGENCY - avascular necrosis of cartilage if not drained. Simple nasal fracture: ice, analgesia, reassess in 5-7 days when swelling reduced, reduce if cosmetic deformity. Rule out: CSF rhinorrhea (beta-2 transferrin), orbital blowout fracture.",3,"apply",["nasal fracture","septal hematoma","management"],"ent-urg"));
cards.push(c("card-tn3-ent-"+n++,"What is the 2-week rule for head and neck cancer referral?","Urgent ENT referral (2wk) for: hoarseness >3wk, persistent neck lump, unilateral ear pain with normal ear, oral ulcer/lesion >3wk, unexplained dysphagia, unilateral nasal obstruction with bloody discharge","Head and neck SCC risk factors: tobacco, alcohol, HPV (oropharyngeal). HPV+ oropharyngeal cancer increasing in young non-smokers, better prognosis. Pan-endoscopy for staging. Treatment: surgery and/or chemoradiation depending on site and stage.",4,"recall",["head and neck cancer","referral","red flags"],"ent-urg"));
cards.push(c("card-tn3-ent-"+n++,"How is obstructive sleep apnea diagnosed and managed?","Diagnosis: polysomnography (AHI>=5 + symptoms or AHI>=15). STOP-BANG screening (>=3 high risk). Treatment: CPAP (first-line moderate-severe), weight loss, positional therapy, MAD for mild. Surgery: UPPP/tonsillectomy for select patients","OSA affects 5-15% adults. Consequences: HTN, CV disease, MVA risk, depression. CPAP reduces AHI and CV risk. Adherence is the main challenge (50% at 1yr). Commercial driver screening required in many jurisdictions. Children: adenotonsillectomy is first-line.",3,"apply",["OSA","CPAP","STOP-BANG"],"ent-urg"));

// OPHTHALMOLOGY - URGENT (10)
cards.push(c("card-tn3-oph-"+n++,"How is acute angle-closure glaucoma diagnosed and managed?","Presentation: severe eye pain, headache, nausea, halos around lights, mid-dilated fixed pupil, red eye, IOP >40mmHg, hazy cornea. Emergency treatment: timolol 0.5% + pilocarpine 2% + IV acetazolamide 500mg + mannitol if needed. Definitive: laser PI","AACG is an ophthalmologic EMERGENCY - permanent vision loss if untreated. Shallow anterior chamber is risk factor. Avoid mydriatic drugs in at-risk patients. Fellow eye prophylactic laser PI. Occurs in dim light (pupil dilates, iris blocks angle).",5,"apply",["acute angle-closure","glaucoma","emergency"],"ophtho-urg"));
cards.push(c("card-tn3-oph-"+n++,"What are the symptoms and management of retinal detachment?","Symptoms: floaters, flashes (photopsia), curtain/shadow in visual field. Types: rhegmatogenous (most common, retinal tear), tractional (diabetic), exudative (inflammatory). Treatment: URGENT ophthalmology - surgical repair (pneumatic retinopexy, scleral buckle, vitrectomy)","Risk factors: myopia, prior cataract surgery, trauma, lattice degeneration. Macula-on detachment: surgical emergency same day (better prognosis). Macula-off: urgent within 1-7 days. New floaters/flashes always warrant dilated fundus exam to rule out retinal tear.",4,"apply",["retinal detachment","floaters","surgery"],"ophtho-urg"));
cards.push(c("card-tn3-oph-"+n++,"How are chemical eye burns managed?","IMMEDIATE copious irrigation with NS or water for at least 30 minutes before ANY other assessment. Check pH (target 7.0-7.4). Alkali worse than acid (penetrates deeper). Urgent ophthalmology. Morgan lens for continuous irrigation","Do NOT delay irrigation for anything - this is the single most important intervention. Remove contact lenses and particulate matter. Alkali: liquefactive necrosis, penetrates. Acid: coagulative, self-limiting. Grade by limbal blanching and corneal clarity (Roper-Hall). Cycloplegic + topical antibiotic after irrigation.",5,"apply",["chemical burn","eye","irrigation"],"ophtho-urg"));
cards.push(c("card-tn3-oph-"+n++,"What is the approach to a painful red eye?","Emergencies: acute angle closure (fixed mid-dilated pupil), corneal ulcer (hypopyon), uveitis (consensual photophobia), endophthalmitis, orbital cellulitis, chemical burn. Urgent: acute glaucoma, retinal detachment symptoms, globe rupture","Differentiate: conjunctivitis (diffuse, discharge), episcleritis (sectoral, mild), scleritis (deep boring pain, violaceous), keratitis (photophobia, fluorescein uptake), iritis/uveitis (consensual photophobia, cells/flare). Always check visual acuity, pupil exam, IOP, slit lamp.",3,"analyze",["red eye","differential","ophthalmology"],"ophtho-urg"));
cards.push(c("card-tn3-oph-"+n++,"How is central retinal artery occlusion (CRAO) diagnosed and managed?","Presentation: painless sudden monocular vision loss, APD, pale retina with cherry-red spot, boxcar segmentation of vessels. Emergency: <6h - consider intra-arterial tPA (limited evidence), ocular massage, lower IOP, workup for embolic source","CRAO is an ophthalmic stroke equivalent. 90-minute tolerance before irreversible damage. Emergent workup: carotid doppler, ECG, echocardiogram, ESR/CRP (giant cell arteritis). If GCA suspected: immediate high-dose steroids to protect fellow eye. Prognosis poor.",5,"apply",["CRAO","vision loss","cherry-red spot"],"ophtho-urg"));
cards.push(c("card-tn3-oph-"+n++,"How is temporal (giant cell) arteritis managed to prevent visual loss?","ESR often >50, CRP elevated. Do NOT wait for temporal artery biopsy to start treatment. Prednisone 60-80mg daily (or IV methylpred if visual symptoms). Biopsy within 2 weeks (remains positive on steroids). Taper over 1-2 years","GCA: age >50, new headache, jaw claudication, scalp tenderness, PMR symptoms. Risk of bilateral blindness if untreated. Temporal artery biopsy is gold standard but skip lesions cause false negatives (long specimen, bilateral if needed). ASA 81mg added.",5,"apply",["giant cell arteritis","temporal arteritis","prednisone"],"ophtho-urg"));
cards.push(c("card-tn3-oph-"+n++,"How is anterior uveitis (iritis) diagnosed and managed?","Presentation: eye pain, photophobia (including CONSENSUAL), perilimbal injection, small pupil (miosis), cells/flare in anterior chamber on slit lamp. Treatment: topical steroids (prednisolone acetate) + cycloplegic (cyclopentolate)","Consensual photophobia (pain when light in OTHER eye) is pathognomonic for uveitis. HLA-B27 associated (ankylosing spondylitis, reactive arthritis, IBD, psoriatic arthritis). Workup for recurrent: HLA-B27, CXR (sarcoidosis), syphilis, TB. Ophthalmology referral.",4,"apply",["uveitis","iritis","HLA-B27"],"ophtho-urg"));
cards.push(c("card-tn3-oph-"+n++,"How is orbital cellulitis differentiated from preseptal and how is it managed?","Preseptal: eyelid swelling/erythema, normal vision/motility/no proptosis. Oral antibiotics. Orbital: proptosis, painful EOM, decreased vision, chemosis, fever. Emergency: CT orbits, IV antibiotics (ceftriaxone + metronidazole or cloxacillin), ophthalmology/ENT","Orbital cellulitis most commonly from sinusitis extension. Complications: subperiosteal abscess (may need surgical drainage), cavernous sinus thrombosis (bilateral signs, CN III/IV/VI palsies), intracranial abscess. Preseptal in children <5 may be from bacteremia (Hib now rare with vaccination).",4,"apply",["orbital cellulitis","preseptal","CT"],"ophtho-urg"));
cards.push(c("card-tn3-oph-"+n++,"What is the management of corneal abrasion vs corneal ulcer?","Abrasion: fluorescein uptake without infiltrate. Treat: topical antibiotic (erythromycin or fluoroquinolone), avoid patching (no benefit). Ulcer: white infiltrate visible, may have hypopyon. URGENT: corneal cultures then hourly fortified topical antibiotics","Contact lens wearers: fluoroquinolone coverage (Pseudomonas risk). Never use topical steroids without ophthalmology guidance (worsens infectious keratitis). Corneal ulcer is a vision-threatening emergency. Acanthamoeba keratitis in CL wearers: severe pain, ring infiltrate.",3,"apply",["corneal abrasion","corneal ulcer","fluorescein"],"ophtho-urg"));
cards.push(c("card-tn3-oph-"+n++,"What is the approach to sudden painless vision loss?","Vascular: CRAO (pale retina, cherry-red spot), CRVO (flame hemorrhages, cotton-wool spots), vitreous hemorrhage (diabetic). Non-vascular: retinal detachment (curtain), optic neuritis (pain with movement, APD), wet AMD (metamorphopsia)","All require urgent/emergent ophthalmology. CRAO: stroke workup + consider thrombolysis. CRVO: monitor for neovascularization, anti-VEGF if macular edema. Optic neuritis: MRI brain for MS. Wet AMD: anti-VEGF injections. Amaurosis fugax: same workup as TIA.",4,"analyze",["vision loss","CRAO","CRVO","differential"],"ophtho-urg"));

// UROLOGY - UTI (10)
cards.push(c("card-tn3-uro-"+n++,"How is uncomplicated vs complicated UTI defined and what empiric antibiotics are used?","Uncomplicated: cystitis in non-pregnant premenopausal woman. Rx: nitrofurantoin 100mg BID x5d (first-line) or TMP-SMX x3d. Complicated: pregnancy, male, catheter, structural abnormality, immunosuppression, upper tract - broader coverage needed","AMMI Canada/Bugs & Drugs guidelines. Avoid fluoroquinolones for uncomplicated UTI (collateral damage, resistance). Complicated: requires culture, imaging if recurrent. Pyelonephritis: TMP-SMX or ciprofloxacin PO x7d if mild, IV ceftriaxone if requires admission.",3,"apply",["UTI","uncomplicated","nitrofurantoin"],"uro-uti"));
cards.push(c("card-tn3-uro-"+n++,"What is the management of acute pyelonephritis?","Outpatient (mild, can tolerate PO): ciprofloxacin x7d or TMP-SMX x14d. Inpatient: IV ceftriaxone or fluoroquinolone. Admit if: sepsis, unable to tolerate PO, obstruction, pregnancy, immunosuppressed","Urine culture + sensitivities essential. Blood cultures if septic. CT with contrast (or US) if no improvement at 48-72h (rule out abscess, obstruction). Pregnant: admit for IV antibiotics (ceftriaxone). Urologic obstruction with infection = EMERGENCY drainage.",4,"apply",["pyelonephritis","ceftriaxone","management"],"uro-uti"));
cards.push(c("card-tn3-uro-"+n++,"When should asymptomatic bacteriuria (ASB) be treated?","Treat ONLY in: pregnancy (risk pyelo/preterm labor) and before urologic procedures. Do NOT treat: elderly, diabetics, catheterized, spinal cord injury, nursing home residents","Screening for ASB recommended only in pregnancy (first trimester). Treatment of ASB in other populations increases resistance and C. difficile risk without benefit. A common source of inappropriate antibiotic use in Canada.",3,"apply",["asymptomatic bacteriuria","pregnancy","antibiotics"],"uro-uti"));
cards.push(c("card-tn3-uro-"+n++,"What is the approach to recurrent UTIs in women?",">=3 UTIs/year or >=2 in 6 months. Behavioral: post-coital voiding, hydration, cranberry (weak evidence). Prophylaxis options: post-coital antibiotic (nitrofurantoin 100mg or TMP-SMX), continuous low-dose prophylaxis, self-start therapy","Urine culture to confirm each episode. Rule out structural abnormality (US, CT). Consider: vaginal estrogen for postmenopausal women (restores lactobacilli). Imaging/cystoscopy if atypical features. D-mannose has some evidence for prevention.",3,"apply",["recurrent UTI","prophylaxis","women"],"uro-uti"));
cards.push(c("card-tn3-uro-"+n++,"How is UTI managed in pregnancy?","ASB: screen in first trimester, treat with cephalexin, amoxicillin, or nitrofurantoin (avoid at term). Cystitis: same as ASB treatment x7d. Pyelonephritis: admit for IV antibiotics (ceftriaxone)","Avoid: TMP-SMX (first trimester: folate antagonist; third: kernicterus), fluoroquinolones (cartilage), nitrofurantoin near term (hemolytic anemia). Monthly urine cultures after treatment. Untreated ASB in pregnancy: 20-40% develop pyelo.",4,"apply",["UTI","pregnancy","antibiotics"],"uro-uti"));
cards.push(c("card-tn3-uro-"+n++,"How is catheter-associated UTI (CAUTI) managed?","Diagnosis requires symptoms (NOT just positive culture). Remove or replace catheter. Treat x7d (10-14d if delayed response). Do NOT treat asymptomatic catheterized patients even with positive culture","CAUTI prevention: avoid unnecessary catheters, remove early, closed drainage, daily reassessment of need. Nurse-driven removal protocols reduce CAUTI rates. Candida in urine with catheter: usually colonization, only treat if symptomatic or high-risk (neutropenic, renal transplant).",3,"apply",["CAUTI","catheter","UTI"],"uro-uti"));
cards.push(c("card-tn3-uro-"+n++,"How is UTI diagnosed in elderly patients?","Symptoms required: dysuria, frequency, urgency, suprapubic pain, new incontinence, gross hematuria. Do NOT rely on pyuria alone (common asymptomatic finding). Confusion alone is NOT an indication to treat UTI","Over-diagnosis of UTI in elderly is extremely common and harmful. Positive UA/culture without urinary symptoms should not be treated. Delirium workup should include UTI in differential but also other causes. Urine dip sensitivity/specificity poor in elderly.",3,"apply",["UTI","elderly","diagnosis"],"uro-uti"));
cards.push(c("card-tn3-uro-"+n++,"What is the management of acute prostatitis?","Presentation: fever, perinatal pain, dysuria, urinary retention, boggy tender prostate on DRE. Treatment: fluoroquinolone (ciprofloxacin) x4-6wk or TMP-SMX x4-6wk. If septic: IV ceftriaxone + aminoglycoside","Prostatic abscess: suspect if no improvement at 48h, CT confirms, may need drainage. Chronic bacterial prostatitis: recurrent UTI with same organism, treat x4-6wk. Chronic prostatitis/CPPS (most common): no infection, multimodal therapy (alpha-blocker, physio, CBT).",4,"apply",["prostatitis","fluoroquinolone","management"],"uro-uti"));
cards.push(c("card-tn3-uro-"+n++,"What is the approach to urinary retention?","Acute: catheterize (Foley or intermittent). Measure PVR. If >1L: monitor for post-obstructive diuresis. Causes: BPH (most common in men), medications (anticholinergics, opioids), neurogenic (cauda equina - emergency), stricture","Cauda equina syndrome: saddle anesthesia, bilateral leg weakness, urinary retention - MRI STAT and surgical decompression. Medications causing retention: anticholinergics, opioids, alpha-agonists (pseudoephedrine), antihistamines. Post-catheterization trial of void with alpha-blocker.",3,"apply",["urinary retention","catheter","cauda equina"],"uro-uti"));
cards.push(c("card-tn3-uro-"+n++,"What is the approach to hematuria?","Microscopic (>3 RBC/HPF) or gross. Workup: UA+culture, cytology, CT urogram + cystoscopy for patients >35 or risk factors (smoking, occupational). Transient causes: UTI, exercise, menstruation - repeat UA before full workup","Red flags: gross, painless, >35yo, smoking history. Bladder cancer is most important diagnosis to rule out. Glomerular hematuria (dysmorphic RBCs, casts, proteinuria): nephrology referral. IgA nephropathy most common glomerulonephritis worldwide.",3,"apply",["hematuria","workup","cystoscopy"],"uro-uti"));

// UROLOGY - PROSTATE (10)
cards.push(c("card-tn3-uro-"+n++,"What is the IPSS score and how does it guide BPH management?","International Prostate Symptom Score: 7 questions on urinary symptoms + 1 QoL. Mild 0-7: watchful waiting. Moderate 8-19: medical therapy. Severe 20-35: consider surgery","BPH evaluation: DRE, PSA (baseline), urinalysis, creatinine, IPSS. Uroflowmetry and PVR for moderate-severe. BPH does NOT increase prostate cancer risk. Prostate size does not correlate well with symptom severity.",3,"recall",["BPH","IPSS","prostate"],"uro-prostate"));
cards.push(c("card-tn3-uro-"+n++,"What are the medical treatments for BPH?","Alpha-blockers (tamsulosin, alfuzosin): rapid symptom relief. 5-alpha reductase inhibitors (finasteride, dutasteride): reduce prostate size over 6mo, for large prostates. Combination if large prostate. Tadalafil 5mg daily also effective","Alpha-blockers SE: orthostatic hypotension, dizziness, retrograde ejaculation, intraoperative floppy iris syndrome. 5-ARI SE: decreased libido, ED, gynecomastia, reduces PSA by ~50% (double PSA value for cancer screening). 5-ARI reduces risk of acute retention and surgery.",3,"apply",["BPH","alpha-blocker","tamsulosin","finasteride"],"uro-prostate"));
cards.push(c("card-tn3-uro-"+n++,"When is surgical intervention indicated for BPH?","Indications: refractory urinary retention, recurrent UTIs, bladder stones, renal insufficiency from obstruction, failed medical therapy, recurrent gross hematuria. TURP is gold standard. Alternatives: HoLEP, UroLift, Rezum","TURP complications: retrograde ejaculation (75%), TUR syndrome (hyponatremia from irrigation), bleeding, urethral stricture. HoLEP: size-independent, less bleeding. Minimally invasive (UroLift, Rezum): preserve ejaculation, for moderate symptoms.",4,"apply",["BPH","TURP","surgery"],"uro-prostate"));
cards.push(c("card-tn3-uro-"+n++,"What is the approach to PSA screening and an elevated PSA?","CTFPHC: against routine screening. CUA: shared decision-making 50-70 (45 if high-risk). Elevated PSA: repeat in 4-6wk. If persistently elevated: consider MRI then targeted biopsy. PSA >100 suggests metastatic disease","PSA elevations: BPH, prostatitis, recent ejaculation, cycling, UTI, cancer. PSA velocity >0.75ng/mL/yr concerning. Free PSA%: <10% more likely cancer, >25% more likely benign. mpMRI with PI-RADS scoring reduces unnecessary biopsies.",4,"apply",["PSA","prostate cancer","screening"],"uro-prostate"));
cards.push(c("card-tn3-uro-"+n++,"How is localized prostate cancer managed?","Low-risk (Gleason 6, PSA<10, T1-T2a): active surveillance preferred (PSA q3-6mo, DRE q12mo, repeat biopsy). Intermediate/high-risk: radical prostatectomy or radiation + ADT. Metastatic: ADT + docetaxel or novel hormonal agents","Active surveillance avoids overtreatment. Gleason score: 6=low, 7=intermediate (3+4 better than 4+3), 8-10=high. Side effects of treatment: erectile dysfunction, incontinence (surgery), bowel/bladder toxicity (radiation). 10-year cancer-specific survival >95% for localized.",4,"apply",["prostate cancer","active surveillance","Gleason"],"uro-prostate"));
cards.push(c("card-tn3-uro-"+n++,"What is the presentation and management of acute urinary retention in BPH?","Presentation: inability to void, suprapubic pain, distended bladder. Management: Foley catheter, start tamsulosin, trial of void in 3-5 days. If fails: long-term catheter or surgery referral","Precipitants: medications (anticholinergics, sympathomimetics, opioids), alcohol, cold, constipation. Measure residual volume. If >1L: slow decompression (controversial) and monitor for post-obstructive diuresis (replace fluids if significant). TWOC success ~60% with alpha-blocker.",3,"apply",["urinary retention","BPH","catheter"],"uro-prostate"));
cards.push(c("card-tn3-uro-"+n++,"What is the approach to an incidental prostate nodule on DRE?","Firm, irregular, asymmetric nodule on DRE requires investigation regardless of PSA. Order PSA. Refer urology for biopsy (TRUS-guided or MRI-targeted). 50% of palpable nodules are cancer","DRE detects primarily peripheral zone tumors (70% of cancers arise here). Normal DRE does not exclude cancer. DRE + PSA together are more informative than either alone. BPH causes smooth symmetric enlargement.",3,"apply",["prostate nodule","DRE","biopsy"],"uro-prostate"));
cards.push(c("card-tn3-uro-"+n++,"What is androgen deprivation therapy and its side effects?","ADT: GnRH agonists (leuprolide) or antagonists (degarelix), or surgical orchidectomy. For metastatic or locally advanced prostate cancer. Side effects: hot flashes, osteoporosis, metabolic syndrome, CV risk, sarcopenia, cognitive decline","Initial GnRH agonist causes testosterone flare (can worsen bone pain/cord compression) - give with antiandrogen flare protection x2wk. GnRH antagonists avoid flare. Monitor: DXA, metabolic panel, CV risk. Exercise program essential. Intermittent ADT may reduce side effects.",4,"apply",["ADT","prostate cancer","side effects"],"uro-prostate"));
cards.push(c("card-tn3-uro-"+n++,"How is erectile dysfunction evaluated and managed?","Evaluation: history (psychogenic vs organic), medications review, CV risk assessment, testosterone level, glucose/lipids. Management: lifestyle (exercise, weight loss, smoking cessation), PDE5 inhibitor first-line (sildenafil, tadalafil). Second: vacuum device, ICI, penile prosthesis","ED is a marker of CV disease (shares risk factors and endothelial dysfunction). Assess CV fitness for sexual activity. PDE5i contraindicated with nitrates (severe hypotension). Testosterone replacement if confirmed hypogonadism. Psychogenic: CBT + PDE5i.",3,"apply",["erectile dysfunction","PDE5 inhibitor","management"],"uro-prostate"));
cards.push(c("card-tn3-uro-"+n++,"What is the approach to a scrotal mass?","Painless: testicular cancer until proven otherwise (US + tumor markers AFP/bHCG/LDH). Transilluminates: hydrocele. Does not: solid mass (cancer concern). Painful: torsion (emergency, <6h), epididymitis. Testicular cancer: radical inguinal orchiectomy (never transscrotal)","Testicular torsion: no cremasteric reflex, high-riding testis, <6h for salvage. US if diagnosis unclear but do not delay surgery. Testicular cancer: peak 15-35yr. Seminoma (radiosensitive) vs non-seminoma (chemo). Staging CT + markers guide treatment. 95% cure rate overall.",4,"apply",["scrotal mass","testicular cancer","torsion"],"uro-prostate"));

console.log("ENT+Oph+Uro added. Total: " + cards.length);
fs.writeFileSync("C:/dev/srs-mccqe1/data/_parts123456.json", JSON.stringify(cards));
console.log("Saved");
