const fs = require("fs");
const emCards = JSON.parse(fs.readFileSync("C:/dev/srs-mccqe1/data/_em_cards.json","utf8"));
const cards = [...emCards];
let n = 46;
function c(id,q,a,ex,d,bl,tags,tid){return{id,question:q,answer:a,explanation:ex,difficulty:d,bloomLevel:bl,tags,topicId:tid};}

// PUBLIC HEALTH - SCREENING (15)
cards.push(c("card-tn3-ph-"+n++,"What are the CTFPHC recommendations for breast cancer screening?","Age 50-74: mammography q2-3 years. Age 40-49: do NOT routinely screen. No CBE or BSE for screening","CTFPHC 2018 differs from USPSTF (now recommends from 40). Many provinces still offer from 40. High-risk (BRCA, chest radiation) follow different protocol with MRI. Informed decision-making emphasized.",4,"recall",["breast cancer","screening","CTFPHC","mammography"],"ph-screening"));
cards.push(c("card-tn3-ph-"+n++,"What are the CTFPHC recommendations for cervical cancer screening?","Age 25-69: Pap q3 years. Do not screen <25 or >69 (if adequate prior screening). HPV co-testing not currently recommended by CTFPHC","CTFPHC 2013. Starts at 25 (vs US at 21). BC and Ontario transitioning to HPV-primary q5 years. Stop at 69 if 3 consecutive negatives in prior 10 years. Abnormal Pap follow-up per colposcopy guidelines.",3,"recall",["cervical cancer","Pap smear","CTFPHC"],"ph-screening"));
cards.push(c("card-tn3-ph-"+n++,"What are the CTFPHC recommendations for colorectal cancer screening?","Age 50-74: FIT q2 years or flexible sigmoidoscopy q10 years. Colonoscopy NOT recommended as primary screen for average risk","FIT replaced guaiac FOBT (better sensitivity, no dietary restrictions). Positive FIT requires diagnostic colonoscopy. High-risk (FHx, IBD, polyposis) screened earlier with colonoscopy. CTFPHC 2016.",3,"recall",["colorectal cancer","FIT","screening"],"ph-screening"));
cards.push(c("card-tn3-ph-"+n++,"What are the CTFPHC recommendations for lung cancer screening?","Age 55-74 with 30+ pack-year history (current or quit <15y): annual low-dose CT. Do not screen never-smokers or <30 pack-years","NLST/NELSON trials: 20% mortality reduction with LDCT. Provincial programs in ON, BC, AB. ~25% false positive rate. Always pair with smoking cessation counseling.",3,"recall",["lung cancer","LDCT","screening"],"ph-screening"));
cards.push(c("card-tn3-ph-"+n++,"What is the CTFPHC position on PSA screening for prostate cancer?","Recommend AGAINST routine PSA screening for all ages (2014). Shared decision-making if patient requests. CUA supports discussion for men 50-70","CTFPHC: harms outweigh benefits (overdiagnosis, overtreatment, biopsy complications). CUA differs. MRI-targeted biopsy has improved accuracy since guideline. High-risk: Black men, FHx - discuss from age 45.",4,"recall",["prostate cancer","PSA","CTFPHC"],"ph-screening"));
cards.push(c("card-tn3-ph-"+n++,"Define sensitivity, specificity, PPV, and NPV with their formulas.","Sn=TP/(TP+FN). Sp=TN/(TN+FP). PPV=TP/(TP+FP). NPV=TN/(TN+FN). Sn/Sp independent of prevalence; PPV/NPV vary with prevalence","SnNOut: sensitive test negative rules OUT. SpPIn: specific test positive rules IN. Screening tests prioritize sensitivity. Confirmatory tests prioritize specificity. PPV increases with prevalence.",3,"recall",["sensitivity","specificity","PPV","NPV"],"ph-screening"));
cards.push(c("card-tn3-ph-"+n++,"How are NNT and NNS calculated and interpreted?","NNT = 1/ARR. NNS = 1/(prevalence x sensitivity x treatment efficacy). Lower = more effective. NNS for mammography 50-69: ~720 over 11 years","NNT communicates treatment benefit magnitude. NNS helps evaluate screening program utility. Both useful for shared decision-making with patients. ARR = absolute risk reduction = control event rate - experimental event rate.",3,"apply",["NNT","NNS","biostatistics"],"ph-screening"));
cards.push(c("card-tn3-ph-"+n++,"What are the Wilson-Jungner criteria for evaluating screening programs?","10 criteria: important problem, accepted treatment, facilities available, recognizable latent stage, suitable test, acceptable to population, natural history understood, agreed treatment policy, cost-effective, ongoing process","1968 WHO criteria remain gold standard. Modern additions: program must reduce mortality (not just detect), benefits must outweigh harms (overdiagnosis, false positives). CTFPHC applies these principles to all recommendations.",3,"recall",["Wilson-Jungner","screening criteria"],"ph-screening"));
cards.push(c("card-tn3-ph-"+n++,"What types of bias affect screening program evaluation?","Lead-time: earlier detection without survival change. Length-time: detecting slow-growing tumors preferentially. Selection: healthy volunteers screened. Overdiagnosis: detecting non-harmful disease","Lead-time bias makes screened patients APPEAR to live longer. Mortality reduction (not survival) is the correct outcome. Overdiagnosis particularly relevant in prostate and thyroid screening.",4,"analyze",["bias","screening","lead-time"],"ph-screening"));
cards.push(c("card-tn3-ph-"+n++,"What are the Canadian diabetes screening recommendations?","Screen q3-5y with FPG or A1c from age 40, earlier if high-risk (BMI>25, Indigenous, South Asian, African descent, GDM, HTN). Use CANRISK questionnaire","Diabetes Canada 2018 CPG. Diagnostic: FPG>=7.0, 2h-OGTT>=11.1, A1c>=6.5%, random>=11.1+symptoms. Need 2 abnormal tests if asymptomatic. CANRISK is Canadian-specific risk calculator.",3,"recall",["diabetes","screening","CANRISK"],"ph-screening"));
cards.push(c("card-tn3-ph-"+n++,"What are the CTFPHC recommendations for AAA screening?","One-time abdominal US for men 65-80 who have ever smoked. Do not screen women or never-smokers","AAA screening reduces AAA mortality ~50%. AAA >=3.0cm. Management by size: <4cm q3y surveillance, 4-4.4 annually, 4.5-5.4 q6mo, >=5.5cm surgical repair. Emergency repair for symptomatic/ruptured at any size.",3,"recall",["AAA","screening","ultrasound"],"ph-screening"));
cards.push(c("card-tn3-ph-"+n++,"What is the CTFPHC position on depression screening in primary care?","Recommend AGAINST routine screening for depression in adults (2013). Be alert to symptoms during encounters (case-finding approach)","Controversial. Insufficient evidence screening improves outcomes without integrated treatment program. PHQ-2 then PHQ-9 commonly used tools. Be vigilant in high-risk: chronic illness, postpartum, chronic pain.",3,"recall",["depression","screening","PHQ-9"],"ph-screening"));
cards.push(c("card-tn3-ph-"+n++,"What prenatal screening tests are offered in Canada by trimester?","1st trimester (11-14wk): NT US + PAPP-A + free beta-hCG. 2nd (15-20wk): quad screen. NIPT (cell-free DNA) increasingly offered as primary screen","NIPT >99% sensitivity for trisomy 21, positive still needs amnio/CVS confirmation. Enhanced FTS detects ~85% T21. Coverage varies by province. NIPT cost-covered in most provinces for high-risk or as contingent screen.",3,"recall",["prenatal screening","NIPT","trisomy 21"],"ph-screening"));
cards.push(c("card-tn3-ph-"+n++,"What newborn screening tests are performed across Canada?","Blood spot (heel prick 24-48h): metabolic/endocrine/hemoglobin disorders (PKU, hypothyroidism, CF, sickle cell). Universal hearing screen (OAE/ABR). CCHD screen (pulse ox)","Number of conditions varies by province (Ontario ~30). Screening not diagnostic - positives need confirmatory testing. Too early (<24h) increases false positives for PKU. Critical to treat congenital hypothyroidism within 2 weeks.",3,"recall",["newborn screening","PKU"],"ph-screening"));
cards.push(c("card-tn3-ph-"+n++,"How are ROC curves and likelihood ratios used to evaluate diagnostic tests?","ROC: AUC 1.0=perfect, 0.5=useless. LR+ = Sn/(1-Sp); >10 is strong. LR- = (1-Sn)/Sp; <0.1 is strong. LRs are prevalence-independent","LRs applied to pre-test probability via Fagan nomogram give post-test probability. ROC curves compare tests and select optimal cut-offs. AUC >0.9 excellent, 0.7-0.9 good, 0.5-0.7 poor.",4,"apply",["ROC","likelihood ratio","diagnostics"],"ph-screening"));

// PUBLIC HEALTH - EPIDEMIOLOGY (15)
cards.push(c("card-tn3-ph-"+n++,"What is the difference between incidence and prevalence?","Incidence: new cases/population/time (rate). Prevalence: total cases/population at a point (proportion). Prevalence ~ incidence x duration","Incidence = risk (etiologic studies). Prevalence = burden (health services planning). Chronic diseases: high prevalence relative to incidence. High fatality: low prevalence relative to incidence.",2,"recall",["incidence","prevalence","epidemiology"],"ph-epidemiology"));
cards.push(c("card-tn3-ph-"+n++,"Rank epidemiological study designs by evidence strength.","1) SR/meta-analysis 2) RCT 3) Cohort 4) Case-control 5) Cross-sectional 6) Case series 7) Expert opinion. Cohort measures RR; case-control measures OR","RCTs strongest for interventions but ethical limitations. Cohort: prospective, measures incidence. Case-control: efficient for rare diseases. Cross-sectional: prevalence only, no temporality. Ecological fallacy in aggregate studies.",3,"recall",["study design","evidence hierarchy"],"ph-epidemiology"));
cards.push(c("card-tn3-ph-"+n++,"Differentiate relative risk, odds ratio, and hazard ratio.","RR = risk exposed/risk unexposed (cohort). OR = (ad)/(bc) from 2x2 (case-control). HR = instantaneous risk ratio from survival analysis with censoring","OR approximates RR when outcome is rare (<10%). Case-control cannot calculate RR directly. HR accounts for variable follow-up and censoring. All measure association not causation.",4,"apply",["relative risk","odds ratio","hazard ratio"],"ph-epidemiology"));
cards.push(c("card-tn3-ph-"+n++,"What are the Bradford Hill criteria for causation?","Strength, Consistency, Specificity, Temporality (only absolute), Biological gradient, Plausibility, Coherence, Experiment, Analogy","Temporality is the ONLY essential criterion. Strong associations less likely confounded. Originally applied to smoking and lung cancer (1965). Help distinguish causation from correlation in observational studies.",3,"recall",["Bradford Hill","causation"],"ph-epidemiology"));
cards.push(c("card-tn3-ph-"+n++,"Differentiate confounding from effect modification.","Confounding: third variable distorts exposure-outcome relationship (bias to eliminate). Effect modification: exposure effect differs across subgroups (biological finding to report stratified). Test: adjusted vs crude differs >10% = confounding","Address confounding: randomization, restriction, matching, stratification, multivariable analysis. Effect modification: report stratum-specific estimates. Residual confounding from unmeasured variables always possible in observational studies.",4,"analyze",["confounding","effect modification"],"ph-epidemiology"));
cards.push(c("card-tn3-ph-"+n++,"What is the difference between internal and external validity?","Internal: results free from bias within study (accuracy). External: results generalizable to other populations. Internal is necessary but not sufficient for external","Threats to internal: selection bias, information bias, confounding. Threats to external: narrow inclusion, single-center, volunteer bias. RCTs often high internal but low external. Pragmatic trials sacrifice some internal for generalizability.",3,"recall",["internal validity","external validity"],"ph-epidemiology"));
cards.push(c("card-tn3-ph-"+n++,"Define and differentiate key measures of disease frequency.","Incidence rate = cases/person-time. Cumulative incidence = cases/population at risk. Attack rate = cases during outbreak/at-risk. Mortality rate = deaths/population. CFR = deaths/cases x 100%","Person-time accounts for variable follow-up. Age standardization allows population comparisons (Canada uses 2011 population for direct standardization). Attack rate used in outbreak settings.",3,"apply",["incidence rate","mortality","epidemiology"],"ph-epidemiology"));
cards.push(c("card-tn3-ph-"+n++,"What are Type I and Type II errors?","Type I (alpha=0.05): false positive, rejecting true null. Type II (beta=0.20): false negative, failing to reject false null. Power = 1-beta >= 0.80","Larger sample reduces both errors. Multiple comparisons inflate Type I (Bonferroni correction). Underpowered studies risk Type II. A priori sample size calculation essential. Non-significant result does not prove null.",3,"recall",["Type I error","Type II error","power"],"ph-epidemiology"));
cards.push(c("card-tn3-ph-"+n++,"What do p-values and confidence intervals represent?","p-value: probability of results as extreme if null true. 95% CI: 95% of repeated CIs would contain true parameter. CI excluding null (0 for diff, 1 for ratio) = significant","p-value is NOT probability null is true. Wide CI = imprecision (small sample). CI more informative than p-value (gives effect size + precision). Statistical significance does not equal clinical significance.",3,"recall",["p-value","confidence interval"],"ph-epidemiology"));
cards.push(c("card-tn3-ph-"+n++,"What are the key nationally notifiable diseases in Canada?","TB, HIV/AIDS, measles, invasive meningococcal, pertussis, syphilis, gonorrhea, hepatitis B/C, cholera, Ebola, mpox (~60 total). Report: clinician to local PH to province to PHAC","Mandated by provincial legislation. Urgent diseases (measles, meningococcal) require immediate reporting. PHAC coordinates via CNDSS. List varies slightly by jurisdiction.",3,"recall",["notifiable diseases","PHAC","surveillance"],"ph-epidemiology"));
cards.push(c("card-tn3-ph-"+n++,"What are the steps in an outbreak investigation?","1) Verify diagnosis 2) Confirm outbreak (observed>expected) 3) Case definition 4) Case finding 5) Descriptive epi (person/place/time, epi curve) 6) Hypotheses 7) Analytical study 8) Control measures 9) Communicate","Epi curve shape: point source (single peak), continuous (plateau), propagated (successive peaks). Do not delay control measures for investigation completion. R0 guides control: need 1-1/R0 reduction.",4,"apply",["outbreak","investigation","epidemic curve"],"ph-epidemiology"));
cards.push(c("card-tn3-ph-"+n++,"Name and define the levels of prevention.","Primary: prevent disease (vaccination). Secondary: early detection (screening). Tertiary: reduce disability (rehab). Quaternary: prevent overdiagnosis/overtreatment (deprescribing). Primordial: prevent risk factors (policy)","Population-level primary prevention has greatest impact. Most screening is secondary. Periodic health exam incorporates all levels. Quaternary prevention increasingly emphasized to combat medicalization.",2,"recall",["prevention levels","public health"],"ph-epidemiology"));
cards.push(c("card-tn3-ph-"+n++,"How are attributable risk and population attributable risk calculated and used?","AR = risk_exposed - risk_unexposed. AR% = AR/risk_exposed. PAR = risk_total - risk_unexposed. PAR% = PAR/risk_total. NNT = 1/AR","PAR depends on both RR AND prevalence of exposure. High-prevalence modest-RR exposures may have larger PAR than rare high-RR exposures. PAR guides public health priority setting. AR guides individual patient counseling.",4,"apply",["attributable risk","PAR","NNT"],"ph-epidemiology"));
cards.push(c("card-tn3-ph-"+n++,"What are the key elements of the Canadian Pandemic Influenza Preparedness plan?","Surveillance, public health measures (isolation/quarantine), mass vaccination, antiviral stockpiling (oseltamivir), healthcare surge capacity, risk communication, F/P/T coordination via PHAC","COVID-19 lessons: importance of early border measures, domestic vaccine manufacturing, equity in distribution, mental health supports. NESS maintains PPE stockpiles. Pandemic preparedness requires all-of-government approach.",3,"recall",["pandemic","CPIP","PHAC"],"ph-epidemiology"));
cards.push(c("card-tn3-ph-"+n++,"What are the Canadian adult immunization schedule highlights?","Tdap x1 then Td q10y. Influenza annually >=6mo. PCV20 or PCV15+PPSV23 >=65 or high-risk. Shingrix >=50 x2 doses. HPV catch-up to 26. COVID per NACI","NACI provides evidence-based recs; provinces implement variably. HCW requirements: influenza, HepB, varicella. Immunocompromised: avoid live vaccines (MMR, varicella, LAIV). Pregnancy: Tdap each pregnancy 27-32wk.",3,"recall",["immunization","vaccines","NACI"],"ph-epidemiology"));

// PUBLIC HEALTH - SOCIAL DETERMINANTS (15)
cards.push(c("card-tn3-ph-"+n++,"What are the social determinants of health recognized in Canada?","Income, education, employment, social/physical environments, biology, health services, gender, culture, Indigenous status, social support, childhood experiences. Income is strongest single predictor","PHAC Key Health Inequalities report documents disparities across 72 indicators. Health equity requires addressing root causes not just healthcare access. 1% increase in income inequality associated with increased mortality across provinces.",3,"recall",["SDOH","social determinants","health equity"],"ph-social-det"));
cards.push(c("card-tn3-ph-"+n++,"What are the key health disparities facing Indigenous peoples in Canada?","Life expectancy 10-15y lower. Diabetes 3-5x, TB >40x (Inuit), youth suicide 5-7x, infant mortality 2-3x. Lower access to clean water, housing, healthcare","Rooted in colonization, residential schools, systemic racism. TRC Calls to Action include 7 health recommendations. Jordans Principle ensures First Nations children get needed services. Cultural safety training now mandatory.",4,"recall",["Indigenous health","disparities","TRC"],"ph-social-det"));
cards.push(c("card-tn3-ph-"+n++,"How does cultural safety differ from cultural competence?","Competence: learning about other cultures. Safety: recognizing power imbalances, addressing systemic racism, patient defines if encounter felt safe. Requires self-reflection on own biases","Developed from Maori nursing in NZ. Shifts from knowing the other to examining how colonial structures affect care. CPSO and regulators mandate training. NOT about memorizing cultural practices.",3,"analyze",["cultural safety","Indigenous health"],"ph-social-det"));
cards.push(c("card-tn3-ph-"+n++,"What is the impact of poverty on health in Canada?","Lowest income quintile: 3-5y lower life expectancy, 2x diabetes, higher CVD/mental illness. Child poverty: more asthma, obesity, developmental delay. ~1 in 7 below poverty line","Food insecurity affects 1 in 8 households. Canada Poverty Reduction Strategy targets 50% reduction by 2030. Screen with single question: Do you have difficulty making ends meet? Poverty is a modifiable risk factor.",3,"recall",["poverty","health outcomes","Canada"],"ph-social-det"));
cards.push(c("card-tn3-ph-"+n++,"How do adverse childhood experiences (ACEs) affect adult health?",">=4 ACEs: 4-12x substance use/depression/suicide risk; 2-4x CVD, cancer, COPD. Dose-response relationship (Felitti 1998 ACE Study)","Mechanisms: toxic stress on brain development, HPA axis dysregulation, health risk behaviors. Trauma-informed care recognizes widespread ACE impact. ACE screening increasingly used in Canadian primary care.",3,"recall",["ACEs","toxic stress","childhood"],"ph-social-det"));
cards.push(c("card-tn3-ph-"+n++,"What are the 5 principles of the Canada Health Act and its coverage gaps?","Public administration, Comprehensiveness, Universality, Portability, Accessibility. NOT covered: dental, vision, outpatient Rx, mental health, home care, LTC","~30% healthcare spending is private. National pharmacare proposed. Dental care program for low-income started 2022-23. Provinces administer own systems within CHA. Federal transfer payments conditional on CHA compliance.",3,"recall",["Canada Health Act","universal healthcare"],"ph-social-det"));
cards.push(c("card-tn3-ph-"+n++,"What is health literacy and how does it affect outcomes?","Ability to access, understand, and use health information. ~60% Canadian adults have inadequate health literacy. Low literacy: poorer self-management, more ED visits, higher mortality","Use plain language (grade 6-8), teach-back method, visual aids. Numeracy often worse than literacy. Ottawa Decision Aids are Canadian evidence-based shared decision-making tools. Vulnerable: elderly, immigrants, low SES.",3,"apply",["health literacy","communication"],"ph-social-det"));
cards.push(c("card-tn3-ph-"+n++,"What are the health effects of homelessness in Canada?","Life expectancy 42-52y. 3-6x mortality. Mental illness 30-40%, high substance use, TB, HIV, HCV, frostbite. ~235,000 experience homelessness annually","Housing First model (no preconditions) has strong evidence. Federal Reaching Home strategy funds programs. Low-barrier care, harm reduction, trauma-informed approach. Physicians should connect with social services and advocate for housing.",3,"apply",["homelessness","disparities"],"ph-social-det"));
cards.push(c("card-tn3-ph-"+n++,"What is harm reduction and what programs exist in Canada?","Policies reducing substance use harms without requiring abstinence. Programs: supervised consumption sites, needle exchange, naloxone distribution, safe supply, OAT (methadone, suboxone)","Insite (Vancouver 2003) was first SCS. Evidence: reduced OD deaths, HIV, public drug use; increased treatment uptake. Health Canada grants CDSA exemptions. Safe supply provides pharmaceutical alternatives to toxic unregulated supply.",3,"recall",["harm reduction","supervised consumption","opioid"],"ph-social-det"));
cards.push(c("card-tn3-ph-"+n++,"What are the TRC health-related Calls to Action?","CTA 18: acknowledge disparities from government policies. 19: close health gaps. 22: value Indigenous healing. 23-24: increase Indigenous HCWs and cultural competency training for all","TRC documented residential school abuses (150,000 children, >4000 deaths). Intergenerational trauma contributes to current disparities. All Canadian medical schools now include Indigenous health curriculum. MCCQE expects this knowledge.",4,"recall",["TRC","Calls to Action","Indigenous"],"ph-social-det"));
cards.push(c("card-tn3-ph-"+n++,"What is implicit bias in healthcare?","Unconscious attitudes affecting decisions. Affects pain management (Black patients less analgesia), referrals, diagnostic workup, communication. IAT measures unconscious bias","Mitigate: awareness, perspective-taking, individuation, counter-stereotypic imaging, institutional policies, diverse workforce. Canadian regulators increasingly require EDI training. Systemic bias compounds individual bias.",3,"analyze",["implicit bias","health equity"],"ph-social-det"));
cards.push(c("card-tn3-ph-"+n++,"What should be screened in the refugee health assessment?","TB (CXR+IGRA), HIV, HBV, HCV, syphilis, malaria (endemic areas), parasites, iron deficiency, lead (children), dental, mental health (PTSD), catch-up vaccines, vision/hearing","CCIRH guidelines. IFHP covers government-assisted refugees. Latent TB 30-50% from high-burden countries. Mental health screening includes torture/trauma history with culturally appropriate tools.",4,"apply",["refugee health","screening","immigration"],"ph-social-det"));
cards.push(c("card-tn3-ph-"+n++,"How does climate change affect health in Canada?","Direct: heat illness, wildfire smoke, extreme weather. Indirect: vector-borne expansion (Lyme northward), food/water insecurity, mental health. Disproportionate: Indigenous, northern, low-income","Canada warming 2x global average, Arctic 3x. Lyme cases up >10-fold since 2009. Wildfire smoke growing respiratory concern. Lancet Countdown Canada tracks 41 climate-health indicators.",3,"recall",["climate change","health","Lyme"],"ph-social-det"));
cards.push(c("card-tn3-ph-"+n++,"Describe the Canadian opioid crisis: epidemiology and response.","~22 deaths/day (~8000/yr). 80%+ involve fentanyl. Response: Good Samaritan Act (2017), expanded naloxone, SCS, prescribing guidelines, safe supply pilots","BC highest death rate. Good Samaritan Act protects people calling 911 during OD. Canadian pain guidelines emphasize non-opioid multimodal analgesia first-line. Toxic unregulated supply is primary driver.",4,"recall",["opioid crisis","fentanyl","public health"],"ph-social-det"));
cards.push(c("card-tn3-ph-"+n++,"What is MAID in Canada and what are the eligibility criteria?",">=18, capable, eligible for Canadian health services, grievous/irremediable condition causing intolerable suffering. Track 1: death reasonably foreseeable. Track 2: not foreseeable (extra safeguards). 2 independent assessments","Legal since 2016 (Carter v Canada). Bill C-7 (2021) expanded Track 2. Mental illness as sole condition eligible March 2027 (delayed). ~13,000 MAID deaths 2022 (4.1% of all deaths). Conscience rights protect objecting providers.",4,"recall",["MAID","medical assistance in dying"],"ph-social-det"));

console.log("PH cards added. Total so far: " + cards.length);
fs.writeFileSync("C:/dev/srs-mccqe1/data/_parts12.json", JSON.stringify(cards));
console.log("Parts 1-2 saved");
