const fs = require("fs");
const cards = [];
let n = 1;
function c(id,q,a,ex,d,bl,tags,tid) { return {id,question:q,answer:a,explanation:ex,difficulty:d,bloomLevel:bl,tags,topicId:tid}; }

// EM-RESUS (20)
cards.push(c("card-tn3-em-"+n++,"In adult ACLS, what is the recommended dose of epinephrine during cardiac arrest?","Epinephrine 1 mg IV/IO every 3-5 minutes","Per AHA/HSFC 2020 guidelines, epinephrine 1 mg (1:10,000) IV/IO every 3-5 min. For shockable rhythms give after 2nd shock. For non-shockable rhythms give immediately upon IV/IO access.",4,"recall",["ACLS","epinephrine","cardiac arrest"],"em-resus"));
cards.push(c("card-tn3-em-"+n++,"List the Hs and Ts of reversible causes of cardiac arrest.","Hs: Hypovolemia, Hypoxia, Hydrogen ion (acidosis), Hypo/Hyperkalemia, Hypothermia. Ts: Tension pneumothorax, Tamponade, Toxins, Thrombosis (PE/coronary)","Systematic evaluation of reversible causes is critical during each rhythm check. In Canada hypothermia arrests are particularly relevant given climate. Do not declare death until rewarmed to 32C.",3,"recall",["ACLS","cardiac arrest","reversible causes"],"em-resus"));
cards.push(c("card-tn3-em-"+n++,"When and at what dose should amiodarone be given in shock-refractory VF/pVT?","Amiodarone 300 mg IV after 3rd shock, then 150 mg for recurrent VF/pVT. Alternative: lidocaine 1-1.5 mg/kg","ALPS trial showed amiodarone and lidocaine improved survival to hospital admission vs placebo for witnessed VF. Per HSFC amiodarone is first-line antiarrhythmic for refractory VF.",4,"apply",["ACLS","amiodarone","VF"],"em-resus"));
cards.push(c("card-tn3-em-"+n++,"What defibrillation energies are used for adult VF/pVT?","Biphasic: 120-200 J initial (device-specific), same or higher for subsequent. Monophasic: 360 J all shocks. If unknown use max energy.","Minimize peri-shock pause to less than 10 seconds. Resume compressions immediately post-shock without rhythm check. CPR quality (rate 100-120, depth 5-6cm, full recoil) is the strongest predictor of ROSC.",3,"recall",["defibrillation","VF","ACLS"],"em-resus"));
cards.push(c("card-tn3-em-"+n++,"What drugs and doses are used for Rapid Sequence Intubation?","Induction: Ketamine 1-2 mg/kg or Propofol 1-2 mg/kg. Paralytic: Succinylcholine 1-1.5 mg/kg (onset 45s) or Rocuronium 1.2 mg/kg (onset 60s)","Ketamine preferred in hemodynamic instability and asthma. Propofol causes hypotension. Etomidate 0.3 mg/kg is another option but may cause adrenal suppression. Preoxygenation with 100% O2 for 3 min or 8 vital capacity breaths.",5,"apply",["RSI","intubation","ketamine","rocuronium"],"em-resus"));
cards.push(c("card-tn3-em-"+n++,"What are the contraindications to succinylcholine?","Hyperkalemia, burns/crush >48h, denervation injury, malignant hyperthermia susceptibility, neuromuscular disease, penetrating eye injury, prolonged immobilization","Succinylcholine causes 0.5 mEq/L K+ rise normally. Upregulated extrajunctional AChRs in burns/denervation cause potentially fatal hyperkalemia. Use rocuronium 1.2 mg/kg instead, reversible with sugammadex 16 mg/kg.",4,"recall",["RSI","succinylcholine","contraindications"],"em-resus"));
cards.push(c("card-tn3-em-"+n++,"What is targeted temperature management after cardiac arrest?","Maintain 32-36C for at least 24h in comatose patients with ROSC. Rewarm at 0.25-0.5C/h. Neuroprognostication deferred to 72h+ using multimodal assessment.","TTM2 trial: no benefit of 33C vs 36C but fever prevention is critical. Active cooling devices preferred. Monitor for shivering (treat with sedation). Avoid hyperthermia during rewarming phase.",4,"apply",["TTM","post-cardiac arrest","hypothermia"],"em-resus"));
cards.push(c("card-tn3-em-"+n++,"Describe the ACLS algorithm for symptomatic bradycardia.","Atropine 1 mg IV q3-5 min (max 3 mg). If ineffective: transcutaneous pacing, dopamine 5-20 mcg/kg/min, or epinephrine 2-10 mcg/min infusion","Atropine ineffective in infranodal block (Mobitz II, complete heart block). Start transcutaneous pacing immediately if high-degree block. Verify capture by palpating femoral pulse. Transvenous pacing is definitive.",4,"apply",["bradycardia","ACLS","atropine","pacing"],"em-resus"));
cards.push(c("card-tn3-em-"+n++,"What is the stepwise management of stable SVT?","Vagal maneuvers (modified Valsalva) then adenosine 6mg rapid IV push then 12mg then 12mg. Refractory: diltiazem 0.25 mg/kg IV or metoprolol","Modified Valsalva with passive leg raise has higher conversion rate than standard. Adenosine requires rapid push with saline flush at proximal site. Contraindicated in pre-excited AF and severe asthma. Half-life only 6 seconds.",4,"apply",["SVT","adenosine","tachycardia"],"em-resus"));
cards.push(c("card-tn3-em-"+n++,"How is unstable tachycardia managed?","Synchronized cardioversion with procedural sedation. Energy: narrow regular 50-100J, narrow irregular 120-200J, wide regular 100J, wide irregular use defibrillation dose","Unstable = hypotension, AMS, ischemic chest pain, acute HF. Do NOT synchronize for VF or polymorphic VT (use defibrillation). Ensure sync markers align with R waves before delivering shock.",5,"apply",["cardioversion","unstable tachycardia"],"em-resus"));
cards.push(c("card-tn3-em-"+n++,"What is the first-line vasopressor and target in septic shock?","Norepinephrine targeting MAP 65 mmHg. Second-line: vasopressin 0.03 U/min. Third: epinephrine. Add hydrocortisone 200 mg/d for refractory shock","SSC 2021 guidelines: start vasopressors after 30 mL/kg crystalloid if still hypotensive. Dynamic measures (pulse pressure variation, passive leg raise) guide further fluids. Balanced crystalloids (RL) preferred over NS for large-volume resuscitation.",4,"apply",["septic shock","norepinephrine","vasopressors"],"em-resus"));
cards.push(c("card-tn3-em-"+n++,"What are the indications and technique for emergency cricothyrotomy?","Indication: CICO (cannot intubate, cannot oxygenate). Technique: vertical skin incision, horizontal stab through cricothyroid membrane, bougie, 6.0 cuffed ETT. Contraindicated in children <8 (needle cric instead)","Final step in difficult airway algorithm after failed intubation and failed supraglottic airway. Landmark: palpable depression between thyroid and cricoid cartilages in midline. Scalpel-bougie-tube technique is fastest and most reliable.",5,"apply",["cricothyrotomy","difficult airway","CICO"],"em-resus"));
cards.push(c("card-tn3-em-"+n++,"How is tension pneumothorax managed emergently?","Needle decompression (14G) at 4th/5th ICS anterior axillary line (preferred) or 2nd ICS MCL, followed by chest tube insertion","Clinical diagnosis: do not delay for CXR. Signs: hypotension, JVD, tracheal deviation, absent breath sounds. Finger thoracostomy is an alternative in intubated patients. 4th/5th ICS AAL preferred due to thinner chest wall.",4,"apply",["tension pneumothorax","needle decompression"],"em-resus"));
cards.push(c("card-tn3-em-"+n++,"What is the massive transfusion protocol?","1:1:1 ratio pRBC:FFP:platelets. TXA 1g IV within 3h of injury. Permissive hypotension (SBP 80-90) until surgical control in penetrating trauma","PROPPR and CRASH-2 trials provide evidence. Activate for anticipated >10u pRBC/24h or >4u/1h. Avoid lethal triad (hypothermia, acidosis, coagulopathy). POC testing (TEG/ROTEM) guides component therapy. Warm all products.",5,"apply",["massive transfusion","hemorrhagic shock","TXA"],"em-resus"));
cards.push(c("card-tn3-em-"+n++,"What are the components and scoring of the Glasgow Coma Scale?","Eye 1-4, Verbal 1-5, Motor 1-6. Total 3-15. Severe TBI: 3-8 (intubate). Moderate: 9-12. Mild: 13-15. Motor is most prognostic.","Assess after resuscitation. Record intubated verbal as 1T. GCS has inter-rater variability limitations. FOUR score is an alternative for intubated patients. Serial GCS monitoring detects deterioration.",3,"recall",["GCS","trauma","neurological assessment"],"em-resus"));
cards.push(c("card-tn3-em-"+n++,"What does each eFAST view assess in trauma?","RUQ: hepatorenal recess (Morrisons). LUQ: splenorenal. Suprapubic: pelvic free fluid. Subxiphoid: pericardial effusion. Bilateral anterior lung: pneumothorax","Sensitivity ~85% for free fluid, improves with serial exams. Positive eFAST + hemodynamic instability = OR. Absent lung sliding on anterior views suggests pneumothorax. M-mode shows barcode sign (PTX) vs seashore sign (normal).",3,"recall",["eFAST","trauma","ultrasound"],"em-resus"));
cards.push(c("card-tn3-em-"+n++,"What are weight-based pediatric cardiac arrest drug doses?","Epi: 0.01 mg/kg (0.1 mL/kg of 1:10,000) q3-5min. Defib: 2J/kg first, 4J/kg subsequent. Amiodarone: 5mg/kg (max 300mg). IO preferred if no rapid IV.","Pediatric arrests usually respiratory etiology. Most common rhythm: PEA/asystole. Use Broselow tape for unknown weight. Compressions: infants 4cm depth, children 5cm, rate 100-120. 15:2 compression-ventilation ratio with 2 rescuers.",5,"apply",["pediatric","cardiac arrest","PALS"],"em-resus"));
cards.push(c("card-tn3-em-"+n++,"What are the criteria, dosing, and contraindications for IV alteplase in acute ischemic stroke?","0.9 mg/kg (max 90mg), 10% bolus then 60min infusion within 4.5h onset. CI: active bleeding, BP >185/110, PLT <100k, INR >1.7, recent surgery","Canadian Stroke Best Practice Guidelines. Extended window (3-4.5h) excludes age >80, DM+prior stroke, NIHSS >25. EVT for large vessel occlusion up to 24h with perfusion imaging. BP must be controlled before and 24h after tPA.",5,"apply",["stroke","tPA","alteplase"],"em-resus"));
cards.push(c("card-tn3-em-"+n++,"Outline the ABCDE primary survey in trauma.","A: Airway + C-spine protection. B: Breathing (assess/treat pneumothorax). C: Circulation (hemorrhage control, 2 large-bore IVs). D: Disability (GCS, pupils). E: Exposure + environmental control","ATLS systematic approach: address life threats as found. Primary survey <5 min. C-spine immobilized until cleared. Adjuncts: monitoring, Foley, NG/OG, CXR, pelvis XR, eFAST.",3,"recall",["ATLS","trauma","primary survey"],"em-resus"));
cards.push(c("card-tn3-em-"+n++,"How does cardiac arrest management differ in pregnancy?","Standard ACLS + manual left uterine displacement + IV access above diaphragm. If no ROSC by 4 min, perimortem cesarean by 5 min if >=23 weeks gestation","Perimortem C-section relieves aortocaval compression improving maternal resuscitation AND neonatal outcomes. Same defibrillation doses. Remove fetal monitors before shock. Consider amniotic fluid embolism, eclampsia, hemorrhage as causes.",5,"apply",["cardiac arrest","pregnancy","perimortem cesarean"],"em-resus"));

// EM-TOX (15)
cards.push(c("card-tn3-em-"+n++,"Name the 5 classic toxidromes with distinguishing features.","Sympathomimetic: tachy, HTN, diaphoresis, mydriasis. Anticholinergic: tachy, DRY hot skin, mydriasis, urinary retention. Cholinergic: SLUDGE-BBB. Opioid: miosis, resp depression. Sedative-hypnotic: CNS depression","Key difference anticholinergic vs sympathomimetic: DRY skin vs diaphoresis. Serotonin syndrome overlaps sympathomimetic but has clonus/hyperreflexia. Toxidrome recognition directs empiric antidote therapy.",4,"analyze",["toxidromes","toxicology"],"em-tox"));
cards.push(c("card-tn3-em-"+n++,"What is the antidote, dosing, and decision criteria for acetaminophen overdose?","NAC: IV protocol 150/50/100 mg/kg over 21h. Treat if level above Rumack-Matthew treatment line (150 mcg/mL at 4h) or staggered ingestion with any detectable level + ALT elevation","Most effective within 8h but beneficial up to 24h+. Draw 4h level (earlier level uninterpretable). In Canada IV NAC preferred for liver failure. King College Criteria predict need for transplant in fulminant failure.",5,"apply",["acetaminophen","NAC","Rumack-Matthew"],"em-tox"));
cards.push(c("card-tn3-em-"+n++,"How is salicylate toxicity managed?","Activated charcoal if <2h. IV NaHCO3 targeting urine pH 7.5-8 and serum pH 7.45-7.55. Hemodialysis for level >100 mg/dL, renal failure, cerebral edema, or clinical deterioration","CRITICAL: do NOT intubate unless absolutely necessary - losing hyperventilatory compensation causes rapid acidemia and cardiovascular collapse. Correct hypokalemia before alkalinization (K+ must be adequate for renal HCO3 retention). Mixed resp alkalosis + met acidosis is classic.",5,"apply",["salicylate","toxicology","hemodialysis"],"em-tox"));
cards.push(c("card-tn3-em-"+n++,"What are the signs and management of TCA overdose?","Wide QRS >100ms, R in aVR >3mm, anticholinergic signs, seizures, hypotension. Treat: NaHCO3 1-2 mEq/kg IV boluses until QRS <100ms. Intralipid for refractory CV toxicity","Sodium channel blockade causes QRS widening. Alkalinization increases protein binding of drug and overcomes sodium channel block. Avoid phenytoin and class IA/IC antiarrhythmics. Seizures: benzodiazepines only.",5,"apply",["TCA","overdose","sodium bicarbonate"],"em-tox"));
cards.push(c("card-tn3-em-"+n++,"When is flumazenil contraindicated in benzodiazepine overdose?","Chronic BZD use (seizure risk), co-ingestion with proconvulsant (TCA, cocaine), unknown ingestion, seizure disorder. Half-life shorter than most BZDs causing re-sedation","In practice flumazenil is rarely used in overdose due to seizure risk. Supportive care with airway protection is preferred. If used: 0.2mg IV, repeat q1min to max 3mg. Main role: reversal of procedural sedation with known short-acting BZD.",4,"apply",["flumazenil","benzodiazepine","contraindications"],"em-tox"));
cards.push(c("card-tn3-em-"+n++,"How is toxic alcohol (methanol/ethylene glycol) poisoning managed?","Fomepizole 15 mg/kg IV loading (blocks alcohol dehydrogenase). Hemodialysis for level >50 mg/dL, visual symptoms (methanol), renal failure (EG), or severe acidosis","Early: elevated osmol gap. Late: anion gap metabolic acidosis as parent metabolized to toxic metabolites (formic acid causes blindness in methanol, oxalic acid causes renal failure in EG). Adjuncts: folate for methanol, thiamine/pyridoxine for EG.",5,"apply",["toxic alcohol","methanol","fomepizole"],"em-tox"));
cards.push(c("card-tn3-em-"+n++,"Describe the management of organophosphate poisoning.","Atropine 2-4 mg IV doubled q5min until secretions dry (no maximum dose). Pralidoxime 1-2g IV over 30 min. Full decontamination with PPE","Atropine treats muscarinic effects only - titrate to secretion drying NOT heart rate. Pralidoxime reactivates AChE before permanent aging (give within 24-48h). Nicotinic effects (fasciculations, paralysis) only respond to pralidoxime. PPE essential to prevent secondary exposure.",5,"apply",["organophosphate","atropine","pralidoxime"],"em-tox"));
cards.push(c("card-tn3-em-"+n++,"What is the systematic approach to the unknown overdose patient?","ABCs, check glucose, naloxone 0.04mg IV titrate up, ECG (QRS and QTc), acetaminophen + salicylate levels, osmol gap, VBG/lactate, consider charcoal if <1-2h with protected airway","Wide QRS: consider TCA, class I antiarrhythmics (treat with NaHCO3). Long QTc: multiple drug classes. Elevated osmol gap: toxic alcohols. Thiamine before glucose in malnourished/alcoholic patients.",4,"apply",["unknown overdose","toxicology"],"em-tox"));
cards.push(c("card-tn3-em-"+n++,"What are the indications, dosing, and limitations of activated charcoal?","1 g/kg (max 50g) PO within 1-2h of adsorbable substance. Not adsorbed: iron, lithium, alcohols, heavy metals, potassium (PHAILS). CI: unprotected airway, caustics, hydrocarbons","Multi-dose AC (MDAC q4h) enhances elimination of carbamazepine, dapsone, phenobarbital, quinine, theophylline via GI dialysis. Whole bowel irrigation (PEG-ELS) for sustained-release, iron, body packers.",3,"apply",["activated charcoal","decontamination"],"em-tox"));
cards.push(c("card-tn3-em-"+n++,"How is beta-blocker overdose managed?","Glucagon 5-10mg IV bolus then 1-5mg/h (first-line). High-dose insulin: 1 U/kg bolus then 1-10 U/kg/h with dextrose. Intralipid for lipophilic agents. Vasopressors as adjuncts","Glucagon bypasses beta-receptors via own receptor-cAMP pathway. High-dose insulin improves inotropy. Signs: bradycardia, hypotension, hypoglycemia (except with sotalol), bronchospasm, seizures (propranolol). ECMO as rescue for refractory cardiogenic shock.",5,"apply",["beta-blocker","overdose","glucagon"],"em-tox"));
cards.push(c("card-tn3-em-"+n++,"How is calcium channel blocker overdose managed?","Calcium: CaCl 1-3g or Ca gluconate 3-6g IV. High-dose insulin euglycemia: 1U/kg bolus then 1-10 U/kg/h. Vasopressors. Intralipid. Consider ECMO","Most lethal cardiovascular poisoning. Hyperglycemia at presentation predicts severity and good insulin response. Maintain glucose 8-12 mmol/L with dextrose infusion during high-dose insulin. Methylene blue emerging for refractory vasoplegia.",5,"apply",["CCB","overdose","high-dose insulin"],"em-tox"));
cards.push(c("card-tn3-em-"+n++,"How do serotonin syndrome and neuroleptic malignant syndrome differ in presentation and management?","SS: rapid onset hours, clonus, hyperreflexia, diaphoresis, diarrhea. Rx: cyproheptadine. NMS: onset days, lead-pipe rigidity, hyperthermia, normal/decreased reflexes. Rx: dantrolene, bromocriptine","SS: excess serotonin (SSRI+MAOI, SSRI+tramadol, linezolid combinations). NMS: dopamine blockade (antipsychotics). Both: elevated CK, AMS, autonomic instability. Key differentiator: clonus/hyperreflexia (SS) vs rigidity (NMS).",4,"analyze",["serotonin syndrome","NMS"],"em-tox"));
cards.push(c("card-tn3-em-"+n++,"What is the management of acute opioid overdose including dosing and monitoring?","Naloxone 0.04mg IV initially, titrate q2-3min to RR >12 (not full consciousness). Observe for re-sedation. Infusion: 2/3 of effective bolus dose per hour for long-acting opioids","Community naloxone: intranasal 4mg or IM 0.4mg. Titrate to respiratory effort to avoid precipitating withdrawal. Fentanyl may need multiple doses. Canada Good Samaritan Drug Overdose Act provides legal protection for calling 911.",4,"apply",["opioid","naloxone","overdose"],"em-tox"));
cards.push(c("card-tn3-em-"+n++,"What are the features and management of lithium toxicity?","Mild (1.5-2.5): hold + IV NS. Moderate (2.5-3.5): consider HD. Severe (>3.5 or symptomatic): emergent HD. Signs: tremor, ataxia, confusion, seizures, arrhythmias. Charcoal NOT effective","Narrow therapeutic index 0.6-1.2 mEq/L. Toxicity potentiated by dehydration, NSAIDs, ACEi, thiazides. Chronic toxicity more dangerous at lower levels than acute. SILENT syndrome: irreversible neurological damage post-toxicity.",4,"apply",["lithium","toxicity","hemodialysis"],"em-tox"));
cards.push(c("card-tn3-em-"+n++,"Describe the stages and management of iron overdose.","Stage I (0-6h): GI hemorrhage. II (6-24h): apparent improvement. III (12-48h): systemic shock. IV (2-4d): hepatic necrosis. V (2-6wk): GI scarring. Rx: WBI + deferoxamine 15mg/kg/h for level >500","Charcoal does not adsorb iron. Deferoxamine chelates free iron producing vin rose urine. AXR may show radiopaque pills. Stop deferoxamine at 24h (ARDS risk). Serum iron >350 at 4-6h = significant toxicity.",5,"apply",["iron","overdose","deferoxamine"],"em-tox"));

// EM-ANAPHYLAXIS (10)
cards.push(c("card-tn3-em-"+n++,"What is the first-line treatment and correct dosing for anaphylaxis?","Epinephrine 0.3-0.5 mg IM (1:1000) anterolateral thigh. Peds: 0.01 mg/kg max 0.3mg. Repeat q5-15min. NO absolute contraindication to epi in anaphylaxis","Epi IM is the ONLY first-line. IV epi 1-5 mcg/min for refractory shock only. Delay in epi is primary risk factor for death. Per Canadian Allergy and CPS guidelines always give before H1/H2 blockers or steroids.",5,"apply",["anaphylaxis","epinephrine"],"em-anaphylaxis"));
cards.push(c("card-tn3-em-"+n++,"What are the WAO/EAACI diagnostic criteria for anaphylaxis?","(1) Skin/mucosal + respiratory OR hypotension after likely allergen. (2) 2+ organ systems after likely allergen. (3) Hypotension after KNOWN allergen. Any one criterion sufficient","Skin findings absent in ~20%. Tryptase (draw within 1-2h, compare baseline at >24h) confirms mast cell degranulation. Anaphylaxis is a clinical diagnosis - never delay treatment for investigations.",4,"recall",["anaphylaxis","diagnostic criteria"],"em-anaphylaxis"));
cards.push(c("card-tn3-em-"+n++,"What is a biphasic reaction in anaphylaxis and what observation period is recommended?","Recurrence of symptoms 1-72h after resolution without re-exposure (1-20% incidence). Minimum observation: 4-6h. High-risk (severe, multiple epi doses, asthma): 8-12h or admit","Risk factors for biphasic: severe initial presentation, delayed epinephrine, oral allergen exposure. Methylprednisolone 1-2 mg/kg given to reduce biphasic risk (limited evidence). Discharge with 2 EpiPens and allergist referral.",3,"apply",["biphasic","anaphylaxis","observation"],"em-anaphylaxis"));
cards.push(c("card-tn3-em-"+n++,"How is refractory anaphylaxis (not responding to IM epinephrine) managed?","IV epinephrine infusion 1-5 mcg/min, aggressive IVF 1-2L NS, nebulized salbutamol, glucagon 1-5mg IV if on beta-blocker, vasopressin for refractory hypotension","Keep patient SUPINE with legs elevated - upright positioning causes empty ventricle syndrome and cardiac arrest. Beta-blocked patients: glucagon bypasses beta receptors. Consider ECMO for refractory cardiovascular collapse.",5,"apply",["refractory anaphylaxis","epinephrine infusion"],"em-anaphylaxis"));
cards.push(c("card-tn3-em-"+n++,"What mandatory prescriptions and instructions are given at anaphylaxis discharge?","2 epinephrine auto-injectors, written action plan, MedicAlert recommendation, allergist referral, trigger avoidance education, return precautions for biphasic reaction","EpiPen Jr 0.15mg (15-30kg), EpiPen 0.3mg (>30kg). 2 devices because second dose may be needed before EMS. Teach: epi FIRST not antihistamines. Provincial formulary coverage varies across Canada.",3,"apply",["anaphylaxis","EpiPen","discharge"],"em-anaphylaxis"));
cards.push(c("card-tn3-em-"+n++,"What are the most common anaphylaxis triggers in Canadian children vs adults?","Children: food (peanut, tree nut, milk, egg, shellfish). Adults: drugs (penicillin, NSAIDs), Hymenoptera stings. Perioperative: NMBAs. Idiopathic ~20%","Health Canada mandates labeling of 11 priority allergens. Prevalence 1-2% lifetime. Food allergy prevalence increasing. Latex allergy declining with non-latex gloves. Cofactors (exercise, alcohol, NSAIDs) lower anaphylaxis threshold.",3,"recall",["anaphylaxis","allergens","Canada"],"em-anaphylaxis"));
cards.push(c("card-tn3-em-"+n++,"What is the role of antihistamines and corticosteroids in anaphylaxis?","ADJUNCTS ONLY. H1 (diphenhydramine 25-50mg) + H2 (ranitidine 50mg). Steroids (methylprednisolone 125mg IV) may reduce biphasic risk (4-6h onset). Neither replaces epinephrine","Dangerous common error: treating with antihistamines alone. H1/H2 only help skin symptoms, no effect on bronchospasm or hypotension. Steroids too slow for acute phase. Canadian guidelines emphasize epi first always.",3,"apply",["antihistamines","steroids","anaphylaxis"],"em-anaphylaxis"));
cards.push(c("card-tn3-em-"+n++,"How does immune (IgE) anaphylaxis differ from non-immune anaphylaxis?","Immune: requires prior sensitization, IgE-mediated mast cell degranulation. Non-immune (formerly anaphylactoid): direct mast cell activation (radiocontrast, opioids, vancomycin). First-exposure possible. Treatment IDENTICAL","Anaphylactoid term being phased out. Radiocontrast premedication: prednisone 50mg at 13/7/1h before + diphenhydramine + low-osmolar contrast. Non-immune reactions dose-dependent and often less severe than IgE-mediated.",3,"analyze",["anaphylaxis","non-immune"],"em-anaphylaxis"));
cards.push(c("card-tn3-em-"+n++,"What is food-dependent exercise-induced anaphylaxis (FDEIA)?","Anaphylaxis during exercise 2-6h after specific food (wheat, shellfish most common). Neither food alone nor exercise alone triggers it. Prevention: avoid trigger food 4-6h pre-exercise, carry EpiPen","Cofactors lowering threshold: NSAIDs, alcohol, heat, menstruation, sleep deprivation. Most common subtype of exercise-induced anaphylaxis. Diagnosis by clinical history. Supervised exercise challenge in specialized centers only.",3,"apply",["FDEIA","exercise-induced anaphylaxis"],"em-anaphylaxis"));
cards.push(c("card-tn3-em-"+n++,"What is Kounis syndrome and why is it important in anaphylaxis?","Allergic acute coronary syndrome: mast cell mediators cause coronary vasospasm (Type I), plaque rupture (Type II), or stent thrombosis (Type III). Check troponin and ECG for ST changes","Occurs during anaphylaxis, especially in patients with pre-existing CAD. Treatment: epinephrine for anaphylaxis + cardiology consult for ACS management. Avoid beta-blockers in anaphylaxis context. Consider in any anaphylaxis patient with chest pain.",4,"analyze",["Kounis syndrome","anaphylaxis","ACS"],"em-anaphylaxis"));

console.log("EM total: " + cards.length);
fs.writeFileSync("C:/dev/srs-mccqe1/data/_em_cards.json", JSON.stringify(cards));
console.log("EM cards saved");
